### ISSUE TITLE
Agents FP permanently changes your prof

### ISSUE THREAD

**Issue by Kazrae** [project-rubika/issues#1001]
### Reproduction steps

```bash
1. Cast any FP nano
2. Let it run out or die
3. Try to learn new agent nano / Shift+click yourself
```

### Expected results

```bash
Prof should revert back to agent once the nano is gone out of the ncu
```

### Actual results

```bash
Casted Fp Advy yesterday and today i noticed i can't use a new agent nano.
Shift+click myself to see i'm still an Advy
```

### Bug prevalence

Everytime (tested twice)

### Description

```bash
pls fix lol
```

### Report link

https://pastebin.com/u70YEQR9

**Comment by kajoriEU** [comment]
Confirmed.

TempSet (or ChangeVariable on portal) is not working correctly

1. `.ncu run 32030`
2. zone/relog
3. `.ncu clear`
4. VisualProf stays Advy

**Comment by kajoriEU** [comment]
I’m still able to reproduce this issue using the steps outlined in my previous comment.

**Comment by Kazrae** [comment]
Seems to be fixed now, after dying i'm an Agent again.
