### ISSUE TITLE
MA move Gives nano rather then takes nano

### ISSUE THREAD

**Issue by westtell4** [project-rubika/issues#1003]
**Describe the bug**
using  Jab of the snake Which is supposed to take two nano gives two nano instead
**To Reproduce**
1. find something to fight
2. Use Jab of the Snake
3. watch chat for you increased your nano pool with two points 

**Expected behavior**
To remove 2 points from  users nano pool on use 

**Screenshots**
![image](https://github.com/user-attachments/assets/153e548d-efb8-4b66-ac38-bf23b2faef27)

![image](https://github.com/user-attachments/assets/c3a7c4dc-4924-4c10-b24e-ec6fa0fedd31)

**Character info:**
Crimsonma

**Comment by kajoriEU** [comment]
It just gives a wrong message into the chat. See #932. 

When using any QL of Jab of the Snake you can see your currentnano going down.

**Comment by westtell4** [comment]
Yes its going down by 2 close the ticket i guess..
