### ISSUE TITLE
Some meshes have wrong size and duplicated on NPCs.

### ISSUE THREAD

**Issue by 3F1-1009** [project-rubika/issues#1011]
**Describe the bug**
Some of the meshes from shoulderpads and back items are wrong size and duplicated.
Possibly caused by equipped items not checking for Breed stat.
Duplicate meshes appear because item fails to check Breed and multiple criterias pass.

**To Reproduce**
1. Go to 3253.2 892.0 y 0.0 655
2. Notice how ICC Peacekeepers have huge shoulderpads.
3. Go to 1270.5 2909.6 y 0.2 790
4. Notice how Nihana Finchers back item is wrong size

**Expected behavior**
Items with meshes should have appropriate size for breed/gender combo

**Screenshots**

![Screenshot_348](https://github.com/user-attachments/assets/02605a08-b3d2-42f4-bb4f-c2b3a02f34f1)

**Character info:**

```
Copy/paste the output of /getfull here
```

**Playfield info:**

```
Copy/paste the output of Shift+F9 here
```
----

**Comment by RaggyLP** [comment]
Confirmed. Target Breed checks seems to be either missing or not accepting the values. Refer along with #996.

**Comment by 3F1-1009** [comment]
![Screenshot_355](https://github.com/user-attachments/assets/4f1076f9-93dd-4a19-a717-2bf76abe808c)
Looks like it's fixed.
