### ISSUE TITLE
Curator stun (or maybe all stuns) interrupts combat

### ISSUE THREAD

**Issue by StormlashTV** [project-rubika/issues#1012]
### Reproduction steps

```bash
1. Go to TOTW and find The Curator
2. Start fighting him
3. Wait for him to stun you and you should be forced out of combat
```

### Expected results

```bash
I expected not to stop attacking him
```

### Actual results

```bash
It made me stop attacking him after I get stunned
```

### Bug prevalence

Sometimes

### Description

```bash
Was teamed at that time
```

### Report link

https://pastebin.com/By1VtxkY

**Comment by kajoriEU** [comment]
I attempted to replicate this issue with Stormlash in the Discord beta-testing channel, but we were unable to reproduce it at this time.

**Comment by kajoriEU** [comment]
We couldn't reproduce this issue anymore. If more information becomes available, please feel free to reopen the issue.

**Comment by donkeyohtay** [comment]
It looks like I can reproduce this using a pet and Malahs in Nascence. It doesn't seem to be every time, but when my pet gets stunned he will sometimes exit combat.
