### ISSUE TITLE
Omni Assault Pack unequips on zone

### ISSUE THREAD

**Issue by CRMCG-1** [project-rubika/issues#1018]
### Reproduction steps

```bash
1.
2.
3.
Equip - zone - observe
```

### Expected results

```bash
Stay equipped
```

### Actual results

```bash
does not
```

### Bug prevalence

Upon zoning

### Description

```bash
Playshift req bug
```

### Report link

https://pastebin.com/hx0ZCsVJ

**Comment by RaggyLP** [comment]
Duplicate of #844.
