### ISSUE TITLE
Trimmer Cooldowns not working correctly

### ISSUE THREAD

**Issue by oatbag03** [project-rubika/issues#1020]
**Describe the bug**
Trimmer items, specifically the Divert Energy to X line, do not have a cooldown. 

**To Reproduce**
1. Put item Trimmer - Divert Energy to Hitpoints in action bar (.item 88381 88382 30)
2. do .get life on engineer pet
3. spam click the trimmer as many times as you like (no cooldown)
4. do .get life on engineer pet

**Expected behavior**
Trimmer would work one time and increase the max hp of the engineer pet one time before locking out EE.

**Screenshots**

get succeeded - Bob (131313) life is 6914 (6914 base + 0 mod + 0 trickle + 0 custom).
to
.get succeeded - Bob (131313) life is 51810 (6914 base + 44896 mod + 0 trickle + 0 custom).

![image](https://github.com/user-attachments/assets/c634cf6d-f275-465e-ad66-4f83aebd9657)

**Character info:**

RenderDebug ToggleCapRefraction:  OFF
Bob (131313)

    accountflags 	0

    aggdef 	0

    aggressiveness 	0

    agility 	187

    aimedshot 	456

    amsmodifier 	0

    assaultrifle 	456

    attitude 	1

    biologicalmetamorphose 	546

    bodydevelopment 	46

    bow 	456

    bowspecialattack 	456

    brawl 	456

    breakingentry 	546

    breed 	7

    breedhostility 	0

    burst 	456

    cash 	0

    charstate 	0

    chemicalac 	914

    chemistry 	478

    clan 	95

    closecombatinitiative 	546

    coldac 	914

    computerliteracy 	478

    concealment 	546

    conformity 	20

    currentmovementmode 	3

    currentnano 	2012

    damageoverridetype 	0

    debug 	0

    dimach 	456

    disarmtrap 	546

    distanceweaponinitiative 	546

    dodge 	478

    driveair 	478

    driveground 	478

    duck 	478

    electricalengineering 	478

    energy 	4098

    energyac 	868

    EquippedRHWeapon 	0

    equippedweapontype 	0

    evade 	478

    expansion 	3

    extroverty 	100

    fastattack 	456

    fatness 	1

    fieldquantumphysics 	478

    fireac 	914

    firstaid 	478

    flags 	403182081

    flingshot 	456

    fullauto 	456

    grenade 	456

    HasKnuBotData 	1

    headmesh 	0

    healdelta 	82

    healinterval 	1

    health 	27660

    intelligence 	187

    isfightingme 	0

    level 	91

    life 	51810

    losheight 	0

    lr_energyweapon 	456

    lr_multipleweapon 	456

    mapnavigation 	478

    martialarts 	456

    materialcreation 	546

    materiallocation 	546

    materialmetamorphose 	546

    maxnanoenergy 	2012

    maxncu 	99

    mechanicalengineering 	478

    meleeac 	868

    meleedamagemodifier 	0

    meleeenergyweapon 	456

    meleemultiple 	456

    monsterdata 	45873

    monsterscale 	110

    nanoac 	552

    nanodelta 	82

    nanoenergypool 	546

    nanointerval 	1

    nanoprogramming 	478

    nanoprowessinitiative 	546

    npc_type 	100001

    npcfamily 	95

    onehandbluntweapons 	456

    onehandedgedweapon 	456

    parry 	546

    perception 	546

    petmaster 	2188

    petstate 	1

    pharmaceuticals 	478

    physicalprowessinitiative 	546

    piercing 	456

    pistol 	456

    poisonac 	914

    profession 	0

    projectileac 	868

    proximityrangeindoors 	13

    proximityrangeoutdoors 	25

    psychic 	187

    psychologicalmodification 	546

    psychology 	478

    race 	1

    radiationac 	914

    rifle 	456

    riposte 	456

    runspeed 	1349

    selectedtarget 	131486

    selectedtargettype 	16

    sense 	187

    senseimprovement 	546

    sex 	1

    shotgun 	456

    side 	1

    sneakattack 	456

    stability 	100

    stamina 	187

    strength 	187

    submachinegun 	456

    swim 	546

    throwingknife 	456

    throwngrapplingweapons 	456

    timeexist 	0

    titlelevel 	3

    treatment 	478

    tutoring 	478

    twohandbluntweapons 	456

    twohandedgedweapons 	456

    VisualFlags 	31

    visualprofession 	15

    weaponsmithing 	478

    xp 	0

.getfull succeeded.

**Playfield info:**

Extended location information:
- 89.7, 279.3, 111.6 (89.7 279.3 y 111.6 127)
- Pf Proxy: Model=51100:127 GS=0 SG=0 R=127, resource: 127
- zone: 8, area: "Abandoned Mall", room: "Entrance Stairs"
Server id: 2188, character id: 50000:2188, time: 2024-09-27 21:19:28 (UTC)
Version: 00.6.5_EP1, map id: NOT FOUND, build: 52606.

----

**Comment by oatbag03** [comment]
Also I couldn't get Trimmer - Divert Energy to Avoidance or Trimmer - Divert Energy to Defense to do anything.

Trimmer - Increase Aggressiveness and Trimmer - Positive Aggressive-Defensive both change the bot's stats as expected.

**Comment by kajoriEU** [comment]
The cooldown issue with trimmers has been resolved. For any other problems, please open a separate issue.



![{E203C35C-26D9-4946-8682-32FA3F776EC4}](https://github.com/user-attachments/assets/7d994dbb-96e0-4484-baf6-6d81084c06d2)
