### ISSUE TITLE
containers cannot be opened when targeting certain objects

### ISSUE THREAD

**Issue by 7RO11** [project-rubika/issues#1025]
### Reproduction steps

```bash
1. have a container .item 99228 99228 1
2. select/lmb a shop terminal
3. open/rmb the container
```

### Expected results

```bash
the container opens
```

### Actual results

```bash
no container opens
```

### Bug prevalence

everytime

### Description

```bash
this applies to corpses too, but not all terminals
mail, bank, insurance and mission terminals do not exhibit this behavior
```

### Report link

https://pastebin.com/eZ5wSkrs

**Comment by kajoriEU** [comment]
The issue has been resolved with the latest patches, and it can no longer be reproduced. Marking this as fixed and closing the issue. :)
