### ISSUE TITLE
False Profession upon death sets profession to nothing

### ISSUE THREAD

**Issue by NaveZero** [project-rubika/issues#1031]
**Describe the bug**
When you're playing an agent and die while FP is running your profession is set to " Not chosen yet.", there also seems to be a problem of the FP being permanent once you enter it and make you unable to change FP.

**To Reproduce**
Play an agent with FP running and die while it's running.

**Expected behavior**
FP is supposed to clear upon death and return you to the Agent "flag"

**Screenshots**

**Character info:**

Character: Rafeg

Currently no profession at all.

**Playfield info:**

```
Copy/paste the output of Shift+F9 here
```
----

**Comment by oatbag03** [comment]
![image](https://github.com/user-attachments/assets/f1ece196-d6ee-4e38-8e5f-1736ef132474)

**Comment by oatbag03** [comment]
After you end up in this state- Agent nanos can still be cast, except for more false profession type nanos:
This effect can only be utilitized by Agent.
This effect can only be utilitized by Enforcer.

**Comment by oatbag03** [comment]
Getfull results:

    currentncu 	67

    currentplayfield 	566

    currentstate 	0

    custom_flags 	1

    deadtimer 	0

    dimach 	2280

    disarmtrap 	2279

    distanceweaponinitiative 	2279

    dodge 	2279

    driveair 	2279

    driveground 	2279

    drivewater 	2279

    duck 	2279

    electricalengineering 	2277

    energyac 	20500

    energydamagemodifier 	23

    EquippedRHWeapon 	1

    equippedweapontype 	1

    evade 	2279

    expansion 	2

    fastattack 	2279

    fatness 	1

    features 	6

    fieldquantumphysics 	2276

    fireac 	20776

    firedamagemodifier 	23

    firstaid 	2279

    flags 	528961

    flingshot 	2278

    fullauto 	2276

    globalresearchgoal 	0

    globalresearchlevel 	0

    gmlevel 	127

    gos 	0

    grenade 	2279

    headmesh 	40261

    healdelta 	7

    healinterval 	19

    health 	6445

    icon 	0

    inplay 	0

    insurancepercentage 	0

    insurancetime 	0

    intelligence 	1106

    invaderskilled 	0

    isfightingme 	0

    itemtype 	0

    killedbyinvaders 	0

    lastconcreteplayfieldinstance 	0

    lastmailchecktime 	1283065897

    lastperkresettime 	0

    lastsaved 	100

    lastsavexp 	0

    lastxp 	30371850

    level 	100

    life 	4945

    lr_energyweapon 	2278

    lr_multipleweapon 	2277

    mapareapart1 	0

    mapareapart2 	0

    mapareapart3 	0

    mapareapart4 	0

    mapflags 	0

    mapnavigation 	2278

    mapoptions 	0

    martialarts 	2282

    materialcreation 	2791

    materiallocation 	2760

    materialmetamorphose 	2791

    maxnanoenergy 	7833

    maxncu 	2008

    mechanicalengineering 	2277

    meleeac 	20500

    meleedamagemodifier 	23

    meleeenergyweapon 	2276

    meleemultiple 	2277

    members 	999

    mesh 	17530

    metatype 	0

    missionbits1 	0

    missionbits10 	0

    missionbits11 	0

    missionbits12 	0

    missionbits2 	0

    missionbits3 	0

    missionbits4 	0

    missionbits5 	0

    missionbits6 	0

    missionbits7 	0

    missionbits8 	0

    missionbits9 	0

    monsterdata 	0

    monsterscale 	100

    monthspaid 	0

    nanoac 	2275

    nanodelta 	7

    nanoenergypool 	2441

    nanofocuslevel 	0

    nanointerval 	18

    nanoprogramming 	2276

    nanoprowessinitiative 	2614

    nextxp 	31962150

    npcostmodifier 	0

    onehandbluntweapons 	2276

    onehandedgedweapon 	2277

    otarmedforces 	0

    otfollowers 	0

    otmed 	1234567890

    otoperator 	0

    ottrans 	0

    otunredeemed 	0

    PaidPoints 	0

    parry 	2278

    perception 	2279

    personalresearchgoal 	0

    personalresearchlevel 	0

    pharmaceuticals 	2326

    physicalprowessinitiative 	2279

    piercing 	2277

    pistol 	2279

    playerid 	1234567890

    playeroptions 	0

    playfieldtype 	0

    poisonac 	20776

    poisondamagemodifier 	23

    previoushealth 	50

    prevmovementmode 	3

    profession 	5

    projectileac 	20500

    projectiledamagemodifier 	23

    psychic 	1103

    psychologicalmodification 	2761

    psychology 	2278

    PVPDuelDeaths 	0

    PVPDuelKills 	0

    PVPDuelScore 	0

    PVPProfessionDuelDeaths 	0

    PVPProfessionDuelKills 	0

    PVPRankedSoloDeaths 	0

    PVPRankedSoloKills 	0

    PVPRankedTeamDeaths 	0

    PVPRankedTeamKills 	0

    PVPSoloScore 	0

    PVPTeamScore 	0

    race 	1

    radiationac 	20776

    radiationdamagemodifier 	23

    rifle 	2331

    riposte 	2280

    rp 	0

    runspeed 	2110

    savedxp 	30371850

    selectedtarget 	2975

    selectedtargettype 	0

    sense 	1125

    senseimprovement 	2760

    sessiontime 	0

    sex 	2

    shadowbreed 	0

    shadowbreedtemplate 	0

    shotgun 	2277

    side 	0

    sk 	0

    sneakattack 	2278

    socialstatus 	0

    specialcondition 	1

    specialization 	0

    stamina 	1106

    state 	0

    strength 	1103

    submachinegun 	2277

    swim 	2276

    team 	0

    teamside 	0

    temporaryskillreduction 	0

    tempsaveplayfield 	0

    tempsaveteamid 	0

    tempsavex 	0

    tempsavey 	0

    throwingknife 	2278

    throwngrapplingweapons 	2277

    titlelevel 	4

    treatment 	2278

    tutoring 	2277

    twohandbluntweapons 	2276

    twohandedgedweapons 	2276

    unarmedtemplateinstance 	0

    unreadmailcount 	0

    unsavedxp 	0

    veteranpoints 	0

    visualbreed 	2

    VisualFlags 	31

    visualsex 	2

    vp 	0

    waitstate 	1

    weaponsmithing 	2276

    xp 	30371850

    xpkillrange 	5

    xpmodifier 	10

**Comment by RaggyLP** [comment]
Confirmed. This can currently be rectified by GM/Dev by using `set profession 5` and `.set visualprofession 5`.

**Comment by kajoriEU** [comment]
Closing this as fixed :)


https://github.com/user-attachments/assets/9d77e062-a897-46f5-b839-04b3b5726995
