### ISSUE TITLE
Ranged attacks not pausing properly on movement

### ISSUE THREAD

**Issue by portalerprk** [project-rubika/issues#146]
**Describe the bug**
Ranged attacks not pausing properly on movement. Specifically if you start running and THEN start combat.

**To Reproduce**
1. Start running.. dont stop
2. Start attack on a target
3. Ranged attack UI pauses as expected.. but the server still takes the shot

**Expected behavior**
Should pause serverside as it does in the client.

**Comment by RaggyLP** [comment]
This one one back I'm afraid.


https://github.com/project-rubika/issues/assets/156821187/2d0443f9-cff9-4094-a4ff-648f06109b4d

Movement doesn't block the attack from firing, so you can theoretically kite forever with ranged weapons without needing to stop to shoot.

**Comment by portalerprk** [comment]
Ah it appears strafing is not being tracked as a movement state that blocks attack charge.

**Comment by RaggyLP** [comment]
Just tested. Both Strafing and Jumping seperately or combined. Forward and Backwards movement defintely block charge, even when jumping. 

So:

Currently blocking charge:
W
S
W + Jump
S + Jump

Not blocking charge:

Jump
Z
C
Z + Jump
C + Jump
