### ISSUE TITLE
"Fear" not implemented

### ISSUE THREAD

**Issue by portalerprk** [project-rubika/issues#207]
See https://aoitems.com/item/30094/sneaking-terror/

**Comment by RaggyLP** [comment]
Fear appears to be broken again. Tested using both Enforcer's Fear line and MA fears.


![image](https://github.com/project-rubika/issues/assets/156821187/d35efc9f-6aad-4aa2-8f44-b8bc67065e28)
![image](https://github.com/project-rubika/issues/assets/156821187/d1c8789d-c11d-4ab2-a215-a14913d719ca)
![image](https://github.com/project-rubika/issues/assets/156821187/4f5f8bad-271e-4b54-99ed-d400b8778067)

**Comment by TheTinkeringIdiot** [comment]
Confirmed. Casting Presence of the Dominator on a mob shows that Presence of the Overlord correctly appears in the target's NCU, but it's status does not switch to "Horrified" or "Feared", and it does not run away. 

![image](https://github.com/project-rubika/issues/assets/96996793/6fc32add-6c07-4ed2-9112-1175aa8d9a9f)

**Comment by TheTinkeringIdiot** [comment]
Fear has been fixed but mob positioning and travel has an issue described in #632
