### ISSUE TITLE
NPC Vendors are spawning with a physical terminal at their location

### ISSUE THREAD

**Issue by portalerprk** [project-rubika/issues#310]
NPC Vendors are spawning with a physical terminal at their location

![image](https://user-images.githubusercontent.com/60405799/218263619-623d7acd-9137-4c53-afdc-fcdda248c4ce.png)

**Comment by prkdrake** [comment]
Seems to be resolved for now, closing - I'm sure we will see it again soon!

**Comment by prkdrake** [comment]
See #468

**Comment by TheTinkeringIdiot** [comment]
This appears to have been fixed in recent changes.

**Comment by RaggyLP** [comment]
This one simply never stays dead.

**Comment by JulianVallee** [comment]
Got another one in Newland Miir, this time with location info.. maybe it helps:
```
Extended location information:
- 215.2, 169.7, 5.0 (215.2 169.7 y 5.0 2063)
- Pf Proxy: Model=51100:2063 GS=0 SG=0 R=2063, resource: 2063
- zone: 0, area: "Area"
Server id: 1515, character id: 50000:1515, time: 2024-04-10 01:46:17 (UTC)
Version: 00.6.1_EP1, map id: NOT FOUND, build: 52606.
```

**Comment by prkdrake** [comment]
Should be fixed with the latest update

**Comment by RaggyLP** [comment]
After running about for a good hour or so, I've not seen hide nor hair of the stupid sexy terminals. Might this be the end? *Tentatively* closing as fixed as of 25/08/2024.
