### ISSUE TITLE
The /tp command allows the user to go to an invalid playfield

### ISSUE THREAD

**Issue by abc** [project-rubika/issues#316]
**Describe the bug**
It's possible to use the /tp command to teleport to an invalid playfield, which causes the game to crash, and the character becomes inaccessible (this issue has been raised separately, see #315)

**To Reproduce**
1. Create a new character.
2. Use the tp command to go to an invalid playfield, e.g. `/tp 1337 1 1`
3. The game will crash, and the character will be inaccessible.

**Expected behavior**
The /tp command should fail with an error, e.g. "1337 is not a valid playfield". 

**Additional context**
Do not fix this bug until after #315 has been fixed - this bug is useful to have to test #315.

**Comment by playboyfixer** [comment]
Unable to go to playfield 1 as it does not appear to be a valid playfield. Please contact the dev team.
.teleport succeeded.

confirm fixed

**Comment by prkdrake** [comment]
Thanks!
