### ISSUE TITLE
Mr. Blake's dialogue is broken

### ISSUE THREAD

**Issue by abc** [project-rubika/issues#318]
**Describe the bug**
Several lines of conversation in dialogue with Mr Blake are broken, causing the line of text to not render, and the NPC does not emote.

**To Reproduce**
1. Go to Mr. Blake in Rome Blue (`/tp 735 653 408`, then walk up the ramp and across the floor)
2. Talk to Mr. Blake
3. Go through the conversation options with him, and notice that there are several items of "missing" dialogue/text.

**Expected behavior**
Mr. Blake should have his full dialogue, and he should use emotes while speaking.

**Comment by reneraen** [comment]
Is this related to the https://www.ao-universe.com/guides/classic-ao/quests-guides-3/omni-start-up-quests ?

**Comment by RaggyLP** [comment]
Confirmed, partially. There are definitely lines of dialogue missing from Mr. Blake, he is however emoting through his dialogue.

![image](https://github.com/project-rubika/issues/assets/156821187/434c83fd-ff32-43fe-ad7c-318ae5309d56)

**Comment by RaggyLP** [comment]
Mr. Blake's conversation tree currently breaks on options [6003], [6009] and [6010], however, he gives you the mission (8UTV) on options [6014] and [6018].

Also prints an Unhandled Exception on [6020]
`[ERR] Unhandled exception in social command handler ({social surprised}) - Requested value 'surprised' was not found.`

All other conversation paths appear to be fine.

**Comment by prkdrake** [comment]
This should be fixed with the next update, please re-test and let us know. Thanks!

**Comment by RaggyLP** [comment]
Confirmed. Mr. Blake is now able to send witless Omni-tek employees off on long and arduous tasks. Closing as fixed as of 21/08/2024.
