### ISSUE TITLE
The quests for Lieutenant Echholt do not work

### ISSUE THREAD

**Issue by abc** [project-rubika/issues#319]
**Describe the bug**
The [quests around giving items to Lieutenant Echholt](https://www.ao-universe.com/guides/classic-ao/quests-guides-3/omni-start-up-quests) do not seem to be working correctly. The dialogue is broken and you do not get the mission updates/rewards.

**To Reproduce**
1. Go to Mr. Blake in Rome Blue (`/tp 735 653 408`, then walk up the ramp and across the floor) and talk to him, and agree to help.
2. Check your mission log. You should have a quest in there to bring a transmitter to Lieutenant Echholt.
3. Check your inventory, you should have a radio transciever.
4. Go to Lieutenant Echholt in Omni Forest (`/tp 716 488 1822`)
5. Create a bottle of Whiskey for Echholt (`/item 130598 130598 1`)
6. Talk to the Lieutenant, and trade him the radio transciever item.
7. Give him the Whiskey.

**Expected behavior**
You should receive a [helmet](https://auno.org/ao/db.php?id=258474) as a reward for giving Echholt the transmitter, and you should receive a [backpack](https://auno.org/ao/db.php?id=245585) as a reward for giving Echholt the whiskey. Additionally, the dialogue should not be broken.

**Comment by RaggyLP** [comment]
Unable to currently repo as the Lieutenant Echholt is currently missing from his location in the Barracks. Further to this, there is a seperate issue that randomly teleports the player to Greater Omni Forest when at the NPC location.

**Comment by TheTinkeringIdiot** [comment]
Unable to confirm as Playfield 408 is invalid.

![image](https://github.com/project-rubika/issues/assets/96996793/c73cc586-3930-4208-be55-36f30647d0ae)

**Comment by RaggyLP** [comment]
Echholt is now present, gives rewards for both of his quests (Radio Transmitter and Whiskey) and also provides the item necessary for his Gloves quest. Closing as fixed as of 16/08/2024.
