### ISSUE TITLE
Vendor random weapons can be generated with invalid quality levels

### ISSUE THREAD

**Issue by abc** [project-rubika/issues#322]
**Describe the bug**
Many weapons in AO have a low ID, a high ID, and a QL range, and there are a number of weapons available at a range of QLs. For example, the Sig SG 992 SWAT has 5 different variants: 

| Name | Low ID | High ID | QL Range |
| --- | --- | --- | --- | 
| Rusty Sig SG 992 SWAT Edition 2 | 124016 | 124017 | 1 – 7 |
| Sig SG 992 SWAT Edition 2 | 124018 | 124019 |  8 – 91 |
| Sig SG 992 SWAT Vagabond | 124020 | 124021 |  92 – 189 |
| Sig SG 992 SWAT Edition 1 | 124022 | 124023 |  190 – 199 |
| Sig SG 992 SWAT Army Special | 124024 | 124024 | 200 |

Weapons with a given ID are being generated in shops outside the above QL ranges, e.g. a QL 3 Sig SG 992 SWAT Edition 1. 

![image](https://github.com/project-rubika/issues/assets/3063240/a5f04d24-a50b-42cf-a99a-94ad7124db70)

The stats of the weapon look like they have been scaled down (but not completely to the equivalent of a QL3 Rusty Sig SG 992 SWAT Edition 2)

![image](https://github.com/project-rubika/issues/assets/3063240/4497f387-36ef-420e-a66c-617b58e41c69)

However, when the weapon is used, it's clear that the stats shown in the item info screen are not accurate, and the weapon appears to be performing as if it's the low QL of the item (e.g. a QL 190 Sig SG 992 SWAT Edition 1, damage 5-194). This damage is from a level 6 soldier:

![image](https://github.com/project-rubika/issues/assets/3063240/c0fb6675-69cd-4e34-8fd5-a641d5ef1ae5)

**Comment by playboyfixer** [comment]
checked several basic shops and didn't find anything that didn't belong either

**Comment by prkdrake** [comment]
Great, thanks for checking!
