### ISSUE TITLE
Character names are not filtered/checked

### ISSUE THREAD

**Issue by abc** [project-rubika/issues#323]
**Describe the bug**
I'm not sure if this is a bug or a feature, but it's possible to create characters with naughty words in their names.

**Comment by abc** [comment]
Should now be fixed. I have added name validation with these rules:"
- Must always start with an uppercase letter.
- Must only contain alphanumeric characters (A-Z, 0-9)
- Must only have one uppercase letter. 
- Must not match a word in the banned list.

Currently, the banned list is just two words: `bannedword` and `cunt`. There is a system in place to whitelist names, which has been implemented for `scunthorpe`. 

If someone could test this and respond that it's working as expected then we can close this ticket. Thanks :)

**Comment by portalerprk** [comment]
Tested. LGTM
