### ISSUE TITLE
Zoning into buildings doesn't face away from the door you entered automatically

### ISSUE THREAD

**Issue by Unknownprk** [project-rubika/issues#326]

**Comment by prkdrake** [comment]
This is an issue with the Subway. Would be nice to have this fixed for the subway event, it's really noticeable.

**Comment by prkdrake** [comment]
This has now been fixed, needs confirmation that it's fixed :)

**Comment by jellyfinapkdd** [comment]
Tested about 10 shops and subway, all faced right way. I did find however find backyard/arrival in bor faced wrong way. Found this in backyard 7,8 and 9.

**Comment by prkdrake** [comment]
Thanks - those playfields you mentioned which don't work are actually different, this change only applies to a certain type of playfield called a proxy playfield, you can tell when you enter one when you see "NEW PF" in the chat. We'll get around to fixing the other doors as a seperate issue
