### ISSUE TITLE
You can have more than one normal engineer robot pet 

### ISSUE THREAD

**Issue by abc** [project-rubika/issues#328]
**Describe the bug**
Engineers should have a limit of one normal robot pet and one dog robot pet. At present, there is no limit.

**To Reproduce**
1. Login as an engineer
2. Cast the Feeble Automaton nano
3. Right-click the engineer shell in your inventory.
4. Cast the Feeble Automaton nano again.
5. Right-click the other engineer shell in your inventory.
6. Notice that you now have two robot pets. 

**Expected behavior**
You should get an error message that says you're only allowed to have one pet. Check live for exact wording. 

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/3063240/d4220467-352a-47ea-936a-97c98fa3163e)

**Additional context**
- Playfield: neutral backyard
- Character Name: blakeengi

**Comment by portalerprk** [comment]
I think this has been inadvertently fixed.

**Comment by prkdrake** [comment]
I can confirm that this has now been fixed.
