### ISSUE TITLE
Buying multiples of the same item from a vendor costs the same as one

### ISSUE THREAD

**Issue by abc** [project-rubika/issues#329]
**Describe the bug**
If you buy multiple copies of the same item, for example, if you buy 5x Simple First-Aid Kit for 26 credits, you are only charged for one of the sets of First-Aid Kits, e.g. you are charged 26 when you should be charged 156 credits. (26 credits * 5 = 156 credits)

**To Reproduce**
1. Set your cash to 1000.
2. Buy 2 copies of the same item from a vendor.
3. Notice that your cash has only been deducted by the price of one of the item.

**Expected behavior**
Your cash should be deducted for the full price of the goods you purchase.

**Comment by RaggyLP** [comment]
Confirmed using ammo.

![image](https://github.com/project-rubika/issues/assets/156821187/69691ad3-8408-4629-a7a3-a83b65416a5d)
![image](https://github.com/project-rubika/issues/assets/156821187/f4831f93-ba78-4a10-8dc1-429acc17b5da)

Interestingly, this also works on items that generate seperate inventory instances, but has a totally seperate issue of the cost being determined incorrectly.

![image](https://github.com/project-rubika/issues/assets/156821187/3b93da48-802d-42b5-a9a0-ccb3849c6f91)
![image](https://github.com/project-rubika/issues/assets/156821187/d3e898d6-b9c7-4e1a-bb1f-b5c511c5d64f)

The vost/value calculation for multiple purchases is possibly incorrect.

**Comment by prkdrake** [comment]
Should be fixed now, please take a look and let us know! Thanks :)

**Comment by TheTinkeringIdiot** [comment]
This appears to be fixed!

![image](https://github.com/project-rubika/issues/assets/96996793/72c75cf0-f4a2-4c98-9667-e857f338bb93)
