### ISSUE TITLE
Players can’t target themselves with hostile nanos

### ISSUE THREAD

**Issue by abc** [project-rubika/issues#332]
**Describe the bug**
On live servers, you can hit yourself with hostile nanos. I believe that the False Profession nano line is technically hostile, so we probably need to implement this too. 

**To Reproduce**
1. Log in as a Nano Technician.
2. Try to cast an NT nuke on yourself.
3. Notice "Your target can't be attacked." in system chat.

**Expected behavior**
You should be able to hit yourself with hostile nanos.

**Comment by portalerprk** [comment]
Fix is in `refs/develop` .

**Comment by prkdrake** [comment]
I can confirm that this has been fixed.
