### ISSUE TITLE
Occasionally vendors have no items

### ISSUE THREAD

**Issue by abc** [project-rubika/issues#336]
**Describe the bug**
Sometimes, when you enter a playfield, vendor inventories aren't loaded properly, so there is no items in any of the shops.

**To Reproduce**

This bug is intermittent, I'm not sure what conditions it happens under, but it seems to be when you enter a playfield quickly after first logging in.

1. Log in and go into a playfield with shops, e.g. Borealis Fairtrade.
2. Open one of the vendors.
3. The shop is empty.

**Expected behavior**
The shop shouldn't be empty.

**Comment by prkdrake** [comment]
Closed because this was caused by #400 and has been (mostly) fixed now.
