### ISSUE TITLE
Leveling items do not work

### ISSUE THREAD

**Issue by SharpTony** [project-rubika/issues#337]
**Describe the bug**
For example, trying to level up Morphing Memories or tier armor does not work.

**To Reproduce**
1. Get a Morphing Memory (`/item 202726 202727 1`)
2. Right click the morphing memory
3. Notice the morphing memory doesn't increase in QL.

**Expected behavior**
The morphing memory should increase in QL.

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/69978423/1bcb8aa7-5798-4c3b-8e74-474433a6354d)

**Comment by S4ff0** [comment]
![immagine](https://github.com/project-rubika/issues/assets/56939765/08fe670d-22a1-4d36-9ee6-432822764272)
![immagine](https://github.com/project-rubika/issues/assets/56939765/b362a389-7fe4-490b-88ae-69e3a0fc4c8a)
![immagine](https://github.com/project-rubika/issues/assets/56939765/20895176-f093-4d06-919d-2c9f13a1620e)
seems to work

**Comment by S4ff0** [comment]
but when i tried to right click the weared item it just duplicate it xd
one inside bag one still wearing;

**Comment by prkdrake** [comment]
Yep, confirmed working now.
> but when i tried to right click the weared item it just duplicate it xd

Didn't happen for me with Morphing Memory, I got this message instead:

> Items must be unequipped before they can be deleted!

Possible that Living Cyber armor has this bug? Can you reproduce and raise a bug report if you see that error again please @S4ff0? Thank you! <3

Closing this ticket as original issue is solved.

**Comment by prkdrake** [comment]
Actually, I did manage to reproduce something similar - it did upgrade the item and it appeared to duplicate, but it was actually unequipped and upgraded and disappeared from my deck and appeared in my inventory when I zoned. So it is using instead of unequipping the item, which isn't correct, so a bug ticket should indeed be created for that.
