### ISSUE TITLE
Quantum Wings conditions aren't checked properly

### ISSUE THREAD

**Issue by SharpTony** [project-rubika/issues#338]
**Describe the bug**
When you go to cast Quantum Wings, if you're in a normal Rubi-Ka playfield, you get the error: Unable to execute nano program. You can't execute this nano on the target.

However, if you go into a proxy playfield (e.g. the interior of Rome Blue Basic (`/tp rbb`) you can cast the nano.

**To Reproduce**
1. Go to MP
2. Click on Quantum Wings
3. Scroll down to system chat window
4. See error or Notice this behavior

**Expected behavior**
You should fly around like a pretty bird

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/69978423/c7a2b99e-298b-42de-b914-9bff400a65a9)

**Comment by prkdrake** [comment]
This has been fixed now, needs verified.

**Comment by jellyfinapkdd** [comment]
Tested, works great. No problems here.
