### ISSUE TITLE
PvP flag disappears when zoning

### ISSUE THREAD

**Issue by SharpTony** [project-rubika/issues#339]
**Describe the bug**
When flagged, zoning will remove flags from around the name, but the nano will still be present in your NCU.

**To Reproduce**
1. Go to attack a guard, then zone
2. Click on your toon
3. Scroll down to NCU window
4. See error or Notice this behavior, flags will be gone from player's name, but nano persists in ncu

**Expected behavior**
The flags should always be visible as long as the nano is in your NCU

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/69978423/21c559b3-f571-4852-a590-393d2700db16)

**Comment by portalerprk** [comment]
Done.

**Comment by prkdrake** [comment]
I can confirm this is fixed now.
