### ISSUE TITLE
Concealment breaks combat

### ISSUE THREAD

**Issue by SharpTony** [project-rubika/issues#340]
**Describe the bug**
Using conceal and trying to use a special completely breaks combat.  Conceal also has a 0 second cooldown, but does not actually do anything.

**To Reproduce**
1. Go to a mob
2. Click on H and try to attack
3. Scroll down to combat window
4. See error or Notice this behavior - it should let you sneak around and use certain specials

**Expected behavior**
You should be able to sneak past mobs if your concealment is high enough, as well as use Aimed Shot/Sneak Attack.

**Comment by prkdrake** [comment]
@SharpTony Could you get a minute to take another look at this and let us know if we can close it, please?

Thank you!

**Comment by prkdrake** [comment]
Closing this because as far as I can tell it's all working as intended.
