### ISSUE TITLE
It’s possible to hit an NPC which is already dead/dying 

### ISSUE THREAD

**Issue by abc** [project-rubika/issues#343]
**Describe the bug**
Under certain circumstances, it’s possible to hit an NPC again after it’s already dead. For example, if you one-hit kill an enemy with a special attack, your character will often immediately follow up with a regular attack too, even as the NPC has hit zero hp and is going through it’s death animation. This doesn’t occur on live. 

**To Reproduce**
1. Play with a high level character who does a good bunch of damage and equip some gear with a special attack. 
2. Go find a low level npc e.g. a level 1 backyard mob. 
3. Instead of starting combat with q, hit the enemy with a special attack e.g. burst, fling shot, full auto, etc. 
4. Sometimes, you will hit the NPC multiple times, even if the initial attack kills it instantly. 

**Expected behavior**
You shouldn’t hit an NPC any more after it has died/is dying.

**Comment by portalerprk** [comment]
Resolved. Silly mistake.

**Comment by prkdrake** [comment]
Looks fixed now, thanks!
