### ISSUE TITLE
NPCs recover HP much faster than is expected

### ISSUE THREAD

**Issue by abc** [project-rubika/issues#344]
**Describe the bug**
At present, NPCs that you’re engaged in combat with occasionally seem to be healing themselves as though you’re not in combat with them, e.g. they seem to have a much higher than usual HP recovery rate. 

**Expected behavior**
While you’re in combat with an NPC, it should only heal from natural HealDelta (which is almost unnoticeably slow for most mobs) and from any healing nanos/effects on it, e.g. if it casts a healing nano or has a HoT running. 

If the NPC is out of combat, e.g. if the player fighting it leaves/dies or if it cannot engage a player attacking it (for example, if it can’t reach a player standing behind some barrier), it should recover HP much faster.

**Comment by prkdrake** [comment]
This should now be fixed.

**Comment by Random823** [comment]
I tested this with several mods on RK, looks like this fixed.

**Comment by prkdrake** [comment]
Thank you!
