### ISSUE TITLE
Buff nanos can’t be cast on pets

### ISSUE THREAD

**Issue by abc** [project-rubika/issues#346]
Pet classes such as MP and Engineer or an Agent under False Profession should be able to buff their pets. No other player should be able to cast buffs on pets, however.

**Comment by portalerprk** [comment]
The requirement for these types of nanos includes a check on "NpcFamily" (stat 455) .. but we miss classified that as another stat. The NpcFamily issue has been fixed however still need to implement the serverside check to only allow targeting your OWN pets.

**Comment by S4ff0** [comment]
i tried  Medical buff "Evocation of Unrestricted Ferocity" 
but it says "Unable to execute nano program. You can't execute this nano on the target."  when i tried to buff  "fury Externalization"

**Comment by portalerprk** [comment]
Try one more time. Apologies. Our automatic deployments were turned off so Ithaca hadn't had the latest code.

**Comment by S4ff0** [comment]
will try asap;

**Comment by S4ff0** [comment]
![immagine](https://github.com/project-rubika/issues/assets/56939765/88f99be9-ad55-4644-90d4-d69e2471aecb)
seems to work ; i could use that buff from mp on pet attack ;
