### ISSUE TITLE
Pets do not follow correctly

### ISSUE THREAD

**Issue by abc** [project-rubika/issues#347]
Pets have really bad tracking of their controllers.

**Comment by TheTinkeringIdiot** [comment]
Confirmed. 

From #492 (closed as duplicate):

![image](https://github.com/project-rubika/issues/assets/96996793/be82ccea-5552-40b9-9083-b4f9627dcf8b)

![image](https://github.com/project-rubika/issues/assets/96996793/408f4168-1304-4843-bbde-06f8e23a050e)

**Comment by TheTinkeringIdiot** [comment]
Info from #440 

![image](https://github.com/project-rubika/issues/assets/96996793/28b0635d-90b0-4923-beca-6b656754c9b4)

![image](https://github.com/project-rubika/issues/assets/96996793/1c388116-f338-4a20-9573-cee7d1fc5e1d)

![image](https://github.com/project-rubika/issues/assets/96996793/f4c7acd7-b358-4800-b043-6bb183f73771)

**Comment by TheTinkeringIdiot** [comment]
This issue is fixed. Pets now correctly follow their masters, and follow orders as they should.
