### ISSUE TITLE
Weapon vendors do not have any actual weapons for sale

### ISSUE THREAD

**Issue by abc** [project-rubika/issues#349]
Weapon vendors (e.g. inside RBB) no longer have any weapons for sale; they're ammo vendors now! I'm guessing this is a minor regression caused by the interpolation changes; it's probably a minor fix.

**Comment by prkdrake** [comment]
Should be working again.

**Comment by jellyfinapkdd** [comment]
Tested with omni,clan and neutral stores. All weapon vendors had weapons for sale.

Did basic, advanced and superior.

**Comment by westtell4** [comment]
and i can confirm this is working

**Comment by prkdrake** [comment]
Awesome, thanks :)
