### ISSUE TITLE
Smugglers Den Entrance Not working

### ISSUE THREAD

**Issue by westtell4** [project-rubika/issues#352]
**Describe the bug**
The Smugglers Den  Entrance hole is not Doing anything.

**To Reproduce**
teleport to Smugglers den  from the /showfile Menu  thingy run into entrance the  expected result does not happen

**Expected behavior**
Enter the smugglers Den

Extended location information:
- 1752.6, 870.7, 13.8 (1752.6 870.7 y 13.8 615)
- Pf Proxy: Model=51100:615 GS=0 SG=0 R=615, resource: 615
- zone: 1681, area: "Os"
Server id: 1, character id: 50000:581, time: 2023-12-12 15:29:29 (UTC)
Version: 00.3.2_EP1, map id: NOT FOUND, build: 52606
 
also getting this
 ----------------------------------
------SEND THIS TO THE DEVS------
  destProxyModelType: 51102
  destProxyModelInst: 125
  destProxyGroup: 0
  destProxySubgroup: -1072889241
  destProxyLocalizerType: 100002
  destProxyLocalizerInst: 2
----------------------------------

**Comment by Unknownprk** [comment]
Should be fixed now

**Comment by westtell4** [comment]
Doesn't seem to be working

**Comment by westtell4** [comment]
Working as intended
