### ISSUE TITLE
Newly created Adventurer starts with 2x Solar Powered Pistol rather than 2x Solar Powered Adventuring Pistol

### ISSUE THREAD

**Issue by westtell4** [project-rubika/issues#353]
Make a new adventurer and it doesn't start with its proper weapons 
 
Drake wanted me to add :
The root problem with this is that the template cluster for Solar Powered Pistol and Solar Powered Adventuring Pistol share the same hash and QL, but have a different item ID. So we need to add the ability to load a template cluster based not only on hash, but also parent hash

**Comment by prkdrake** [comment]
Should now be fixed

**Comment by westtell4** [comment]
Can Confirm it is working as intended
