### ISSUE TITLE
Mob levels in Subway are not correct

### ISSUE THREAD

**Issue by sagstuen** [project-rubika/issues#357]
Tested on level 15 keeper

The mobs in here are all level 1 and level 10.
- Muggers are level 10, and apear green to me.
- Rest of the level10 mobs are grey to me

Everything before the stairs are level 1.
Everything after the stairs apear to be level 10, Except mobs that are also before the stairs

Fragmented Soul actually aggroed me.... level 10, but grey.

Eumenides apears level 10, but are grey.
Vergil Aeneid is level 25, and blood red.

Abmouth does not spawn.

**Comment by sagstuen** [comment]
Correction to this.... Noticed after the report that I had actually leveled from 15 to 16. Set my level back to 15, and the level 10 mobs are green to me agin, so discard that.

Nevertheless... all mobs before the stairs are level 1, and everything after is level 10, except mobs also before the stairs.

**Comment by prkdrake** [comment]
Should be fixed now, though I noticed another issue, but I will raise as a separate ticket. @sagstuen (or any other beta tester) could you please re-test this and let me know if you're happy for it to be closed? Thanks!

**Comment by westtell4** [comment]
seems to be fine i don't remember everything  exact levels but feels fine to me (spent alot of time in the subway)

**Comment by prkdrake** [comment]
Thank you :)
