### ISSUE TITLE
Weapons not consuming Ammo

### ISSUE THREAD

**Issue by westtell4** [project-rubika/issues#358]
it would seem that weapons are not consuming Ammo

Went to a vendor bought the original electronicum X2
used them in combat without Energy ammo in my inventory

**Expected behavior**
the Expected behavior is that the Weapon will have a fixed number of rounds Before it needs to reload pulling ammo from the player characters inventory

**Screenshots**
![bcd39b9937b216d4fe189effebb5b05c](https://github.com/project-rubika/issues/assets/11027099/76cbd73a-124e-487d-9d96-19ce891fa16f)
![58d1b1e4df1c4e7842f1e0b1c6e87ffd](https://github.com/project-rubika/issues/assets/11027099/a43a259c-8e8b-42cf-a49a-0a1608123b5e)

**Comment by portalerprk** [comment]
https://github.com/project-rubika/issues/assets/60405799/a3e2c8c2-48c3-456c-b975-7c74fc366643

**Comment by abc** [comment]
> Went to a vendor bought the original electronicum X2
used them in combat without Energy ammo in my inventory

On live, this works too. Purchased guns come with ammo in them, and only need more ammo when you reload. So the Electronicum would be able to be used for 20 shots before you start getting the "out of ammo" message

**Comment by portalerprk** [comment]
On PRK, it seems default ammo count is `1/ClipSize` We can make sure they sell with a full clip. :-P 

Also, an interesting note. The client will send some sort of packet related to manual reloading your weapon if you hit "R" on they keyboard. We appear to not be processing this packet.

**Comment by abc** [comment]
That's strange, the default reload keybind is V. It's an action in the Actions menu (CTRL+2) as well.

**Comment by portalerprk** [comment]
https://github.com/project-rubika/issues/assets/60405799/c580544f-199d-4d7d-97b8-06632c8df47a

**Comment by westtell4** [comment]
The thing is it was at 1/20  on both guns and not stoping to reload

**Comment by westtell4** [comment]
https://gyazo.com/80184997d90b5dbad7ee4c36a81613af here is a short video of it with no reloading and 1/20 after combat

**Comment by westtell4** [comment]
https://gyazo.com/dc5398bc09cad9c9c0f82123350f1090 finally started yelling about ammo  near end of the video but still doesn't show a number of shots in the description

**Comment by portalerprk** [comment]
Ok! @westtell4  give it another shot on Ithaca. Apologies for the back and forth on this one. As is often the case, its tricky. There is a packet responsible to informing the client about a weapon's details. The order in which we send it in relation to adding to your inventory is important and was not correct. Additionally the field in that packet responsible for placement was using an incorrect value.

So I _**think**_ it should be ok now. Please test on Ithaca.

**Comment by westtell4** [comment]
One of them is working.. One of them is not https://gyazo.com/05b01e204d48d353f3dc293c06466e7f here is a video the first part of this video i'm using the  broken one when i hit V to reload it says action is not available... near the end i switch to one that works

**Comment by portalerprk** [comment]
> One of them is working.. One of them is not https://gyazo.com/05b01e204d48d353f3dc293c06466e7f here is a video the first part of this video i'm using the  broken one when i hit V to reload it says action is not available... near the end i switch to one that works 
> 
> 

How did you get each gun into your inventory, and does the problem go away after you zone/camp?
