### ISSUE TITLE
Solar powered weapons try to use ammo.

### ISSUE THREAD

**Issue by 3F1-1009** [project-rubika/issues#360]
**Describe the bug**
Solar powered weapons stop working after you try to reload them or equip/re-equip them

**To Reproduce**
1. Get a Solar Powered Pistol (/item 121567 121567 1)
2. Equip the pistol
3. Attack something
4. You get a message that you have no ammo for Solar Powered Pistol.
5. If you do not get the message, try to reload the weapon.

**Expected behavior**
Solar powered weapons do not use ammo.

**Screenshots**

**Character info:**

```
Copy/paste the output of /getfull here
```

**Playfield info:**

```
Copy/paste the output of Shift+F9 here
```
----

**Comment by westtell4** [comment]
Can confirm this is working

**Comment by prkdrake** [comment]
Thanks :)
