### ISSUE TITLE
Eumenides doesn't spawn properly

### ISSUE THREAD

**Issue by portalerprk** [project-rubika/issues#361]
A little birdie has said that Eumenides does not spawn properly. We need to verify and fix if not proper.

**Comment by RaggyLP** [comment]
Eumenides is spawning correctly at the relevant location.

![image](https://github.com/project-rubika/issues/assets/156821187/87499daa-2f19-4761-b0a4-f44224d21cb7)


Closing as fixed as of 23:07 UTC - 27/01/24
