### ISSUE TITLE
Mob instances always have the same level, even if it's meant to be variable

### ISSUE THREAD

**Issue by prkdrake** [project-rubika/issues#363]
**Describe the bug**
Many mobs have a level range, which denotes a minimum and a maximum level. Each instance of such an NPC should randomly have a level between this range.

What's actually happening is that the level is being rolled once per instance per playfield, so if you enter, e.g. Galway County outside of Rome Blue, every Male Captain will have the same level.

**Comment by Zolarix** [comment]
Verifying using Subway -> Filth Fleas as the example via this report: https://github.com/project-rubika/issues/issues/451

Worth mentioning that according to the player in the report, this didn't happen until after they killed a couple of fleas. However there is no screenshot evidence that the fleas were ever the expected level for the start of the subway.

**Comment by Zolarix** [comment]
Adding that on a subsequent visit to the Subway, all the mobs had their levels scrambled again, with the filth fleas all being level 12 this time. I was unable to manipulate their level by killing them.

**Comment by prkdrake** [comment]
This should be fixed now, please re-test and let us know, thanks!

**Comment by TheTinkeringIdiot** [comment]
This appears to be fixed. I checked in Subway and ToTW and confirmed that same type mobs (i.s. Filth Fleas, Cultists, etc) exist in a range of levels appropriate to the instance.
