### ISSUE TITLE
Eumenides uses melee combat animation instead of guns

### ISSUE THREAD

**Issue by portalerprk** [project-rubika/issues#364]
![Image](https://github.com/project-rubika/issues/assets/60405799/01136c79-116a-4672-af9e-6416c335edcf)

**Comment by prkdrake** [comment]
When I saw him, he was using his gun properly. As Portaler suggested, this is probably a strange race condition about whether or not his weapon or him loads first.

**Comment by prkdrake** [comment]
I believe this should have been fixed by the system changes - needs re-checking.

**Comment by RaggyLP** [comment]
![image](https://github.com/project-rubika/issues/assets/156821187/467786e9-6637-44f8-a634-2a867a2f88fd)

Eumenides now actively uses his gun (and casts buffs!). Confirmed fixed as of 18:31 UTC - 25/01/24

**Comment by prkdrake** [comment]
Good for him, hope that +13 AC or whatever it is serves him well :P Thanks for confirming
