### ISSUE TITLE
Players aren't warned when teaming beyond level range

### ISSUE THREAD

**Issue by prkdrake** [project-rubika/issues#368]
**Describe the bug**
Each level has a range of levels for players they can team with and still gain XP. For example, a level 10 character can team with players between level 4 and level 17. If a player in the team is level 3, that character will not gain any XP. If a character in the team is level 18 or above, then the level 10 player will not gain any XP.

When inviting a player above the level of the lowest level player in the team, the team leader should get a warning which checks they're sure they want to invite that player. Likewise, when a player is invited into a team where they wouldn't gain XP, they also should get a confirmation dialog box.

This feature has not been implemented yet - the invite does not care about levels.

**Comment by prkdrake** [comment]
Involved messages are an N3 message 135/112 with CharacterActionType Action: 168/169.

**Comment by prkdrake** [comment]
Parameter2 = 1 is used as confirmation on the TeamRequest message

**Comment by prkdrake** [comment]
This has been partially implemented. At present, the "too high" warning is sent if target is higher level than leader, and "too low" if the target is lower than leader. Need to check the actual team caps for all team members.

**Comment by prkdrake** [comment]
Fully implemented now, ready for testing :)

**Comment by Random823** [comment]
Created second account to test this, everything looks great. Get the message as expected.

**Comment by prkdrake** [comment]
Awesome, thanks for confirming!

**Comment by Zolarix** [comment]
Also verified fixed - removing `Fixed - Needs Verification`
