### ISSUE TITLE
Every player in a team gets the same amount of XP

### ISSUE THREAD

**Issue by prkdrake** [project-rubika/issues#370]
**Describe the bug**
On Live, when you're teamed up, XP is, in some way at least, split among team members, though it's not an even split - some extra/bonus XP is created I believe. The idea being that you share the XP, but you can kill faster, so it's overall a gain to levelling speed. 

What we have on PRK is that everyone in the party gains the same amount of XP as the highest level character in the party would gain from killing the mob solo.

We should probably discuss what we want, or implement some system where we can easily tweak the values, before implementing an exact system to decide how XP gains are handled in a team.

**Comment by TheTinkeringIdiot** [comment]
This has been fixed in recent updates, and team members of different levels no longer gain the same amount of XP.
