### ISSUE TITLE
Follow command is not implemented

### ISSUE THREAD

**Issue by prkdrake** [project-rubika/issues#374]
The command /follow should cause you to follow slightly behind another player. When you type it, nothing happens.

**Comment by RaggyLP** [comment]
Confirmed, however, the command is accepted wiht the following message.
![image](https://github.com/project-rubika/issues/assets/156821187/8f60e088-26e6-4ee1-9e16-cb2aa4321eea)
But, no movement occurs.

**Comment by TheTinkeringIdiot** [comment]
Confirmed this remains an issue after recent updates to mob pathing.

**Comment by RaggyLP** [comment]
/follow is now implemented as of 16/08/24.
