### ISSUE TITLE
Items within backpacks disappear on logout

### ISSUE THREAD

**Issue by S4ff0** [project-rubika/issues#381]
backpack inside backpack that have items are just temporarily; if you log out and relogin - all the items inside the backpack inside the main backpak will all disappear ;

main backpack -> small backpack -> items   *** all items going to disappear on relog;

**Comment by S4ff0** [comment]
items inside bank don't save position ( if relog or zoning - exit shop and reenter)

**Comment by S4ff0** [comment]
i tried to move a small back pack inside bank and could not take it back correctly; 
even if i get it inside back i can t open it; 
if i zone or logout login the item is not anymore a smallbackpack but something else inside bank; in my case a map reader upgrade - side lvl 1;

**Comment by prkdrake** [comment]
@S4ff0 Please create one issue per problem you have noticed - could you please split your comments into new issues? Thanks!

**Comment by S4ff0** [comment]
sure i can;  i just thinked it was all part of the same problem ; sorry ^

**Comment by portalerprk** [comment]
By "backpack within backpack" I'm guessing you mean, "backpack within inventory"? If so this has been fixed. 

If you mean putting a backpack within another backpack inside your inventory/bank.. I don't think even live allows this?

**Comment by S4ff0** [comment]
i mean small back pack inside inventory (with items inside)
so main inventory -> small back pack -> items * those will despawn / disappear if u relog;
