### ISSUE TITLE
Items in bank have their slot position reset on zone

### ISSUE THREAD

**Issue by S4ff0** [project-rubika/issues#382]
items inside bank don't save position ( if relog or zoning - exit shop and reenter)

**Comment by portalerprk** [comment]
Should be fixed.

**Comment by S4ff0** [comment]
moved position of items inside back and inside small back pack
moved back in inventory or in bank 
zoned and logout login  all consistency :) good  WORKING ; 
(i remember there was a dupe bug with conteiner but don't remember how to  reproduce; if here is not working its better then official lol )
