### ISSUE TITLE
Containers placed into the bank have unusual behaviour

### ISSUE THREAD

**Issue by S4ff0** [project-rubika/issues#383]
i tried to move a small back pack inside bank and could not take it back correctly;
even if i get it inside my backback i can t open it (seems it moved the wrong item but with small back pack icon)
if i zone or logout login the item is not anymore a smallbackpack but something else inside bank; in my case a map reader upgrade - side lvl 1; the small backpack is still inside bank but can't do anything to get it out xd;

**Comment by portalerprk** [comment]
Should be fixed.

**Comment by S4ff0** [comment]
i could move the item small back pack from inside back put stuff inside  let it back in back and get back in inventory;
all seems to work smootly;
zoned working;
Log out / log in working ;
seems ok ^_-
