### ISSUE TITLE
Entering certain buildings results in a map not found error | Send this to the Devs

### ISSUE THREAD

**Issue by S4ff0** [project-rubika/issues#385]
can't enter zone in rome
------SEND THIS TO THE DEVS------
  destProxyModelType: 51102
  destProxyModelInst: 1191
  destProxyGroup: 0
  destProxySubgroup: -1073478945
  destProxyLocalizerType: 100002
  destProxyLocalizerInst: 1
----------------------------------
Extended location information:
- 545.5, 286.9, 17.4 (545.5 286.9 y 17.4 735)
- Pf Proxy: Model=51100:735 GS=0 SG=0 R=735, resource: 735
- zone: 188, area: "Rome Blue"
Server id: 1, character id: 50000:538, time: 2023-12-25 03:33:20 (UTC)
Version: 00.3.6_EP1, map id: NOT FOUND, build: 52606.

![immagine](https://github.com/project-rubika/issues/assets/56939765/1ff41889-1324-490d-8645-ba331d6ea059)

**Comment by prkdrake** [comment]
Other instances of this issue: #386 #387 #388

Unknown has an idea for a fix for this issue

**Comment by RaggyLP** [comment]
`------SEND THIS TO THE DEVS------
  destProxyModelType: 51102
  destProxyModelInst: 2060
  destProxyGroup: 0
  destProxySubgroup: -1073675488
  destProxyLocalizerType: 100002
  destProxyLocalizerInst: 1
----------------------------------


Extended location information:
- 674.9, 584.7, 68.7 (674.9 584.7 y 68.7 800)
- Pf Proxy: Model=51100:800 GS=0 SG=0 R=800, resource: 800
- zone: 366, area: "Borealis"
Server id: 764, character id: 50000:764, time: 2024-01-17 22:34:32 (UTC)
Version: 00.4.5_EP1, map id: NOT FOUND, build: 52606.

`
![image](https://github.com/project-rubika/issues/assets/156821187/351c3634-3dcd-4645-b073-68dcdb7b47a4)

**Comment by RaggyLP** [comment]
`------SEND THIS TO THE DEVS------
  destProxyModelType: 51102
  destProxyModelInst: 2060
  destProxyGroup: 0
  destProxySubgroup: -1072495840
  destProxyLocalizerType: 100002
  destProxyLocalizerInst: 1
----------------------------------

Extended location information:
- 708.2, 704.1, 67.5 (708.2 704.1 y 67.5 800)
- Pf Proxy: Model=51100:800 GS=0 SG=0 R=800, resource: 800
- zone: 442, area: "Borealis"
Server id: 1, character id: 50000:764, time: 2024-01-17 22:38:03 (UTC)
Version: 00.4.5_EP1, map id: NOT FOUND, build: 52606.
`

![image](https://github.com/project-rubika/issues/assets/156821187/64344f28-15f9-4ca3-9a30-f129dd97f523)

**Comment by RaggyLP** [comment]
`------SEND THIS TO THE DEVS------
  destProxyModelType: 51102
  destProxyModelInst: 2003
  destProxyGroup: 0
  destProxySubgroup: -1073151360
  destProxyLocalizerType: 100002
  destProxyLocalizerInst: 1
----------------------------------

Extended location information:
- 418.3, 474.2, 8.0 (418.3 474.2 y 8.0 640)
- Pf Proxy: Model=51100:640 GS=0 SG=0 R=640, resource: 640
- zone: 230, area: "Downtown Tir"
Server id: 1, character id: 50000:764, time: 2024-01-17 23:06:22 (UTC)
Version: 00.4.5_EP1, map id: NOT FOUND, build: 52606.
`

![image](https://github.com/project-rubika/issues/assets/156821187/76c33ca6-7d09-4f16-83a9-3dbee2882863)

**Comment by RaggyLP** [comment]
------SEND THIS TO THE DEVS------
  destProxyModelType: 51102
  destProxyModelInst: 1321
  destProxyGroup: 0
  destProxySubgroup: -1065483648
  destProxyLocalizerType: 100002
  destProxyLocalizerInst: 2
----------------------------------
Extended location information:
- 401.6, 482.6, 11.9 (401.6 482.6 y 11.9 640)
- Pf Proxy: Model=51100:640 GS=0 SG=0 R=640, resource: 640
- zone: 250, area: "Downtown Tir"
Server id: 430, character id: 50000:764, time: 2024-01-17 23:11:07 (UTC)
Version: 00.4.5_EP1, map id: NOT FOUND, build: 52606.

![image](https://github.com/project-rubika/issues/assets/156821187/af1a8003-edd5-42ea-a60e-670626462b5e)

**Comment by TheTinkeringIdiot** [comment]
------SEND THIS TO THE DEVS------
  destProxyModelType: 51102
  destProxyModelInst: 1191
  destProxyGroup: 0
  destProxySubgroup: -1071643962
  destProxyLocalizerType: 100002
  destProxyLocalizerInst: 1
----------------------------------

```
Extended location information:
- 334.7, 204.1, 6.6 (334.7 204.1 y 6.6 710)
- Pf Proxy: Model=51100:710 GS=0 SG=0 R=710, resource: 710
- zone: 108, area: "Trade District"
Server id: 1, character id: 50000:1092, time: 2024-01-24 03:51:47 (UTC)
Version: 00.4.6_EP1, map id: NOT FOUND, build: 52606.
```

![image](https://github.com/project-rubika/issues/assets/96996793/6e19bad4-a657-46cc-89d7-746c3be3c4ba)

**Comment by TheTinkeringIdiot** [comment]
![image](https://github.com/project-rubika/issues/assets/96996793/9134df71-cfdb-47d3-a8cc-ba922d1e13ce)

```
Extended location information:
- 509.6, 1807.4, 39.4 (509.6 1807.4 y 39.4 716)
- Pf Proxy: Model=51100:716 GS=0 SG=0 R=716, resource: 716
- zone: 1542, area: "Omni-Pol Barracks Region"
Server id: 1, character id: 50000:1165, time: 2024-01-27 21:55:08 (UTC)
Version: 00.4.7_EP1, map id: NOT FOUND, build: 52606.
```

**Comment by RaggyLP** [comment]
------SEND THIS TO THE DEVS------
  destProxyModelType: 51102
  destProxyModelInst: 1833
  destProxyGroup: 0
  destProxySubgroup: -1073282425
  destProxyLocalizerType: 100002
  destProxyLocalizerInst: 1
----------------------------------

![image](https://github.com/project-rubika/issues/assets/156821187/40db1086-c37f-4a9d-bac8-9732a42c133c)

```
Extended location information:
- 3231.2, 2338.1, 25.5 (3231.2 2338.1 y 25.5 647)
- Pf Proxy: Model=51100:647 GS=0 SG=0 R=647, resource: 647
- zone: 5358, area: "Cyborg Encampment"
Server id: 1, character id: 50000:1028, time: 2024-01-28 19:32:17 (UTC)
Version: 00.4.7_EP1, map id: NOT FOUND, build: 52606.
```

**Comment by feralfern** [comment]
![feralfern bug1](https://github.com/project-rubika/issues/assets/166332288/d0a9c06a-30e6-4b5c-b695-382deecaa66e)


------SEND THIS TO THE DEVS------
  destProxyModelType: 51102
  destProxyModelInst: 2030
  destProxyGroup: 0
  destProxySubgroup: -1069677887
  destProxyLocalizerType: 100002
  destProxyLocalizerInst: 1
----------------------------------

**Comment by TheTinkeringIdiot** [comment]
Reported by @dahomburg in #726 

In Borealis POS 674.5, 587.8, 66.8, facing south, between agency sign and whop-pah sign, trying to enter "Basic Weapon Shop" instead of Playfield change I got that:
------SEND THIS TO THE DEVS------
destProxyModelType: 51102
destProxyModelInst: 2060
destProxyGroup: 0
destProxySubgroup: -1073675488
destProxyLocalizerType: 100002
destProxyLocalizerInst: 1

**Comment by Starbouy138** [comment]
Mining Shacks in Clondyke

------SEND THIS TO THE DEVS------
  destProxyModelType: 51102
  destProxyModelInst: 1627
  destProxyGroup: 0
  destProxySubgroup: -1069153634
  destProxyLocalizerType: 100002
  destProxyLocalizerInst: 1
----------------------------------

Extended location information:
- 2518.4, 2290.0, 1.3 (2518.4 2290.0 y 1.3 670)
- Pf Proxy: Model=51100:670 GS=0 SG=0 R=670, resource: 670
- zone: 4622, area: "Frisko Forest Heights"
Server id: 1676, character id: 50000:1676, time: 2024-07-14 22:35:25 (UTC)
Version: 00.6.1_EP1, map id: NOT FOUND, build: 52606.

![image](https://github.com/user-attachments/assets/df87c224-dea2-4f9c-a6ea-318245cb091a)

**Comment by Starbouy138** [comment]
Armor Shop at Lush Hills Resort.
------SEND THIS TO THE DEVS------
  destProxyModelType: 51102
  destProxyModelInst: 2051
  destProxyGroup: 0
  destProxySubgroup: -1072168265
  destProxyLocalizerType: 100002
  destProxyLocalizerInst: 1
----------------------------------
Extended location information:
- 1520.1, 524.3, 45.0 (1520.1 524.3 y 45.0 695)
- Pf Proxy: Model=51100:695 GS=0 SG=0 R=695, resource: 695
- zone: 1338, area: "South Fields"
Server id: 1, character id: 50000:1676, time: 2024-07-15 00:43:25 (UTC)
Version: 00.6.1_EP1, map id: NOT FOUND, build: 52606.

![image](https://github.com/user-attachments/assets/588b94b8-bb14-4e2c-b0a7-104350919b3e)

**Comment by Starbouy138** [comment]
Another building at Lush Hills Resort.
------SEND THIS TO THE DEVS------
  destProxyModelType: 51102
  destProxyModelInst: 1191
  destProxyGroup: 0
  destProxySubgroup: -1072364873
  destProxyLocalizerType: 100002
  destProxyLocalizerInst: 1
----------------------------------
Extended location information:
- 1524.0, 546.1, 45.0 (1524.0 546.1 y 45.0 695)
- Pf Proxy: Model=51100:695 GS=0 SG=0 R=695, resource: 695
- zone: 1338, area: "South Fields"
Server id: 1, character id: 50000:1676, time: 2024-07-15 00:50:19 (UTC)
Version: 00.6.1_EP1, map id: NOT FOUND, build: 52606.

![image](https://github.com/user-attachments/assets/9332ef29-0785-40aa-aab5-c9d14324e594)

**Comment by SharpTony** [comment]
![image](https://github.com/user-attachments/assets/718d40ea-6a88-4be3-86a6-7628fa37667b)

**Comment by SharpTony** [comment]
![image](https://github.com/user-attachments/assets/47186d06-4354-42bf-9ec5-2fd218a8b997)

**Comment by Dezzyx** [comment]
### Tir county by NPC Sam Chin. Clan Clothing Shop (top info) and building that just says "Door" (on my right, bottom info)

![Screenshot 2024-08-24 223944](https://github.com/user-attachments/assets/1ce66a7e-9f16-4857-95ee-91b34fe7e65d)

**Comment by Dezzyx** [comment]
### Tir County Outpost, Clan Shops (East road from Sam Chin). 

**Info from top to bottom: Weapons, Pharmacist, Armory. (Supermarket shop is fine)**

![Screenshot 2024-08-24 231705](https://github.com/user-attachments/assets/f4e62b4b-8628-4553-9278-6fe0a91070fd)

**Comment by Dezzyx** [comment]
### Tir Door (apartment?)

------SEND THIS TO THE DEVS------
  destProxyModelType: 51102
  destProxyModelInst: 1330
  destProxyGroup: 0
  destProxySubgroup: -1065745792
  destProxyLocalizerType: 100002
  destProxyLocalizerInst: 1

Extended location information:
- 420.7, 524.1, 8.0 (420.7 524.1 y 8.0 640)
- Pf Proxy: Model=51100:640 GS=0 SG=0 R=640, resource: 640
- zone: 270, area: "Tir City"
Server id: 2052, character id: 50000:2052, time: 2024-08-27 03:25:54 (UTC)
Version: 00.6.3_EP1, map id: NOT FOUND, build: 52606.


![Screenshot 2024-08-27 052114](https://github.com/user-attachments/assets/5872228f-6d8a-4ebc-bfa6-641220454e40)

**Comment by prkdrake** [comment]
All of these should be fixed with the latest update.

**Comment by RaggyLP** [comment]
![its-done-frodo](https://github.com/user-attachments/assets/d2721fb5-76e7-42be-8a31-8e4ad83f07b7)
Confirmed. Closing as fixed as of 03/09/2024!
