### ISSUE TITLE
can't get back item from store

### ISSUE THREAD

**Issue by S4ff0** [project-rubika/issues#389]
once you put an item for sell it can't be traded back in character inventory
![immagine](https://github.com/project-rubika/issues/assets/56939765/1fd6c4f4-bc6f-4db6-adb9-8ba35420f8ea)

**Comment by 3F1-1009** [comment]
Also causes ghost item in equipment tab.

Open trade with shop.
Put something in trade.
(optional) Try to take back the item from trade (doesn't work)
Decline trade.
Unequip something from character equipment (something you had equipped before entering the playfield).
Item you tried to take back from trade is now a ghost item in a slot you unequipped.
