### ISSUE TITLE
right click to autoequip NCU chip or belt, don't work

### ISSUE THREAD

**Issue by S4ff0** [project-rubika/issues#390]
Right clicking on NCU chip (or belt after removing all the chip) will start the time bar but when it complete it don't swap items or get them mounted in the wear window ;
The items just remain in the backpack; 
example

start weared equip 
![immagine](https://github.com/project-rubika/issues/assets/56939765/d3ab9207-6973-4645-b767-148780c0643d)
![immagine](https://github.com/project-rubika/issues/assets/56939765/8fd1e951-7499-4f15-953f-e43ce30ea6f7)
right click on ncu memory give
![immagine](https://github.com/project-rubika/issues/assets/56939765/4b49de19-c593-48a7-8665-6c8deb408d99)

left mouse click to substitute 1 ncu with the other inside inventory start the substitution time bar
![immagine](https://github.com/project-rubika/issues/assets/56939765/bfa815bf-f6c1-4623-beac-77b97de02887)

at the end of the progress bar no item is substitute ; everything stay as was before as showed in the image below
![immagine](https://github.com/project-rubika/issues/assets/56939765/c07fdbe2-1ed4-4187-a584-2c93a48f70eb)

could be a related problem
i moved all the chip from the belt as shown below
![immagine](https://github.com/project-rubika/issues/assets/56939765/5ed49abe-0f8c-4a96-aba9-b843eb37eb9f)

then started with right click the substitution of the belt inside inventory  as showed in the progress bar
![immagine](https://github.com/project-rubika/issues/assets/56939765/00f25ef9-03b3-4bf3-a8d0-84139eba3214)
at the end the item didn't changed / swapped as show in the image below
![immagine](https://github.com/project-rubika/issues/assets/56939765/8ed982ae-6935-449f-b06f-c8e79f9919df)

i tried to zone the item didn't changed as  show below
![immagine](https://github.com/project-rubika/issues/assets/56939765/00506a2c-a42e-47fc-a161-f2b2c7779712)
i relog and the items didn't change
![immagine](https://github.com/project-rubika/issues/assets/56939765/91144dc5-80dd-4ef3-9bf1-157d62f78564)

hope its clearer now ; let me know :D

**Comment by prkdrake** [comment]
Is this just for stuff in the backpack? Try zoning? I've definitely swapped NCU belts and chips in and out without issue

**Comment by S4ff0** [comment]
i tried to zone but it didn't work i can try again ;

**Comment by prkdrake** [comment]
Can you give details of the items that you're trying to equip/unequip and provide some reproduction steps please?

**Comment by S4ff0** [comment]
they was just normal ncu chip (the ones from store) i mounted 2 chip 7 ncu
then tried to swap with 2 chip with 8 ncu (normal one from shop)
i deleted them;
so i gived myself a memory loop as in picture 
![immagine](https://github.com/project-rubika/issues/assets/56939765/4fb5cc07-2fb5-4578-a793-316d49d29b9c)
with right click it says  "This computer deck slot is not available."
with left mouse click and drop on one of the NCU chip it start to swap but at the end it don't work;
i tried to zone but it don't work;
can i give u other info ?  want me to stream ?

**Comment by prkdrake** [comment]
I think I understand, the problem is that if you have NCU chips already equipped, you can't right click to swap the equipped NCU chip with the NCU chip in your inventory?

**Comment by S4ff0** [comment]
maybe the other chip didn't show the message about the slot was occupied, but i am enough sure on official it will just swap with the first available working slot ;
anyway i trie with left mouse to move the item and it still make the bar to move but at the end it doesn move ; i am sure on the official it swap them :D

**Comment by S4ff0** [comment]
i found another chip i try to install it with left click mouse
when the bar is full load the items are still the same;
![immagine](https://github.com/project-rubika/issues/assets/56939765/3b2650c1-e494-43a1-9294-286285f4dc88)

**Comment by prkdrake** [comment]
Okay, thanks - could you please try to summarize our findings from these comments above into the original post in the form of reproduction steps: For example, something like this: 

Please don't just copy this - run through it and make sure this reproduces the bug, change it if you need to. It takes a lot of time for us to figure out exactly what is causing a bug report like this if we don't have these steps. There's a reason why the template includes them!

Thanks!

```
**Steps to reproduce**
1. Get an NCU belt (`/item 252158 252158 1`)
2. Get two basic NCU chips (`/item 36778 36778 20 2`)
3. Get one different NCU chip (`/item 36786 36786 40`)
4. Equip the NCU belt and the two basic NCU chips.
5. Right click the third NCU chip.
6. Notice the equip delay progress bar at the top left appears and progresses.

**Expected behaviour**
The third NCU chip should replace the basic NCU chip in Deck 1 slot after the equip delay bar is completed.

**Actual behaviour**
The third NCU chip is not equipped, despite showing the equip delay progress bar.
```

**Comment by TheTinkeringIdiot** [comment]
Confirmed.

Following Drake's steps resulted in the 3rd NCU not being equipped with a message "You've maxed out your belt slots". 

Repeating the same steps with a 3 slot belt (`/item 36777 36777 25`) with one slot empty correctly replaces the NCU in slot 1 with the new NCU. 

However when all three slots are full, right clicking a new NCU again shows the equip delay and finishes without equipping the new NCU and the "You've maxed our your belt slots" message.
