### ISSUE TITLE
Monster does not die and continues to fight with zero HP

### ISSUE THREAD

**Issue by gigabite1123** [project-rubika/issues#393]
Some monsters, when reduced to zero HP, do not actually die, and instead stay alive and can even continue to follow you around and attempt to continue fighting you.

If you encounter a monster with this issue, please comment below with the name of the monster and also ideally the coordinates for where it can be found, roughly (the output from Shift+F9). Thanks!

---

Original issue below

While fighting through totw, it appears that very specific named mobs become "zombies". When viewing with debug on, they are marked as dead but continue to follow you.

Named mobs affected:
"windcaller donnel"

"windcaller yatila"
Extended location information:
- 96.2, 260.8, 13.0 (96.2 260.8 y 13.0 1931)
- Pf Proxy: Model=51100:1931 GS=0 SG=0 R=1931, resource: 1931
- zone: 14, area: "Temple of Three Winds", room: "Past_room1"
Server id: 102079, character id: 50000:639, time: 2023-12-28 06:46:16 (UTC)
Version: 00.3.6_EP1, map id: NOT FOUND, build: 52606.

"windcaller yen"
Extended location information:
- 159.2, 346.5, 36.0 (159.2 346.5 y 36.0 1931)
- Pf Proxy: Model=51100:1931 GS=0 SG=0 R=1931, resource: 1931
- zone: 6, area: "Temple of Three Winds", room: "Present_temple"
Server id: 1, character id: 50000:639, time: 2023-12-28 06:44:20 (UTC)
Version: 00.3.6_EP1, map id: NOT FOUND, build: 52606.

"windcaller rendal"
Extended location information:
- 160.5, 337.2, 36.0 (160.5 337.2 y 36.0 1931)
- Pf Proxy: Model=51100:1931 GS=0 SG=0 R=1931, resource: 1931
- zone: 6, area: "Temple of Three Winds", room: "Present_temple"
Server id: 1, character id: 50000:639, time: 2023-12-28 06:44:55 (UTC)
Version: 00.3.6_EP1, map id: NOT FOUND, build: 52606.

"windcaller tilla"
Extended location information:
- 255.0, 480.5, 14.8 (255.0 480.5 y 14.8 1931)
- Pf Proxy: Model=51100:1931 GS=0 SG=0 R=1931, resource: 1931
- zone: 26, area: "Temple of Three Winds", room: "Future"
Server id: 639, character id: 50000:639, time: 2023-12-28 06:53:11 (UTC)
Version: 00.3.6_EP1, map id: NOT FOUND, build: 52606.

"The Re-Animator"
Extended location information:
- 60.9, 295.7, 16.0 (60.9 295.7 y 16.0 1931)
- Pf Proxy: Model=51100:1931 GS=0 SG=0 R=1931, resource: 1931
- zone: 28, area: "Temple of Three Winds", room: "Past"
Server id: 639, character id: 50000:639, time: 2023-12-28 06:46:57 (UTC)
Version: 00.3.6_EP1, map id: NOT FOUND, build: 52606.

"acolyte seleen"
Extended location information:
- 170.0, 152.3, 20.0 (170.0 152.3 y 20.0 1931)
- Pf Proxy: Model=51100:1931 GS=0 SG=0 R=1931, resource: 1931
- zone: 7, area: "Temple of Three Winds", room: "EntryHall"
Server id: 1, character id: 50000:639, time: 2023-12-28 07:04:25 (UTC)
Version: 00.3.6_EP1, map id: NOT FOUND, build: 52606.

shadowfade armor or books
https://www.ao-universe.com/guides/classic-ao/location-guides-5/temple-of-three-winds-loot-table

**Comment by S4ff0** [comment]
i am at entrance first mob;  and he is killing cacodemon lvl 200 :O   cultist lvl 31
![immagine](https://github.com/project-rubika/issues/assets/56939765/a2c9f73b-6089-47b7-b706-9fe8e48cd184)
![immagine](https://github.com/project-rubika/issues/assets/56939765/2beb7d00-5117-4fa7-8d6b-515492c7a085)

**Comment by portalerprk** [comment]
> i am at entrance first mob;  and he is killing cacodemon lvl 200 :O   cultist lvl 31
> 
> ![immagine](https://github.com/project-rubika/issues/assets/56939765/a2c9f73b-6089-47b7-b706-9fe8e48cd184)
> 
> ![immagine](https://github.com/project-rubika/issues/assets/56939765/2beb7d00-5117-4fa7-8d6b-515492c7a085)
> 
> ![immagine](https://github.com/project-rubika/issues/assets/56939765/6951cc9a-eebe-4d4f-bc16-a24abfa02c0e)
> 
> 
> 
> 
> 
> 

Definitely a problem! Please open as a new case, not as a comment in another case 😁

**Comment by prkdrake** [comment]
Seems to still be occurring - issues #501 and #503 are instances of this. (Windcaller Donna, Guardian of Time and the Curator)

**Comment by prkdrake** [comment]
Yeah, I've renamed the issue - it's a broad problem when a monster has invalid loot. If you find any instances, comment them here and we'll fix them up

**Comment by wowpin** [comment]
Encountered this issue in Formans - Bodyguards in Director's room (who BTW is not there):

![image](https://github.com/project-rubika/issues/assets/30692035/7dbbe5a4-7af2-406d-80b6-6e603f8eda8c)

Bodyguard fights until he reaches 0HP, then pauses fighting, resumes when he replenishes a few HP.

Shift+F9 output:
(23:08) Extended location information:
(23:08) - 376.1, 374.9, 46.0 (376.1 374.9 y 46.0 1941)
(23:08) - Pf Proxy: Model=51100:1941 GS=0 SG=0 R=1941, resource: 1941
(23:08) - zone: 41, area: "Area"
(23:08) Server id: 113743, character id: 50000:789, time: 2024-01-17 22:08:21 (UTC)
(23:08) Version: 00.4.5_EP1, map id: NOT FOUND, build: 52606.

**Comment by galku** [comment]
I did /set debug 1 on an npc where this happened, and it looks like this:

![image](https://github.com/project-rubika/issues/assets/6178161/a348bd9d-d8b7-44c1-80cd-0416ef548c06)

**Comment by prkdrake** [comment]
I think this issue is now broadly resolved, though I don't know for sure. Would appreciate a second look at it!

**Comment by TheTinkeringIdiot** [comment]
Confirmed fixed.
