### ISSUE TITLE
Dynaboss can't find their aura nanos and fails to spawn.

### ISSUE THREAD

**Issue by 3F1-1009** [project-rubika/issues#395]
**Describe the bug**
Trying to spawn a rhinoman boss monster creates following error:

System.Exception: Could not find target for nano Pink glow TargetType: Target casted by Warlord Face breaker Titan guts

**To Reproduce**
1. Try to spawn BOMS
2. Error

**Expected behavior**
Boss should find its auras and spawn

**Screenshots**

**Character info:**

```
Copy/paste the output of /getfull here
```

**Playfield info:**

Any playfield I believe

```
Extended location information:
- 51.9, 108.8, 5.0 (51.9 108.8 y 5.0 954)
- Pf Proxy: Model=51100:954 GS=0 SG=0 R=954, resource: 954
- zone: 17, area: "Junkyard"
Server id: 1, character id: 50000:601, time: 2023-12-29 01:53:32 (UTC)
Version: 00.3.6_EP1, map id: NOT FOUND, build: 52606.
```

----

**Comment by portalerprk** [comment]
![image](https://github.com/project-rubika/issues/assets/60405799/981ca920-f449-4561-aef5-db83045e1bdc)
Lookin good
