### ISSUE TITLE
Monsters in Steps of Madness missing idle mesh

### ISSUE THREAD

**Issue by gigabite1123** [project-rubika/issues#396]
There are multiple monsters in steps of madness that fail to have a mesh until death:

![Capture1](https://github.com/project-rubika/issues/assets/155043689/f434ce78-46ef-4498-8b4e-3ee433d332dc)

betrayer of memory(no mesh):
Extended location information:
- 256.8, 130.6, 27.7 (256.8 130.6 y 27.7 1933)
- Pf Proxy: Model=51100:1933 GS=0 SG=0 R=1933, resource: 1933
- zone: 9, area: "Steps of Madness", room: "Throne Room"
Server id: 1, character id: 50000:639, time: 2023-12-29 02:02:53 (UTC)
Version: 00.3.6_EP1, map id: NOT FOUND, build: 52606.

thief of reason(no mesh):
Extended location information:
- 256.8, 130.6, 27.7 (256.8 130.6 y 27.7 1933)
- Pf Proxy: Model=51100:1933 GS=0 SG=0 R=1933, resource: 1933
- zone: 9, area: "Steps of Madness", room: "Throne Room"
Server id: 1, character id: 50000:639, time: 2023-12-29 02:02:53 (UTC)
Version: 00.3.6_EP1, map id: NOT FOUND, build: 52606.

betrayer of memory(no mesh until killed):
Extended location information:
- 256.8, 130.6, 27.7 (256.8 130.6 y 27.7 1933)
- Pf Proxy: Model=51100:1933 GS=0 SG=0 R=1933, resource: 1933
- zone: 9, area: "Steps of Madness", room: "Throne Room"
Server id: 1, character id: 50000:639, time: 2023-12-29 02:02:53 (UTC)
Version: 00.3.6_EP1, map id: NOT FOUND, build: 52606.

guardian of thought(no mesh until killed):
Extended location information:
- 256.8, 130.6, 27.7 (256.8 130.6 y 27.7 1933)
- Pf Proxy: Model=51100:1933 GS=0 SG=0 R=1933, resource: 1933
- zone: 9, area: "Steps of Madness", room: "Throne Room"
Server id: 1, character id: 50000:639, time: 2023-12-29 02:02:53 (UTC)
Version: 00.3.6_EP1, map id: NOT FOUND, build: 52606.

guardian of thought(no mesh until killed):
Extended location information:
- 256.8, 130.6, 27.7 (256.8 130.6 y 27.7 1933)
- Pf Proxy: Model=51100:1933 GS=0 SG=0 R=1933, resource: 1933
- zone: 9, area: "Steps of Madness", room: "Throne Room"
Server id: 1, character id: 50000:639, time: 2023-12-29 02:02:53 (UTC)
Version: 00.3.6_EP1, map id: NOT FOUND, build: 52606.

frazzled nerves(no mesh until killed):
Extended location information:
- 247.3, 315.7, 31.5 (247.3 315.7 y 31.5 1933)
- Pf Proxy: Model=51100:1933 GS=0 SG=0 R=1933, resource: 1933
- zone: 4, area: "Steps of Madness", room: "Downward Spiral"
Server id: 1, character id: 50000:639, time: 2023-12-29 02:00:00 (UTC)
Version: 00.3.6_EP1, map id: NOT FOUND, build: 52606.

guardian of thought(no mesh until killed):
Extended location information:
- 259.9, 195.3, 29.1 (259.9 195.3 y 29.1 1933)
- Pf Proxy: Model=51100:1933 GS=0 SG=0 R=1933, resource: 1933
- zone: 5, area: "Steps of Madness", room: "Daylight Breakthrough"
Server id: 639, character id: 50000:639, time: 2023-12-29 02:01:39 (UTC)
Version: 00.3.6_EP1, map id: NOT FOUND, build: 52606.

guardian of thought(no mesh until killed):
Extended location information:
- 259.2, 191.7, 30.1 (259.2 191.7 y 30.1 1933)
- Pf Proxy: Model=51100:1933 GS=0 SG=0 R=1933, resource: 1933
- zone: 5, area: "Steps of Madness", room: "Daylight Breakthrough"
Server id: 1, character id: 50000:639, time: 2023-12-29 02:01:41 (UTC)
Version: 00.3.6_EP1, map id: NOT FOUND, build: 52606.

roving eye(no mesh until killed):
Extended location information:
- 190.0, 285.6, 27.8 (190.0 285.6 y 27.8 1933)
- Pf Proxy: Model=51100:1933 GS=0 SG=0 R=1933, resource: 1933
- zone: 3, area: "Steps of Madness", room: "Notum Alley"
Server id: 639, character id: 50000:639, time: 2023-12-29 01:58:36 (UTC)
Version: 00.3.6_EP1, map id: NOT FOUND, build: 52606.

Mind fragment(no mesh until killed):
Extended location information:
- 170.3, 263.4, 26.9 (170.3 263.4 y 26.9 1933)
- Pf Proxy: Model=51100:1933 GS=0 SG=0 R=1933, resource: 1933
- zone: 13, area: "Steps of Madness", room: "Dinobone Room"
Server id: 102374, character id: 50000:639, time: 2023-12-29 01:55:26 (UTC)
Version: 00.3.6_EP1, map id: NOT FOUND, build: 52606.

Jealousy(no mesh until killed):
Extended location information:
- 157.9, 224.8, 26.0 (157.9 224.8 y 26.0 1933)
- Pf Proxy: Model=51100:1933 GS=0 SG=0 R=1933, resource: 1933
- zone: 1, area: "Steps of Madness", room: "Green Circle of Death"
Server id: 639, character id: 50000:639, time: 2023-12-29 01:53:53 (UTC)
Version: 00.3.6_EP1, map id: NOT FOUND, build: 52606.

Roving eye 1(no mesh until killed):
Extended location information:
- 147.2, 141.5, 23.9 (147.2 141.5 y 23.9 1933)
- Pf Proxy: Model=51100:1933 GS=0 SG=0 R=1933, resource: 1933
- zone: 12, area: "Steps of Madness", room: "Room of Corpses"
Server id: 639, character id: 50000:639, time: 2023-12-29 01:51:59 (UTC)
Version: 00.3.6_EP1, map id: NOT FOUND, build: 52606.

Roving eye 2(no mesh until killed):
Extended location information:
- 147.2, 141.5, 23.9 (147.2 141.5 y 23.9 1933)
- Pf Proxy: Model=51100:1933 GS=0 SG=0 R=1933, resource: 1933
- zone: 12, area: "Steps of Madness", room: "Room of Corpses"
Server id: 639, character id: 50000:639, time: 2023-12-29 01:51:59 (UTC)
Version: 00.3.6_EP1, map id: NOT FOUND, build: 52606.

brain splitter(no mesh until killed):
Extended location information:
- 89.2, 111.9, 26.9 (89.2 111.9 y 26.9 1933)
- Pf Proxy: Model=51100:1933 GS=0 SG=0 R=1933, resource: 1933
- zone: 11, area: "Steps of Madness", room: "Dragonhead Room"
Server id: 639, character id: 50000:639, time: 2023-12-29 01:50:51 (UTC)
Version: 00.3.6_EP1, map id: NOT FOUND, build: 52606.

foundation of sanity(no mesh until killed):
Extended location information:
- 78.8, 159.0, 27.8 (78.8 159.0 y 27.8 1933)
- Pf Proxy: Model=51100:1933 GS=0 SG=0 R=1933, resource: 1933
- zone: 14, area: "Steps of Madness", room: "Bypassed Corridor"
Server id: 1, character id: 50000:639, time: 2023-12-29 01:48:15 (UTC)
Version: 00.3.6_EP1, map id: NOT FOUND, build: 52606.

roving eye(no mesh until killed):
Extended location information:
- 76.8, 114.9, 27.2 (76.8 114.9 y 27.2 1933)
- Pf Proxy: Model=51100:1933 GS=0 SG=0 R=1933, resource: 1933
- zone: 11, area: "Steps of Madness", room: "Dragonhead Room"
Server id: 639, character id: 50000:639, time: 2023-12-29 01:49:40 (UTC)
Version: 00.3.6_EP1, map id: NOT FOUND, build: 52606.

 Saece [66 Fixer]
------------------------------------
    strength 	825
    stamina 	806
    agility 	815
    sense 	857
    psychic 	803
    intelligence 	806
    nextxp 	4636050
    lastsavexp 	265700
    xp 	4379115
    waitstate 	2
    lastxp 	4356050
    lastsaved 	2609550
    minmembers 	4
    isfightingme 	8
    charstate 	0
    exitstatel 	-1069940611
    externaldoorinstance 	0
    externalplayfieldinstance 	716
    driveground 	2209
    drivewater 	2209
    mapnavigation 	2207
    playfieldtype 	1
    selectedtargettype 	0
    expansionplayfield 	0
    treatment 	2204
    concealment 	2211
    breakingentry 	2205
    disarmtrap 	2249
    perception 	2278
    driveair 	2209
    biologicalmetamorphose 	2254
    psychologicalmodification 	2231
    materialcreation 	2201
    materiallocation 	2225
    senseimprovement 	2238
    firstaid 	2234
    nanoprogramming 	2201
    computerliteracy 	2201
    psychology 	2207
    chemistry 	2201
    tutoring 	2243
    materialmetamorphose 	2268
    runspeed 	1291
    mechanicalengineering 	2202
    electricalengineering 	2202
    fieldquantumphysics 	2201
    weaponsmithing 	2203
    pharmaceuticals 	2201
    physicalprowessinitiative 	2209
    nanoprowessinitiative 	2210
    dodge 	2314
    evade 	2340
    duck 	2273
    nanoac 	2027
    burst 	2269
    fullauto 	2204
    bowspecialattack 	2208
    lr_multipleweapon 	2270
    closecombatinitiative 	2209
    distanceweaponinitiative 	2277
    submachinegun 	2336
    shotgun 	2204
    rifle 	2207
    lr_energyweapon 	2206
    flingshot 	2230
    aimedshot 	2274
    throwingknife 	2206
    grenade 	2207
    throwngrapplingweapons 	2204
    bow 	2208
    pistol 	2207
    assaultrifle 	2205
    twohandedgedweapons 	2204
    meleeenergyweapon 	2201
    parry 	2208
    sneakattack 	2205
    meleemultiple 	2204
    fastattack 	2207
    adventuring 	2203
    swim 	2202
    onehandbluntweapons 	2204
    onehandedgedweapon 	2203
    piercing 	2203
    twohandbluntweapons 	2203
    nanoenergypool 	1002
    maxnanoenergy 	2003214
    martialarts 	2266
    brawl 	2272
    riposte 	2209
    dimach 	2211
    health 	2180025
    selectedtarget 	639
    currentmovementmode 	3
    side 	1
    life 	2103414
    bodydevelopment 	1001
    level 	66
    sex 	2
    visualsex 	2
    titlelevel 	3
    equippedweapontype 	0
    EquippedRHWeapon 	0
    expansion 	3
    fatness 	2
    breed 	2
    visualbreed 	2
    profession 	4
    visualprofession 	4
    flags 	528961
    monsterscale 	100
    currentnano 	167102
    headmesh 	40271
    cash 	75955
    gmlevel 	511
    maxncu 	2224
    monsterdata 	0
    team 	0
    healdelta 	100019
    reflectradiationac 	200
    reflectprojectileac 	200
    reflectenergyac 	200
    reflectfireac 	200
    reflectcoldac 	200
    reflectchemicalac 	200
    reflectpoisonac 	200
    reflectmeleeac 	200
    projectileac 	20000
    energyac 	20000
    meleeac 	20000
    coldac 	20000
    fireac 	20000
    chemicalac 	20508
    radiationac 	20000
    poisonac 	20000
    xpmodifier 	500
    beltslots 	6
    race 	1
    accountflags 	1234567890
    VisualFlags 	31
    clan 	0
    healinterval 	3
    nanointerval 	2
    aggdef 	100
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    specialization 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    savedxp 	0
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    alignment 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    age 	0
    attackspeed 	5
    metatype 	0
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
    amsmodifier 	0
    damageoverridetype 	0
    meleedamagemodifier 	0
    xppool 	0
    ip 	743500
    dmsmodifier 	0
    reflectreturnedchemicalac 	0
    shieldchemicalac 	0
    npcostmodifier 	0
    reflectreturnedpoisonac 	0
    shieldpoisonac 	0
    reflectreturnedcoldac 	0
    shieldcoldac 	0
    reflectreturnedenergyac 	0
    shieldenergyac 	0
    specialattackshield 	0
    reflectreturnedmeleeac 	0
    shieldmeleeac 	0
------------------------------------

**Comment by prkdrake** [comment]
Happens for several MP pets too. Noticed it on the heal pets.

**Comment by TheTinkeringIdiot** [comment]
Confirmed. Most non-boss mobs in SoM are missing textures.

**Comment by TheTinkeringIdiot** [comment]
This has been fixed. Mobs and bosses in SoM now wear their appropriate textures.
