### ISSUE TITLE
SL "dynaboss" mobs drop way too high quality symbiants.

### ISSUE THREAD

**Issue by 3F1-1009** [project-rubika/issues#399]
**Describe the bug**
"boss" mobs in shadowlands drop symbiants that are way too high quality level.

**To Reproduce**
1. Go to 548.0 248.3 y 32.4 4313
2. Kill the Devastator or any other "boss" monster in the area.
3. Loot that it drops can be a symbiant for lvl 160+ players

**Expected behavior**
One would expect them to drop loot in range of their level or just a bit higher

**Screenshots**
![Screenshot_79](https://github.com/project-rubika/issues/assets/103999128/bc36cdad-9ec1-483e-95fa-16f8f9f90fc0)

```
Extended location information:
- 548.0, 248.3, 32.4 (548.0 248.3 y 32.4 4313)
- Pf Proxy: Model=51100:4313 GS=0 SG=0 R=4313, resource: 4313
- zone: 133, area: "The Brink"
Server id: 647, character id: 50000:647, time: 2023-12-30 00:05:15 (UTC)
Version: 00.3.6_EP1, map id: NOT FOUND, build: 52606.

```
----

**Comment by prkdrake** [comment]
Correct me if I'm wrong here, but the only mobs who should drop symbiants at all are the bosses spawned at incarnators, aren't they? I do have vague recollections of dynabosses dropping symbiants, though, so maybe this is something they changed. Does anyone definitively remember or have some reference for this?

**Comment by prkdrake** [comment]
Asked on Discord: 

![image](https://github.com/project-rubika/issues/assets/154430828/fd92af11-f6c4-47a9-8fba-6665371bb273)

**Comment by prkdrake** [comment]
I believe this was fixed by the same fix that was causing mobs to drop invalid weapons, needs to be re-tested

**Comment by Random823** [comment]
Tested nasc training area, looks good. Dropped low lvl symbs.

**Comment by prkdrake** [comment]
Glad to hear it, thanks!
