### ISSUE TITLE
Vendors are very slow to load

### ISSUE THREAD

**Issue by prkdrake** [project-rubika/issues#400]
**Describe the bug**
When you try to trade with a vendor after just entering a playfield, often it hasn't loaded the inventory and it is quite slow to do so. 

**To Reproduce**
1. Teleport to rome blue basic `/tp rbb`
2. Enter the shop and immediately try to trade with a terminal.
3. Notice it is empty
4. Wait 2 minutes
5. Trade with the terminal again.
6. Notice that the vendor now has items.

**Expected behavior**
The terminal should have items within seconds of loading the playfield, if possible.

**Comment by prkdrake** [comment]
This should now be fixed - vendors should now take only a handful of seconds to load. I'm sure there are still improvements which could be made here but it's a major improvement :)

**Comment by S4ff0** [comment]
i hopened few in rome seems fast; will test more;
