### ISSUE TITLE
Mugger in subway are not aggressive whatsoever

### ISSUE THREAD

**Issue by Varzog** [project-rubika/issues#404]
**Describe the bug**

Mugger in subway should be aggressive, no matter your level, right now, they just stand and wait.

**Expected behavior**
They should aggressive, and attack you no matter how strong, or weak you are

**Screenshots**

<img width="423" alt="Capture" src="https://github.com/project-rubika/issues/assets/155806194/e4fb20ea-f93b-4f23-b320-940283db4d6a">

**Comment by Enfodoug** [comment]
Hm. I have been in there today and they all attacked me.

**Comment by portalerprk** [comment]
I think there is a "they're deep red to me I wont attack" bit of logic that might supersede their aggressiveness. They *should* have a more extended aggressive range. 

But I think on live your right that they will attack no matter what :-) Will address this grave issue :-P

**Comment by Random823** [comment]
Tested, mugger all attacked me.

**Comment by portalerprk** [comment]
Yes.. will need to inform the chief of police.
