### ISSUE TITLE
Subway Entrance in Newland City does not work

### ISSUE THREAD

**Issue by Random823** [project-rubika/issues#405]
**Describe the bug**
Subway entrance in Newland city does let you zone into Subway

**To Reproduce**
1. Go to 'Newland City Subway Entrance'
2. Try to go through the door

**Expected behavior**
Zone into Subway

**Comment by abc** [comment]
Yeah, I believe that the NLC entrance wasn’t actually tied to the subway until later versions - the Neutral subway entrance is in Borealis, and I’m pretty sure the NLC subway door can be used by ACG missions :p

**Comment by prkdrake** [comment]
Had a chat with the team about this - for the time being, we're going to close this (and other tickets about the subway entrance locations) as wontfix - subway entrances are in Old Athens, Rome Stretch and Borealis.
