### ISSUE TITLE
Unable to zone in Nemesis Nano Formulas in Rome

### ISSUE THREAD

**Issue by Random823** [project-rubika/issues#406]
------SEND THIS TO THE DEVS------
  destProxyModelType: 51102
  destProxyModelInst: 2042
  destProxyGroup: 0
  destProxySubgroup: -1072495900
  destProxyLocalizerType: 100002
  destProxyLocalizerInst: 1
----------------------------------

**Describe the bug**
Can't zone going through door.

**To Reproduce**
1. Go to 'Rome'
2. Try to zone into shop

**Comment by prkdrake** [comment]
Duplicate issue of #385

**Comment by prkdrake** [comment]
Thanks for raising this - if you find more, add them as a comment on #385 so we can keep them together. I think we will probably fix them all at the same time.
