### ISSUE TITLE
Muggers in the subway drop a "NoName" item.

### ISSUE THREAD

**Issue by Enfodoug** [project-rubika/issues#407]
**Describe the bug**
Muggers in the subway drop a "NoName" item from time to time.
It can not be lootet. 

**To Reproduce**
Go to subway and kill Muggers. 

**Expected behavior**
Correct the item or remove it. 

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/156118657/bf989cf3-1c81-4666-ae78-30afa0fa98db)

**Playfield info:**
```
(20:45) Extended location information:
(20:45) - 147.3, 291.8, 107.6 (147.3 291.8 y 107.6 127)
(20:45) - Pf Proxy: Model=51100:127 GS=0 SG=0 R=127, resource: 127
(20:45) - zone: 6, area: "Abandoned Mall", room: "Mini to Shopping"
(20:45) Server id: 660, character id: 50000:660, time: 2024-01-09 19:45:15 (UTC)
(20:45) Version: 00.4.2_EP1, map id: NOT FOUND, build: 52606.
```
----

**Comment by 3F1-1009** [comment]
It appears to be item ID 300001

**Comment by prkdrake** [comment]
This is one of our custom items we added for testing, if we're gonna keep it then we will have to release an RDB patch.

**Comment by 3F1-1009** [comment]
This should now be fixed and Mugger should drop a valid item.

**Comment by Enfodoug** [comment]
They drop now a tag. Seems fixed.

**Comment by prkdrake** [comment]
Awesome, thanks for confirming :D
