### ISSUE TITLE
Missing Descriptions on "Shoulderpads Quests"

### ISSUE THREAD

**Issue by Enfodoug** [project-rubika/issues#412]
**Describe the bug**
The questgiver does not hand out the quest to get the shoulderpad. 
Here: Dodga Demercel in Aegean. `/tp 606 1122 585`
https://www.ao-universe.com/guides/classic-ao/quests-guides-3/shoulderpads-quests

**To Reproduce**
Talk to Dodga Demercel.
"How are you?"
"What is your job here?"
"You can't apply for more people?"
"Paperwork?"
"How can I help you?"
...
Here shoould be an option to get the quest, but it's missing.

**Expected behavior**
Get the quest... i guess. 

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/156118657/bb49e2d1-469a-45ec-9709-c345ff9f563c)

**Playfield info:**

```
(10:55) Extended location information:
(10:55) - 608.8, 1121.9, 69.9 (608.8 1121.9 y 69.9 585)
(10:55) - Pf Proxy: Model=51100:585 GS=0 SG=0 R=585, resource: 585
(10:55) - zone: 1863, area: "The Rising Sun"
(10:55) Server id: 660, character id: 50000:660, time: 2024-01-11 09:55:59 (UTC)
(10:55) Version: 00.4.2_EP1, map id: NOT FOUND, build: 52606.

```
----

**Comment by TheTinkeringIdiot** [comment]
Confirmed. Both Dodga and Alvin (`.tp 1540 2500 695`) fail to present the correct options that allow the player to volunteer for their missions. 

![image](https://github.com/project-rubika/issues/assets/96996793/a298cbfb-606a-4b98-8c36-e9c512e5de68)

**Comment by RaggyLP** [comment]
An update to this ticket.

Dodga's conversation options now work, however, generates an unhandled command on [2044] that stops him giving the quest/
`Unhandled command - {mission KXRM 6 7}`

**Comment by prkdrake** [comment]
This should be fixed with the next update, please re-test and let us know. Thanks!

**Comment by RaggyLP** [comment]
Partially confirmed. Dodga now presents the player with his quest (KXRM), however, the description is broken.
![image](https://github.com/user-attachments/assets/a4463744-9ea0-41c4-b140-438b364a6fe4)

And the same for Alvin's quest (DSOT)
![image](https://github.com/user-attachments/assets/e60f4d09-3168-419f-add9-a0aea161f6bf)

**Comment by prkdrake** [comment]
This should now be fixed as of the latest release.

**Comment by RaggyLP** [comment]
Confirmed. Full run from start to finish through both Clan and Omni questlines confirms that the whole questline is now functioning exactly as it should be! Incredible work! Closing as fixed as of 25/08/2024.
