### ISSUE TITLE
New characters start off quite injured

### ISSUE THREAD

**Issue by prkdrake** [project-rubika/issues#413]
**Describe the bug**
When a new character is created and logged in, they start already having taken some damage.

**To Reproduce**
1. Create a new character.
2. When you get into the world, notice you have low health.

**Expected behavior**
A character should enter Rubi-Ka for the first time with full health.

**Comment by RaggyLP** [comment]
![image](https://github.com/project-rubika/issues/assets/156821187/da351165-48b0-4e23-9ccc-0bc28eb7297d)

New chars are no longer at the lowest HP point, but do still spawn in slightly damage.

**Comment by prkdrake** [comment]
Can you check `/getfull health` and `/getfull life` and let me know which breed? thanks!

**Comment by RaggyLP** [comment]
![image](https://github.com/project-rubika/issues/assets/156821187/1925401b-7777-44aa-8a4e-5079ad1945a4)
Opifex Male

(Health was regen'd via HD)

**Comment by prkdrake** [comment]
Should now be fixed

**Comment by RaggyLP** [comment]
Confirmed. Fixed as of 19/08/2024.

![image](https://github.com/user-attachments/assets/d9bdb154-ac64-4020-b239-28ec58f182dc)
