### ISSUE TITLE
Nanos like touch of marius that do not have a strain are stacking their stats

### ISSUE THREAD

**Issue by portalerprk** [project-rubika/issues#414]
Nanos like touch of marius that do not have a strain are stacking their stats

Make sure you have targetted yourself.
Check your current complit (/getfull computerliteracy)
Run CL Expertise  (.ncu run 26425)
Check your updated complit (/getfull computerliteracy)
Run CL Expertise again (.ncu run 26425)
Check your updated complit (/getfull computerliteracy)
Zone in any way you prefer
Check your updated complit (/getfull computerliteracy)

Notice that your CL does go up when the nano is cast, but when you zone, it goes back down.

**Comment by 3F1-1009** [comment]
Seems to be working as intended now. 
![Screenshot_126](https://github.com/project-rubika/issues/assets/103999128/6cf377ea-d18c-4d0c-a2fe-19de4b808156)
