### ISSUE TITLE
ICC peacekeepers don't , "keep the peace"

### ISSUE THREAD

**Issue by GlitchyGirl** [project-rubika/issues#415]
**Describe the bug**
ICC peace keepers won't attack hostile mobs in the ICC area.

**To Reproduce**
Drag a vulture squabbler into the area with the Whompas and watch the ICC peacekeepers do nothing :D

1. Run out of the area
2. Gain aggro from a near by mob ( in this case the vulture squabbler) 
3. Watch it attack
4.  See the ICC guards do nothing

**Expected behavior**
ICC guards are supposed to attack hostile mobs/entities in the area

**Screenshots**

![image](https://github.com/project-rubika/issues/assets/43483963/f5f48420-cbb9-4d2d-9f26-b91db3fdc79d)

**Character info:**
NanoFae

**Comment by TheTinkeringIdiot** [comment]
Confirmed in several cities and backyards that guards in general do not intervene in combat when either the player or friendly NPCs are attacked. 

![image](https://github.com/project-rubika/issues/assets/96996793/d013050a-a276-408f-b5db-394069cda62c)

**Comment by RaggyLP** [comment]
Confirmed solved. Closing as fixed as of 12/06/2024.
