### ISSUE TITLE
You can't right click when a store window is open to cancel a purchase

### ISSUE THREAD

**Issue by GlitchyGirl** [project-rubika/issues#416]
**Describe the bug**
Right clicking on the item in question, will not allow you to cancel it as a purchase should you change your mind.  You need to close the store window and open it again.

**To Reproduce**
1. Go to any store terminal
2. Click on an item to purchase
3. Right click, or left click on the item to cancel it's purchase
4. Observe that you cannot do so 

**Expected behavior**
You are supposed to be able to cancel the purchase of an object without having to close the terminal all the way out.

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/43483963/0d5575a4-2c4c-46dd-986b-6c3c271fd750)

**Comment by TheTinkeringIdiot** [comment]
Cannot replicate. All shops and vendor trade interfaces allow canceling an item with both left and right click. This must have been fixed with some of the recent updates to shops fixing other issues.
