### ISSUE TITLE
Missing Description for MG and SMG, and Melee Energy Weapons from the, "Second Hand Peddler" NPC

### ISSUE THREAD

**Issue by GlitchyGirl** [project-rubika/issues#417]
**Describe the bug**
Second Hand Peddler doesn't display the text description for "Machine Guns, and Submachine Guns", or "Melee Energy Weapons".
**To Reproduce**
1. Go to Second Hand Peddler
2. Click on ,"Can you tell me what you are selling"?
3.Click on, "Please tell me more about weapons."
4. Scroll down to and click on, "Machine Guns and Submachine guns.", or " Melee Energy Weapons" 
5. See the lack of description

**Expected behavior**
A paragraph describing the Machine Gun, and SMG weapons along with the profession that tends to use them.  Same for Melee Energy Weapons.

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/43483963/097d1da5-3051-4db5-8b96-3965606b3349)

**Character info:**
NanoFae

**Comment by TheTinkeringIdiot** [comment]
Confirmed. 

The options described are available but replies are empty when selected.

**Comment by RaggyLP** [comment]
Secondhand Peddler now explains each weapon in detail. Closing as fixed as of 17/08/2024
