### ISSUE TITLE
Some items cannot be purchased from the vendors in the newie back yard.

### ISSUE THREAD

**Issue by GlitchyGirl** [project-rubika/issues#420]
**Describe the bug**
Attempting to purchase items from the second hand peddler will result in an error indicating that you need a negative amount of credits to purchase it.

**To Reproduce**
1. Go to Second Hand peddler 
2. Click on battered light combat sleeves
3. See error or Notice this behavior

**Expected behavior**
Should be able to add this to  window for purchasing.

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/43483963/1b60cc45-4ab2-43fd-b635-04d5e2abccd7)

**Character info:**

```
Copy/paste the output of /getfull here
```

**Playfield info:**

```
Copy/paste the output of Shift+F9 here
```
----

**Comment by prkdrake** [comment]
This should be fixed now. Price interpolation isn't 100% perfect yet, but it's now much closer, and shouldn't make things more expensive to buy than they should be anymore.

**Comment by Random823** [comment]
Confirmed, this is working as intended.

**Comment by prkdrake** [comment]
Thanks!
