### ISSUE TITLE
Some nanos are not removed with /command ncu clear

### ISSUE THREAD

**Issue by 3F1-1009** [project-rubika/issues#426]
**Describe the bug**
Some nanos running in ncu do not get removed when using command ncu clear

**To Reproduce**
1. Cast nano 231341 on yourself
2. Cast nano 231279 on yourself
3. Do /command ncu clear
4. Do /command ncu clear again
5. Notice how the two nanos are not cleared from NCU

**Expected behavior**
All and any nanos running in NCU should be removed.

**Comment by portalerprk** [comment]
This is by design I guess

![image](https://github.com/project-rubika/issues/assets/60405799/c1611ace-22f6-47f8-a206-d88dca25fb43)

Should `.ncu clear` force it?

**Comment by 3F1-1009** [comment]
I think .ncu clear is a debug command so it should remove everything unconditionally. As it is now I have 2 nanos with visual effect (which should not be cast on player in first place) permanently stuck in my NCU.
