### ISSUE TITLE
OT Basic Startup Equipment Shops missing token board from sale

### ISSUE THREAD

**Issue by praxis1988** [project-rubika/issues#429]
**Describe the bug**
Missing token board from shop terminal.

**To Reproduce**
Check the Basic Startup Equipment Shop

4. See error or Notice this behavior
Lacking basic token board from terminal.

**Expected behavior**
If you are omni you can buy the token board from "OT Basic Startup Equipment" in Omni trade. At the east/west mission terminals. If you're Clan you can buy them from the outdoor shops beside the mission terminals north and south of OA Hill.

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/25720793/f572915e-9470-4fe7-b9c7-a03cc6d9f18e)

**Character info:**
Dacia1310 [50 Enforcer]
------------------------------------
    strength 	173
    stamina 	171
    agility 	160
    sense 	151
    psychic 	158
    intelligence 	154
    flags 	528961
    monsterscale 	102
    currentnano 	2271
    headmesh 	40100
    cash 	899999700
    gmlevel 	511
    expansion 	3
    breed 	4
    visualbreed 	4
    profession 	9
    visualprofession 	9
    level 	50
    sex 	1
    visualsex 	1
    titlelevel 	3
    equippedweapontype 	16518
    EquippedRHWeapon 	16518
    health 	5025
    selectedtarget 	726
    currentmovementmode 	3
    bodydevelopment 	60
    waitstate 	1
    exitstatel 	-1073740641
    externaldoorinstance 	0
    externalplayfieldinstance 	0
    playfieldtype 	0
    side 	2
    metatype 	400
    nextxp 	1659350
    xp 	1551350
    lastsaved 	1551350
    lastxp 	1551350
    currentncu 	1
    selectedtargettype 	0
    runspeed 	67
    closecombatinitiative 	87
    life 	733
    onehandedgedweapon 	65
    meleeenergyweapon 	61
    meleemultiple 	10
    fastattack 	72
    twohandedgedweapons 	81
    psychologicalmodification 	26
    twohandbluntweapons 	73
    materialcreation 	29
    sneakattack 	74
    parry 	55
    materiallocation 	26
    firstaid 	53
    piercing 	57
    materialmetamorphose 	28
    maxnanoenergy 	271
    brawl 	54
    onehandbluntweapons 	72
    senseimprovement 	35
    psychology 	60
    biologicalmetamorphose 	28
    martialarts 	50
    dimach 	48
    riposte 	48
    adventuring 	51
    swim 	52
    throwingknife 	50
    throwngrapplingweapons 	51
    physicalprowessinitiative 	48
    evade 	49
    duck 	49
    concealment 	48
    computerliteracy 	222
    maxncu 	8
    monsterdata 	0
    shieldprojectileac 	9
    shieldmeleeac 	9
    shieldenergyac 	9
    shieldchemicalac 	9
    shieldradiationac 	9
    shieldcoldac 	9
    shieldnanoac 	9
    shieldfireac 	9
    shieldpoisonac 	9
    projectileac 	6940
    meleeac 	6940
    energyac 	6940
    chemicalac 	6940
    radiationac 	4305
    coldac 	5342
    poisonac 	6940
    fireac 	6940
    reflectmeleeac 	0
    reflectpoisonac 	0
    reflectfireac 	0
    reflectnanoac 	0
    reflectcoldac 	0
    reflectprojectileac 	0
    reflectenergyac 	0
    reflectchemicalac 	0
    reflectradiationac 	0
    team 	0
    xpmodifier 	7
    dmsmodifier 	10
    fatness 	1
    race 	1
    accountflags 	1234567890
    VisualFlags 	31
    isfightingme 	0
    clan 	0
    healinterval 	24
    nanoenergypool 	44
    nanointerval 	24
    aggdef 	100
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    specialization 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    savedxp 	0
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    nanoac 	5
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    alignment 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    lastsavexp 	0
    grenade 	43
    bow 	44
    pistol 	44
    rifle 	44
    submachinegun 	46
    shotgun 	46
    assaultrifle 	45
    drivewater 	43
    distanceweaponinitiative 	43
    bowspecialattack 	44
    treatment 	43
    mechanicalengineering 	44
    electricalengineering 	44
    lr_energyweapon 	43
    lr_multipleweapon 	44
    disarmtrap 	43
    perception 	42
    driveair 	43
    mapnavigation 	43
    tutoring 	43
    burst 	46
    nanoprowessinitiative 	43
    flingshot 	45
    aimedshot 	42
    dodge 	44
    fieldquantumphysics 	44
    weaponsmithing 	45
    pharmaceuticals 	43
    nanoprogramming 	43
    chemistry 	45
    breakingentry 	44
    driveground 	43
    fullauto 	48
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    age 	0
    attackspeed 	5
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    beltslots 	0
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
------------------------------------

.getfull succeeded.

**Playfield info:**

Extended location information:
- 248.7, 350.0, 8.0 (248.7 350.0 y 8.0 710)
- Pf Proxy: Model=51100:710 GS=0 SG=0 R=710, resource: 710
- zone: 166, area: "Trade District"
Server id: 1, character id: 50000:726, time: 2024-01-12 11:20:03 (UTC)
Version: 00.4.2_EP1, map id: NOT FOUND, build: 52606.

**Comment by praxis1988** [comment]
checked and it's still not showing up.

![image](https://github.com/project-rubika/issues/assets/25720793/7182d07b-b03d-4a0f-81a4-331f9ebe8c2f)

**Comment by TheTinkeringIdiot** [comment]
Confirmed.

Token board is missing from both Clan and Omni Startup Equipment shops.

**Comment by RaggyLP** [comment]
![image](https://github.com/user-attachments/assets/2256841e-acf1-4298-b444-deea02876617)
![image](https://github.com/user-attachments/assets/a22672c5-485e-4587-9dd6-ae9daa80df5d)

Closing as fixed as of 18/08/2024.
