### ISSUE TITLE
Make leader and kick player buttons in team window do not work

### ISSUE THREAD

**Issue by AOFlux** [project-rubika/issues#432]
**Describe the bug**
Make leader and kick player buttons in team window do not work

**To Reproduce**
1. Go to team window
2. Right click on a player other than yourself
3. Left click on "make player leader" or "kick player from the team

**Expected behavior**
The player you right clicked on should have been either made leader or kicked.

Nothing happens.

**Comment by prkdrake** [comment]
Duplicates of #366 and #371

**Comment by AOFlux** [comment]
Sorry, I'll check for duplicates from now on.
