### ISSUE TITLE
Overflow inventory has not been fully implemented

### ISSUE THREAD

**Issue by GlitchyGirl** [project-rubika/issues#433]
**Describe the bug**
There is no inventory overflow function, or if it does exist it's not triggering correctly.   More specifically when you have no spots left, and you upgrade an item that can be leveled.  (For example here, my NCU hacker interface) it will overflow it into the overflow window.

Here it doesn't seem to do that, so items that overflow are either inaccessible or gone from the player.

**To Reproduce**
1.  Ensure that all your inventory slots are used up, with one of the inventory slots belonging to an item that can be right clicked to upgrade.
2. Rightclick/upgrade the item.
3. The item will disappear, and give the message, "Item must be unique" 

Additional note - relogging does not return the item

**Expected behavior**
An inventory overflow window is supposed to pop up, with a tool tip indicating that items not retrieved from this window are lost on zoning.

 
![image](https://github.com/project-rubika/issues/assets/43483963/4bd9fa20-b65b-45af-91a6-57497748bb32)

**Comment by RaggyLP** [comment]
Raising the priority on this as it is an integral element of the intentory management process for players.

**Comment by prkdrake** [comment]
Some amount of overflow inventory support has been added

**Comment by RaggyLP** [comment]
![image](https://github.com/user-attachments/assets/ef131a69-cb50-4114-a092-5c6cde3928b6)
Confirmed, overflow is now in place for certain elements, tested using mission rewards.

**Comment by prkdrake** [comment]
Should now be pretty much fully working

**Comment by kajoriEU** [comment]
Unfortunately it still breaks somewhat on leveling items.

When Leveling up an item with inventory being full, overflow does not open. `You need at least one free inventory slot! Please remove an item and try again.` is printed in chat and item is potentially lost.


https://github.com/user-attachments/assets/a26b67a7-e595-4d3a-a1b1-d52fadf13d47

**Comment by prkdrake** [comment]
Should be fixed with the latest update.

**Comment by kajoriEU** [comment]
The latest update seems to have fixed it 👍  


![{1F1BB277-8642-4D53-BE80-A0C94B196727}](https://github.com/user-attachments/assets/49308129-5206-4fbc-9a02-53b9bcb19cf6)


### Closing as fixed as of 15/09/2024
