### ISSUE TITLE
Attempting to enter a building in Boralis outputs an error, indicating that it should be sent to the devs. 

### ISSUE THREAD

**Issue by GlitchyGirl** [project-rubika/issues#434]
**Describe the bug**
There's a store that if memory serves sell healing supplies, but entering it gives an error that it says to send to the devs.

**To Reproduce**
1.  Attempt to enter  the building
2. Observe the following error message

------SEND THIS TO THE DEVS------
  destProxyModelType: 51102
  destProxyModelInst: 2062
  destProxyGroup: 0
  destProxySubgroup: -1073741024
  destProxyLocalizerType: 100002
  destProxyLocalizerInst: 1
----------------------------------

**Expected behavior**
That one is able to enter the building

 ** Location ** 

Extended location information:
- 625.6, 427.1, 68.2 (625.6 427.1 y 68.2 800)
- Pf Proxy: Model=51100:800 GS=0 SG=0 R=800, resource: 800
- zone: 265, area: "Borealis"
Server id: 1, character id: 50000:717, time: 2024-01-12 16:12:57 (UTC)
Version: 00.4.3_EP1, map id: NOT FOUND, build: 52606.-

**Comment by prkdrake** [comment]
This is another instance of #385
