### ISSUE TITLE
Multiple unique items can be purchased.

### ISSUE THREAD

**Issue by GlitchyGirl** [project-rubika/issues#435]
**Describe the bug**
Multiple unique items can be purchased at once, despite not showing that you are purchasing multiple unique items.

**To Reproduce**
1. Go to any store terminal selling a unique ql item
2. Click on the object as if to purchase multiple of them. (click multiple times)
3. Ensure you have enough money (/set cash xxxxx ) 
4. Hit accept
5. Observe the multiple unique items

**Expected behavior**
It should only let you purchase one of the item, or let you not purchase the unique item if it's in inventory already. (Second part works) 

**Screenshots**

Whilst purchasing the item
![image](https://github.com/project-rubika/issues/assets/43483963/97045dc6-521d-41cb-9fe7-98642e18220a)

After making the purchase 
![image](https://github.com/project-rubika/issues/assets/43483963/a33a6471-ef14-49db-a0f6-7a7baf3e4314)

**Comment by Random823** [comment]
Confirmed, working as intended. Tested with a Floating Torch from shop. Could not buy another.

**Comment by prkdrake** [comment]
Awesome, thanks for checking :)
