### ISSUE TITLE
Invalid gun drops, from enemies in the subway at least. 

### ISSUE THREAD

**Issue by GlitchyGirl** [project-rubika/issues#437]
**Describe the bug**
Enemies killed in the subway (only place I've tested this so far with loot drops/as far as I've gotten on this character), will drop invalid guns.  Or guns that have low ql, and requirements to equip with damage and effects on par with their higher QL counterparts.

**To Reproduce**
1. Go to subway (only place I can confirm)
2. Kill an enemy until you loot a gun
3. Observe it's requirements, and it's stats/name
4. Additionally, attempting to sell it will display a large sum of money in the trade terminal, but will instead take away money when sold

**Expected behavior**
Item should be in line with it's QL, and equip requirements, should give the correct amount of money when sold

** Additional notes **

Seems tied to or be similar to the bug seen here: https://github.com/project-rubika/issues/issues/322

**Comment by prkdrake** [comment]
This should now be fixed, could someone please verify this and let us know? Thank you!

**Comment by playboyfixer** [comment]
Tested: looters dropped low QL weapons, low req

Your Rifle and Sniper-Rifle is required to be at least 35!
Your Pistol is required to be at least 33!
Your Pistol is required to be at least 34!

selling to shop gives low creds in return which is correct
![image](https://github.com/project-rubika/issues/assets/156527345/4251bee7-2634-4ed2-9eb1-83e9fc9e35da)

**Comment by playboyfixer** [comment]
Irreparable Sentinels ETE Strike Gun
Ammo: 0/20
Rarity: Unknown
Quality level: 8
Requirements:
Wield:

On Self:
  Fling Shot from 18 and 
  Pistol from 34

Irreparable Seburo Bobsons
Ammo: 0/25
Rarity: Unknown
Quality level: 8
Requirements:
Wield:

On Self:
  Fling Shot from 18 and 
  Burst from 27 and 
  Ranged Ener from 22 and 
  Pistol from 33

Gripo-Com AKR 1K20
Ammo: 0/8
Rarity: Unknown
Quality level: 8
Requirements:
Wield:

On Self:
  Aimed Shot from 19 and 
  Rifle from 35

**Comment by playboyfixer** [comment]
All armor & weapon drops so far match exact level of mob dropping it (looter lvl 8 dropping QL 8 items
![image](https://github.com/project-rubika/issues/assets/156527345/587a8186-2aed-4cd8-a5dd-c267116d0535)

**Comment by playboyfixer** [comment]
Confirmed drops are now within the 25% QL range of npc level

**Comment by prkdrake** [comment]
awesome, thanks!
