### ISSUE TITLE
When looting some weapons, the loot window will not update showing that this item was looted.

### ISSUE THREAD

**Issue by GlitchyGirl** [project-rubika/issues#438]
**Describe the bug**
When looting some weapons from enemy corpses, those weapons will not show up as looted in the inventory window.

**To Reproduce**
1. Kill an enemy that drops a weapon (can also drop other items too)
2. Loot the corpse of the weapon, and observe that the weapon gives a message that it was looted but does not show up as looted in the inventory.
3. If another non-item weapon is there, loot it, and notice that the inventory updated, along with the same message indicating that it was looted

**Expected behavior**
Weapons looted should show as looted by:
1. Disappearing from the loot window when clicked on/looted
2. Having a text confirmation showing that weapon was looted

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/43483963/4f32735d-5ea7-4c22-a05a-da6f72f3029d)

**Comment by prkdrake** [comment]
I believe this should no longer occur, but I'm not 100% sure - could someone please verify whether this is still happening?

**Comment by Random823** [comment]
The loot windows acts as it should but I know receive a [Team Loot Messages] when looting. Not in a team.

**Comment by Random823** [comment]
Know = now

**Comment by prkdrake** [comment]
Okay, thanks - sounds like that should be raised as a separate issue @Random823, can you write a ticket for it? Thank you!

**Comment by Random823** [comment]
will do!
