### ISSUE TITLE
Bureaucrat Assistant Malfunctioning

### ISSUE THREAD

**Issue by Xannon21** [project-rubika/issues#440]
**Describe the bug**
-Bureaucrat Assistant is a white blob with no textures
-Bureaucrat Assistant is clunky when ordered to attack while standing outside melee range.

**To Reproduce**
1. Summon Assistant
2. Select target monster
3. Order Assistant to start combat via /pet attack macro or pet info 'Attack'

Current behavior:  

-When ordered to attack the Assistant will charge in and once reaching the target will stand idle for ~10 seconds after that period if the target has not relocated it may begin combat.
-Assistant is not issuing chat text (i.e. "Charge") when ordered to attack.
-Repeated uses of /petattack will cause the Assistant to rubberband as he is moving to the target.

**Expected behavior**
-When ordered to attack Assistant should move to melee range and begin combat with target.

**Screenshots**

![image](https://github.com/project-rubika/issues/assets/156465789/4ceb011b-05f7-49e0-b7b3-d122d5105327)
![image](https://github.com/project-rubika/issues/assets/156465789/49467095-13cc-408d-9283-bfa8cd73b2e9)

**Character info:**

```
Copy/paste the output of /getfull here
```
Xannick [38 Bureaucrat]
------------------------------------
    strength 	131
    stamina 	131
    agility 	114
    sense 	84
    psychic 	84
    intelligence 	84
    flags 	528961
    monsterscale 	112
    currentnano 	923
    headmesh 	40681
    cash 	898304084
    gmlevel 	127
    expansion 	3
    breed 	1
    visualbreed 	1
    profession 	8
    visualprofession 	8
    level 	38
    sex 	2
    visualsex 	2
    titlelevel 	2
    equippedweapontype 	17412
    EquippedRHWeapon 	17412
    health 	1671
    selectedtarget 	700
    selectedtargettype 	0
    currentncu 	353
    exitstatel 	-1069676651
    externaldoorinstance 	0
    externalplayfieldinstance 	0
    playfieldtype 	0
    nanoac 	179
    martialarts 	27
    brawl 	32
    riposte 	24
    dimach 	21
    adventuring 	30
    swim 	31
    onehandbluntweapons 	32
    onehandedgedweapon 	31
    piercing 	30
    twohandbluntweapons 	32
    twohandedgedweapons 	32
    meleeenergyweapon 	26
    parry 	28
    sneakattack 	24
    meleemultiple 	30
    fastattack 	25
    throwingknife 	27
    grenade 	24
    throwngrapplingweapons 	30
    bow 	26
    pistol 	25
    assaultrifle 	29
    submachinegun 	30
    shotgun 	107
    rifle 	25
    lr_energyweapon 	21
    flingshot 	50
    aimedshot 	21
    burst 	30
    fullauto 	32
    bowspecialattack 	25
    lr_multipleweapon 	80
    closecombatinitiative 	21
    distanceweaponinitiative 	76
    physicalprowessinitiative 	21
    nanoprowessinitiative 	114
    dodge 	136
    evade 	191
    duck 	125
    mechanicalengineering 	46
    electricalengineering 	80
    fieldquantumphysics 	21
    weaponsmithing 	26
    pharmaceuticals 	22
    nanoprogramming 	21
    computerliteracy 	21
    psychology 	54
    chemistry 	26
    tutoring 	43
    materialmetamorphose 	183
    biologicalmetamorphose 	314
    psychologicalmodification 	336
    materialcreation 	321
    materiallocation 	320
    senseimprovement 	305
    firstaid 	45
    treatment 	45
    concealment 	23
    breakingentry 	57
    disarmtrap 	22
    perception 	21
    driveair 	22
    driveground 	22
    drivewater 	22
    mapnavigation 	21
    bodydevelopment 	133
    nanoenergypool 	200
    runspeed 	795
    maxnanoenergy 	923
    expansionplayfield 	0
    xp 	666464
    nextxp 	713550
    lastsavexp 	47900
    charstate 	0
    isfightingme 	0
    lastxp 	662650
    maxncu 	392
    fatness 	1
    side 	0
    race 	1
    accountflags 	1234567890
    life 	1671
    monsterdata 	0
    VisualFlags 	31
    currentmovementmode 	3
    clan 	0
    projectiledamagemodifier 	40
    meleedamagemodifier 	40
    energydamagemodifier 	40
    chemicaldamagemodifier 	40
    radiationdamagemodifier 	40
    colddamagemodifier 	40
    firedamagemodifier 	40
    poisondamagemodifier 	40
    criticalincrease 	7
    amsmodifier 	100
    dmsmodifier 	310
    team 	0
    xpmodifier 	1000
    meleeac 	2520
    projectileac 	2520
    energyac 	2520
    fireac 	2673
    coldac 	2520
    radiationac 	2775
    chemicalac 	2673
    poisonac 	2520
    beltslots 	6
    healinterval 	25
    nanointerval 	26
    aggdef 	100
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    specialization 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    savedxp 	0
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    alignment 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    age 	0
    waitstate 	2
    attackspeed 	5
    metatype 	0
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
------------------------------------

.getfull succeeded.

**Playfield info:**

```
Copy/paste the output of Shift+F9 here
```
----
Extended location information:
- 1943.6, 774.3, 15.4 (1943.6 774.3 y 15.4 795)
- Pf Proxy: Model=51100:795 GS=0 SG=0 R=795, resource: 795
- zone: 2252, area: "Omni Tek mine"
Server id: 1, character id: 50000:700, time: 2024-01-12 20:42:16 (UTC)
Version: 00.4.3_EP1, map id: NOT FOUND, build: 52606.

**Comment by wowpin** [comment]
Just thought I'd mention that the "clunkyness" described above (including the rubber-banding on repeated using of /pet attack) is the very same behavior as observed in #492 and #347.

**Comment by TheTinkeringIdiot** [comment]
Added this info to #347 where several similar pet pathing/behavior issues are aggregated.
