### ISSUE TITLE
Unequipping back items not possible

### ISSUE THREAD

**Issue by playboyfixer** [project-rubika/issues#441]
**Describe the bug**
It's impossible to unequip back items, atleast for backpack (pioneer backpack).

**To Reproduce**
1. I had spawned GA1 and right clicked it, getting "You must have a Defensive Stance running!"
2. After this I can't unequip the pioneer backpack I had equipped. 

**Expected behavior**
can unequip :P

**Screenshots**

**Character info:**
Playboyfixer, lvl 1 fixer
```
Copy/paste the output of /getfull here
```

**Playfield info:**
Extended location information:
- 421.0, 338.3, 8.0 (421.0 338.3 y 8.0 540)
- Pf Proxy: Model=51100:540 GS=0 SG=0 R=540, resource: 540
- zone: 170, area: "Old Athen West"
Server id: 725, character id: 50000:725, time: 2024-01-13 15:09:42 (UTC)
Version: 00.4.3_EP1, map id: NOT FOUND, build: 52606.

----

**Comment by playboyfixer** [comment]
Update: when zoning the item is unequipped after all

**Comment by portalerprk** [comment]
Updating rolling out now. Please test when possible.

**Comment by playboyfixer** [comment]
Tested with Pioneer backpack and a random cloak bought from armor shop, working perfectly now.
