### ISSUE TITLE
Light of Reclaim terminal antenna in incorrect location (in front of terminal)

### ISSUE THREAD

**Issue by playboyfixer** [project-rubika/issues#447]
**Describe the bug**
The light on top of the reclaim terminal antenna is incorrectly in front of the terminal

**To Reproduce**
Go to reclaim terminal, light will be in front of terminal instead of on top of antenna

**Expected behavior**
Should be on top of antenna

**Screenshots**
Situation in PRoject RK:
![image](https://github.com/project-rubika/issues/assets/156527345/d3417544-32cb-41c8-a8d5-449e24739b96)

screenshot from old AO:
![image](https://github.com/project-rubika/issues/assets/156527345/76376ecb-261c-45ad-9f9a-7bd7cf9e243a)

**Character info:**
Playboyfixer [20 Fixer]
------------------------------------
    strength 	63
    stamina 	66
    agility 	75
    sense 	70
    psychic 	63
    intelligence 	66
    flags 	528961
    monsterscale 	100
    currentnano 	355
    headmesh 	223889
    cash 	899649622
    gmlevel 	127
    expansion 	3
    breed 	2
    visualbreed 	2
    profession 	4
    visualprofession 	4
    level 	20
    sex 	2
    visualsex 	2
    titlelevel 	2
    equippedweapontype 	20
    EquippedRHWeapon 	20
    health 	345
    selectedtarget 	725
    exitstatel 	-1073348481
    externaldoorinstance 	0
    externalplayfieldinstance 	0
    playfieldtype 	0
    side 	1
    selectedtargettype 	0
    currentncu 	0
    submachinegun 	107
    burst 	96
    nextxp 	155250
    xp 	139864
    lastsaved 	139850
    lastxp 	139850
    waitstate 	1
    bodydevelopment 	95
    runspeed 	109
    nanoenergypool 	95
    nanoac 	79
    distanceweaponinitiative 	96
    senseimprovement 	95
    treatment 	107
    materialmetamorphose 	95
    biologicalmetamorphose 	90
    psychologicalmodification 	95
    nanoprowessinitiative 	97
    dodge 	107
    evade 	96
    computerliteracy 	106
    currentmovementmode 	3
    isfightingme 	0
    charstate 	0
    materiallocation 	49
    maxncu 	8
    fatness 	1
    race 	1
    accountflags 	1234567890
    life 	420
    monsterdata 	0
    VisualFlags 	31
    clan 	0
    team 	0
    healinterval 	27
    maxnanoenergy 	355
    nanointerval 	26
    aggdef 	100
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    specialization 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    savedxp 	0
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    alignment 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    lastsavexp 	0
    martialarts 	22
    meleemultiple 	22
    onehandbluntweapons 	21
    onehandedgedweapon 	22
    piercing 	22
    twohandbluntweapons 	21
    twohandedgedweapons 	21
    meleeenergyweapon 	21
    throwingknife 	22
    grenade 	22
    throwngrapplingweapons 	22
    bow 	22
    pistol 	23
    rifle 	23
    shotgun 	22
    assaultrifle 	22
    drivewater 	22
    closecombatinitiative 	22
    physicalprowessinitiative 	22
    bowspecialattack 	22
    firstaid 	22
    mechanicalengineering 	22
    electricalengineering 	22
    materialcreation 	21
    lr_energyweapon 	21
    lr_multipleweapon 	22
    disarmtrap 	22
    perception 	22
    adventuring 	22
    swim 	21
    driveair 	22
    mapnavigation 	21
    tutoring 	21
    brawl 	21
    riposte 	23
    dimach 	22
    parry 	21
    sneakattack 	22
    fastattack 	23
    flingshot 	23
    aimedshot 	22
    duck 	22
    fieldquantumphysics 	21
    weaponsmithing 	21
    pharmaceuticals 	21
    nanoprogramming 	21
    psychology 	22
    chemistry 	21
    concealment 	22
    breakingentry 	22
    driveground 	22
    fullauto 	21
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    age 	0
    radiationac 	0
    attackspeed 	5
    metatype 	0
    fireac 	0
    poisonac 	0
    coldac 	0
    chemicalac 	0
    energyac 	0
    meleeac 	0
    projectileac 	0
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    beltslots 	0
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
------------------------------------

.getfull succeeded.

**Playfield info:**
Extended location information:
- 347.2, 390.8, 8.0 (347.2 390.8 y 8.0 540)
- Pf Proxy: Model=51100:540 GS=0 SG=0 R=540, resource: 540
- zone: 188, area: "Old Athen West"
Server id: 725, character id: 50000:725, time: 2024-01-13 16:48:44 (UTC)
Version: 00.4.3_EP1, map id: NOT FOUND, build: 52606.

----

**Comment by TheTinkeringIdiot** [comment]
Confirmed.

There is indeed a strange floating light in front of reclaim terminals. 

![image](https://github.com/project-rubika/issues/assets/96996793/408edd68-bfcd-41f7-ba2f-7104f329ae7a)

**Comment by prkdrake** [comment]
This should be fixed now

**Comment by TheTinkeringIdiot** [comment]
It does not appear to be fixed, the Quaternions strike again!

![image](https://github.com/project-rubika/issues/assets/96996793/5a4d9d15-5b33-42c6-b3b7-f398aa8b328e)

**Comment by RaggyLP** [comment]
Works on my machine.jpg

![image](https://github.com/project-rubika/issues/assets/156821187/3ae8896f-dbad-4ab1-b123-05259e1b9a59)

**Comment by TheTinkeringIdiot** [comment]
This is fixed in the RDB. Closing.
