### ISSUE TITLE
Uklesh stun locks himself

### ISSUE THREAD

**Issue by portalerprk** [project-rubika/issues#448]
Uklesh stun locks himself

**Comment by RaggyLP** [comment]
![image](https://github.com/user-attachments/assets/33ef76d2-727b-4c6c-afa1-2868d4dd1c60)

Uklesh stunlocks himself

**Comment by kajoriEU** [comment]
Uklesh seems to properly stun again.

Closing this as fixed 👍 

![{C9680EEE-7E90-4369-98BD-6FD717E6426F}](https://github.com/user-attachments/assets/f6313ccb-40ce-4f0e-9c92-e4ad42056f2a)
