### ISSUE TITLE
OA BY 16 exit not at actual door location

### ISSUE THREAD

**Issue by playboyfixer** [project-rubika/issues#450]
**Describe the bug**
When exiting backyard 16 in Old Athen, you don't show up at the door but at the exit where FC's AO by 16 location currently is

**To Reproduce**
1. Go north of OA hill to backyard 16 and enter
2. Exit by 16 again
3. You'll now be at another location more north-northeast

**Expected behavior**
Exit location being at the actual door of backyard

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/156527345/ba25eb54-c4f4-425e-8017-963b3572c575)
![image](https://github.com/project-rubika/issues/assets/156527345/f4396182-f418-419c-a965-c6f232ac66f9)

**Character info:**

**Playfield info:**
**_BY 16 location:_**
Extended location information:
- 425.9, 429.9, 8.0 (425.9 429.9 y 8.0 540)
- Pf Proxy: Model=51100:540 GS=0 SG=0 R=540, resource: 540
- zone: 210, area: "Old Athen West"
Server id: 1, character id: 50000:725, time: 2024-01-14 09:30:46 (UTC)
Version: 00.4.3_EP1, map id: NOT FOUND, build: 52606.

**_Where you end up exiting:_**
Extended location information:
- 434.5, 468.4, 8.0 (434.5 468.4 y 8.0 540)
- Pf Proxy: Model=51100:540 GS=0 SG=0 R=540, resource: 540
- zone: 230, area: "Old Athen West"
Server id: 725, character id: 50000:725, time: 2024-01-14 09:31:27 (UTC)
Version: 00.4.3_EP1, map id: NOT FOUND, build: 52606.

----

**Comment by 3F1-1009** [comment]
We found the problem and are working on it.

**Comment by playboyfixer** [comment]
tested and confirmed, exit works correct now
