### ISSUE TITLE
Multiple MA attacks in basic attacks booth with negative skill req

### ISSUE THREAD

**Issue by playboyfixer** [project-rubika/issues#455]
**Describe the bug**
In the Basic Attacks booth (OA basic store) there are multiple MA attacks that are not in FC's AO, which require negative skills. Will include screenshot list-view of AO + Proj RK

**To Reproduce**
1. Go to basic store
2. open Basic Attacks booth
3. you'll see about 8 MA attacks total, should only be 3

**Expected behavior**
MA attacks should have correct skill req listed

**Screenshots**
regular AO:
![image](https://github.com/project-rubika/issues/assets/156527345/796f6298-1e15-464d-8066-e4a9705eeaaf)

Project RK:
![image](https://github.com/project-rubika/issues/assets/156527345/1b1f2b35-015c-4ffa-a3d4-2c8cff9c1f38)
![image](https://github.com/project-rubika/issues/assets/156527345/aa493a26-5ff8-40ed-86dc-eb382b39fe01)

**Character info:**
Nopantsninja [1 MartialArtist]
------------------------------------
    strength 	6
    stamina 	9
    agility 	18
    sense 	13
    psychic 	6
    intelligence 	9
    flags 	528961
    monsterscale 	100
    currentnano 	43
    headmesh 	223889
    cash 	99892188
    gmlevel 	127
    expansion 	3
    breed 	2
    visualbreed 	2
    profession 	2
    visualprofession 	2
    level 	1
    sex 	2
    visualsex 	2
    titlelevel 	1
    health 	53
    equippedweapontype 	1
    EquippedRHWeapon 	1
    selectedtarget 	747
    bodydevelopment 	11
    nanoenergypool 	10
    runspeed 	13
    martialarts 	13
    physicalprowessinitiative 	12
    treatment 	12
    brawl 	11
    dimach 	12
    computerliteracy 	11
    side 	1
    exitstatel 	-1073740644
    externaldoorinstance 	-1071840740
    externalplayfieldinstance 	540
    playfieldtype 	1
    senseimprovement 	11
    materialmetamorphose 	11
    biologicalmetamorphose 	11
    psychologicalmodification 	11
    materiallocation 	11
    nanoprowessinitiative 	12
    maxncu 	8
    selectedtargettype 	0
    fatness 	1
    race 	1
    accountflags 	1234567890
    life 	53
    monsterdata 	0
    VisualFlags 	31
    isfightingme 	0
    currentmovementmode 	3
    clan 	0
    team 	0
    healinterval 	29
    maxnanoenergy 	43
    nanointerval 	28
    aggdef 	100
    nextxp 	1450
    lastxp 	0
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    specialization 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    savedxp 	0
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    nanoac 	5
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	1
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    alignment 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    lastsavexp 	0
    xp 	0
    meleemultiple 	8
    onehandbluntweapons 	7
    onehandedgedweapon 	7
    piercing 	8
    twohandbluntweapons 	6
    twohandedgedweapons 	6
    meleeenergyweapon 	7
    throwingknife 	8
    grenade 	8
    throwngrapplingweapons 	8
    bow 	8
    pistol 	9
    rifle 	9
    submachinegun 	7
    shotgun 	8
    assaultrifle 	8
    drivewater 	8
    closecombatinitiative 	7
    distanceweaponinitiative 	7
    bowspecialattack 	8
    firstaid 	8
    mechanicalengineering 	8
    electricalengineering 	7
    materialcreation 	7
    lr_energyweapon 	7
    lr_multipleweapon 	8
    disarmtrap 	8
    perception 	7
    adventuring 	8
    swim 	7
    driveair 	8
    mapnavigation 	7
    tutoring 	7
    riposte 	8
    parry 	7
    sneakattack 	8
    fastattack 	9
    burst 	8
    flingshot 	9
    aimedshot 	8
    duck 	8
    dodge 	8
    evade 	8
    fieldquantumphysics 	6
    weaponsmithing 	6
    pharmaceuticals 	7
    nanoprogramming 	7
    psychology 	7
    chemistry 	7
    concealment 	8
    breakingentry 	8
    driveground 	8
    fullauto 	6
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    age 	0
    waitstate 	2
    radiationac 	1
    attackspeed 	5
    metatype 	0
    fireac 	3
    poisonac 	1
    coldac 	3
    chemicalac 	1
    energyac 	3
    meleeac 	3
    projectileac 	3
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    beltslots 	0
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
------------------------------------

.getfull succeeded.

**Playfield info:**
Extended location information:
- 198.3, 164.4, 5.0 (198.3 164.4 y 5.0 1180)
- Pf Proxy: Model=51100:1180 GS=0 SG=0 R=1180, resource: 1180
- zone: 1, area: "Supermarket"
Server id: 747, character id: 50000:747, time: 2024-01-15 11:09:01 (UTC)
Version: 00.4.4_EP1, map id: NOT FOUND, build: 52606.

----

**Comment by TheTinkeringIdiot** [comment]
This appears to have been fixed in a recent update.
