### ISSUE TITLE
Vendors sell weapons with only 1 ammo in the clip

### ISSUE THREAD

**Issue by portalerprk** [project-rubika/issues#456]
Vendors have become very stingy with their ammunition. They only sells weapons with 1 shot in the clip.

**Comment by TheTinkeringIdiot** [comment]
Confirmed that this behavior does occur. Also confirmed that the vendors on live servers also sell items with one round in the magazine. 

Leaving open and flagging as Enhancement for consideration of future change. 

![image](https://github.com/project-rubika/issues/assets/96996793/a9ee7a3b-9292-4eb0-9519-e6a662020c17)

**Comment by prkdrake** [comment]
Matching live behaviour is good enough to close for me!
