### ISSUE TITLE
Grid access terminals do not work.

### ISSUE THREAD

**Issue by 3F1-1009** [project-rubika/issues#457]
**Describe the bug**
Using a grid access terminal does 1 of 2 things:
1) If you meet the requirements, then it does nothing.
2) If you do not meet the requirements, then you get a message about requirements, but twice.

**To Reproduce**
1. Go to 637.0 727.1 y 66.8 800
2. R-click on grid terminal
3. Nothing happens/Requirement message x2

**Expected behavior**
Player should be teleported to grid or requirements message should be shown once.

**Notes**
I have tested this behavior in Borealis city and OA.

**Comment by prkdrake** [comment]
Should be fixed now!

**Comment by 3F1-1009** [comment]
Working as intended now.
