### ISSUE TITLE
Launcher does not update current player count periodically

### ISSUE THREAD

**Issue by portalerprk** [project-rubika/issues#462]
Launcher does not update current player count periodically.

![image](https://github.com/project-rubika/issues/assets/60405799/a248e885-0d40-4df1-9e0d-d44fd744e94e)

**Comment by TheTinkeringIdiot** [comment]
Confirmed.

The launcher's Player count does not update even to include the player running it. 

![image](https://github.com/project-rubika/issues/assets/96996793/323628e1-bfbd-42c2-9bf0-98f60220083e)

**Comment by RaggyLP** [comment]
Launcher now dynamically updates to reflect the current number of active players. Clsoing as fixed as of 18/08/2024.
