### ISSUE TITLE
Linux launcher does not create ProjectRubiKa folder in non-default wine prefix

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#463]
**Describe the bug**
The launcher does not automatically create the ProjectRubiKa folder when attempting to change the wine prefix (that already exists) on a fresh install. 

**To Reproduce**
1. Start PRK.Launcher on Ubuntu 22.04 (with fresh 
2. Settings
3. Change Client Dir field to non-default (i.e. not .wine) prefix that already exists. Include the ProjectRubiKa folder at the end of the path. 
4. Change Prefix Root to non-default prefix
5. Save
6. Settings modal persists with error message: "AO Client path must be on the C: drive in the prefix root"

**Expected behavior**
The settings modal should close and settings be saved. 

**Workaround**
Manually creating the necessary ProjectRubiKa folder in the non-default prefix allows settings to be saved.

**Comment by portalerprk** [comment]
Oh you've hit a sore spot for sure! I do all my dev and playtime on a Kubuntu. :-) There are definitely rough edges.

**Comment by TheTinkeringIdiot** [comment]
Same here! My official client lives in a win32 wine prefix, which is how I ran in to this - since PRK is x86_64. Trying to run the Launcher using my default win32 .wine prefix lets everything look find until the Patcher launches, which just dies silently.

**Comment by TheTinkeringIdiot** [comment]
OBE, closing as fixed.
