### ISSUE TITLE
Cannot login on any character

### ISSUE THREAD

**Issue by AOFlux** [project-rubika/issues#467]
**Describe the bug**
Cannot login on any character. I was logged in on a character in Bore FT, and a message "Changing area, please wait" appeared in the chat window (without me doing anything - I was semi-afk looking for stuff on Auno.org), and Anarchy just froze. Now, I cannot log in on any character.

**To Reproduce**
Cannot reproduce, the character just doesn't log in - I'm stuck at "Anarchy Online is loading..." screen.

**Comment by prkdrake** [comment]
Closing this for now - it was just a performance issue on the server.
