### ISSUE TITLE
Items duplicate during trade

### ISSUE THREAD

**Issue by playboyfixer** [project-rubika/issues#470]
**Describe the bug**
When entering an item in trade window, the item is duplicated

**To Reproduce**
1. open trade with someone
2. enter item to trade

**Expected behavior**
Item shouldn't duplicate

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/156527345/087edde5-9739-4afe-82cd-5f273a36f68f)
![image](https://github.com/project-rubika/issues/assets/156527345/de5b1251-72a3-416c-bc9f-2082bfda19b8)
![image](https://github.com/project-rubika/issues/assets/156527345/9e0646fd-b899-4eea-969a-6a5aa5627414)

**Character info:**
Playboyfixer [220 Fixer]
------------------------------------
    bow 	2424
    pistol 	2433
    assaultrifle 	2403
    shotgun 	2418
    rifle 	2433
    lr_energyweapon 	2404
    aimedshot 	2428
    bowspecialattack 	2428
    lr_multipleweapon 	2418
    closecombatinitiative 	2417
    physicalprowessinitiative 	2417
    duck 	2424
    mechanicalengineering 	2413
    electricalengineering 	2400
    fieldquantumphysics 	2389
    weaponsmithing 	2391
    pharmaceuticals 	2400
    nanoprogramming 	2391
    psychology 	2409
    chemistry 	2380
    concealment 	2430
    disarmtrap 	2422
    perception 	2417
    driveair 	2422
    driveground 	2422
    drivewater 	2422
    mapnavigation 	2409
    strength 	1565
    stamina 	1481
    agility 	1745
    sense 	1713
    psychic 	1549
    intelligence 	1565
    flags 	528961
    monsterscale 	103
    currentnano 	10280
    headmesh 	223889
    cash 	100001676
    gmlevel 	127
    expansion 	3
    breed 	2
    visualbreed 	2
    profession 	4
    visualprofession 	4
    level 	220
    sex 	2
    visualsex 	2
    titlelevel 	7
    equippedweapontype 	20
    EquippedRHWeapon 	20
    health 	10045
    selectedtarget 	725
    exitstatel 	-1073348481
    externaldoorinstance 	0
    externalplayfieldinstance 	0
    playfieldtype 	0
    side 	1
    selectedtargettype 	0
    currentncu 	2
    submachinegun 	3512
    burst 	3350
    nextxp 	3067008
    xp 	2555840
    lastsaved 	2555840
    lastxp 	2555840
    waitstate 	1
    bodydevelopment 	2110
    runspeed 	3353
    nanoenergypool 	3130
    nanoac 	2940
    distanceweaponinitiative 	3357
    senseimprovement 	3481
    treatment 	3512
    materialmetamorphose 	3480
    biologicalmetamorphose 	3320
    psychologicalmodification 	3488
    nanoprowessinitiative 	3371
    dodge 	3524
    evade 	3364
    computerliteracy 	3491
    currentmovementmode 	3
    isfightingme 	0
    charstate 	0
    materiallocation 	3330
    firstaid 	2434
    swim 	2412
    tutoring 	2553
    aggdef 	1
    gang_dog_tags 	6
    lastsavexp 	6500
    expansionplayfield 	0
    flingshot 	2441
    fullauto 	2387
    debug 	0
    age 	99
    onehandbluntweapons 	2387
    breakingentry 	3200
    materialcreation 	2537
    martialarts 	2412
    brawl 	2382
    riposte 	2432
    dimach 	2420
    adventuring 	2407
    onehandedgedweapon 	2402
    piercing 	2407
    twohandbluntweapons 	2380
    twohandedgedweapons 	2382
    meleeenergyweapon 	2380
    parry 	2411
    sneakattack 	2421
    meleemultiple 	2416
    fastattack 	2433
    throwingknife 	2425
    grenade 	2424
    throwngrapplingweapons 	2418
    maxncu 	2008
    fatness 	1
    race 	1
    accountflags 	1234567890
    life 	8545
    monsterdata 	0
    VisualFlags 	31
    clan 	0
    xpmodifier 	13
    meleeac 	20698
    projectileac 	20698
    energyac 	20671
    chemicalac 	20619
    radiationac 	20541
    coldac 	20619
    fireac 	20541
    poisonac 	20619
    team 	0
    healinterval 	1
    maxnanoenergy 	10280
    nanointerval 	1
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    specialization 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    savedxp 	0
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    alignment 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    attackspeed 	5
    metatype 	0
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    beltslots 	0
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
    projectiledamagemodifier 	0
    meleedamagemodifier 	0
    energydamagemodifier 	0
    chemicaldamagemodifier 	0
    radiationdamagemodifier 	0
    colddamagemodifier 	0
    firedamagemodifier 	0
    poisondamagemodifier 	0
    amsmodifier 	0
    dmsmodifier 	0
------------------------------------

.getfull succeeded.

**Playfield info:**
Extended location information:
- 455.9, 409.8, 15.0 (455.9 409.8 y 15.0 540)
- Pf Proxy: Model=51100:540 GS=0 SG=0 R=540, resource: 540
- zone: 211, area: "Old Athen East"
Server id: 725, character id: 50000:725, time: 2024-01-16 19:07:57 (UTC)
Version: 00.4.4_EP1, map id: NOT FOUND, build: 52606.

----

**Comment by portalerprk** [comment]
@playboyfixer - test on Ithaca when ready. Thanks

**Comment by playboyfixer** [comment]
just tested, working perfect now. no duplicate during trade or after trade
