### ISSUE TITLE
Critical hits are not possible or are very unlikely

### ISSUE THREAD

**Issue by Rasuru2** [project-rubika/issues#471]
**Describe the bug**
Pets haven't crit in over 10 mob kills - not once

**Comment by prkdrake** [comment]
Should be working now

**Comment by Zolarix** [comment]
I tested on a 220 command-made MA in a backyard and got 3x crits in a row. If the bug was engineer pet-specific I will revisit this verification.

**Comment by wowpin** [comment]
Can confirm engi pet also managed to crit a few times:

![image](https://github.com/project-rubika/issues/assets/30692035/9b90af34-57a9-47c4-b8b4-3b645ca0c588)
