### ISSUE TITLE
When a user inserts wrong password on login screen, the feedback window is not useful

### ISSUE THREAD

**Issue by reneraen** [project-rubika/issues#475]
**Describe the bug**
The feedback window when a user tries to log in with an incorrect password is very limited in usability. It's completely blank and thus doesn't give any good feedback to the player.

**To Reproduce**
1. Go to the Project Rubi-Ka Launcher
2. Click on Play
3. Enter your username or password (wrong)
5. Select "Login"
6. See blank screen

**Expected behavior**
As a user that makes a mistake, either in username or password, I expect to be given a descriptive message that tells me that the password or username is unknown

**Screenshots**
![telegram-cloud-photo-size-4-5852951547615494111-y](https://github.com/project-rubika/issues/assets/48966634/78f17d39-0152-474c-92ef-24fdbd9eb432)

**Character info:**

```
N/A
```

**Comment by reneraen** [comment]
after a while you'll get the 504 Gateway Time-out...

**Comment by prkdrake** [comment]
Should be fixed now, needs re-testing

**Comment by RaggyLP** [comment]
![image](https://github.com/project-rubika/issues/assets/156821187/0a648617-2705-4ea8-aeac-11e72b460553)

There is a small delay of around 3s~ before the page is displayed, potentially webhost performance related? Confirmed as fixed as of 18:04 UTC - 25/01/24

**Comment by prkdrake** [comment]
It's just that the built-in web browser sucks, FC has the same issue on the live server
