### ISSUE TITLE
AoE Nukes do not damage targets in area

### ISSUE THREAD

**Issue by CRMCG-1** [project-rubika/issues#480]
**Describe the bug**
When targeting with an AoE, the nuke is on the "first spell" while the resulting AoE lacks any effect except aggro. 

**To Reproduce**
Use any target-cast AoE attack (VE, for example) on hostile enemies, or on-self. 

**Expected behavior**
The "first" spell does nothing, while the second causes damage to enemies in the area. 

**Screenshots**

**Character info:**

```
Copy/paste the output of /getfull here
```

**Playfield info:**

```
Copy/paste the output of Shift+F9 here
```
----

**Comment by reneraen** [comment]
I've validated same behaviour on my characters as well. It triggers aggro but no additional damage is added to the non-targetted targets in the area.

**Comment by reneraen** [comment]
What an interesting bug.

I've attempted all the AoE nukes except the one's that require cyberdeck and they have the same issue, the list of nano's attempted are:
![image](https://github.com/project-rubika/issues/assets/48966634/281a5e4d-4efc-407d-8ef6-a250f8cf20bc)


HOWEVER, here's where it becomes interesting. It's not that AoE doesn't work. It's that based on the amount of targets in the vicinity, it actually hits... the targetted mob (singular) for that amount. So if you had 100 targets around you, and ran an AoE attack, it would hit one target for 100(targets)x80(damage of nuke).

The below experiment is with 3 targets within the area of the attack (all visible in the image), casted 
![telegram-cloud-photo-size-4-5855203347429179778-y](https://github.com/project-rubika/issues/assets/48966634/b0ce9ca1-03c6-40d0-b7e3-2ce3ac740c15)

Here are some examples of various cases with various amount of npc's within the range of the AoE attack.
![telegram-cloud-photo-size-4-5855203347429179773-y](https://github.com/project-rubika/issues/assets/48966634/f059a128-b007-4d19-8fac-23f44a3e13dc)

**Comment by reneraen** [comment]
A fun one in this is that AoE DoT ( https://portal.project-rk.com/server/Ithaca/item/28799 ) actually hits you (same bug obviously) for the amount of players in the vicinity, but it executes on the targets, so all the follow-up dots... hit the targets in the vicinity 
![telegram-cloud-photo-size-4-5855203347429179779-x](https://github.com/project-rubika/issues/assets/48966634/aab62661-8706-4fbe-bc65-59c96a58e39c)

**Comment by portalerprk** [comment]
@reneraen  - Pushed a fix, please test.

**Comment by reneraen** [comment]
Works perfectly based on the limited testing I've done now. Cheers on the quick fixing here @portalerprk :)
