### ISSUE TITLE
Otacustes / Merc location in Eastern Foul Plains doesn't spawn mobs properly on zone initialisation

### ISSUE THREAD

**Issue by reneraen** [project-rubika/issues#481]
**Describe the bug**
Mobs are not where they should be and thus the spawn cannot function normally

**To Reproduce**
1. Go to Eastern Foul Plains ( /tp 710 1380 620)
2. Enter the camp
3. See lack of NPCs that should be there (terticus, secondus, primus etc. and randomly Otacustes)
4. Instead see also placeholder LE01 with "Unknown Hash: TEBU" etc. (but not in every location where they should be.

**Expected behavior**
Killable mobs should be places in locations

**Screenshots**
<img width="805" alt="image" src="https://github.com/project-rubika/issues/assets/48966634/eddc1c6d-0f7a-4cca-928d-1a1c13d18487">

**Character info:**

```
Not applicable
```

**Playfield info:**

```
(23:20) Extended location information:
(23:20) - 735.6, 1380.0, 49.3 (735.6 1380.0 y 49.3 620)
(23:20) - Pf Proxy: Model=51100:620 GS=0 SG=0 R=620, resource: 620
(23:20) - zone: 2670, area: "B.C.B.D.L.A."
(23:20) Server id: 772, character id: 50000:772, time: 2024-01-16 22:20:06 (UTC)
(23:20) Version: 00.4.4_EP1, map id: NOT FOUND, build: 52606.

```
----

**Comment by Rasuru2** [comment]
Also checked a few Dyna Camps in Omni Forrest and I didn't see any mobs or Dynas. Additionally I went to Steps of Maddness and the mobs all have less than 80 HP asside from Neleb.

**Comment by reneraen** [comment]
> Also checked a few Dyna Camps in Omni Forrest and I didn't see any mobs or Dynas. Additionally I went to Steps of Maddness and the mobs all have less than 80 HP asside from Neleb.

This is not same behaviour. Should be raised as several different tickets. The mob hp one is a calculation that has been talked about but it's not created as a separate ticket. It should however.

**Comment by reneraen** [comment]
Actually, I think this one might be more related to https://github.com/project-rubika/issues/issues/333

**Comment by 3F1-1009** [comment]
This seems to be problem coming from server having to choose from multiple NPCs that can spawn in one spot.

**Comment by portalerprk** [comment]
Fix is out. Needs testing.

**Comment by RaggyLP** [comment]
There are now Tertius & Secundus mobs now spawning in the area instead of Leets with hash names. They droped Refined implant/clusters as expected too. This particular issue is now fixed, however, the rest of the Merc raid prcoess requires further implementations. Closing this ticket as fixed from 18:15 UTC - 29/02/24 

![image](https://github.com/project-rubika/issues/assets/156821187/25d5bbf8-3dd1-4e83-885a-3fbeb97593f9)
![image](https://github.com/project-rubika/issues/assets/156821187/d546039a-bc0c-42d7-b47f-c0c85f8f7d4b)
