### ISSUE TITLE
Character creation: Atrox missing two faces

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#482]
**Describe the bug**
Two head options for Atrox are missing textures/models. 

**To Reproduce**
1. Start character creation
2. Select Atrox
3. Scroll through head options. Missing instances are 8 and 9 clicks to the right for me. 

**Expected behavior**
Atrox should probably have heads.

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/96996793/2809bde4-27ae-47ae-8874-f1c28dad0b14)

**Comment by Unknownprk** [comment]
This should now be working

**Comment by galku** [comment]
Verified working on client 0.4.7. Great job!
