### ISSUE TITLE
Character Creation: Strange Solitus Male Heads

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#483]
**Describe the bug**
Solitus Male head options appear to have a model/texture mismatch resulting in very strange looking head options. 

**To Reproduce**
1. Enter character creation
2. Select Solitus Male
3. Scroll through head options - several are strangely shaped for the applied texture

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/96996793/f960d45b-2aca-4f39-92fc-c078a5c25b1f)

**Comment by TheTinkeringIdiot** [comment]
![image](https://github.com/project-rubika/issues/assets/96996793/c0e91640-6e9c-40d5-a25a-a2a560e32b49)

**Comment by TheTinkeringIdiot** [comment]
Soli Female, Opifex M/F and Nanomage M/F look OK with all available options.

**Comment by prkdrake** [comment]
That first one is a custom head texture, it's SharpTony's face, lol. We also added, iirc, some of the cyborg head textures, which might be what you're seeing

**Comment by TheTinkeringIdiot** [comment]
Ha ha that's hilarious. 

It seems mostly confined to Solitus Male, which appears to have the most variation in head shape. Like the textures and models are being mismatched. The second screenshot is the most apparent example - I believe I recognize that face from live, but the model it's on doesn't appear to match.

**Comment by RaggyLP** [comment]
Checked the Solitus Male head on Live and this option has the game head structure as on PRK. Other than the Cyborg Head on both Soli M/F and Sharptonys face, there doesn't seem to be any other issues as listed. 

![image](https://github.com/project-rubika/issues/assets/156821187/82cef38a-d9c3-42be-b718-125799960d9f)

Closing this one for now :)
