### ISSUE TITLE
Weapon attack/recharge cycle pauses while moving

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#491]
**Describe the bug**
Weapon attack and recharge bars halt in place while the character is moving. 

**To Reproduce**
1. Select an enemy
2. Begin autoattack
3. Move the character
4. While the character is moving, the attack and recharge bars pause progress

**Expected behavior**
The attack or recharge of a weapon should continue while the character is moving until either extreme is reached. At that point progress does pause until the character stops moving and the attack or recharge cycle can complete. For example, starting the attack and then running toward an enemy should allow the attack time to count up until the bar is full, then pause until the character stops moving again at which time the attack executes.

**Comment by prkdrake** [comment]
Are you sure that it works that way on live? I thought the bars pause like that when you move on live as well, I remember it used to do that at least.

**Comment by TheTinkeringIdiot** [comment]
I could have sworn they did but double checked on live and apparently I'm misremembering. Nevermind, closing.
