### ISSUE TITLE
Aggression Enhancer cannot be equipped in Utils3

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#493]
**Describe the bug**
The Aggression Enhancer can be equipped in slots Utils3 and Decks 1, 2, 4, and 5. Attempting to equip the item in Utils3 results in the equip bar executing quickly, and then the item is not equipped. 

**To Reproduce**
1. Acquire an Aggression Enhancer
2. Pick up the Aggression Enhancer with the mouse, then attempt to place it in Utils3
3. The equip delay bar executes
4. The Aggression Enhancer does not appear in Utils3, and remains in inventory

**Expected behavior**
The Aggression Enhancer should successfully equip in Utils3

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/96996793/22abbbca-e399-4e33-9b56-0146f883a8e8)

**Comment by reneraen** [comment]
Note to self: should validate if this is all items in hud1,hud2,hud3, utils1, utils2, utils3 and if it's locked to certain characters or all characters.

Spawning Night vision goggles: ```/item 29738 29738 1 1```
Spawning Low Light Targeting Scope: ```/item 88375 88376 200 1```
Spawning Aggression enhancer: ```/item 83920 83919 2 1```
Spawning Flurry of blows: ```/item 85907 85908 25 1```
Spawning Treatment library: ```/item 161769 161770 5 1```
Spawning Da Taunter!: ```/item 158045 158046 10 1```

**Comment by TheTinkeringIdiot** [comment]
Behavior has changed, but the Aggression Enhancer still cannot be equipped. The item fails to equip as before, but now chat says "You've maxed our your belt slots" if no NCU deck is equipped. 

![image](https://github.com/project-rubika/issues/assets/96996793/1d91ff04-9ee7-4c23-98b2-ec930a965210)

Equipping a NCU belt allows the Aggression Enhancer to be equipped in Utils3.

**Comment by prkdrake** [comment]
I have reproduced this. You need free deck slots to equip the aggression enhancer into Utils3 even if you click and drop it directly into the Utils3 slot. Probably something weird with requirements check.

**Comment by RaggyLP** [comment]
This now appears to be solved, the item can be placed in Util 3 and also activated from the slot with no issues. Closing as fixed as of 31/08/2024.
