### ISSUE TITLE
Holding both mouse buttons does not cause the character to run forward

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#495]
**Describe the bug**
Default behavior on live is for holding both mouse buttons down together to act as the W key does and move the character forward until one or both are released. 

**To Reproduce**
1. Log in
2. Press and hold both left and right mouse buttons
3. Character does not move forward

**Expected behavior**
Holding both the left and right mouse buttons together should move the character forward.

**Comment by prkdrake** [comment]
I'm almost 100% sure this isn't a feature on live, at least in the old client. Maybe it's possible to do by changing your keybinds, though I'm not sure about that - either way, this is definitely a client-side thing, so it's not really in the scope of the project at the moment

**Comment by prkdrake** [comment]
@Unknownprk - tagging you for visibility

**Comment by prkdrake** [comment]
I checked on live, and it's the same thing there. I think you guys must be misremembering from another game! Closing as wontfix

**Comment by Dezzyx** [comment]
They could be mistaking it for pressing down scroll wheel, which is a default binding for Forward referred to as "Middle Press". Which I think sometimes may also be what you call pressing Left+Right mouse buttons at once. But in AO clicking both does not seem equal a key. It can also mean an actual Middle (third) mouse button. Mine does not register as a binding, but it's tied to mouse DPI change so maybe why. I mean to say maybe once in AO the "Middle Press" binding was Left+Right click, then changed to scroll press / potential third button.

![Screenshot 2024-08-19 182355](https://github.com/user-attachments/assets/9af5a53b-db22-420a-8e19-c97790a364b2)
