### ISSUE TITLE
Unable to login character in after crash

### ISSUE THREAD

**Issue by Auctoria** [project-rubika/issues#498]
**Describe the bug**
Unable to log character Auctoria in after crash while zoning (Omni Trade to Omni Ent via whompah)

**To Reproduce**
1. Log in to client account
2. Select character "Auctoria"
3. Select Play
4. wait for "Please Wait" loading bar to timeout and get retruned to log in

**Expected behavior**
Load into game

**Screenshots**
N/A

**Character info:**
Auctoria, Level 1 Enforcer
```
Copy/paste the output of /getfull here
Unavailable
```
**Playfield info:**
Omni-1 Entertainment (705)
```
Copy/paste the output of Shift+F9 here
Unavailable
----

**Comment by prkdrake** [comment]
This kind of thing can happen for a few reasons 

1. The character itself is broken in some way
2. The playfield you're trying to get into is broken
3. There are some issues on the server itself

We have a button in the Player Portal (Game Accounts -> Characters) that lets you return your character to Newland City. If you encounter an issue like this, try using that, and hopefully you can log back in.

**Comment by reneraen** [comment]
based on the time this was submitted (10:00 GMT) I think this was around the time when the playfield server was acting up. Could you please verify that this is the case and that you can login now (before doing the suggested workaround from Prkdrake above), @Auctoria ?

**Comment by prkdrake** [comment]
Since the server has been wiped, this seems no longer relevant to keep around.
