### ISSUE TITLE
Playshift requirements are not enforced

### ISSUE THREAD

**Issue by CRMCG-1** [project-rubika/issues#499]
**Describe the bug**
When entering certain playfields (Camelot Castle, in this instance) with a Yalm equipped, your player character may still "fly" in a fashion similar to Quantum Wings. 

**To Reproduce**
Equip a Stiletto (or other) type of Yalm, enter Camelot Castle (potentially other indoor zones, too) 

**Expected behavior**
Both vehicle and flight to disengage

**Comment by portalerprk** [comment]
Can you try flying into a shop?

**Comment by TheTinkeringIdiot** [comment]
Confirmed. 

Equipping a Yalmaha - 29478 (`/item 117322 96088 30`) then flying in to a shop leaves the Yalm equipped (which is normal) but also does not cancel the flying effect. The player reverts to the normal model inside the shop but can still fly.

**Comment by portalerprk** [comment]
Fixing in https://github.com/project-rubika/engines/pull/496

**Comment by RaggyLP** [comment]
Confirmed, this is now no longer an issue. Closing as fixed as of 31/08/2024.
