### ISSUE TITLE
Many items have only QL1 and QL200 - implants, clusters, stims and more

### ISSUE THREAD

**Issue by AOFlux** [project-rubika/issues#502]
**Describe the bug**
Implants, clusters and stims are being generated only with QL1 or QL200.
Implants are not being bumped while using a cluster on them.

**To Reproduce**
1. Do /item 107033 107033 60 (this is a regular QL60 implant) - it will be spawned as QL60, but with QL1 requirements and QL1 effects.
2. Can replicate for the majority of components and utilities - including treatment libraries and more.

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/156434075/6b9dc806-a712-4aa1-93ef-4c8d63d8a4e9)

**Comment by prkdrake** [comment]
You're not using the command correctly - you need the low ID and the high ID, and you're only specifying one of the IDs. 

If you look here:

https://portal.project-rk.com/server/Ithaca/item/107033

![image](https://github.com/project-rubika/issues/assets/154430828/0bd6e4a0-26a2-47f6-8bf1-eb6990ec288b)

Try the item command using these parameters:

`.item 107033 107034 60`

**Comment by AOFlux** [comment]
Ah, my bad. Thanks !

**Comment by prkdrake** [comment]
No problem, thanks for raising the issue anyways, it might be a good idea to ask in the discord if something is an issue before raising a bug ticket in future, someone probably would have caught the mistake and helped you out with it.

**Comment by AOFlux** [comment]
Got it, will ask in discord from now on ! Thanks !
