### ISSUE TITLE
Can't Equip Candy Cord due to Title Level

### ISSUE THREAD

**Issue by Rasuru2** [project-rubika/issues#508]
**Describe the bug**
Trying to equip a ql 5 candy cord that requires TL1 on my Level 1 Engi. Getting a message
"Your Title level is required to be at least 1!
You're unable to wear this item.." 

**To Reproduce**
1. Make a level 1 toon 
2. Spawn Candy Cord
3. /item 151745 151746 5 1
4. Try to equip 

**Expected behavior**
Should be able to equip no problem since a level 1 is already title level 1

Get Full 

Everbots [5 Engineer]
------------------------------------
    strength 	34
    stamina 	34
    agility 	34
    sense 	34
    psychic 	34
    intelligence 	42
    flags 	528961
    monsterscale 	103
    currentnano 	99
    headmesh 	223801
    cash 	899944303
    gmlevel 	127
    expansion 	3
    breed 	1
    visualbreed 	1
    profession 	3
    visualprofession 	3
    level 	5
    sex 	2
    visualsex 	2
    titlelevel 	1
    health 	130
    equippedweapontype 	1028
    EquippedRHWeapon 	1028
    selectedtarget 	777
    side 	1
    alignment 	1750
    currentmovementmode 	3
    waitstate 	1
    exitstatel 	-1073348481
    externaldoorinstance 	-1070988772
    externalplayfieldinstance 	540
    playfieldtype 	1
    treatment 	34
    firstaid 	26
    grenade 	18
    mechanicalengineering 	19
    electricalengineering 	19
    fieldquantumphysics 	19
    weaponsmithing 	19
    pharmaceuticals 	20
    psychology 	19
    chemistry 	19
    tutoring 	169
    duck 	18
    materialcreation 	70
    materiallocation 	70
    breakingentry 	18
    disarmtrap 	18
    psychologicalmodification 	65
    swim 	40
    bodydevelopment 	33
    runspeed 	49
    nanoenergypool 	33
    pistol 	53
    lr_multipleweapon 	49
    burst 	53
    flingshot 	53
    computerliteracy 	40
    senseimprovement 	55
    materialmetamorphose 	60
    currentncu 	16
    selectedtargettype 	0
    timeexist 	2
    99333 	2
    assaultrifle 	28
    submachinegun 	28
    shotgun 	28
    rifle 	28
    bow 	28
    aimedshot 	28
    fullauto 	28
    bowspecialattack 	28
    biologicalmetamorphose 	30
    maxnanoenergy 	144
    distanceweaponinitiative 	16
    dodge 	13
    maxncu 	18
    fatness 	1
    race 	1
    accountflags 	1234567890
    life 	151
    monsterdata 	0
    VisualFlags 	31
    isfightingme 	0
    clan 	0
    team 	0
    projectiledamagemodifier 	7
    energydamagemodifier 	17
    chemicalac 	294
    coldac 	294
    energyac 	335
    fireac 	265
    meleeac 	335
    poisonac 	294
    projectileac 	335
    radiationac 	265
    chemicaldamagemodifier 	10
    poisondamagemodifier 	10
    healdelta 	12
    shieldmeleeac 	10
    shieldprojectileac 	10
    shieldenergyac 	10
    shieldfireac 	10
    shieldcoldac 	10
    shieldchemicalac 	10
    shieldradiationac 	10
    shieldpoisonac 	10
    xpmodifier 	8
    healinterval 	28
    nanointerval 	28
    aggdef 	100
    nextxp 	15650
    lastxp 	0
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    specialization 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    savedxp 	0
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    nanoac 	5
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    lastsavexp 	4000
    xp 	15149
    martialarts 	13
    meleemultiple 	13
    onehandbluntweapons 	13
    onehandedgedweapon 	13
    piercing 	13
    twohandbluntweapons 	13
    twohandedgedweapons 	13
    meleeenergyweapon 	14
    throwingknife 	13
    throwngrapplingweapons 	13
    drivewater 	13
    closecombatinitiative 	13
    physicalprowessinitiative 	13
    lr_energyweapon 	13
    perception 	14
    adventuring 	13
    driveair 	13
    mapnavigation 	14
    brawl 	13
    riposte 	13
    dimach 	13
    parry 	13
    sneakattack 	14
    fastattack 	13
    nanoprowessinitiative 	13
    evade 	13
    nanoprogramming 	15
    concealment 	13
    driveground 	13
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    age 	0
    attackspeed 	5
    metatype 	0
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    beltslots 	0
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
    charstate 	0
    amsmodifier 	0
    damageoverridetype 	0
    xppool 	0
    ip 	6790
------------------------------------

.getfull succeeded.

**Comment by reneraen** [comment]
@Rasuru2 : could you please use /getfull on yourself when commiting these kinds of issues? :)

**Comment by Rasuru2** [comment]
Yes - sorry! Will do moving forward.

**Comment by reneraen** [comment]
Verified this bug. Even tried manually setting titlelevel for my character for the item: Candy Cord (ql5): https://portal.project-rk.com/server/Ithaca/item/151746?ql=5&debug=True

![telegram-cloud-photo-size-4-5857129751930584928-x](https://github.com/project-rubika/issues/assets/48966634/46976ee7-4335-4fb3-954a-78d4ce4b00b9)

Without any success. Setting level to 15 through ```/set level 15``` as mentioned by @3F1-1009 works though.

**Comment by 3F1-1009** [comment]
Requirements in game:
  Sense from 21 and 
  TitleLevel from 1

Requirements in portal db:

titlelevel GreaterThan 1 And
sense GreaterThan 20

TitleLevel appears to be interpolated wrong

**Comment by portalerprk** [comment]
Should be fixed now. Please test and confirm.

**Comment by RaggyLP** [comment]
Candy Cord can now be equipped at TL1. Confirmed fixed as of 13:47 UTC - 17/02/24

![image](https://github.com/project-rubika/issues/assets/156821187/bd2cf0c5-8db9-455d-bad5-aa03c4cd45e6)
