### ISSUE TITLE
Removing unique item from shop sell window will give a message you already have the item

### ISSUE THREAD

**Issue by playboyfixer** [project-rubika/issues#512]
**Describe the bug**
When putting an unique item in a shop booth window to sell, but then removing it again will remove it fine, but give you a message that it's unique and you already have it:

Intelligent Ocular Symbiant, Artillery Unit Aban unique and you already have it in your inventory.

**To Reproduce**
1. open shop booth
2. put an unique item in the shop booth to sell
3. remove the unique item again

**Expected behavior**
No message should come, as you can't carry more than 1 unique anyway

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/156527345/9dde2819-63df-46e2-9b48-e5c0294d0e0f)
![image](https://github.com/project-rubika/issues/assets/156527345/10395193-53c1-46aa-a874-1c01ed5fde87)
![image](https://github.com/project-rubika/issues/assets/156527345/b11c1a0c-d04d-4864-91ad-7a57e22776e2)

**Character info:**
Playboyfixer [220 Fixer]
------------------------------------
    strength 	765
    stamina 	681
    agility 	945
    sense 	913
    psychic 	749
    intelligence 	765
    flags 	528961
    monsterscale 	103
    currentnano 	10280
    headmesh 	223889
    cash 	98750669
    gmlevel 	127
    expansion 	3
    breed 	2
    visualbreed 	2
    profession 	4
    visualprofession 	4
    level 	220
    sex 	2
    visualsex 	2
    titlelevel 	7
    equippedweapontype 	20
    EquippedRHWeapon 	20
    health 	8545
    selectedtarget 	725
    exitstatel 	-1073740642
    externaldoorinstance 	-1071447524
    externalplayfieldinstance 	540
    playfieldtype 	1
    side 	1
    selectedtargettype 	0
    currentncu 	0
    submachinegun 	1312
    burst 	1150
    nextxp 	3067008
    xp 	2555840
    lastsaved 	2555840
    lastxp 	2555840
    waitstate 	1
    bodydevelopment 	1110
    runspeed 	1333
    nanoenergypool 	1130
    nanoac 	940
    distanceweaponinitiative 	1157
    senseimprovement 	1131
    treatment 	1312
    materialmetamorphose 	1130
    biologicalmetamorphose 	970
    psychologicalmodification 	1138
    nanoprowessinitiative 	1171
    dodge 	1324
    evade 	1164
    computerliteracy 	1291
    currentmovementmode 	3
    isfightingme 	0
    charstate 	0
    materiallocation 	980
    firstaid 	234
    swim 	212
    tutoring 	353
    aggdef 	1
    gang_dog_tags 	6
    lastsavexp 	6500
    expansionplayfield 	0
    flingshot 	241
    fullauto 	187
    debug 	0
    age 	99
    onehandbluntweapons 	187
    breakingentry 	1000
    materialcreation 	187
    martialarts 	212
    brawl 	182
    riposte 	232
    dimach 	220
    adventuring 	207
    onehandedgedweapon 	202
    piercing 	207
    twohandbluntweapons 	180
    twohandedgedweapons 	182
    meleeenergyweapon 	180
    parry 	211
    sneakattack 	221
    meleemultiple 	216
    fastattack 	233
    throwingknife 	225
    grenade 	224
    throwngrapplingweapons 	218
    bow 	224
    pistol 	233
    assaultrifle 	203
    shotgun 	218
    rifle 	233
    lr_energyweapon 	204
    aimedshot 	228
    bowspecialattack 	228
    lr_multipleweapon 	218
    closecombatinitiative 	217
    physicalprowessinitiative 	217
    duck 	224
    mechanicalengineering 	213
    electricalengineering 	200
    fieldquantumphysics 	189
    weaponsmithing 	191
    pharmaceuticals 	200
    nanoprogramming 	191
    psychology 	209
    chemistry 	180
    concealment 	230
    disarmtrap 	222
    perception 	217
    driveair 	222
    driveground 	222
    drivewater 	222
    mapnavigation 	209
    maxncu 	264
    fatness 	1
    race 	1
    accountflags 	1234567890
    life 	5545
    monsterdata 	0
    VisualFlags 	31
    clan 	0
    xpmodifier 	3
    team 	0
    chemicalac 	119
    coldac 	119
    energyac 	171
    fireac 	41
    meleeac 	198
    poisonac 	119
    projectileac 	198
    radiationac 	41
    beltslots 	6
    healinterval 	7
    maxnanoenergy 	4280
    nanointerval 	4
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    specialization 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    savedxp 	0
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    alignment 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    attackspeed 	5
    metatype 	0
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
------------------------------------

.getfull succeeded.

**Playfield info:**
Extended location information:
- 194.6, 193.8, 7.1 (194.6 193.8 y 7.1 1182)
- Pf Proxy: Model=51100:1182 GS=0 SG=0 R=1182, resource: 1182
- zone: 1, area: "Area"
Server id: 725, character id: 50000:725, time: 2024-01-17 21:33:15 (UTC)
Version: 00.4.5_EP1, map id: NOT FOUND, build: 52606.

----

**Comment by TheTinkeringIdiot** [comment]
Confirmed. The UNIQUE item can be removed from the shop interface and properly returns to the player's inventory, but also displays the error as reported. Testing with another UNIQUE item Nanoprogramming Interface (`.item 161699 161699 1`) displayed the same behavior. 

![image](https://github.com/project-rubika/issues/assets/96996793/9ce2fb23-e6a0-4d94-934b-8c4f88eb0bcb)

**Comment by kajoriEU** [comment]
This does not seem to be reproducible anymore.

Closing this as fixed for now.

https://github.com/user-attachments/assets/55e31c24-e054-4139-b9e4-414426c7f358
