### ISSUE TITLE
Jump height is about 2x the actual AO jump height

### ISSUE THREAD

**Issue by playboyfixer** [project-rubika/issues#514]
**Describe the bug**
Jump height is 2ce what I can go in actual AO

**To Reproduce**
1. Jump
2. jump again
3. jump once more, just to be sure :P

**Expected behavior**
jump height 50% of what it is now (maybe +300% for fixers ;) )

**Screenshots**
regular AO height
![image](https://github.com/project-rubika/issues/assets/156527345/e4d2c464-fe2d-4fd5-ace1-e4e6813e2ff1)

Proj RK height
![image](https://github.com/project-rubika/issues/assets/156527345/ae94bd32-339d-4b17-90e6-cb4a1ee1b35d)

**Character info:**
(22:02) Playboyfixer [220 Fixer]
------------------------------------
    materiallocation 	980
    firstaid 	234
    swim 	212
    tutoring 	353
    aggdef 	1
    gang_dog_tags 	6
    lastsavexp 	6500
    expansionplayfield 	0
    flingshot 	241
    fullauto 	187
    debug 	0
    age 	99
    onehandbluntweapons 	187
    breakingentry 	1000
    materialcreation 	187
    martialarts 	212
    brawl 	182
    riposte 	232
    dimach 	220
    adventuring 	207
    onehandedgedweapon 	202
    piercing 	207
    twohandbluntweapons 	180
    twohandedgedweapons 	182
    meleeenergyweapon 	180
    parry 	211
    sneakattack 	221
    meleemultiple 	216
    fastattack 	233
    throwingknife 	225
    grenade 	224
    throwngrapplingweapons 	218
    bow 	224
    pistol 	233
    assaultrifle 	203
    shotgun 	218
    rifle 	233
    lr_energyweapon 	204
    aimedshot 	228
    bowspecialattack 	228
    lr_multipleweapon 	218
    closecombatinitiative 	217
    physicalprowessinitiative 	217
    duck 	303
    mechanicalengineering 	213
    electricalengineering 	200
    fieldquantumphysics 	189
    weaponsmithing 	191
    pharmaceuticals 	200
    nanoprogramming 	191
    psychology 	209
    chemistry 	180
    concealment 	230
    disarmtrap 	222
    perception 	217
    driveair 	222
    strength 	765
    stamina 	681
    agility 	945
    sense 	913
    psychic 	749
    intelligence 	765
    flags 	528961
    monsterscale 	103
    currentnano 	9139
    headmesh 	223889
    cash 	98762228
    gmlevel 	127
    expansion 	3
    breed 	2
    visualbreed 	2
    profession 	4
    visualprofession 	4
    level 	220
    sex 	2
    visualsex 	2
    titlelevel 	7
    equippedweapontype 	20
    EquippedRHWeapon 	20
    health 	5545
    selectedtarget 	725
    exitstatel 	-1073740642
    externaldoorinstance 	0
    externalplayfieldinstance 	0
    playfieldtype 	0
    side 	1
    selectedtargettype 	0
    currentncu 	73
    submachinegun 	1312
    burst 	1150
    nextxp 	3067008
    xp 	2555840
    lastsaved 	2555840
    lastxp 	2555840
    waitstate 	1
    bodydevelopment 	1110
    runspeed 	2053
    nanoenergypool 	1130
    nanoac 	940
    distanceweaponinitiative 	1157
    senseimprovement 	1131
    treatment 	1312
    materialmetamorphose 	1130
    biologicalmetamorphose 	970
    psychologicalmodification 	1138
    nanoprowessinitiative 	1171
    dodge 	1403
    evade 	1243
    computerliteracy 	1291
    currentmovementmode 	3
    isfightingme 	0
    charstate 	0
    driveground 	222
    drivewater 	222
    mapnavigation 	209
    maxncu 	264
    fatness 	1
    race 	1
    accountflags 	1234567890
    life 	5545
    monsterdata 	0
    VisualFlags 	31
    clan 	0
    xpmodifier 	3
    team 	0
    chemicalac 	119
    coldac 	119
    energyac 	171
    fireac 	41
    meleeac 	198
    poisonac 	119
    projectileac 	198
    radiationac 	41
    beltslots 	6
    healinterval 	7
    maxnanoenergy 	4280
    nanointerval 	4
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    specialization 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    savedxp 	0
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    alignment 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    attackspeed 	5
    metatype 	0
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
------------------------------------

(22:02) .getfull succeeded.

**Playfield info:**
(22:02) Extended location information:
(22:02) - 590.7, 364.9, 0.0 (590.7 364.9 y 0.0 640)
(22:02) - Pf Proxy: Model=51100:640 GS=0 SG=0 R=640, resource: 640
(22:02) - zone: 194, area: "Tir City"
(22:02) Server id: 725, character id: 50000:725, time: 2024-01-17 22:02:37 (UTC)
(22:02) Version: 00.4.5_EP1, map id: NOT FOUND, build: 52606.
----

**Comment by reneraen** [comment]
I think this is related to the nerf around when SL was released from my own experience as well... as jumping used to be more "fun" in this game (like it is on PRK)

**_This behaviour is technically also referenced here_**: https://forums-archive.anarchy-online.com/showthread.php?401764-Jumping-height-is-influenced-by/page2 

which I'd say isn't technically a bug. It's just how it was pre-nerf back in... some patch.

**Comment by TheTinkeringIdiot** [comment]
As the forum thread linked by reneraen indicates, this is most likely normal pre-nerf behavior. Max jump height can be adjusted in the future if necessary.
