### ISSUE TITLE
Random sitting when zoning

### ISSUE THREAD

**Issue by PlaneteerAO** [project-rubika/issues#515]
Randomly after zoning, character will be sitting upon entering the new zone. This has happened zoning from West Athen to Old Athen, and using the Whompah from ICC to Tir.

**Comment by reneraen** [comment]
@PlaneteerAO : please follow the template.

**Comment by prkdrake** [comment]
Should be fixed now, needs to be re-tested, please let us know :) Thanks!

**Comment by RaggyLP** [comment]
Following the repro steps given by @wowpin, it would appear that this is now fixed as of 19:24 UTC - 25/01/24
