### ISSUE TITLE
When using the command menu to grant a QL 230 right wrist control symbiant, it will instead grant a "Alert Ocular Symbiant, Control Unit Aban" which breaks the character when equipped

### ISSUE THREAD

**Issue by Zolarix** [project-rubika/issues#521]
**Describe the bug**
When using the command menu to grant a QL 230 right wrist Control symbiant, it will instead grant a "Alert Ocular Symbiant, Control Unit Aban" according to the command response.

This does still appear to have all of the properties of a right wrist implant, including the thumbnail and statistics. However, once equipped, the head of the character will disappear. A few minutes later, the character will be disconnected.

Upon attempting to log back in, consecutive attempts may fail. If you are able to connect, you will see some placeholder stats in the character info window, all equipment slots will be empty even though the character model still has items equipped, and the character's Info panel will say "Profession: Not chosen yet." The character will not be able to zone.

**To Reproduce**

1. Use the command menu to give yourself a QL 230 right wrist control symbiant (The menu runs the command '/item 236298 236398 230')
2. Do whatever is necessary to equip the symbiant (in my case I used a command to set the level to 220, allocated IP and perks, gave myself stat buffs and equipped medsuit, 6 deck, 5x Ql 240 Yuttos, shades of lucubration and 2x VTEs).
3. Equip the symbiant.
Observe -> The character's head disappears. The described symptoms will follow.

**Expected behavior**

**Screenshots**
![Screenshot 2024-01-18 184242](https://github.com/project-rubika/issues/assets/96363854/66440b74-f3fb-41e6-8b59-76ae49487e48)
![Screenshot 2024-01-18 185034](https://github.com/project-rubika/issues/assets/96363854/54dc172b-cb92-4415-99a0-be14d9be11e5)

**Character info:**

```
/getfull does not work once in this state. Basic properties:
Level 220
Nanomage
Male
Default model
Meta-physicist
All attributes, Nanoskills, Computer Literacy, Treatment, First Aid, Run Speed maxed out.
```

**Playfield info:**

```
Extended location information:
- 206.6, 125.0, 5.0 (206.6 125.0 y 5.0 1187)
- Pf Proxy: Model=51100:1187 GS=0 SG=0 R=1187, resource: 1187
- zone: 0, area: "Area"
Server id: 907, character id: 50000:907, time: 2024-01-18 18:56:56 (UTC)
Version: 00.4.5_EP1, map id: NOT FOUND, build: 52606.

```
----

**Comment by prkdrake** [comment]
This should now be fixed, thanks for reporting it. 

Could someone please re-test and let us know?

**Comment by Zolarix** [comment]
Menu now runs the command:  '/item 236398 236398 230'
Command returns: '1x QL 230 Vigorous Right Wrist Symbiant, Control Unit Aban to your inventory.' which is accurate, unlike the old behavior.
When equipping the item, the head does not disappear and the character can be logged into with its stats and inventory being preserved.
Issue is now resolved.
