### ISSUE TITLE
Red dress gives error in database listing on portal listing

### ISSUE THREAD

**Issue by reneraen** [project-rubika/issues#532]
**Describe the bug**
I search for "Red dress" (https://portal.project-rk.com/server/Ithaca/search/red%20dress) and get the search results
**To Reproduce**
1. Go to portal.project-rk.com
2. Type in "red dress"
3. Click the search result
4. See error screen pop up

**Expected behavior**

**Screenshots**
<img width="777" alt="image" src="https://github.com/project-rubika/issues/assets/48966634/d8d06186-a6d2-432f-a2c4-4371628ff59a">
![image](https://github.com/project-rubika/issues/assets/48966634/dacf2c24-22ec-4f91-adf2-c7b5f96c7c8c)
<img width="1112" alt="image" src="https://github.com/project-rubika/issues/assets/48966634/ae8b97ca-4224-4a47-8684-5a4ec37b019f">

----

**Comment by portalerprk** [comment]
Fixed. @reneraen  please confirm and close.

**Comment by reneraen** [comment]
Confirmed working. Thank you :)
