### ISSUE TITLE
Token board resets on right click instead of showing token numbers.

### ISSUE THREAD

**Issue by praxis1988** [project-rubika/issues#534]
**Describe the bug**
When right clicking the token board, if you're not the appropriate level for the next upgrade, it resets your token board to the previous level.
It should display the number of tokens accumulated & not delete the token board.

**To Reproduce**
Get a token board (change sides with a side change from the shop, to receive the token board).
Set your tokens to whatever number.
Right click token board to upgrade it.
Continue right clicking until it returns to the base token board.

**Expected behavior**
When right clicking the token board, it shouldn't delete the current token board.

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/25720793/7a806953-b1c3-4b02-8c8e-d7e93845da52)
![image](https://github.com/project-rubika/issues/assets/25720793/36014b61-aa78-4096-aa6d-ef97b1847db5)

**Character info:**
Thurisaz [2 Adventurer]
------------------------------------
    strength 	9
    stamina 	12
    agility 	21
    sense 	16
    psychic 	9
    intelligence 	12
    flags 	528961
    monsterscale 	100
    currentnano 	37
    headmesh 	40242
    cash 	1361
    gmlevel 	127
    expansion 	3
    breed 	2
    visualbreed 	2
    profession 	6
    visualprofession 	6
    level 	2
    sex 	3
    visualsex 	3
    titlelevel 	1
    health 	79
    equippedweapontype 	1028
    EquippedRHWeapon 	1028
    selectedtarget 	823
    currentmovementmode 	3
    waitstate 	2
    bodydevelopment 	18
    runspeed 	19
    pistol 	19
    distanceweaponinitiative 	16
    treatment 	18
    lr_multipleweapon 	17
    flingshot 	20
    computerliteracy 	16
    exitstatel 	-1073740874
    externaldoorinstance 	-418378777
    externalplayfieldinstance 	3047
    selectedtargettype 	0
    isfightingme 	0
    charstate 	0
    xp 	3230
    playfieldtype 	0
    side 	2
    metatype 	1750
    savedxp 	757
    lastsaved 	1
    nextxp 	4050
    lastsavexp 	1450
    lastxp 	1450
    maxncu 	8
    sneakattack 	9
    fatness 	1
    race 	1
    accountflags 	1234567890
    life 	79
    monsterdata 	0
    VisualFlags 	31
    clan 	0
    team 	0
    aggdef 	100
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    specialization 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    nanoac 	5
    maxnanoenergy 	37
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    alignment 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    healinterval 	29
    nanoenergypool 	7
    nanointerval 	28
    martialarts 	8
    meleemultiple 	9
    onehandbluntweapons 	7
    onehandedgedweapon 	8
    piercing 	8
    twohandbluntweapons 	7
    twohandedgedweapons 	7
    meleeenergyweapon 	8
    throwingknife 	9
    grenade 	9
    throwngrapplingweapons 	9
    bow 	9
    rifle 	9
    submachinegun 	8
    shotgun 	9
    assaultrifle 	8
    drivewater 	9
    closecombatinitiative 	8
    physicalprowessinitiative 	8
    bowspecialattack 	9
    senseimprovement 	7
    firstaid 	9
    mechanicalengineering 	9
    electricalengineering 	8
    materialmetamorphose 	7
    biologicalmetamorphose 	7
    psychologicalmodification 	8
    materialcreation 	8
    materiallocation 	8
    lr_energyweapon 	8
    disarmtrap 	9
    perception 	8
    adventuring 	8
    swim 	8
    driveair 	9
    mapnavigation 	8
    tutoring 	8
    brawl 	7
    riposte 	9
    dimach 	8
    parry 	8
    fastattack 	9
    burst 	8
    nanoprowessinitiative 	9
    aimedshot 	9
    duck 	9
    dodge 	9
    evade 	9
    fieldquantumphysics 	7
    weaponsmithing 	7
    pharmaceuticals 	8
    nanoprogramming 	8
    psychology 	8
    chemistry 	8
    concealment 	9
    breakingentry 	8
    driveground 	9
    fullauto 	7
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    age 	0
    radiationac 	0
    attackspeed 	5
    fireac 	0
    poisonac 	0
    coldac 	0
    chemicalac 	0
    energyac 	0
    meleeac 	0
    projectileac 	0
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    beltslots 	0
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
------------------------------------

.getfull succeeded.

**Playfield info:**
Extended location information:
- 61.9, 61.7, 14.0 (61.9 61.7 y 14.0 950)
- Pf Proxy: Model=51100:950 GS=0 SG=0 R=950, resource: 950
- zone: 7, area: "Omni-Tek Virtual Training Ground"
Server id: 1, character id: 50000:823, time: 2024-01-19 22:54:45 (UTC)
Version: 00.4.5_EP1, map id: NOT FOUND, build: 52606.

**Comment by praxis1988** [comment]
Even if higher level, the tokenboard does not upgrade past the 1st one.

![image](https://github.com/project-rubika/issues/assets/25720793/69bd2322-098f-4a1f-863d-6ccc0bc29344)

**Comment by prkdrake** [comment]
I'm able to reproduce this, but it only seems to happen with the basic board, if you spawn any of the other boards they work as expected. Still testing.

**Comment by prkdrake** [comment]
This should be fixed now, needs to be re-tested

**Comment by RaggyLP** [comment]
![image](https://github.com/project-rubika/issues/assets/156821187/0ab4243d-085e-4591-acf8-2e50318f8215)
Board no longer resets back down to basic when it reaches its maximum. Confirmed as fixed as of 18:24 UTC - 25/01/24

**Comment by prkdrake** [comment]
Thanks for confirming
