### ISSUE TITLE
When NPCs are aggro'd away from their fixed locations, they do not return

### ISSUE THREAD

**Issue by portalerprk** [project-rubika/issues#546]
When NPCs are aggro'd away from their fixed locations, they do not return. 

For example, if for whatever reason a vendor type NPC is aggro'd and chases a target, once combat completes they do not return to their starting location.

Steps:
- Go to NLC
- Stand in marketplace
- `.spawn npc CULT` and target it him when he spawns
- `.sc s`
- He will engage/aggro
- He will cast Mongo and aggro the NPCs in the area
- They will chase. If the NPCs survive they will not reset to original locations.

**Comment by TheTinkeringIdiot** [comment]
I don't have access to the given commands, but can replicate this problem using mezz to end combat. Several attempts show that NPCs indeed to not return to their starting location after combat ends, even after 30 minutes or more without combat.

**Comment by TheTinkeringIdiot** [comment]
Confirmed this remains after leashing fix. It seems that combat ending does not trigger the leash.

**Comment by RaggyLP** [comment]
Tested using the Bartender in Fair Trade and now when combat ends, she returns to her expected location if leashed. Closing as fixed as of 31/08/2024.
