### ISSUE TITLE
Multiple nanos can be cast in the delay between recharge and casting

### ISSUE THREAD

**Issue by prkdrake** [project-rubika/issues#553]
**Describe the bug**
When you begin casting a nano, a timer starts counting up towards the nano's cast delay. When the nano is cast, you have to wait for a timer to count down for the nano's recharge delay. 

If you're spamming the casting of a spell, you can cast it multiple times in the gap between recharge finishing, and the timer for the casting to start. 

I accomplished this with fast nano init spam-casting Volcanic Eruption. 

**To Reproduce**
1. Log in to a nano technician 
2. Upload Volcanic Eruption (`.item 28841 28841 182`)
3. Put VE on your hotbar. 
4. Spam-press the hotbar key for VE. 
5. Notice that you'll cast it and hit multiple times before recharge/casting stops you from casting it more. 

**Expected behavior**
You should only be able to cast it once before casting/recharge prevents additional casts.

**Comment by RaggyLP** [comment]
Confirmed reproducable using the above steps. The thing I did notice doing this, was the times when the extra cast was doable, the nano recharge bar itself was not present.


https://github.com/project-rubika/issues/assets/156821187/737b3c7f-8f99-4fc7-b8c4-af7bd1a9b9b5

**Comment by prkdrake** [comment]
Prioritising this as priority 2 because it's abusable. If you set up an AHK script (or similar) you could probably fire it off way too many times.

**Comment by prkdrake** [comment]
I believe this has now been fixed.

**Comment by RaggyLP** [comment]
Confirmed. Mashing the hell out of nanos no longer turns you into a casting minigun. Closing as fixed as of 25/08/2024.
