### ISSUE TITLE
/command effect GfxEffect is visually local and not announced to other clients

### ISSUE THREAD

**Issue by 3F1-1009** [project-rubika/issues#556]
**Describe the bug**
/command effect GfxEffect should be broadcast to other clients nearby

**To Reproduce**
1. Log in 2 different characters
2. Make sure 2 characters are near eachother (at least visual range)
3. Use `/command effect GfxEffect Value 45000` on character 1
4. Effect is visible only for character 1, not character 2

**Expected behavior**
Effect should be visible to any character in visual range

**Comment by TheTinkeringIdiot** [comment]
Confirmed. 

Tested with two different characters in close proximity. The given command resembles the visual effect of a NT area nuke around the commanding player. The other player sees no effect at all.
