### ISSUE TITLE
Treatment Laboratory Low Id incorrect in Player Portal, making all spawned QLs have the same stats

### ISSUE THREAD

**Issue by Zolarix** [project-rubika/issues#562]
**Describe the bug**
~~Unable to spawn Treatment Laboratory items to workaround shops not having items.~~
Edit: @TheTinkeringIdiot helpfully indicated that healing items ARE available (with working High Id and Low Id) in the GM Menu, something I managed to miss.
[Treatment Laboratory PRK Portal](https://portal.project-rk.com/server/Ithaca/item/25812).

**To Reproduce**
1. Enter `/item <High Id> <Low Id> <QL>` using the High Id and Low Id provided by the portal (25812) and the desired QL (10).

Observe -> The spawned stack of Treatment Laboratory does have a QL 10 but requires the same amount of Treatment and heals the same as a QL 1.

**Expected behavior**
Treatment requirement and On Target healing should scale with the QL of the item. This can be achieved by making the Low Id in Player Portal 25811, but the fact it isn't indicates the Player Portal may have a lower level issue.

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/96363854/e9efc9e1-f993-48d7-ad20-36dd51654907)

![image](https://github.com/project-rubika/issues/assets/96363854/c99a946f-c702-46ca-9e52-edff5fb53f25)

![image](https://github.com/project-rubika/issues/assets/96363854/370423bf-a55a-4069-88c7-de65f4d6a888)

----

**Comment by TheTinkeringIdiot** [comment]
Confirmed. `/item 25812 25812 10` spawns 50 QL10 Treatment Laboratory that heal for 15 points as the QL1 item does. 

According to Auno, the high QL for this item is [25811](https://auno.org/ao/db.php?id=25811). `/item 25812 25811 10` correctly spawns 50 QL10 Treatment Laboratory that heal for 82 points, appropriate for QL10. 

The in-game GM menu commands reflect this ID range as well. This appears to be an issue with the item's representation in the portal DB lookup (or maybe in the RDB itself, lots of strange edge cases in there).

**Comment by Zolarix** [comment]
[Simple Nano Kit](https://portal.project-rk.com/server/Ithaca/item/85366) High Id matches the Low Id on Player Portal and I can't see a GM Menu entry for these.

**Comment by prkdrake** [comment]
Just for a bit of extra info: the same ID for both high and low will always return the exact same item regardless of QL.

**Comment by 3F1-1009** [comment]
With changes to portal, this should no longer be a problem. Someone please confirm.
