### ISSUE TITLE
Random teleporting to Greater Omni Forest whilst in the Omni Forest

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#563]
**Describe the bug**
Whilst in the Omni Barracks where some of the Omni Start-up quests take place, players will be randomly teleported to a close-to-boundary location within Greater Omni Forest

**To Reproduce**
1. Go to the Omni Barracks in Omni Forest
2. Move to Lieutenant Echholt's location
3. Wait a bit/move around a little in the area. | Log out, log back in. (Unsure on the specific trigger).

**Expected behavior**
Players shouldn't be randomly teleported to another location.

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/156821187/806316cd-f326-4926-8b3f-c363e79f58e0)
![image](https://github.com/project-rubika/issues/assets/156821187/be4ede5b-87d0-440b-afd8-4d4b1677a122)

**Playfield info:**

```
Extended location information:
- 485.1, 1820.4, 39.4 (485.1 1820.4 y 39.4 716)
- Pf Proxy: Model=51100:716 GS=0 SG=0 R=716, resource: 716
- zone: 1542, area: "Omni-Pol Barracks Region"
Server id: 1, character id: 50000:1028, time: 2024-01-27 13:45:30 (UTC)
Version: 00.4.7_EP1, map id: NOT FOUND, build: 52606.
```
```
Extended location information:
- 1034.2, 2996.1, 14.6 (1034.2 2996.1 y 14.6 717)
- Pf Proxy: Model=51100:717 GS=0 SG=0 R=717, resource: 717
- zone: 4835, area: "Sunken Swamps"
Server id: 1, character id: 50000:1028, time: 2024-01-27 15:38:03 (UTC)
Version: 00.4.7_EP1, map id: NOT FOUND, build: 52606.
```
----

**Comment by RaggyLP** [comment]
Further discussion surrounding this points to possible 'wall'/boundary errors present in the zone and might not be directly tied to the Omni Barracks area.

**Comment by 3F1-1009** [comment]
Previously confirmed, but random. May have been fixed with backend DB change.

**Comment by prkdrake** [comment]
Can someone quickly re-check this and if it's not happening anymore close for now and keep an eye out for it happening again - likely an RDB think as 3f1 said

**Comment by RaggyLP** [comment]
Stood at the barracks where it kept happening for 30 mins, no random TPs, going to close as fixed as of 23:21 UTC - 17/02/24
