### ISSUE TITLE
Steps of Madness is virtually empty

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#568]
**Describe the bug**
Most of the mobs in Steps of Madness are missing aside from a few in the first two or three rooms. 

**To Reproduce**
1. Enter SoM
2. It's nearly empty

**Expected behavior**
There should be mobs in a dungeon

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/96996793/50ee2b9b-f2e9-46a7-8ce2-a2acf51d5e82)

**Playfield info:**

```
Extended location information:
- 84.6, 128.3, 26.9 (84.6 128.3 y 26.9 1933)
- Pf Proxy: Model=51100:1933 GS=0 SG=0 R=1933, resource: 1933
- zone: 11, area: "Steps of Madness", room: "Dragonhead Room"
Server id: 100041, character id: 50000:1130, time: 2024-01-28 02:17:51 (UTC)
Version: 00.4.7_EP1, map id: NOT FOUND, build: 52606.

```
----

**Comment by TheTinkeringIdiot** [comment]
Also note that all bosses in the dungeon are missing.

**Comment by TheTinkeringIdiot** [comment]
Seems this was partially server lag. After some minutes several mobs did appear, including Neleb and the spider boss. The dungeon is still missing most of the normal complement and the other bosses.

**Comment by RaggyLP** [comment]
Confirmed, the number of mobs throughout the instance is sparse at best.

**Comment by TheTinkeringIdiot** [comment]
This is fixed, SoM has the expected population again.
