### ISSUE TITLE
Cyborgs are missing/not spawning.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#572]
**Describe the bug**
The mob type 'Cyborg' is not spawning in the expected locations. Identified missing from the following areas:

```
NE Perpetual Wastelands - 3743.2, 2499.7, 40.8 | 3972.6, 2797.6, 39.3
Mort Craters - 1354.1, 580.9, 39.4 | 855.0, 2276.0, 10.1
Milky Way - 4467.5, 1044.1, 22.9
Greater Tir County - 3230.5, 2343.6, 25.5
Avalon - 1278.8, 3981.0, 45.4
```

**To Reproduce**
1. Go to any of the above locations.
2. Notice a distinct lack of Borgs

**Expected behavior**
Cyborgs of varying level should be present at the above locations.

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/156821187/a52207c6-b8a5-499f-910e-f90e5b67f56b)

**Comment by 3F1-1009** [comment]
Confirmed missing in Perpetual Wastelands. Haven't checked other locations, but I assume problem is caused by same thing.
Same base cause as #481 , but I would currently not merge the issues.

**Comment by prkdrake** [comment]
I believe this has been fixed now, but I might be wrong

**Comment by RaggyLP** [comment]
Confirmed. Borgs are now populating the expected places. Closing as fixed as of 25/08/2024.
