### ISSUE TITLE
Moving an NCU Memory between the inventory and a backpack will decrement the maxncu on the client by the amount the Memory advertises

### ISSUE THREAD

**Issue by Zolarix** [project-rubika/issues#574]
**Describe the bug**
Every time an NCU chip is moved between inventories of the player, it reduces the visually displayed Max NCU by the amount that the memory says it increases NCU by when equipped.

`.getfull maxncu` shows that this does not affect the server player data. This consequently _**doesn't prevent the full maxncu being used**_, however it makes planning and tactics confusing and much more difficult without commands and inconvenient with commands.

When going below zero, the value will loop back around starting at the max unsigned 32-bit integer value, 4294967296.

**To Reproduce**
1. Create a new character (Opifex Default Male Fixer)
2. Travel to Borealis FT
3. Buy a Small Backpack
4. Spawn a QL 1 NCU Memory using command `.item 36778 36779 1`
(I verified this issue affects  4 different types of naturally spawned NCU Memories, including Yuttos)
5. Do not equip the Memory. Instead, move it from the Inventory to the Small Backpack
Observe -> NCU displayed in the NCU window goes from 8 down to 6 (the same amount as the NCU provided by the item). 
6. Move the Memory back into the inventory.
Observe -> NCU decrements by 2 on the client again.

**Expected behavior**
Moving NCU Memory between inventories should not affect the player's maxncu stat on the client.

**Screenshots**
![Screenshot 2024-01-27 225021](https://github.com/project-rubika/issues/assets/96363854/d46b40fa-4f97-441d-b1b7-bc9fbf9b3313)
![Screenshot 2024-01-28 144258](https://github.com/project-rubika/issues/assets/96363854/a23a13af-d8da-4e33-8fda-e82538a21ff2)
![Screenshot 2024-01-28 144337](https://github.com/project-rubika/issues/assets/96363854/e1dcf5e2-13c3-4e6e-8184-f3d8e2b98b75)
![Screenshot 2024-01-28 144404](https://github.com/project-rubika/issues/assets/96363854/18e34497-22f4-4fb7-9546-19dd32d6eb28)
![Screenshot 2024-01-28 144433](https://github.com/project-rubika/issues/assets/96363854/d23df3e7-cc56-4ac4-a4fe-37f49a59295e)
![Screenshot 2024-01-28 144512](https://github.com/project-rubika/issues/assets/96363854/fdd8e89f-9729-4630-9b6c-d8d777b83176)

**Character info:**

```
Underrun [1 Fixer]
    maxncu 	8

.getfull succeeded - Underrun's maxncu is 8 (8 + 0).
```

----

**Comment by RaggyLP** [comment]
Confirmed, simply moving the item around reduces NCU visually by the amount the chip is supposed to alter.

![image](https://github.com/project-rubika/issues/assets/156821187/d1869643-7e56-48af-9a65-e1eafcc4bff7)
![image](https://github.com/project-rubika/issues/assets/156821187/bf2e4b3a-13dc-432f-86fa-ea1b40b1230a)

**Comment by TheTinkeringIdiot** [comment]
I witnessed this with armor as well. AC values decrease each time a piece of armor is moved to or from a bag. Server values (`.get`) do not reflect the changes displayed on the client, so it appears to be a local phenomenon.

**Comment by RaggyLP** [comment]
Re-tested. Moving NCU from Inventory to a Bag Space still reduces visible NCU.

![image](https://github.com/project-rubika/issues/assets/156821187/9f7d1e3a-7b29-4787-bf63-1e981603a89b)

**Comment by portalerprk** [comment]
Should be fixed. Updates rolling out now.

**Comment by RaggyLP** [comment]
Moving the NCU around doesn't reduce client-side NCU values anymore! Confirmed fixed as of 00:27 UTC - 08/03/24

![image](https://github.com/project-rubika/issues/assets/156821187/7bb37012-eddd-49fb-9102-7512e3f183b9)
![image](https://github.com/project-rubika/issues/assets/156821187/4d6a4469-79b9-4b8c-8f72-c46d1046b9b0)
