### ISSUE TITLE
Stacked items can be split in bag

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#576]
**Describe the bug**
A stacked item like ammo can be split while inside of a bag. The split items cannot be removed from the bag, but the original stack can. The two stacks cannot be recombined in the bag, and when the bag closes, the split items are destroyed. 

**To Reproduce**
1. Place a stack of items in a bag
2. Split the stack (ctrl+shift+left drag)
3. Place the split items elsewhere in the bag
4. Attempt to remove the split items from the bag - they cannot be removed
5. Move the original stack outside of the bag
6. Close the bag
7. Reopen the bag - the split items are missing and have not been added to the original stack. 

**Expected behavior**
Stacks cannot be split inside of a bag.  

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/96996793/78d28fa4-9f5c-435f-bb9b-8dea12c838c8)

**Comment by 3F1-1009** [comment]
Confirmed using steps above. Additionally, the original stack that you got back from bag can no longer be stacked with other instances of same item.

**Comment by TheTinkeringIdiot** [comment]
Issue remains but has changed slightly with recent fixes. 

The bag-split stack of items can again be re-stacked with items outside of the bag, so the aspect reported by 3F1 appears to be resolved. 

Stacks of items can still be split inside of bags. Doing so and closing the bag will result in the split-off portion being lost. Splitting a stack and attempting to re-combine them while both are still in the bag can cause varying behavior. Attempting to add the split-off stack back to the original will cause the split-off stack to be lost when the bag is closed. Attempting to add the original stack to the split-off stack will cause both stacks to be lose when the bag is closed. 

Attempts to replicate this bug on the live servers are met with a "You can't split this item" chat message when attempting to place a split-off stack of items in the same bag as the original stack, and nothing happening when trying to place the split stack elsewhere - the stack simply doesn't split. 

![image](https://github.com/project-rubika/issues/assets/96996793/01b68bbc-7503-47d0-981c-f9e00e6f377d)

**Comment by portalerprk** [comment]
On Live
https://github.com/project-rubika/issues/assets/60405799/ed646ff7-b670-47ab-9f25-112418bec8f5


On PRK
https://github.com/project-rubika/issues/assets/60405799/71ef2f2c-a1c2-4952-9c09-c423898e6224

**Comment by TheTinkeringIdiot** [comment]
Are we on the same version of PRK? Your second gif does not match what I'm seeing in game at all. I can follow your exact steps in that gif and upon logging back in the split items are missing from the bag. 

On live it's as your gif shows, but only with consumables. Other stackable items like ammo cannot be split in a bag.

**Comment by TheTinkeringIdiot** [comment]
Confirmed fixed on latest. Non-consumable stacked items are allowed to split in a bag, which is not allowed on the live game, but that's probably more enhancement than bug. Consumable items split as they do on live.
