### ISSUE TITLE
Monsters with stock phrases open a blabot window when interacted with

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#579]
**Describe the bug**
It's possible to open a chat dialog with some enemy mobs. I discovered the effect on a Clawfinger Ruffian and Bio-X39 Outcast in Aegean and Wartorn Valley.

**To Reproduce**
1. Find Clawfinger Ruffian in Aegaen or Bio-X39 Outcast in Wartorn Valley
2. Right click
3. Get chat menu

**Expected behavior**
These mobs are not for talking, these mobs are for killing. 

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/96996793/cd733e6f-be00-481b-b9ff-32134e7b4e27)

![image](https://github.com/project-rubika/issues/assets/96996793/9238182f-46b9-4e48-9430-f2229521ccf3)

**Playfield info:**

```
Extended location information:
- 792.1, 584.0, 4.8 (792.1 584.0 y 4.8 586)
- Pf Proxy: Model=51100:586 GS=0 SG=0 R=586, resource: 586
- zone: 453, area: "Junk Yard"
Server id: 1, character id: 50000:1092, time: 2024-01-30 02:13:10 (UTC)
Version: 00.5.0_EP1, map id: NOT FOUND, build: 52606.

```
----

**Comment by 3F1-1009** [comment]
Confirmed that many NPCs have a dialog when they should actually just speak in vicinity.

**Comment by prkdrake** [comment]
This should now be fixed as of the latest release.

**Comment by RaggyLP** [comment]
Confirmed. Generic statements are now printed to /v instead of opening Blabot windows.
![image](https://github.com/user-attachments/assets/f52c89dc-1472-47a2-b191-217ca426495a)

Closing as fixed as of 25/08/2024.
