### ISSUE TITLE
Zoning between area borders removes the area border effect.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#580]
**Describe the bug**
When moving between different playfields which dislpay the 'splash' zone border effect, this effect disappears when on the other side.

**To Reproduce**
1. Go to any PF zone border
2. Notice particle effect
3. Move across the PF
4. Notice lack of effect.

**Expected behavior**
Particle Effect to denote the border location shouldn't vanish on zoning.

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/156821187/bd251324-f5b6-4f0e-b853-b1a7f9f6cc5b)
![image](https://github.com/project-rubika/issues/assets/156821187/532cc90f-f866-477d-9612-2dd6396272cd)

**Playfield info:**

```
Extended location information:
- 2403.4, 4512.7, 29.3 (2403.4 4512.7 y 29.3 670)
- Pf Proxy: Model=51100:670 GS=0 SG=0 R=670, resource: 670
- zone: 9020, area: "Northern Clondyke"
Server id: 1028, character id: 50000:1028, time: 2024-01-30 11:04:43 (UTC)
Version: 00.5.0_EP1, map id: NOT FOUND, build: 52606.
```
----

**Comment by TheTinkeringIdiot** [comment]
Confirmed. 

The particle effect vanishes for seemingly every zone border after crossing any one. Simply logging out and back in does not restore the particle effect, the client must be fully restarted.

**Comment by RaggyLP** [comment]
This appears to no longer be an issue, closing as fixed as of 31/08/2024.
