### ISSUE TITLE
Pressing the 'Action' hotkey (E) on an NPC with dialogue instead opens trade.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#583]
**Describe the bug**
When using the 'Action' kotkey, usually bound to 'E', on an NPC who usually has dialogue/chat options, will instead directly open up the trade/vendor window instead of the usual dialogue screen.

**To Reproduce**
1. Go to an NPC with dialogue options, such as the Good Time Party Mixer
2. Click them to target and press 'E'
3. Notice the trader window, instead of dialogue screen.

**Expected behavior**
When pressing the action hotkey on a NPC, if they have dialogue, it should prioritise that over the trade function.

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/156821187/39ffcedb-7d5a-43f9-821f-c876fae8a820)

**Comment by TheTinkeringIdiot** [comment]
Confirmed. 

Guards in Old Athen have a chat dialog when right clicked, but the action key opens a trade interface.

**Comment by RaggyLP** [comment]
Fixed as of 15/08/2024.
