### ISSUE TITLE
Outdoor mobs are all level 1

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#585]
**Describe the bug**
Outdoor mobs all over the world are all level 1. I have no been able to find "regular mobs" of any other level. Mobs in higher level zones seems to have a reasonable amount of health and combat difficulty for the area, but are still level 1. 

**To Reproduce**
1. Go to EFP
2. Find a mob
3. It's level 1

**Expected behavior**
Mobs should be an appropriate level for their difficulty and region. 

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/96996793/26b0e262-58af-41da-9c25-e6c58e2193a9)

![image](https://github.com/project-rubika/issues/assets/96996793/5abd6907-5966-43de-91a3-4fb70cc9ed3b)

**Comment by RaggyLP** [comment]
Like, 95% Confirmed. There is the odd random mob in the zone that is actually at a leveant level, however, the vast majority are sat at Level 1. This isn't limited to any particular zone either and seems to be an RK wide experience.

**Comment by TheTinkeringIdiot** [comment]
"Special" mobs, like the ones in and around the domes in Avalon, have their proper levels but "normal" ones are having a...efficacy problem.

**Comment by RaggyLP** [comment]
A sprint around Andromeda gave me a variety of 40-80 level mobs. Athen Shire seems to 5 - 20. So expected level ranges for the areas and all the level 1s are now correctly levelled. Closing as fixed as of - 18:10 UTC 02/02/24
