### ISSUE TITLE
Medusa lifts don't work

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#587]
**Describe the bug**
The lifts to get up into the main Medusa city in DAV don't work. 

**To Reproduce**
1. `/tp 3510 2241 595`
2. Enter the lift
3. Don't rise up into the city

**Expected behavior**
The lift is supposed to life you up into the Medusa city

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/96996793/8e60fb8e-e3ed-4ec2-8a8a-1bad1da1ad6c)

**Playfield info:**

```
Extended location information:
- 3510.6, 2241.1, 47.0 (3510.6 2241.1 y 47.0 595)
- Pf Proxy: Model=51100:595 GS=0 SG=0 R=595, resource: 595
- zone: 5127, area: "Medusa Territory"
Server id: 1, character id: 50000:1228, time: 2024-01-31 04:38:53 (UTC)
Version: 00.5.1_EP1, map id: NOT FOUND, build: 52606.

```
----

**Comment by RaggyLP** [comment]
Confirmed, local teleporting doesn't seem implemented for these types of portals.

![image](https://github.com/project-rubika/issues/assets/156821187/d0e00a9c-13d0-4bbd-954f-ecd313f7006f)

**Comment by RaggyLP** [comment]
This now works, however, is a LocalTP that is being treated as a full zone transition, the specific issue itself is solved. Closing as fixed as of 31/08/2024.
