### ISSUE TITLE
Mobs warp when rooted

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#591]
**Describe the bug**
When rooted, mobs warp to their attack target after a short time. The target halts immediately when the root lands, but after ten seconds or so immediately leaps to its fighting target. The root remains in effect and the mob cannot move other than this warping. 

This may be related to #347 pathing issues, as moving around a rooted mob causes it to warp to where you were a few seconds ago, much like how pets commanded to follow run toward your location at the time the command was given. 

**To Reproduce**
1. Target a hostile mob
2. Cast and land a root nano
3. Move out of the mob's combat range
4. Wait about ten seconds
5. The mob warps to you and its status (`/set debug 1`) changes to "Fighting"

**Expected behavior**
A rooted mob should not move at all.

**Comment by RaggyLP** [comment]
Wasn't able to repo this. Can you re-test @TheTinkeringIdiot? Might've been fixed in passing.

![image](https://github.com/project-rubika/issues/assets/156821187/f2663788-af4e-4714-8b6f-000d9659eeed)

**Comment by TheTinkeringIdiot** [comment]
Yep, looks like this was fixed by the recent changes. Closing as fixed.
