### ISSUE TITLE
The Fixer Grid item 'Data Receptacle' last indefinitely. 

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#601]
**Describe the bug**
The Fixer Grid item Data Receptacle (ID: 160978) does not have the expected temporary tag and as a result, remains in the inventory forever.

**To Reproduce**
1. Cast Hack Grid Data Stream ```.ncu run 160979```
2. Wait 20s
3. See how the item still exists.

**Expected behavior**
The item should expire after 20s.

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/156821187/0562dcd6-5de1-44f4-8514-788a18635b6b)

**Comment by TheTinkeringIdiot** [comment]
Cannot replicate. The fixer grid item listed vanishes 20 seconds after summoning for me. I believe this has been fixed, @RaggyLP please confirm.

**Comment by RaggyLP** [comment]
Yup, appears to be fixed now. Closing as fixed from 00:07 UTC - 05/02/24
