### ISSUE TITLE
ICC/Andomeda has missing cargo ships.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#602]
**Describe the bug**
The cargo ships which are present in most cities are currently missing and instead odd floating cubes.

**To Reproduce**
1. Go to ICC
2. Face South East at Pos: 3256.7, 975.6
3. Witness borg invasion.

**Expected behavior**
There should be models of the cargo ships instead of just cubes.

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/156821187/970d36ab-0310-4f9a-9b0b-a6f48c3b8b00)

**Playfield info:**

```
Extended location information:
- 3256.7, 975.6, 56.7 (3256.7 975.6 y 56.7 655)
- Pf Proxy: Model=51100:655 GS=0 SG=0 R=655, resource: 655
- zone: 3201, area: "Nepal"
Server id: 1, character id: 50000:1028, time: 2024-02-02 19:52:48 (UTC)
Version: 00.5.3_EP1, map id: NOT FOUND, build: 52606.
```
----

**Comment by 3F1-1009** [comment]
Confirmed. The boxes are placeholder/error boxes. Probably caused by client having twk files from version higher than 15.5.

**Comment by prkdrake** [comment]
Probably fixed since moving to 18.4

**Comment by RaggyLP** [comment]
Sadly, not fixed.

![image](https://github.com/user-attachments/assets/ff292f3a-c90b-4f76-8984-3b268bd2c63a)

This is due to the Client using the TWK files from 18.8, with the rebuilt ICC. We would need to bundle a pre-rebalance TWK file for the ICC ships with the client.

**Comment by prkdrake** [comment]
Checked vs 18.4 tweak files, there were no ships in 18.4, thus I've removed them for now. We can re-add them with some real ship meshes later if we want to

**Comment by RaggyLP** [comment]
Confirmed. Bogr threat neutralised. Closing as fixed as of 21/08/2024.
