### ISSUE TITLE
Joining team is currently non-functioning.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#604]
**Describe the bug**
When clicking 'Yes' on the Join Team prompt, you are not entered into a team with the sending character. The situation persists even after zoning/logging out.

**To Reproduce**
1. Send a team invite to a character.
2. Wait for it to be accepted.
3. Notice how you're not in a team.

**Expected behavior**
When the prompt is accepted, the players should be placed into a team together.

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/156821187/421ec0b0-2c56-48d6-baea-219b3f9a8837)
![image](https://github.com/project-rubika/issues/assets/156821187/a37d95c1-ae97-4421-97b1-81b766d1c77a)

**Comment by TheTinkeringIdiot** [comment]
Looks like this got fixed, please double check. 

![image](https://github.com/project-rubika/issues/assets/96996793/6cfa4e8f-bbe7-47cc-95d8-521099648aa8)

**Comment by RaggyLP** [comment]
Confirmed fixed as of 00:08 UTC - 05/02/24

![image](https://github.com/project-rubika/issues/assets/156821187/229fe268-c3a2-4926-a7c7-e9c17976c6f4)
