### ISSUE TITLE
Non attack on sight mobs attacking on sight

### ISSUE THREAD

**Issue by lvp12345** [project-rubika/issues#605]
**Describe the bug**
Mobs not labeled as and also not normally attack on sight are attacking on sight

**To Reproduce**
1. Go to lament lagoon
2. Find Abysal Roamer or Stingers
3. Both dont have may attack on sight tag (stinger normally dont abysal does)

**Expected behavior**
Stinger should not attack on sight, abysal roamer should (but is not tagged as such)

**Screenshots**
[image](https://github.com/project-rubika/issues/assets/1490311/4cdd6cd4-664b-46ab-830a-1b37cc5d58c7)

**Character info:**

```
Copy/paste the output of /getfull here
```

**Playfield info:**
Adonis under water
```
Copy/paste the output of Shift+F9 here
```
----

**Comment by TheTinkeringIdiot** [comment]
This is a repeat of the issue described in #547. Closing as duplicate.
