### ISSUE TITLE
Fixer Grid Data Receptacle becomes permanent on zone

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#608]
**Describe the bug**
The Fixer Grid item Data Receptacle (ID: 160978) is temporary and is removed from the player's inventory 20 seconds after being created. However, if the player zones before those 20 seconds have elapsed, the Data Receptacle becomes permanent and is never removed. 

**To Reproduce**
1. `.ncu run 160979` to summon a Data Receptacle
2. Zone within 20 seconds
3. Wait 1 minute, and Data Receptacle remains in inventory

**Expected behavior**
The Data Receptacle should be removed from the player's inventory after 20 seconds regardless of zoning. 

**Screenshots**
https://gifyu.com/image/SFpfB

**Comment by RaggyLP** [comment]
Confirmed. The item will expire as expected when created without zone, but zoning appears to break the temporary timer on it, so it then remains indefinitely. 

![image](https://github.com/project-rubika/issues/assets/156821187/04d39b39-7d86-45c1-8a74-11fb2e0f6d3e)

**Comment by prkdrake** [comment]
Should be mostly fixed now, but there is still a minor issue with it

**Comment by RaggyLP** [comment]
Confirmed. No longer stays permanent on zone, certainly doesn't stick about for very long either! Closing this one as fixed for now. 15/09/2024.
