### ISSUE TITLE
Self-only buffs are cast on the target instead of the caster.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#610]
**Describe the bug**
Buffs which are listed as self-only are currently casted at target. This also applies to hostile NPCs/in combat.

**To Reproduce**
1. Find a target
2. Cast a self-only buff.
3. Use the .ncu command to see the targets NCU.

**Expected behavior**
Self-only buffs should only be cast on that caster.

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/156821187/cee8233e-5bc6-4dbd-b050-f9d9e05a6762)
![image](https://github.com/project-rubika/issues/assets/156821187/714f2473-a420-4196-b18d-2f94b1e245c9)
![image](https://github.com/project-rubika/issues/assets/156821187/3127ac83-d974-462d-8aae-036f4621ebe4)

**Comment by portalerprk** [comment]
Should be addressed with project-rubika/engines#395

**Comment by RaggyLP** [comment]
Confirmed fixed as of 14:30 UTC - 18/02/24 on project-rubika/engines#395.
