### ISSUE TITLE
Perk dependencies don't cast on fighting targets

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#615]
**Describe the bug**
Perks that place "status" nanos on a fighting target are not doing so, preventing dependent perks from firing. 

For example the Shade Spirit Phylactery perk line are all co-dependent - they must be executed in sequence. The first action, Capture Vigor, fires but does not place "Affected by Capture Vigor" on the target (does not appear in target NCU), so further perks in that line cannot be used. 

Capture Vigor's benefit nano (also called Capture Vigor) does not appear in the user's NCU. 

The same is true for the Shade's Totemic Rights line. Dependency nanos do not appear on targets, and benefit nanos are not cast on the user. 

I tested the Martial Artist/Enforcer "Brawler" line perks Big Smash and Followup Smash. Big Smash fires and does not place "Affected by Big Smash" on the target. However Followup Smash (dependent on Big Smash) _can_ be used shortly after using Big Smash, despite the dependency not being present on the target. 

**To Reproduce**
1. Be Shade
2. Perk Spirit Phylactery 10
3. Use Capture Vigor on a fighting target
4. "Affected by Capture Vigor" does not appear on the target and "Capture Vigor" does not appear on you
5. Followup action "Unsealed Blight" cannot be used. 

**Expected behavior**
Perks should place the listed nanos as described in their info. 

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/96996793/d40dcedd-6a0d-404e-b9f3-88b1af694bb6)

![image](https://github.com/project-rubika/issues/assets/96996793/6955ed10-d942-49a8-94da-fdb9293106f9)

**Comment by RaggyLP** [comment]
Confirmed partially. Capture Vigor *does* apply the debuff, however, the follow up perk is not checking for it's dependancy.

![image](https://github.com/project-rubika/issues/assets/156821187/a74483bc-b668-4634-af64-fe30515cef62)

**Comment by RaggyLP** [comment]
Tested with Spirit Phylactery, Totemic Rites and Sublime Rapport. Also tested on Trader for Distill Life, Power Up and Tinkerer. Confirmed fixed as of 22:23 UTC - 27/02/24
