### ISSUE TITLE
Failed perk actions have non-descriptive errors

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#616]
**Describe the bug**
Perk actions that cannot fire due to missing dependencies do not provide uninterpolated format strings (`Your %s is required to be at least %d`) instead of helpful error messages. 

**To Reproduce**
1. Be MA or Enforcer
2. Perk Brawler 6
3. Attempt to use perk action Followup Smash on a target without using Big Smash first

**Expected behavior**
Error messages should list why the perk action is not firing

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/96996793/899bf6c3-69f0-4a5a-83c1-c9eb00c1e3f6)

**Comment by RaggyLP** [comment]
This has now been fixed, perk errors are now descriptive of their errors. Fixed as of 22:25 UTC - 27/02/24

![image](https://github.com/project-rubika/issues/assets/156821187/1a841cf6-af6b-4a97-8d56-4b2fdc76fc1c)
