### ISSUE TITLE
Maintenance Supervisor Johnson is missing from Foremans.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#623]
**Describe the bug**
The NPC Maintenance Supervisor Johnson who is supposed to be present near the Hangar in Foremans is missing. He is a vital part of the quest line and the first step in gaining the Clearance badge.

**To Reproduce**
1. Go to Foremans
2. Look in the pit near the Hangar

**Expected behavior**
The NPC is meant to be present at the screenshotted location and patrolling around this small area. On death, he is meant to drop an object on the floor which is interactable with a [Security Clearance ID Card Blank](https://auno.org/ao/db.php?id=258764) to create [Security Clearance ID Card - Alpha Clearance](https://auno.org/ao/db.php?id=258739)

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/156821187/80f72226-4317-468f-ac07-136f4a4e9e14)

**Playfield info:**

```
Extended location information:
- 201.1, 107.7, 19.8 (201.1 107.7 y 19.8 1941)
- Pf Proxy: Model=51100:1941 GS=0 SG=0 R=1941, resource: 1941
- zone: 11, area: "Area"
Server id: 108394, character id: 50000:1028, time: 2024-02-21 00:21:04 (UTC)
Version: 00.6.0_EP1, map id: NOT FOUND, build: 52606.
```
----

**Comment by TheTinkeringIdiot** [comment]
Confirmed as described.

**Comment by prkdrake** [comment]
Should be fixed with the latest update.

**Comment by kajoriEU** [comment]
Confirmed. 👍  Maintenance Supervisor Johnsson has finally arrived at Foremans.

![{EA8764E5-F4CD-40A2-B18D-2FD7997A65E5}](https://github.com/user-attachments/assets/d3c8cb39-8bef-4d9b-9dbb-5609c2f01213)

### Closing this issue as fixed as of 15/09/2024.
