### ISSUE TITLE
The Longest Road periodically crashes the client.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#625]
**Describe the bug**
The AO Client will randomly crash whilst in The Longest Road. There doesn't seem to be a pattern to the time between crashes.

**To Reproduce**
1. Go to the Longest Road
2. Wait 

A BugReport/CrashLog has been generated and saved for this.
[Bug0000.txt](https://github.com/project-rubika/issues/files/14352552/Bug0000.txt)
(Crash log is cleansed of personal data)

**Comment by TheTinkeringIdiot** [comment]
Confirmed. Crashing occurs at random, and happened to me even while logging in after a crash.

**Comment by prkdrake** [comment]
pretty thoroughly tested it with multiple characters, including @RaggyLP and @Unknownprk, I believe that the problem has now been solved.

**Comment by RaggyLP** [comment]
![image](https://github.com/user-attachments/assets/61abd601-d2ee-4c0d-a9e9-4a9437524f01)
