### ISSUE TITLE
Keeper Fury item does not work after zoning

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#628]
**Describe the bug**
When running the Fury nano, Keepers (Clan or Omni, not neutral) get a special attack item that can be used on a fighting target. The item does indeed become available while the nano is running, but it cannot be used in combat, giving the "Action is not available" error when attempted. This problem occurs after zoning with the Fury nano running. 

The special attack item remains in the Shift-2 actions menu after zoning, but cannot be used again until the Fury nano is recast. It is as if the Fury item becomes invalid upon zoning. 

This may possibly be related to #608, which describes another temporary item that malfunctions after zoning. 

**To Reproduce**
1. Be Keeper (Clan or Omni)
2. Run Fury
3. Zone
4. Attempt to use action "Righteous Fury" (Clan) or "Unhallowed Fury" (Omni)
5. It doesn't work

**Expected behavior**
The Fury item should continue to work after zoning. 

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/96996793/5666fe6f-5be2-4167-8bf1-f4b36cab3f61)

**Comment by RaggyLP** [comment]
Confirmed, the action is lost on zone.

![image](https://github.com/project-rubika/issues/assets/156821187/a1c271c1-e89c-4996-a2b1-2b7e915da3d8)
![image](https://github.com/project-rubika/issues/assets/156821187/9a7d1791-caab-4c1e-86de-db70ea9600f5)

**Comment by RaggyLP** [comment]
Fury now persists across zoning. Confirmed fixed as of 00:49 UTC - 24/02/24. 

![image](https://github.com/project-rubika/issues/assets/156821187/b253bf86-aee7-414d-9b98-10b1d61713da)
![image](https://github.com/project-rubika/issues/assets/156821187/828bd4ab-45a3-4d11-ac75-5cd80c114495)
