### ISSUE TITLE
Mobs (including pets) get stuck on...something

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#630]
**Describe the bug**
Ground-based pets and mobs get stuck on invisible barriers where no ground features indicate such a barrier is present. Players can move through these spaces without event, but mobs are invariably blocked. 

Mobs remain free to move on their side of the barrier (agro'd mobs will pursue you when you are on "their side" of it), but when confronted by the barrier act as if they've come upon a wall. I have encountered this in multiple places. 

The the stuck mob is hostile and attacking the player, it may "vibrate" (rapidly jump up and down as if it is respawning rapidly) and spam chat with attack messages. 

**To Reproduce**
1. `.tp 2570 2832 620`
2. Agro something nearby
3. Run up the ramp 20-30 meters
4. Agro'd mob can't follow you

**Expected behavior**
Mobs should only get stuck on actual barriers.

**Screenshots**
![mobs_not_following](https://github.com/project-rubika/issues/assets/96996793/7ec1e6fd-9967-4ec0-bc57-2b9f85c91e1b)

![pets_get_stuck](https://github.com/project-rubika/issues/assets/96996793/6708df7a-8470-4e84-babd-6504650691a5)

**Playfield info:**

```
(21:09) Extended location information:
(21:09) - 2560.5, 2828.4, 12.9 (2560.5 2828.4 y 12.9 620)
(21:09) - Pf Proxy: Model=51100:620 GS=0 SG=0 R=620, resource: 620
(21:09) - zone: 5524, area: "E.C.W.F.R.K"
(21:09) Server id: 105836, character id: 50000:1228, time: 2024-02-23 02:09:13 (UTC)
(21:09) Version: 00.6.0_EP1, map id: NOT FOUND, build: 52606.
```

There is another one nearby (that always seems to cause the "vibration") at
```
(21:09) Extended location information:
(21:09) - 2496.2, 2835.2, 23.0 (2496.2 2835.2 y 23.0 620)
(21:09) - Pf Proxy: Model=51100:620 GS=0 SG=0 R=620, resource: 620
(21:09) - zone: 5522, area: "E.C.W.F.R.K"
(21:09) Server id: 106621, character id: 50000:1228, time: 2024-02-23 02:09:55 (UTC)
(21:09) Version: 00.6.0_EP1, map id: NOT FOUND, build: 52606.

```
----

**Comment by prkdrake** [comment]
Possibly fixed with recent navmesh changes

**Comment by RaggyLP** [comment]
Confirmed. Pets and mobs are now able to clear the previously impassable area. closing as fixed as of 25/08/2024.
