### ISSUE TITLE
Pets entering render distance do not continue movement.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#633]
**Describe the bug**
When a players pet enters render distance from outside of it, the pet will remain locked at the edge of render distance, until given a new follow order, at which point it will teleport to the players position.

**To Reproduce**
1. Tell pet to wait
2. Move outside of render
3. Order pet to follow (it moves to render and stays there)
4. Order pet to follow again (it warps to you)

**Expected behavior**
Pet's entering render distance should retain their previous movement instructions and this should be broadcast to the client as movement as well.

**Screenshots**
1.
![image](https://github.com/project-rubika/issues/assets/156821187/52e278d9-9228-4f47-bbab-0a42bb580ee9)
2.
![image](https://github.com/project-rubika/issues/assets/156821187/f6521a47-d1a0-4cb1-8f47-6a823df2d25c)
3.
![image](https://github.com/project-rubika/issues/assets/156821187/a383e786-1a74-4347-a938-a6cf52ea50e1)
4.
![image](https://github.com/project-rubika/issues/assets/156821187/38cbcdeb-2a7f-45d7-9e75-123e90e67740)

**Comment by TheTinkeringIdiot** [comment]
Confirmed. The pet didn't warp all the way back to me after re-entering render distance, but it did teleport most of the way.

**Comment by prkdrake** [comment]
I believe this is now fixed

**Comment by RaggyLP** [comment]
Confirmed. Pets re-entering render distance now move correctly. Closing as fixed as of 25/08/2024.
