### ISSUE TITLE
Neutral Backyards have a very low mob count.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#634]
**Describe the bug**
Neutral Backyards have 4-5 mobs at most + their dyna in comparison to Clan or Omni backyards which have 20-30+ and a dyna.

**To Reproduce**
1. Go to a Neutral BY
2. Notice the general lack of spawns.

**Expected behavior**
Neutral Backyards should be far more populous to match that of sided BYs

**Comment by TheTinkeringIdiot** [comment]
Confirmed. There are some mobs in the Junkyard, but far too few.

**Comment by portalerprk** [comment]
Fix rolling out now.

**Comment by RaggyLP** [comment]
Seems we have a few spawns stuck in the walls! Other than, a lot more here now! Great stuff! 

![image](https://github.com/project-rubika/issues/assets/156821187/bcd968f9-f3be-4fe0-a109-be80353ed71c)
![image](https://github.com/project-rubika/issues/assets/156821187/ba39d7e4-8c56-4166-a5fe-b6ca4703bad9)

**Comment by TheTinkeringIdiot** [comment]
Can confirm. Several mobs are stuck in walls, apparently on spawn. 

![image](https://github.com/project-rubika/issues/assets/96996793/4a8de8dd-8507-4fb0-ad87-fc27fd3404b3)

**Comment by portalerprk** [comment]
Not sure I can do much about that right now. Going to close. We can revisit spawns out of range another time.
