### ISSUE TITLE
Low level Dyna mob HP is significantly higher than it should be.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#638]
**Describe the bug**
The Hp on low level Dyna mobs such as those in backyards is significantly higher than it should be for the level and area that they spawn in. 

**To Reproduce**
1. Go to one of the backyards
2. Locate a Dyna
3. Do ```.getfull health``` and ```.getfull life```
4. Notice both being very high for the location they are present.

**Expected behavior**
Low level dyna mobs should be reasonably killable by a player of a similar level, as most players of this level will be hitting for 2-30 (not crit) max.

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/156821187/66ae8e80-254d-4da2-8e31-d8dee3e579a7)
![image](https://github.com/project-rubika/issues/assets/156821187/081c36bb-273b-485e-ac48-d514470b74b2)
![image](https://github.com/project-rubika/issues/assets/156821187/c426da6b-5ffe-4c3a-af80-fcd4257572d4)

![image](https://github.com/project-rubika/issues/assets/156821187/8ab71334-d042-4afc-9c74-e02da760f17a)
![image](https://github.com/project-rubika/issues/assets/156821187/022c9abd-a123-4a42-b301-1f9512439f9e)
![image](https://github.com/project-rubika/issues/assets/156821187/2ce5ee68-965e-4f7d-bebd-5014df9f4b4c)

**Comment by RaggyLP** [comment]
HP seems to be fine directly following a server restart. Could be linked to #477 

![image](https://github.com/project-rubika/issues/assets/156821187/ca80c61c-7ef5-4969-a743-9c5d28195822)

**Comment by TheTinkeringIdiot** [comment]
This may be related to #477. I confirmed two nights ago that issue remains current.

**Comment by TheTinkeringIdiot** [comment]
Confirmed that backyard dynas that haven't been touched start with a reasonable amount of health.

**Comment by portalerprk** [comment]
Fixed

**Comment by RaggyLP** [comment]
HP is a lot more reasonable now. Confirmed fixed as of 00:14 UTC - 06/03/24

![image](https://github.com/project-rubika/issues/assets/156821187/f4542e12-6200-4bd3-87d0-21989bbd6198)
![image](https://github.com/project-rubika/issues/assets/156821187/d751682c-9787-45f3-a211-045ba4e0a86b)
