### ISSUE TITLE
The Brawl Attack action seems to be missing its stun component.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#639]
**Describe the bug**
When using Brawl, there is supposed to be a chance to stun your target, this seems to be missing in it current incarnation.

**To Reproduce**
1. Create a character with no weapons equipped (or a weapon with brawl enabled)
2. Use Brawl multiple times on a mob.
3. Notice lack of stun.

**Expected behavior**
Brawl has different tiers of stun chance based on your brawl stat. At baseline, Brawl should have a 10% chance to stun:
https://auno.org/ao/db.php?id=70292

**Comment by TheTinkeringIdiot** [comment]
Confirmed. Brawl has between 10% and 20% chance to stun based on QL. I used Brawl 30 times with no visual indication that the target was stunned, nor did anything show up in the target's NCU, and the target remained in the "Fighting" status the entire time.

**Comment by portalerprk** [comment]
Should be resolved. I hope.

**Comment by RaggyLP** [comment]
Confirmed fixed as of 18:32 UTC - 27/02/24

![image](https://github.com/project-rubika/issues/assets/156821187/1dfb467e-c9a1-4804-aae6-cd8ff119a177)
