### ISSUE TITLE
'Empty' bodies persist in the world.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#640]
**Describe the bug**
Bodies which have been fully looted remain in the world. They can be opened repeatedly, this doesn't do anything specifically.

**To Reproduce**
1. Kill a mob
2. Loot everything in its container
3. Notice how the body persists

**Expected behavior**
When a loot container has been cmopletely emptied of Creds/Loot, the container/body should be removed from the game world.

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/156821187/781356b2-d4dd-4407-a54b-29f6f16efaaf)

**Comment by TheTinkeringIdiot** [comment]
Confirmed. Empty bodies do not despawn as they do on the live game.

**Comment by RaggyLP** [comment]
Empty bodies now despawn after 1s~ of empty container. Confirmed fixed as of 22:09 UTC - 26/02/24

![image](https://github.com/project-rubika/issues/assets/156821187/087d57b3-8e71-48ea-9930-6339e8c553ab)
![image](https://github.com/project-rubika/issues/assets/156821187/c02405af-cc60-4572-ab29-1db920f105d7)
