### ISSUE TITLE
Subway XP gains are too low.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#641]
**Describe the bug**
The XP gained for killing mobs in the subway to a lot lower than that of killing the same level mobs on Live. Both characters are the same level (8) with zero increases to XP gains except side XP benefits on live of 4.06%.

**To Reproduce**
1. Go to Subway
2. Kill mobs
3. Compare XP gain to mobs for the same level/type on live.

**Expected behavior**
XP gains on PRK should be closer to those of live.

**Screenshots**
Live
![image](https://github.com/project-rubika/issues/assets/156821187/b2015db0-7859-481f-85d0-03c905ab72a4)
![image](https://github.com/project-rubika/issues/assets/156821187/93fa155a-ad2a-4a90-b7de-28967193b58a)
![image](https://github.com/project-rubika/issues/assets/156821187/dbcf61e6-06b2-4d16-888d-f35a2668e868)
![image](https://github.com/project-rubika/issues/assets/156821187/64a0ed90-da0e-4159-ba4c-ec87efd42a72)

PRK
![image](https://github.com/project-rubika/issues/assets/156821187/6a07666a-7c95-43c0-80dd-e43fb671ed92)
![image](https://github.com/project-rubika/issues/assets/156821187/41cc8d04-2a6f-4d56-b07c-72de5cf38803)
![image](https://github.com/project-rubika/issues/assets/156821187/5eac121b-00d0-4b6c-9d7d-12f900281a7a)
![image](https://github.com/project-rubika/issues/assets/156821187/1b9e33da-c15b-487a-87ad-1f5a2e4337d4)

**Comment by TheTinkeringIdiot** [comment]
Confirmed as described.

**Comment by RaggyLP** [comment]
XP amounts are now changed as of the move to 18.4 Closing this as fixed as of 31/08/2024.
