### ISSUE TITLE
Enemies do not appear on the minimap

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#642]
**Describe the bug**
Mobs (friendly and otherwise) do not appear on the minimap. This appears to be happening everywhere. 

This issue could be related to #637. 

**To Reproduce**
1. Go somewhere with enemy or friendly mobs
2. They don't show up on the minimap

**Expected behavior**
Enemies should appear as red dots on the minimap. Sided mobs should show up as either orange or blue. Neutrals should appear white. 

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/96996793/05113f78-dcc5-412c-b264-2666575b9863)

**Comment by RaggyLP** [comment]
Confirmed, I even toyed around with ```set mapoptions``` to see if I could get them to show, to no avail.

**Comment by portalerprk** [comment]
This is probably related to tab targeting and NPC Family

**Comment by RaggyLP** [comment]
Confirmed fixed as of 22:06 UTC - 26/02/24

![image](https://github.com/project-rubika/issues/assets/156821187/9a3167d3-79eb-49eb-9155-305774e0c082)
