### ISSUE TITLE
Reflect is not implemented.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#647]
**Describe the bug**
ReflectAC currently does not lower the amount of damage taken from a hit. Even with ReflectAC of 100, the full hit is still taken by the player.

**To Reproduce**
1. Create an NT/Soldier
2. Start combat
3. Note the damage from the hit
4. Cast AMS/NS2
5. Note the damage is still the same.

**Expected behavior**
ReflectAC should reduce a damaging hit by a % based on 0 - 100 with 100 being total damage immunity.

**Screenshots**
Nullity Sphere II with 100 ReflectAC still getting hit by damage.
![image](https://github.com/project-rubika/issues/assets/156821187/100a1780-6c77-4ae9-afee-5de052a7a27c)
![image](https://github.com/project-rubika/issues/assets/156821187/c7f2ceb1-7141-4b38-b2a3-7fbd641cb00e)
![image](https://github.com/project-rubika/issues/assets/156821187/ccfa4abd-6d80-4e0e-aa35-7411353eb526)
![image](https://github.com/project-rubika/issues/assets/156821187/331cea53-3c45-434d-b30b-5be1b32d96aa)

**Comment by TheTinkeringIdiot** [comment]
Confirmed. Tested with Total Mirror Shield X and the reflect component appears to have no effect. 

![image](https://github.com/project-rubika/issues/assets/96996793/8912c9bc-b8a2-42a9-bed5-06d363159671)

**Comment by portalerprk** [comment]
Ah. So is it that its successfully reflecting the dmg back on the mob.. but not removing from the incoming damage.

**Comment by portalerprk** [comment]
@RaggyLP  give it a whirl :-)

**Comment by portalerprk** [comment]
In the immortal word's of Daft Punk. "One more time"

**Comment by portalerprk** [comment]
Stacking issues should now be issues.

**Comment by Zolarix** [comment]
Casting Total Mirror Shield Mk I took the damage inflicted down to 3 from 12 (75% reduction as described). Additionally, it reflected 7 points back to the combatant, which matches the amount the nano quotes as being the maximum returned value.

Verified fixed.
