### ISSUE TITLE
-AAD Perks from Shade make mobs unhittable

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#648]
**Describe the bug**
Hitting a mob with the Capture Vigor perk applies a -AAO/-AAD debuff and makes the mob unhittable.

**To Reproduce**
1. Make Shade and get Spirit Phylactery 1
2. Use on a mob
3. Note how the mob cannot be hit during the perk duration.

**Expected behavior**
-AAD should not render the mob unhittable

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/156821187/55ea7892-c2ee-4745-9f30-98caedc29837)

**Comment by prkdrake** [comment]
I think this hopefully should have been fixed with recent changes, please can this be re-checked? Thanks!

**Comment by RaggyLP** [comment]
![image](https://github.com/user-attachments/assets/17645e71-a960-4a97-89dd-7ee036e6de9b)
Appears to be solved! Closing as fixed as of 15/09/2024.
