### ISSUE TITLE
Cyborgs use incorrect weapons

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#649]
**Describe the bug**
Cyborgs are currently stuck using melee attacks set to their attached weapons range. They are not actively shooting their guns.

**To Reproduce**
1. Go to an area with Cyborgs. (.tp 1278 3982 505)
2. Aggro a Cyborg

**Expected behavior**
Cyborgs should switch between using their guns and using melee attack when in range.

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/156821187/dcb3d148-019e-4324-94cf-bc00f73a1f6d)

**Comment by TheTinkeringIdiot** [comment]
Confirmed. 

![image](https://github.com/project-rubika/issues/assets/96996793/591f1ff3-ef07-4a47-becf-22e9695343c3)

**Comment by RaggyLP** [comment]
Confirmed that Cyborgs are now using the Shot/Punch/Punch combo and that the damage profiles are being reported correctly.

![image](https://github.com/project-rubika/issues/assets/156821187/37294b48-7a92-427e-be96-6a49310e7551)
![image](https://github.com/project-rubika/issues/assets/156821187/36043ae9-3c15-4af7-9961-cc0001c11d74)
