### ISSUE TITLE
Zoning after using a Treatment Kit causes the character to arrive sitting

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#655]
**Describe the bug**
After using a treatment kit, while the kit is still on cooldown, zoning causes the character to arrive at the destination seated. 

**To Reproduce**
1. Use a treatment kit
2. Stand and zone before the kit's cooldown is complete
3. You are sitting

**Expected behavior**
Zoning with a treatment kit on cooldown should not cause the character to sit.

**Screenshots**
![zoneing_to_sit](https://github.com/project-rubika/issues/assets/96996793/83b20591-53ff-4ac2-8c51-d070f8b34a69)

**Comment by RaggyLP** [comment]
Confirmed as above. Using a Treatment kit (in this case, the start-up kit given on char creation.), and then zoning while it's on CD causes the char to be in the sitting state on load.

**Comment by portalerprk** [comment]
Fixed.

**Comment by RaggyLP** [comment]
Characters are no longer in the sit state on zoning after using a Treatment Kit. Confirmed fixed as of 00:35 UTC - 06/03/24
