### ISSUE TITLE
Tirbo Ratcatcher dialog is incomplete

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#662]
**Describe the bug**
Tirbo Ratcatcher's dialog is incomplete. His initial prompt is missing, and instructions for filling the trade window appear as dialog text (and are missing a newline character) rather than instructional text. 

**To Reproduce**
1. `.tp 330 355 545`
2. Speak to Tirbo Ratcatcher

**Expected behavior**
NPC dialog normally begins with some form of message.
Instructional messages are colored different or otherwise indicate that they are not part of the conversation dialog. 

**Screenshots**
Tirbo is missing an initial message
![image](https://github.com/project-rubika/issues/assets/96996793/5606caf0-8ac6-4387-b4c7-5920a1e9e1a3)

Instructional messages are part of the dialog
![image](https://github.com/project-rubika/issues/assets/96996793/5d858eb5-db7d-4981-88bf-aa194c6ae964)

**Comment by Starbouy138** [comment]
I can confirm there is missing initial dialog, and I also see what is meant as the instructional dialog is duplicated in the chat window.

![image](https://github.com/user-attachments/assets/9b80c805-38b5-46b9-bea8-0afb02aa987f)

![image](https://github.com/user-attachments/assets/b34f9a1d-88f2-4ac1-a21f-e9fc033332e8)

**Comment by prkdrake** [comment]
This should be fixed with the next update, please re-test and let us know. Thanks!

**Comment by RaggyLP** [comment]
Confirmed. Closing ticket as fixed as of 21/08/2024.
