### ISSUE TITLE
Adventurer morphs do not persist through zone

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#663]
**Describe the bug**
Adventurer shapeshift nanos break on zoning. The nano remains running in the Adventurer's NCU, but the shapeshift effect on the character is dropped and they revert to their normal humanoid form. 

**To Reproduce**
1. Be an Adventurer
2. Cast a morph
3. Zone
4. Be human again

**Expected behavior**
Morphs should persist through zoning, with the exception of Parrot when zoning into a non-flyable indoor zone, which should be cancelled from the Adventurer's NCU.

**Screenshots**
![advy_morph_drop](https://github.com/project-rubika/issues/assets/96996793/0c7035b9-32b3-46dc-85d9-49e7df042229)

**Comment by RaggyLP** [comment]
Confirmed as above. The active morph mesh is removed on zone, despite remaining active in the NCU. This also stops the player using Morph-related nanos.

![image](https://github.com/project-rubika/issues/assets/156821187/bcd2449d-4cd1-4c9a-96c3-778e6b30cf7b)
![image](https://github.com/project-rubika/issues/assets/156821187/ddce629b-bcce-44d1-baa7-9693f7d09e8b)

**Comment by TheTinkeringIdiot** [comment]
I noticed an addendum to this when testing another bug: The lack of shapeshift persistence is self-only. Other players in the vicinity still show the Adventurer as shapeshifted.

**Comment by portalerprk** [comment]
Should be fixed.

**Comment by RaggyLP** [comment]
![image](https://github.com/user-attachments/assets/cc1626af-5333-47bb-ba5a-b7959aa39325)
![image](https://github.com/user-attachments/assets/1d427c8f-8d62-49be-9e9f-d3b77646165d)

Confirmed fixed as of 25/07/24
