### ISSUE TITLE
Zoning while under the effects of Calia's Form: Parrot causes permanent flight until zone

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#665]
**Describe the bug**
Calia's Form: Parrot does not immediately allow the Adventurer to fly as described in #664. However, if the Adventurer zones with this nano running, the morph effect drops (#663), flight is enabled, and flight persists even after the nano is cancelled. Zoning again without the nano cancels the flight effect.

Further zones with the nano running retain the flight ability, even in indoor zones where flight should not be possible (#499). 

**To Reproduce**
1. Be an Adventurer
2. Cast Calia's Form: Parrot
3. Zone
4. Morph drops and flight is enabled
5. Cancel Calia's Form: Parrot
6. Flight remains

**Expected behavior**
Flight should be disabled when Cali's Form: Parrot ends. 

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/96996793/e7d0e733-6b6d-4614-a8af-84e0bef5e7d5)

**Comment by RaggyLP** [comment]
Confirmed. Zoning with Calia's Form: Parrot sets the character into a permanent flight state, even in zones where it shouldn't be possible.

![image](https://github.com/project-rubika/issues/assets/156821187/b01bedca-a399-48ea-84d4-104de0f5a44e)

**Comment by RaggyLP** [comment]
Confirmed fixed. Removing the morph from the NCU now returns the player to expected non-flight enabled state. Fixed as of 25/07/24
