### ISSUE TITLE
Back items with a robe mesh don't override textures of other armor

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#668]
**Describe the bug**
With the Tier 3 Trader Backpack equipped, it should give you a full-body robe in the same way as other robes in the game, however, currently, the textures of the armour equipped 'under' it, are taking priority, leading to odd amalgamations like shown below.

**To Reproduce**
1. Create a Trader capable of equipping the Tier BP
2. Set your side to Clan
3. ```.item 218870 218870 1```
4. Equip the BP whilst wearing pants which have a seperate texture.

**Expected behavior**
The BP should override the player mesh in full and take priority over other textures on gear 'under' it.

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/156821187/6549458e-1a68-45f2-945b-d118a651e5e6)

How it _should_ look:
![image](https://github.com/project-rubika/issues/assets/156821187/d039d6d1-3f12-4c71-8b0d-120218503ce0)

**Comment by TheTinkeringIdiot** [comment]
Confirmed for other cloak-type back items as well.

Wearing ARK Staffing Suit (`.item 231353 231353 1`) and equipping QL200 Chilled Plasteel Pants (`.item 85499 85499 200`) caused the following. 

![image](https://github.com/project-rubika/issues/assets/96996793/83248a76-9dfd-4bc4-be93-92deb015a544)

Similarly with the listed Trader Tier armor item:

![image](https://github.com/project-rubika/issues/assets/96996793/6522681e-0bf2-467c-8188-d6b5db54fb06)

**Comment by prkdrake** [comment]
Should be fixed with the latest update

**Comment by RaggyLP** [comment]
![image](https://github.com/user-attachments/assets/9b87bb40-3dad-4b99-8ad8-5f579557ddd2)

Goodbye Fleshrobe, you were a beautiful bug. Closing as fixed as of 07/09/2024.
