### ISSUE TITLE
RK Solo Mission

### ISSUE THREAD

**Issue by Lopnk** [project-rubika/issues#673]
**Describe the bug**
1. No mission key is generated when pulling a mission. mission appears to be enterable without issue but its disorienting
2. When zoning into mission character is facing the exit. Running forward ends up having you exit the mission
3. Mini map is already revealed when entering mission.
4. no lootable objects found in mission, chests, androids etc
5. first mission room was in the middle of the map.

**To Reproduce**
No real steps other than pull RK mission and observe.

**Expected behavior**
1. a mission key is expected to spawn in inventory
2. character should face away from entry door to assist with not being disoriented
3. mini map should not be revealed and should reshroud when exiting mission and reentering
4. various lootable objects should be found in mission
5. mission entry is usually at one end of a mission and the map fans away from entry point

**Screenshots**

**Character info:**
level 2 keeper
```
Copy/paste the output of /getfull here
Crashed game when attempting this.

**Playfield info:**
mission took place in old athens
```
Copy/paste the output of Shift+F9 here
Extended location information:
- 105.1, 195.0, 5.0 (105.1 195.0 y 5.0 80804)
- Pf Proxy: Model=51103:315489549 GS=0 SG=0 R=80804, resource: 324
- zone: 0, area: "", room: "clanstronghold_entrance"
Server id: 1394, character id: 50000:1394, time: 2024-04-03 02:36:16 (UTC)
Version: 00.6.1_EP1, map id: NOT FOUND, build: 52606.

**Comment by TheTinkeringIdiot** [comment]
I've broken this issue into 5, one for each item listed. Closing in favor of those for tracking purposes.
