### ISSUE TITLE
Brawl stuns character instead of intended target

### ISSUE THREAD

**Issue by Lopnk** [project-rubika/issues#674]
**Describe the bug**
When Brawl lands the stun, it stuns the character and not the intended target

**To Reproduce**
Use Brawl until stun proc happens

**Expected behavior**
Brawl stun should be on target

**Screenshots**

**Character info:**
Level 2 Keeper
```
Copy/paste the output of /getfull here
Game crashed when attempting this

**Playfield info:**
Chat Server: 217.79.255.79
Chat Port:   7001
Pos: 106.0, 196.0, 5.0, Area: . Time: 2024-04-03 02:38:44 (UTC)
Suppression field at 75 Wildlife may attack you.

Copy/paste the output of Shift+F9 here
game crashed when attempting this

**Comment by TheTinkeringIdiot** [comment]
Confirmed. 

The brawl stun effect triggers on the player, not on the combat target. The debug log also fills up with "Stunned" messages while the player is stunned by Brawl. 

![image](https://github.com/project-rubika/issues/assets/96996793/faffebae-be1c-47c4-8954-5cd2b16b1ac6)

![image](https://github.com/project-rubika/issues/assets/96996793/3e192d5f-9188-4960-84f3-9eb219a87518)

**Comment by portalerprk** [comment]
@TheTinkeringIdiot  / @Lopnk - Fixed. Please test when available.

Also note that all the specials (brawl/fa/dimach/full-auto/burst/fs/sneak/etc) will now trigger weapon procs. This was missing.

**Comment by Lopnk** [comment]
![stunwork](https://github.com/project-rubika/issues/assets/58457325/9867d046-5c2a-43ba-8811-9c537b5674b6)
Tested .
4 of 4 times it stunned the target properly
