### ISSUE TITLE
GM Menu Boosters (Target-Other)

### ISSUE THREAD

**Issue by superbloom86** [project-rubika/issues#681]
**Describe the bug**
Discovered on accident, don't believe this is the intent. 

When targeting other players and using the GM Menu, you can "boost" other characters to any level (I believe this works with the other "boosting" functions as well). Accidentally turned a level 5 player into a level 15.

**To Reproduce**
1. Go the GM Menu
2. Go to Boosters
3.  Target player (other than self) assign a boost, such as "level 15"

**Expected behavior**
Just an assumption but I assume this is only supposed to work on "target-self" and not others. 

**Playfield info:**
Performed in Borealis

**Comment by TheTinkeringIdiot** [comment]
This is intentional and cannot be fixed. GM commands are powerful and can be dangerous, please use with care!

GM commands have to work on targets too so that various mob and NPC stats can be monitored and changed for testing.
