### ISSUE TITLE
Mobs in Subway not dropping everything

### ISSUE THREAD

**Issue by TheDragula** [project-rubika/issues#684]
**Describe the bug**
Mobs in Subway not dropping what they are supposed to drop. Only dropped Living Cyber Armor Gloves so far and not one Nucleus Basilis Ring after multiple clearings of the lower Subway part.

**To Reproduce**
1. Go to Subway
2. Kill Premature Pattern, Redundant Scan, Molested Molecules, Incomplete Rebuild, Melded Patterns, Neural Breakdown, Vergil Aeneid and Eumenides
3. Loot those
4. Not getting the correct loot (only checked Armor and Ring drops)

**Expected behavior**
Dropping of the complete Living Cyber Armor Set and Nucleus Basalis Rings

**Screenshots**
![grafik](https://github.com/project-rubika/issues/assets/88660802/e9a8723b-ddcd-495e-98d6-c161a95f8eff)

**Playfield info:**

```
Extended location information:
- 275.6, 98.2, 73.0 (275.6 98.2 y 73.0 127)
- Pf Proxy: Model=51100:127 GS=0 SG=0 R=127, resource: 127
- zone: 43, area: "Sewer Nucleus", room: "Boss Connector"
Server id: 1340, character id: 50000:1340, time: 2024-04-03 04:36:38 (UTC)
Version: 00.6.1_EP1, map id: NOT FOUND, build: 52606.

```
----

**Comment by GlitchyGirl** [comment]
I know that the stim fiends will ONLY drop the nano boosting stim, and occasionally one other thing (usually an implant) but that's about it.

**Comment by prkdrake** [comment]
Should be fixed now

**Comment by 7yk0** [comment]
Confirmed that Eumenides drops ring of Nucleus Basalis now. As for living cyber armor pieces, I have only gotten pants and helmet after a few clearings of subway. Possibly bad RNG on my part. Unable to kill Vergil Aeneid as he hasn't spawned in a while.

**Comment by RaggyLP** [comment]
Working my way through the Subway, mobs are definitely a lot more generous with their drops, and the relevant 'boss' mobs are dropping the things they should be. RNG is, as always, a factor, but it would appear that a lot of the major points have been address. Closing as fixed as of 25/08/2024.
