### ISSUE TITLE
No Carbonrich Rocks in Subway

### ISSUE THREAD

**Issue by TheDragula** [project-rubika/issues#685]
**Describe the bug**
There seems to be no Carbonrich Rocks spawn in Subway

**To Reproduce**
1. Go to Subway
2. Stroll down du Eumenides
3. Search for Carbonrich Rocks
4. Not finding any

**Expected behavior**
Finding Carbonrich Rocks

**Playfield info:**

```
Extended location information:
- 195.1, 97.7, 73.0 (195.1 97.7 y 73.0 127)
- Pf Proxy: Model=51100:127 GS=0 SG=0 R=127, resource: 127
- zone: 42, area: "Fractured Sewers", room: "Slum Cathedral"
Server id: 119434, character id: 50000:1340, time: 2024-04-03 04:47:50 (UTC)
Version: 00.6.1_EP1, map id: NOT FOUND, build: 52606.

```
----

**Comment by TheTinkeringIdiot** [comment]
Confirmed.

Carbonrich rocks are not spawning near the Eumenides spawn point.

**Comment by 3F1-1009** [comment]
![Screenshot_347](https://github.com/user-attachments/assets/38e4d043-ebcd-4c59-96a8-8c4f3e48ee9b)

Appears to be fixed.
