### ISSUE TITLE
Engineer Pistol

### ISSUE THREAD

**Issue by l00del** [project-rubika/issues#687]
The Engineer Pistol (ID 164490) is not leveling up by using right Klick. Also if i spawn different QL, its always like the QL1 in terms of Stats and DMG.

**Comment by TheTinkeringIdiot** [comment]
Confirmed. 

Summoned Solar Powered Engineer Pistol `/item 164512 164513 180` and attempted to level it up by right clicking. 

The item correctly identifies when I haven't got the necessary skills to accomplish leveling the item and issues an appropriate error message. However right clicking the item with the necessary requirements met does nothing.

**Comment by TheTinkeringIdiot** [comment]
I also confirmed that other leveling items (MA Tier armor) are working correctly.

**Comment by prkdrake** [comment]
I believe this is exclusively a problem caused by the items command, if you zone and right click the gun it will work normally. Try creating the pistol through the tradeskill process and update this ticket if there is a problem with it.

**Comment by TheTinkeringIdiot** [comment]
Confirmed fixed. 

I had to zone twice after summoning the item, but afterward it did become clickable and upgraded as expected.
