### ISSUE TITLE
The Pioneer Backpack can't be Equipped

### ISSUE THREAD

**Issue by l00del** [project-rubika/issues#688]
The Pioneer Backpack (ID 152039) can't be equipped.
First the Pioneer seems to be in the "Back" slot, as it should be, but don't Modifier the Stats. Afther Zoning the Pioneer appers again in the inventory not in the "Back" slot.

Looks like its not possible to Properly equipp it.

**Comment by TheTinkeringIdiot** [comment]
Confirmed. 

Summoned the item (`/item 152039 152039 1`) and equipped it. Stats are not increased in the manner the item describes. The item cannot be removed after being equipped. 

After zoning, the item is unequipped in the player's inventory.

**Comment by RaggyLP** [comment]
Merging into #844.
