### ISSUE TITLE
Attacking mobs returns multiple "Attacked by.." Messages

### ISSUE THREAD

**Issue by KevinX08** [project-rubika/issues#694]
**Describe the bug**

Attacking mobs returns multiple "Attacked by.." Messages

**To Reproduce**

1. Find any monster to attack
2. Initiate combat
3. Check chat log
4. Will see multiple messages returned, similar as if social aggro was in play

**Expected behavior**

One message should be returned as long as it is not social aggro.

**Screenshots**

**Character info:**

```
Copy/paste the output of /getfull here
```

Kevinx [2 MartialArtist]
------------------------------------
    strength 	17
    stamina 	20
    agility 	29
    sense 	16
    psychic 	9
    intelligence 	12
    flags 	528961
    monsterscale 	100
    currentnano 	58
    headmesh 	223890
    waitstate 	1
    cash 	899987358
    gmlevel 	127
    expansion 	3
    breed 	2
    visualbreed 	2
    profession 	2
    visualprofession 	2
    level 	2
    sex 	2
    visualsex 	2
    health 	121
    titlelevel 	1
    accountflags 	0
    equippedweapontype 	1
    EquippedRHWeapon 	1
    selectedtarget 	1397
    selectedtargettype 	0
    currentncu 	0
    side 	2
    exitstatel 	-1073740874
    externaldoorinstance 	0
    externalplayfieldinstance 	0
    playfieldtype 	0
    bodydevelopment 	22
    martialarts 	25
    firstaid 	95
    treatment 	95
    nanoenergypool 	11
    brawl 	24
    computerliteracy 	12
    metatype 	1750
    senseimprovement 	12
    psychologicalmodification 	12
    materiallocation 	12
    isfightingme 	0
    xp 	2230
    charstate 	0
    physicalprowessinitiative 	13
    dimach 	13
    riposte 	15
    adventuring 	15
    swim 	15
    onehandbluntweapons 	14
    onehandedgedweapon 	15
    piercing 	15
    twohandbluntweapons 	14
    twohandedgedweapons 	14
    meleeenergyweapon 	14
    parry 	14
    sneakattack 	15
    meleemultiple 	16
    fastattack 	15
    throwingknife 	16
    throwngrapplingweapons 	16
    closecombatinitiative 	13
    evade 	15
    duck 	15
    concealment 	14
    nextxp 	4050
    lastsavexp 	1450
    lastxp 	1450
    maxncu 	8
    currentmovementmode 	3
    fatness 	1
    race 	1
    life 	121
    monsterdata 	0
    VisualFlags 	31
    runspeed 	11
    clan 	0
    healinterval 	29
    maxnanoenergy 	49
    nanointerval 	28
    team 	0
    projectileac 	210
    energyac 	210
    meleeac 	210
    coldac 	213
    fireac 	214
    chemicalac 	213
    radiationac 	213
    poisonac 	214
    xpmodifier 	507
    aggdef 	100
    distanceweaponinitiative 	8
    nanoprowessinitiative 	10
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    specialization 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    savedxp 	0
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    nanoac 	7
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    alignment 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    grenade 	10
    bow 	10
    pistol 	10
    rifle 	10
    submachinegun 	10
    shotgun 	11
    assaultrifle 	10
    drivewater 	9
    bowspecialattack 	10
    mechanicalengineering 	10
    electricalengineering 	9
    materialmetamorphose 	7
    biologicalmetamorphose 	7
    materialcreation 	8
    lr_energyweapon 	8
    lr_multipleweapon 	10
    disarmtrap 	9
    perception 	8
    driveair 	9
    mapnavigation 	8
    tutoring 	8
    burst 	10
    flingshot 	12
    aimedshot 	9
    dodge 	10
    fieldquantumphysics 	7
    weaponsmithing 	8
    pharmaceuticals 	8
    nanoprogramming 	8
    psychology 	8
    chemistry 	9
    breakingentry 	9
    driveground 	9
    fullauto 	9
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    age 	0
    attackspeed 	5
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    beltslots 	0
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
------------------------------------

.getfull succeeded - Listed all stats for Kevinx.

**Playfield info:**

```
Copy/paste the output of Shift+F9 here
```
----

**Comment by TheTinkeringIdiot** [comment]
Is this happening for every mob? Every mob in an area? Have you noticed it happening with a specific type of mob or situation? 

We need some more information to be able to confirm this. Even just a screenshot of it happening would be helpful.

**Comment by Mumblyphuck** [comment]
confirming above issue showing up for me. all mobs so far (BY and outside newland main gate)
![bug1](https://github.com/project-rubika/issues/assets/166165666/a445012d-827b-4591-9158-eb4cb6a9b85b)

SHIFT + F9 (Newland BY 01)
Extended location information:
- 148.0, 51.7, 3.8 (148.0 51.7 y 3.8 954)
- Pf Proxy: Model=51100:954 GS=0 SG=0 R=954, resource: 954
- zone: 11, area: "Junkyard"
Server id: 108543, character id: 50000:1470, time: 2024-04-05 18:34:12 (UTC)
Version: 00.6.1_EP1, map id: NOT FOUND, build: 52606.
Extended location information:
- 148.0, 51.7, 3.8 (148.0 51.7 y 3.8 954)
- Pf Proxy: Model=51100:954 GS=0 SG=0 R=954, resource: 954
- zone: 11, area: "Junkyard"
Server id: 1, character id: 50000:1470, time: 2024-04-05 18:34:15 (UTC)
Version: 00.6.1_EP1, map id: NOT FOUND, build: 52606.

GETFULL follows
Harmacist [4 Doctor]
------------------------------------
    strength 	27
    stamina 	22
    agility 	18
    sense 	15
    psychic 	15
    intelligence 	15
    flags 	528961
    monsterscale 	100
    currentnano 	72
    headmesh 	40100
    waitstate 	1
    cash 	535
    gmlevel 	127
    expansion 	3
    fatness 	0
    breed 	4
    visualbreed 	4
    profession 	10
    visualprofession 	10
    level 	4
    sex 	1
    visualsex 	1
    health 	128
    titlelevel 	1
    accountflags 	0
    equippedweapontype 	1
    EquippedRHWeapon 	1
    bodydevelopment 	26
    nanoenergypool 	28
    evade 	25
    martialarts 	25
    physicalprowessinitiative 	24
    nanoprowessinitiative 	29
    materialmetamorphose 	28
    biologicalmetamorphose 	28
    firstaid 	28
    treatment 	28
    pharmaceuticals 	23
    computerliteracy 	23
    selectedtarget 	1470
    selectedtargettype 	0
    charstate 	0
    isfightingme 	0
    xp 	8412
    exitstatel 	-1073740870
    externaldoorinstance 	-418378760
    externalplayfieldinstance 	3064
    nextxp 	11150
    lastsavexp 	3100
    runspeed 	26
    nanoac 	28
    brawl 	23
    lastxp 	4050
    maxncu 	8
    playfieldtype 	0
    currentmovementmode 	3
    side 	0
    race 	1
    life 	153
    monsterdata 	0
    VisualFlags 	31
    clan 	0
    team 	0
    chemicalac 	7
    coldac 	7
    energyac 	9
    fireac 	7
    meleeac 	11
    poisonac 	8
    projectileac 	11
    radiationac 	9
    aggdef 	100
    closecombatinitiative 	8
    distanceweaponinitiative 	8
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    specialization 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    savedxp 	0
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    maxnanoenergy 	72
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    alignment 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    meleemultiple 	10
    onehandbluntweapons 	11
    onehandedgedweapon 	10
    piercing 	10
    twohandbluntweapons 	11
    twohandedgedweapons 	11
    meleeenergyweapon 	9
    throwingknife 	9
    grenade 	9
    throwngrapplingweapons 	10
    bow 	9
    pistol 	9
    rifle 	9
    submachinegun 	10
    shotgun 	10
    assaultrifle 	9
    drivewater 	8
    bowspecialattack 	9
    senseimprovement 	9
    mechanicalengineering 	9
    electricalengineering 	9
    psychologicalmodification 	8
    materialcreation 	9
    materiallocation 	8
    lr_energyweapon 	8
    lr_multipleweapon 	9
    disarmtrap 	8
    perception 	8
    adventuring 	10
    swim 	10
    driveair 	8
    mapnavigation 	8
    tutoring 	8
    riposte 	9
    dimach 	8
    parry 	10
    sneakattack 	9
    fastattack 	9
    burst 	10
    flingshot 	9
    aimedshot 	8
    duck 	9
    dodge 	9
    fieldquantumphysics 	8
    weaponsmithing 	10
    nanoprogramming 	8
    psychology 	8
    chemistry 	9
    concealment 	8
    breakingentry 	9
    driveground 	8
    fullauto 	11
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    age 	0
    attackspeed 	5
    metatype 	0
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    beltslots 	0
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
    healinterval 	29
    nanointerval 	28
    amsmodifier 	0
    damageoverridetype 	0
    meleedamagemodifier 	0
    currentncu 	0
    dmsmodifier 	0
    reflectreturnedenergyac 	0
    reflectenergyac 	0
    shieldenergyac 	0
    xpmodifier 	0
    xppool 	0
    ip 	6778
    reflectreturnedmeleeac 	0
    reflectmeleeac 	0
    shieldmeleeac 	0
------------------------------------

.getfull succeeded - Listed all stats for Harmacist.

**Comment by TheTinkeringIdiot** [comment]
Confirmed.

When a mob attacks a player, exactly three "Attacked by" messages appear in the player's chat window. Combat otherwise proceeds normally, but there may be a redundant message send happening. 

![image](https://github.com/project-rubika/issues/assets/96996793/faf7b82f-3395-4b64-80fd-21da9e3f9da9)

**Comment by StormlashTV** [comment]
It also duplicates "Nano program executed successfully."

**Comment by RaggyLP** [comment]
This is now fixed as of the merge pushed by Portaler today. Closing as fixed as of 01/09/2024.
