### ISSUE TITLE
Backyard Mob casted QL 36 DOT (Greater Suspicious Death)

### ISSUE THREAD

**Issue by KevinX08** [project-rubika/issues#695]
**Describe the bug**

Daft Clan Diversionist in Rome Blue Backyard casted Greater Suspicious Death

**To Reproduce**

1. Go to one of the Rome Blue Backyards
2. Find Daft Clan Diversionist
3. Initiate combat until they cast Greater Suspicious Death

**Expected behavior**

I know they have a low level DOT and that one should be casted, I forgot the name

**Screenshots**

**Character info:**

```
Copy/paste the output of /getfull here
```

Kevinx [2 MartialArtist]
------------------------------------
    strength 	17
    stamina 	20
    agility 	29
    sense 	16
    psychic 	9
    intelligence 	12
    flags 	528961
    monsterscale 	100
    currentnano 	58
    headmesh 	223890
    waitstate 	1
    cash 	899987358
    gmlevel 	127
    expansion 	3
    breed 	2
    visualbreed 	2
    profession 	2
    visualprofession 	2
    level 	2
    sex 	2
    visualsex 	2
    health 	121
    titlelevel 	1
    accountflags 	0
    equippedweapontype 	1
    EquippedRHWeapon 	1
    selectedtarget 	1397
    selectedtargettype 	0
    currentncu 	0
    side 	2
    exitstatel 	-1073740874
    externaldoorinstance 	0
    externalplayfieldinstance 	0
    playfieldtype 	0
    bodydevelopment 	22
    martialarts 	25
    firstaid 	95
    treatment 	95
    nanoenergypool 	11
    brawl 	24
    computerliteracy 	12
    metatype 	1750
    senseimprovement 	12
    psychologicalmodification 	12
    materiallocation 	12
    isfightingme 	0
    xp 	2230
    charstate 	0
    physicalprowessinitiative 	13
    dimach 	13
    riposte 	15
    adventuring 	15
    swim 	15
    onehandbluntweapons 	14
    onehandedgedweapon 	15
    piercing 	15
    twohandbluntweapons 	14
    twohandedgedweapons 	14
    meleeenergyweapon 	14
    parry 	14
    sneakattack 	15
    meleemultiple 	16
    fastattack 	15
    throwingknife 	16
    throwngrapplingweapons 	16
    closecombatinitiative 	13
    evade 	15
    duck 	15
    concealment 	14
    nextxp 	4050
    lastsavexp 	1450
    lastxp 	1450
    maxncu 	8
    currentmovementmode 	3
    fatness 	1
    race 	1
    life 	121
    monsterdata 	0
    VisualFlags 	31
    runspeed 	11
    clan 	0
    healinterval 	29
    maxnanoenergy 	49
    nanointerval 	28
    team 	0
    projectileac 	210
    energyac 	210
    meleeac 	210
    coldac 	213
    fireac 	214
    chemicalac 	213
    radiationac 	213
    poisonac 	214
    xpmodifier 	507
    aggdef 	100
    distanceweaponinitiative 	8
    nanoprowessinitiative 	10
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    specialization 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    savedxp 	0
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    nanoac 	7
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    alignment 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    grenade 	10
    bow 	10
    pistol 	10
    rifle 	10
    submachinegun 	10
    shotgun 	11
    assaultrifle 	10
    drivewater 	9
    bowspecialattack 	10
    mechanicalengineering 	10
    electricalengineering 	9
    materialmetamorphose 	7
    biologicalmetamorphose 	7
    materialcreation 	8
    lr_energyweapon 	8
    lr_multipleweapon 	10
    disarmtrap 	9
    perception 	8
    driveair 	9
    mapnavigation 	8
    tutoring 	8
    burst 	10
    flingshot 	12
    aimedshot 	9
    dodge 	10
    fieldquantumphysics 	7
    weaponsmithing 	8
    pharmaceuticals 	8
    nanoprogramming 	8
    psychology 	8
    chemistry 	9
    breakingentry 	9
    driveground 	9
    fullauto 	9
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    age 	0
    attackspeed 	5
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    beltslots 	0
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
------------------------------------

.getfull succeeded - Listed all stats for Kevinx.

**Playfield info:**

```
Copy/paste the output of Shift+F9 here
```
Extended location information:
- 119.0, 73.9, 15.7 (119.0 73.9 y 15.7 950)
- Pf Proxy: Model=51100:950 GS=0 SG=0 R=950, resource: 950
- zone: 8, area: "Omni-Tek Virtual Training Ground"
Server id: 1, character id: 50000:1397, time: 2024-04-04 04:11:16 (UTC)
Version: 00.6.1_EP1, map id: NOT FOUND, build: 52606.

----

**Comment by RaggyLP** [comment]
Merging into #686.
