### ISSUE TITLE
Tri Plumbo Low HP

### ISSUE THREAD

**Issue by cbwheels** [project-rubika/issues#697]
**Describe the bug**
Went to Kill Tri Plumbo, his HP bar was super small, he had 100% hp. But when I attacked him it only took 2 hits to take out his entire HP bar.

**To Reproduce**
1. Go to Foremans (Biomare) > go down to sewers passed the floaters and bloaters > find Tri Plumbo
2. Click on Tri Plumbo > you can see he has low hp bar
3. When you attack Tri Plumbo on 100 shade it is 2 shot kill, You hit Tri Plumbo for 1104 points of cold damage. Critical hit!
You hit Tri Plumbo for 748 points of cold damage.

**Expected behavior**
Tri Plumbo is not a super hard Elite Mob or Mini Boss but he is decently tough generally and is quite tanky. He should have more HP than 1800 hp. 

**Screenshots**

**Character info:**
"Xaeti"
Profession: Shade
Level: 100

Copy/paste the output of /getfull here
Xaeti [100 Shade]
------------------------------------
    piercing 	642
    nanoenergypool 	335
    fastattack 	620
    evade 	879
    currentncu 	434
    senseimprovement 	470
    psychologicalmodification 	520
    biologicalmetamorphose 	462
    materiallocation 	496
    materialmetamorphose 	149
    materialcreation 	192
    onehandbluntweapons 	84
    twohandbluntweapons 	80
    onehandedgedweapon 	102
    twohandedgedweapons 	72
    meleeenergyweapon 	193
    brawl 	72
    dimach 	190
    meleemultiple 	242
    martialarts 	233
    visualsex 	3
    health 	5312
    titlelevel 	4
    accountflags 	0
    equippedweapontype 	514
    EquippedRHWeapon 	514
    selectedtarget 	1444
    nextxp 	31962150
    xp 	30371918
    lastsaved 	30371850
    lastxp 	30371850
    selectedtargettype 	0
    currentmovementmode 	3
    specialization 	15
    ip 	265880
    side 	0
    alignment 	20
    sneakattack 	593
    bodydevelopment 	579
    closecombatinitiative 	677
    strength 	53
    stamina 	350
    agility 	395
    sense 	322
    psychic 	30
    intelligence 	333
    flags 	528961
    monsterscale 	53
    currentnano 	517
    headmesh 	223875
    waitstate 	1
    cash 	900000000
    gmlevel 	127
    expansion 	3
    fatness 	2
    breed 	2
    visualbreed 	2
    profession 	15
    visualprofession 	15
    level 	100
    sex 	3
    playfieldtype 	1
    isfightingme 	4
    flingshot 	128
    parry 	257
    duck 	469
    dodge 	469
    riposte 	257
    adventuring 	88
    swim 	114
    throwingknife 	88
    throwngrapplingweapons 	74
    physicalprowessinitiative 	326
    concealment 	753
    distanceweaponinitiative 	302
    nanoprowessinitiative 	400
    nanoac 	122
    maxnanoenergy 	1550
    treatment 	106
    aimedshot 	433
    firstaid 	120
    exitstatel 	-1069676651
    externaldoorinstance 	-1073151205
    externalplayfieldinstance 	795
    maxncu 	634
    race 	1
    life 	5312
    monsterdata 	0
    VisualFlags 	31
    runspeed 	1071
    clan 	0
    procnano3 	210345
    procchance3 	25
    dmsmodifier 	107
    amsmodifier 	9
    skilllockmodifier 	0
    criticaldecrease 	3
    reflectprojectileac 	30
    reflectmeleeac 	30
    reflectenergyac 	30
    reflectchemicalac 	30
    reflectradiationac 	30
    reflectcoldac 	30
    reflectfireac 	30
    reflectpoisonac 	30
    reflectreturnedprojectileac 	49
    reflectreturnedmeleeac 	49
    reflectreturnedenergyac 	49
    reflectreturnedchemicalac 	49
    reflectreturnedradiationac 	49
    reflectreturnedcoldac 	49
    reflectreturnedfireac 	49
    reflectreturnedpoisonac 	49
    team 	0
    meleedamagemodifier 	37
    energydamagemodifier 	37
    projectiledamagemodifier 	18
    firedamagemodifier 	28
    colddamagemodifier 	60
    chemicaldamagemodifier 	37
    poisondamagemodifier 	37
    radiationdamagemodifier 	28
    projectileac 	2454
    energyac 	2113
    meleeac 	3460
    coldac 	2242
    fireac 	2661
    chemicalac 	2559
    radiationac 	2216
    poisonac 	2371
    xpmodifier 	7
    criticalincrease 	10
    beltslots 	6
    perception 	142
    rangeincreaserweapon 	46
    computerliteracy 	88
    healdelta 	70
    aggdef 	100
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    savedxp 	0
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    lastsavexp 	0
    grenade 	93
    bow 	79
    pistol 	96
    rifle 	96
    submachinegun 	72
    shotgun 	69
    assaultrifle 	87
    drivewater 	89
    bowspecialattack 	87
    mechanicalengineering 	96
    electricalengineering 	93
    lr_energyweapon 	56
    lr_multipleweapon 	97
    disarmtrap 	89
    driveair 	89
    mapnavigation 	79
    tutoring 	80
    burst 	75
    fieldquantumphysics 	50
    weaponsmithing 	53
    pharmaceuticals 	91
    nanoprogramming 	88
    psychology 	86
    chemistry 	90
    breakingentry 	70
    driveground 	89
    fullauto 	47
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    age 	0
    attackspeed 	5
    metatype 	0
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
    healinterval 	18
    nanointerval 	28
    charstate 	0
    damageoverridetype 	0
    xppool 	0
    nanodamagemultiplier 	0
    npcostmodifier 	0
    shieldmeleeac 	0
------------------------------------

**Playfield info:**
Pos: 162.2, 115.5, 23.8, Area: Area. Time: 2024-04-04 23:25:47 (UTC)
Suppression field at 75 Wildlife may attack you.

Copy/paste the output of Shift+F9 here
Suppression field at 75 Wildlife may attack you.
Extended location information:
- 162.2, 115.5, 23.8 (162.2 115.5 y 23.8 1941)
- Pf Proxy: Model=51100:1941 GS=0 SG=0 R=1941, resource: 1941
- zone: 24, area: "Area"
Server id: 1444, character id: 50000:1444, time: 2024-04-04 23:24:30 (UTC)
Version: 00.6.1_EP1, map id: NOT FOUND, build: 52606.

----

**Comment by RaggyLP** [comment]
Confirmed, Tri-plumbo's HP is significantly lower than it should be.

![image](https://github.com/project-rubika/issues/assets/156821187/2c698e30-e7eb-4d97-b680-094a9d1378f5)

**Comment by 7RO11** [comment]
it seems that most mobs in biomare have low hp
![3](https://github.com/project-rubika/issues/assets/73971287/6de8d76e-7d29-483f-a002-d2c00b536f3f)
![2](https://github.com/project-rubika/issues/assets/73971287/23967d22-4d60-4630-a628-9ed5755bbb17)
![1](https://github.com/project-rubika/issues/assets/73971287/62207a09-3bb1-4d9c-8d7f-577519d5b0dc)
the only exception i found was the lab director
![4](https://github.com/project-rubika/issues/assets/73971287/b39692a0-2325-4c0a-8424-b2bdeaf38299)

**Comment by prkdrake** [comment]
@Unknownprk fixed the issue with Foremans mobs

**Comment by Smegster11** [comment]
Health scaling has been altered for most low level enemies now.
Example in neutral backyard a level 1 "34-I Helper" in Neutral backyard have 227 health

34-I Helper [1 None]
------------------------------------
    accountflags 	0
    aggdef 	0
    aggressiveness 	0
    agility 	25
    aimedshot 	48
    assaultrifle 	48
    attitude 	0
    biologicalmetamorphose 	38
    bodydevelopment 	0
    bow 	48
    bowspecialattack 	48
    brawl 	48
    breakingentry 	48
    breed 	7
    breedhostility 	0
    burst 	48
    cash 	12
    chemicalac 	10
    chemistry 	46
    clan 	4
    closecombatinitiative 	43
    coldac 	10
    computerliteracy 	46
    concealment 	48
    conformity 	20
    currentmovementmode 	3
    currentnano 	146
    dimach 	48
    disarmtrap 	48
    distanceweaponinitiative 	43
    dodge 	46
    driveair 	46
    driveground 	46
    duck 	51
    electricalengineering 	46
    energy 	91
    energyac 	7
    EquippedRHWeapon 	0
    equippedweapontype 	0
    evade 	51
    expansion 	3
    extroverty 	0
    fastattack 	48
    fatness 	1
    fieldquantumphysics 	46
    fireac 	7
    firstaid 	46
    flags 	0
    flingshot 	48
    fullauto 	48
    grenade 	48
    HasKnuBotData 	1
    headmesh 	0
    healdelta 	2
    healinterval 	30
    health 	227
    intelligence 	25
    isfightingme 	0
    level 	1
    life 	227
    losheight 	0
    lr_energyweapon 	48
    lr_multipleweapon 	48
    mapnavigation 	46
    martialarts 	48
    materialcreation 	38
    materiallocation 	38
    materialmetamorphose 	38
    maxnanoenergy 	1
    mechanicalengineering 	46
    meleeac 	10
    meleeenergyweapon 	48
    meleemultiple 	48
    monsterdata 	17649
    monsterscale 	95
    nanoac 	29
    nanoenergypool 	38
    nanointerval 	28
    nanoprogramming 	46
    nanoprowessinitiative 	43
    npc_type 	80001
    npcfamily 	4
    onehandbluntweapons 	48
    onehandedgedweapon 	48
    parry 	53
    perception 	48
    pharmaceuticals 	46
    physicalprowessinitiative 	43
    piercing 	48
    pistol 	48
    poisonac 	19
    profession 	0
    projectileac 	10
    proximityrangeindoors 	13
    proximityrangeoutdoors 	25
    psychic 	25
    psychologicalmodification 	38
    psychology 	46
    race 	1
    radiationac 	19
    rifle 	48
    riposte 	48
    runspeed 	34
    sense 	25
    senseimprovement 	38
    sex 	1
    shotgun 	48
    side 	3
    sneakattack 	48
    stability 	100
    stamina 	25
    strength 	25
    submachinegun 	48
    swim 	48
    throwingknife 	48
    throwngrapplingweapons 	48
    titlelevel 	0
    treatment 	46
    tutoring 	46
    twohandbluntweapons 	48
    twohandedgedweapons 	48
    VisualFlags 	31
    visualprofession 	15
    waitstate 	2
    weaponsmithing 	46
    xp 	0

**Comment by Unknownprk** [comment]
Hopefully this should be good now, tested through backyards, subway and foremans and health seems to match what we expect

**Comment by 7RO11** [comment]
poked at all the foremans mobs and they seem right
