### ISSUE TITLE
Empty shops in borealis

### ISSUE THREAD

**Issue by JulianVallee** [project-rubika/issues#701]
**Describe the bug**
Multiple shops inside Borealis are empty:
* Yalmaha and tower shops in tower shop building
* Half of the Trade shops inside FT are empty

Also found https://github.com/project-rubika/issues/issues/496, probably related and maybe a regression? Waited some time, shops not filling up.

**To Reproduce**
1. Go to the listed shop
2. Open the shop
3. See that it is empty

**Expected behavior**
Shops should sell items.

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/6720458/b18babe1-56a3-47a1-808b-c8b8c111389d)

**Playfield info:**
```
- 187.7, 136.4, 5.0 (187.7 136.4 y 5.0 4704)
- Pf Proxy: Model=51100:4704 GS=0 SG=0 R=4704, resource: 4704
- zone: 0, area: "Tower Shop"
Server id: 1456, character id: 50000:1456, time: 2024-04-05 00:52:05 (UTC)
Version: 00.6.1_EP1, map id: NOT FOUND, build: 52606.
```

**Comment by TheTinkeringIdiot** [comment]
Confirmed as known issue.

Most of the common shops have been populated, but many of the specialty shops remain empty. Many of those specialty shops are in proxy playfields that don't yet load (like the "Special Edition" shops - #385 and #500 ), but the Tower Store does load and give access to an empty specialty shop.

**Comment by prkdrake** [comment]
Should be fixed now.

**Comment by RaggyLP** [comment]
Confirmed. Closing as fixed as of 19/08/2024.

![image](https://github.com/user-attachments/assets/f419ccc7-8771-4742-9058-7ab952bb9ff9)
