### ISSUE TITLE
Unable to loot item with one inventory slot remaining

### ISSUE THREAD

**Issue by Mumblyphuck** [project-rubika/issues#705]
**Describe the bug**
Looting item returns chat message. item does not move to inventory. one inventory slot open.

**To Reproduce**
1. almost full inventory with one empty space'
2. kill mob and loot an item
3. item loot message broadcasts, item does not leave dead mob or enter player inventory

**Expected behavior**
item moves to inventory or system displays inventory full message

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/166165666/1258c2f3-b401-4dd1-b2ce-a081320f34c3)

Copy/paste the output of /getfull here
Harmacist [5 Doctor]
------------------------------------
    strength 	30
    stamina 	25
    agility 	21
    sense 	18
    psychic 	18
    intelligence 	18
    flags 	528961
    monsterscale 	100
    currentnano 	87
    headmesh 	40100
    waitstate 	1
    cash 	653
    gmlevel 	127
    expansion 	3
    fatness 	0
    breed 	4
    visualbreed 	4
    profession 	10
    visualprofession 	10
    level 	5
    sex 	1
    visualsex 	1
    health 	179
    titlelevel 	1
    accountflags 	0
    equippedweapontype 	1
    EquippedRHWeapon 	1
    bodydevelopment 	31
    nanoenergypool 	34
    evade 	29
    martialarts 	30
    physicalprowessinitiative 	29
    nanoprowessinitiative 	29
    materialmetamorphose 	34
    biologicalmetamorphose 	34
    firstaid 	34
    treatment 	34
    pharmaceuticals 	34
    computerliteracy 	34
    selectedtarget 	1470
    selectedtargettype 	0
    charstate 	0
    isfightingme 	0
    xp 	12974
    exitstatel 	-1073740870
    externaldoorinstance 	-418378760
    externalplayfieldinstance 	3064
    nextxp 	15650
    lastsavexp 	4000
    runspeed 	27
    nanoac 	34
    brawl 	32
    lastxp 	4050
    maxncu 	10
    playfieldtype 	0
    currentmovementmode 	3
    side 	0
    race 	1
    life 	179
    monsterdata 	0
    VisualFlags 	31
    clan 	0
    team 	0
    chemicalac 	8
    coldac 	8
    energyac 	9
    fireac 	8
    meleeac 	11
    poisonac 	8
    projectileac 	11
    radiationac 	10
    aggdef 	100
    closecombatinitiative 	9
    distanceweaponinitiative 	9
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	32
    specialization 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    savedxp 	0
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    maxnanoenergy 	87
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    alignment 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    meleemultiple 	11
    onehandbluntweapons 	11
    onehandedgedweapon 	11
    piercing 	11
    twohandbluntweapons 	11
    twohandedgedweapons 	12
    meleeenergyweapon 	10
    throwingknife 	10
    grenade 	9
    throwngrapplingweapons 	11
    bow 	10
    pistol 	9
    rifle 	9
    submachinegun 	11
    shotgun 	11
    assaultrifle 	10
    drivewater 	9
    bowspecialattack 	10
    senseimprovement 	10
    mechanicalengineering 	9
    electricalengineering 	10
    psychologicalmodification 	9
    materialcreation 	9
    materiallocation 	9
    lr_energyweapon 	9
    lr_multipleweapon 	9
    disarmtrap 	9
    perception 	9
    adventuring 	22
    swim 	11
    driveair 	9
    mapnavigation 	9
    tutoring 	9
    riposte 	9
    dimach 	9
    parry 	11
    sneakattack 	9
    fastattack 	9
    burst 	11
    flingshot 	10
    aimedshot 	9
    duck 	9
    dodge 	9
    fieldquantumphysics 	9
    weaponsmithing 	11
    nanoprogramming 	9
    psychology 	10
    chemistry 	10
    concealment 	9
    breakingentry 	9
    driveground 	9
    fullauto 	12
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    age 	0
    attackspeed 	5
    metatype 	0
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    beltslots 	2
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
    healinterval 	29
    nanointerval 	28
    amsmodifier 	0
    damageoverridetype 	0
    meleedamagemodifier 	0
    currentncu 	0
    dmsmodifier 	0
    reflectreturnedenergyac 	0
    reflectenergyac 	0
    shieldenergyac 	0
    xpmodifier 	0
    xppool 	0
    ip 	7252
    reflectreturnedmeleeac 	0
    reflectmeleeac 	0
    shieldmeleeac 	0
    reflectreturnedradiationac 	0
    reflectradiationac 	0
    shieldradiationac 	0
    npcostmodifier 	0
------------------------------------

.getfull succeeded - Listed all stats for Harmacist.

**Playfield info:**

Copy/paste the output of Shift+F9 here

.getfull succeeded - Listed all stats for Harmacist.
Extended location information:
- 50.1, 133.1, 4.6 (50.1 133.1 y 4.6 954)
- Pf Proxy: Model=51100:954 GS=0 SG=0 R=954, resource: 954
- zone: 25, area: "Junkyard"
Server id: 169503, character id: 50000:1470, time: 2024-04-05 19:19:10 (UTC)
Version: 00.6.1_EP1, map id: NOT FOUND, build: 52606.

**Comment by RaggyLP** [comment]
I was unable to repro with the above steps and was able to loot up to a full invetory with no strange effects. Could you please loot to replicate this again and give more information on that steps taken up to the bug occurring?

**Comment by prkdrake** [comment]
Please test what happens if you try to loot with a full inventory, and raise a bug if you don't get a "your inventory is full" message, and close this issue.

**Comment by RaggyLP** [comment]
Confirmed that inventory operates as expected, both when full and with 1 slot remaining. Closing as fixed.

![image](https://github.com/user-attachments/assets/01eb228b-4225-4c00-9530-9931690714b3)
