### ISSUE TITLE
Explosif's Polychromatic Pillows can't be changed to other variants

### ISSUE THREAD

**Issue by l00del** [project-rubika/issues#708]
The AI Pillows "Explosif's Polychromatic Pillows" (ID 258345 + 258344 + 258343) can't be changed in the other forms by right-click

**Comment by TheTinkeringIdiot** [comment]
Confirmed.

The pillows appear to be usable according to the mouse icon when hovering over them, but right clicking does nothing. 

![image](https://github.com/project-rubika/issues/assets/96996793/cdf96e31-6e45-406a-b897-db2bd555930a)

**Comment by prkdrake** [comment]
Should re-verify this since recent item changes.

**Comment by TheTinkeringIdiot** [comment]
Confirmed fixed. The item now cycles correctly between versions when right clicked. Closing as complete.
