### ISSUE TITLE
Pets disappear when quickly zoning twice

### ISSUE THREAD

**Issue by JulianVallee** [project-rubika/issues#725]
**Describe the bug**
Pets are not properly reassigned when quickly zoning twice in a row.

When the second zoning before the pet gets reassigned after the first zoning, there is no pet left to reassign. Not sure about the architecture, but could be a potential memory leak imo.

**To Reproduce**
1. Summon a pet
2. Zone to somewhere else
3. Zone back again before the pet spawns (1-3 secs leeway, `Pet XXX reassigned.` should not be printed to chat)
4. Pet is gone

**Expected behavior**
Pets should not disappear and reassigning should happen correctly.

**Comment by RaggyLP** [comment]
Confirmed, zonging in the manner described above will remove the pet from the character and not assign a new entity.

**Comment by Unknownprk** [comment]
Potentially fixed now

**Comment by RaggyLP** [comment]
Re-tested using the 3 main pet classes, this now appears to be fixed! Closing as fixed as of 30/06/24.
