### ISSUE TITLE
Borealis PF Entry

### ISSUE THREAD

**Issue by dahomburg** [project-rubika/issues#726]
In Borealis POS 674.5, 587.8, 66.8, facing south, between agency sign and whop-pah sign, trying to enter "Basic Weapon Shop" instead of Playfield change I got that:

------SEND THIS TO THE DEVS------
  destProxyModelType: 51102
  destProxyModelInst: 2060
  destProxyGroup: 0
  destProxySubgroup: -1073675488
  destProxyLocalizerType: 100002
  destProxyLocalizerInst: 1
----------------------------------

**Comment by TheTinkeringIdiot** [comment]
Added info to #385, closing as duplicate.
