### ISSUE TITLE
assassin mission completion

### ISSUE THREAD

**Issue by 7RO11** [project-rubika/issues#728]
**Describe the bug**
assassination missions can be completed without the [special weapon](https://auno.org/ao/db.php?id=123057) provided

**To Reproduce**
1. roll an assassination mission as agent
2. kill the target with a normal weapon
3. mission pays out normally

**Expected behavior**
mission only pays out if the target was killed with the weapon provided

**Screenshots**
same mission as seen in #727 
![quest2](https://github.com/project-rubika/issues/assets/73971287/eb16026d-2480-45e2-962f-e0d7f35dbde7)

**Comment by RaggyLP** [comment]
Confirmed. While not all assassination missions provided a weapon/item to be used on the target, some do. This is currently not implemented for this mission type however.

**Comment by portalerprk** [comment]
Yeah. I dont think we're going to spend time implementing this since its more a painful feature than anything else :-) having to unequip you twinked out weapon so you can go stab X with Y is sort of silly.

**Comment by portalerprk** [comment]
I've removed the "perma death" missions. I also added PF text to mission text

**Comment by 7RO11** [comment]
![desc2](https://github.com/project-rubika/issues/assets/73971287/2c5bb639-cfd3-4f6e-aa9f-af724efede11)
![desc](https://github.com/project-rubika/issues/assets/73971287/d5dc9694-4867-45c0-a031-3589a034c7ab)
found a couple pulling from nlc as 25 agent
