### ISSUE TITLE
Client crash occasionally when multiple toons zoning simultaniously

### ISSUE THREAD

**Issue by Smegster11** [project-rubika/issues#731]
**Describe the bug**
I was testing team functionality, when i noticed fairly consistently, one or more clients crashing when zoning simultaniously, in this instance going from Newland Backyard 1 > The actual Backyard.

If i went through one by one with a small delay this issue did not occur, when all toons set to follow and running into the new zone a crash would take out some of the clients. (zone request unable to handle x amount of requests simultaniously?)

**To Reproduce**
1. Go to 'any Zone door/wall'
2. set multiple toons to follow
3. walk through the door
4. fairly common for crashes to occur at this stage

**Expected behavior**
All toons should make it into the new zone without a client crash

**Screenshots**
n/a

**Character info:**
n/a
```
Copy/paste the output of /getfull here
```
n/a
**Playfield info:**
n/a
```
Copy/paste the output of Shift+F9 here
```
n/a
----

**Comment by prkdrake** [comment]
It seems likely to me that this is caused by a character following another character when the followed character changes zone.

**Comment by kajoriEU** [comment]
I am unable to reproduce this issue at the moment.
