### ISSUE TITLE
Shops providing Jobe Suit measurements are missing two pieces of the set, and Sleeve and Shoulderpads have a hidden 'Unique' flag.

### ISSUE THREAD

**Issue by Starbouy138** [project-rubika/issues#739]
**Describe the bug**
When getting measurements for Jobe armor pieces at the Boutique in Borealis, or the Tailor in Newland, requesting the Sleeve and Shoulderpad twice results in the shopkeeper dialogue giving the expected, successful response, but the chat window informs you the following;
You already possess a unique 'Measurements - Sleeves'
You already possess a unique 'Measurements - Shoulder Pads'
The Measurements for each item has a visible NODROP flag but no UNIQUE flag in the description.

**To Reproduce**
1. Go to the Boutique in Borealis near the Subway and enter. _Alternatively the Newland Tailor shop._
2. L-Click on the shopkeeper to open dialogue, choose "How is life?" then choose "I need to be measured for a set of Jobe Armor, can you help me?"
3. First notice that the Breastplate and Life Support System are not listed as options. Choose "The Jobe Suit Sleeves." or choose "The Jobe Suit Shoulderpad." once and receive the item, then for a second time to make the matching sleeve or shoulder piece.
4. See the dialogue of the Shopkeeper reply as "Tailor: There you go.  Now, is there something else I can help you with?" and you will get the first Sleeve or Shoulderpad, but the second time it gives the same dialogue, but chat reflects this response; 
You already possess a unique 'Measurements - Sleeves'
-or-
You already possess a unique 'Measurements - Shoulder Pads'

**Expected behavior**
I would expect the armor measurements items for, Pants, Boots, Gloves, Helmet, Breastplate, and Life Support System to be Unique, but the Sleeve and Shoulderpad not to be Unique. 
Also, all of these items should be obtainable:
[Measurements - Boots] (http://auno.org/ao/db.php?id=256417)
[Measurements - Breastplate] (http://auno.org/ao/db.php?id=256419)
[Measurements - Gloves] (http://auno.org/ao/db.php?id=256418)
[Measurements - Helmet] (http://auno.org/ao/db.php?id=256420)
[Measurements - Life Support System] (http://auno.org/ao/db.php?id=256421)
[Measurements - Pants] (http://auno.org/ao/db.php?id=256415)
[Measurements - Shoulder Pads] x2 (http://auno.org/ao/db.php?id=256422)
[Measurements - Sleeves] x2 (http://auno.org/ao/db.php?id=256416)

**Screenshots**

**Character info:**

```
Capslayer [38 Keeper]
------------------------------------
    strength 	140
    stamina 	128
    agility 	125
    sense 	135
    psychic 	120
    intelligence 	120
    flags 	528961
    monsterscale 	100
    currentnano 	745
    headmesh 	40687
    waitstate 	2
    cash 	898516916
    gmlevel 	127
    expansion 	3
    breed 	1
    visualbreed 	1
    profession 	14
    visualprofession 	14
    level 	38
    sex 	2
    visualsex 	2
    health 	1673
    titlelevel 	2
    accountflags 	0
    equippedweapontype 	130
    EquippedRHWeapon 	130
    selectedtarget 	1676
    selectedtargettype 	0
    charstate 	0
    aggdef 	100
    exitstatel 	-1073739761
    externaldoorinstance 	-1073610186
    externalplayfieldinstance 	566
    playfieldtype 	1
    nextxp 	713550
    xp 	695209
    lastsaved 	228150
    lastxp 	662650
    bodydevelopment 	251
    runspeed 	229
    closecombatinitiative 	318
    twohandedgedweapons 	313
    senseimprovement 	242
    firstaid 	237
    treatment 	208
    biologicalmetamorphose 	236
    psychologicalmodification 	238
    materiallocation 	265
    nanoenergypool 	182
    fastattack 	297
    evade 	324
    computerliteracy 	181
    currentncu 	0
    expansionplayfield 	0
    materialmetamorphose 	30
    materialcreation 	30
    onehandbluntweapons 	43
    twohandbluntweapons 	55
    onehandedgedweapon 	42
    piercing 	42
    meleeenergyweapon 	41
    sneakattack 	41
    brawl 	123
    dimach 	76
    meleemultiple 	44
    psychology 	64
    dodge 	149
    parry 	100
    riposte 	44
    martialarts 	41
    duck 	71
    adventuring 	42
    swim 	72
    throwingknife 	42
    throwngrapplingweapons 	44
    physicalprowessinitiative 	58
    concealment 	43
    nanoac 	31
    distanceweaponinitiative 	48
    nanoprowessinitiative 	48
    perception 	39
    maxnanoenergy 	724
    bow 	43
    flingshot 	34
    isfightingme 	0
    lastsavexp 	47900
    ip 	15947
    currentmovementmode 	3
    xppool 	616963
    maxncu 	442
    fatness 	1
    side 	0
    race 	1
    life 	1673
    monsterdata 	0
    VisualFlags 	31
    clan 	0
    shieldprojectileac 	2
    shieldmeleeac 	2
    shieldenergyac 	2
    shieldchemicalac 	2
    shieldradiationac 	2
    shieldcoldac 	2
    shieldnanoac 	2
    shieldfireac 	2
    shieldpoisonac 	2
    projectileac 	682
    meleeac 	834
    energyac 	682
    chemicalac 	593
    radiationac 	593
    coldac 	712
    poisonac 	593
    fireac 	712
    reflectmeleeac 	0
    reflectpoisonac 	0
    reflectfireac 	0
    reflectnanoac 	0
    reflectcoldac 	0
    reflectprojectileac 	0
    reflectenergyac 	0
    reflectchemicalac 	0
    reflectradiationac 	0
    team 	0
    xpmodifier 	7
    meleedamagemodifier 	10
    energydamagemodifier 	10
    projectiledamagemodifier 	10
    beltslots 	6
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    specialization 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    savedxp 	0
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    alignment 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    grenade 	37
    pistol 	37
    rifle 	37
    submachinegun 	37
    shotgun 	37
    assaultrifle 	37
    drivewater 	37
    bowspecialattack 	37
    mechanicalengineering 	35
    electricalengineering 	35
    lr_energyweapon 	36
    lr_multipleweapon 	35
    disarmtrap 	37
    driveair 	37
    mapnavigation 	36
    tutoring 	35
    burst 	37
    aimedshot 	38
    fieldquantumphysics 	35
    weaponsmithing 	37
    pharmaceuticals 	35
    nanoprogramming 	35
    chemistry 	36
    breakingentry 	36
    driveground 	37
    fullauto 	38
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    age 	0
    attackspeed 	5
    metatype 	0
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
    healinterval 	24
    nanointerval 	24
------------------------------------

.getfull succeeded - Listed all stats for Capslayer.

```

**Playfield info:**

```
Extended location information:
- 215.1, 169.2, 5.0 (215.1 169.2 y 5.0 2063)
- Pf Proxy: Model=51100:2063 GS=0 SG=0 R=2063, resource: 2063
- zone: 0, area: "Area"
Server id: 1676, character id: 50000:1676, time: 2024-05-03 04:08:52 (UTC)
Version: 00.6.1_EP1, map id: NOT FOUND, build: 52606.

```
----

 
![Jobe Measurements](https://github.com/project-rubika/issues/assets/168038243/ce3a4531-a77b-46b2-a6bd-3f4f152f4bea)

**Comment by RaggyLP** [comment]
Confirmed, the items themselves do not display a UNIQUE tag either.
![image](https://github.com/project-rubika/issues/assets/156821187/3b219f43-b827-4791-a96c-ca9429eb186c)

**Comment by prkdrake** [comment]
Possibly fixed by some recent changes, please re-test

**Comment by Starbouy138** [comment]
Now this NPC does not open with any dialogue at all.
You can also accidentally click on the clothes terminal that is over the top of her and open trade to a clothes shop.
I waited over a minute in the Boutique in Borealis, I zoned, i relogged inside, just to see if there was any difference and nothing changed.
 I then ran to Newland City to the Tailor shop near Fair Trade and General Stores and had the same results.
![image](https://github.com/user-attachments/assets/277f2848-ca63-4c20-b845-77f769470af2)

**Comment by prkdrake** [comment]
This should be fixed with the next update, please re-test and let us know. Thanks!

**Comment by RaggyLP** [comment]
Confirmed. You can now get both Vest and Support System notes and the shoulderpads and sleeves notes are no longer flagged as unique. Closing as fixed as of 21/08/2024.

**Comment by Starbouy138** [comment]
I tested Borealis Amanda's Boutiques Tailor shop and was successful, I deleted the measurement items and went to the Newland Tailor shop and tried again with success. I did so with Capscan Lvl 25 Doc. 
I also then tried with Keeper that I originally opened the ticket with, and was successful.

![image](https://github.com/user-attachments/assets/57eaf4a7-e56e-4567-a8fe-9bcfc477e556)
