### ISSUE TITLE
strange mob tracking

### ISSUE THREAD

**Issue by 7RO11** [project-rubika/issues#748]
**Describe the bug**
mobs that normally aggro on sight instead track the player without attacking

**To Reproduce**
1. Go to subway
2. get close to infectors, nueral burnouts, and other mobs
3. they won't attack you

**Expected behavior**
mobs that attack on sight should attack

**Screenshots**
![1](https://github.com/project-rubika/issues/assets/73971287/0c8f03b1-56f9-43f4-a085-8f93bba87f32)
also happening in biomare
![2](https://github.com/project-rubika/issues/assets/73971287/73fa5be8-dcea-400a-8415-02d7516e08c1)

attacking them does not cause them to aggro either
this only seems to apply to some mobs, muggers do not have this issue

**Comment by 7RO11** [comment]
seems to be fixed with last restart, unsure to keep open

**Comment by RaggyLP** [comment]
Confirmed fixed. Quick turn around :)

Close as of 01/07/2024

**Comment by 7RO11** [comment]
this behavior has returned on mobs inside missions

**Comment by portalerprk** [comment]
If you attack them do they attack back?

**Comment by 7RO11** [comment]
can start combat but no attacks, can't cast
[1](https://github.com/user-attachments/assets/273aa11f-7a38-4d08-bffd-05460aeea9a1)
