### ISSUE TITLE
Variable corpse timer is not implemented

### ISSUE THREAD

**Issue by 7RO11** [project-rubika/issues#749]
**Describe the bug**
certain mobs have long timers on their corpses, usually 30 min, but are only 2 min

**To Reproduce**
1. Go to totw
2. kill uklesh
3. corpse disappears in 2 minutes

**Expected behavior**
the corpse to have a 30 min timer, for other players to loot these mobs long after they were killed

**Screenshots**
![1](https://github.com/project-rubika/issues/assets/73971287/f12bd60e-2b80-4a57-b513-9bd889404624)
![2](https://github.com/project-rubika/issues/assets/73971287/c0c2c87b-18af-4c25-bc45-907191c8cf25)

**Comment by TheTinkeringIdiot** [comment]
Confirmed. 

Killing Guardian of Tomorrow resulted in a corpse with a 3 minute duration, and it did indeed decay after 3 minutes. Boss mobs typically have a 30 minute duration. 

Uklesh has a 2 minute duration. 

![image](https://github.com/user-attachments/assets/56eb0f10-3efe-464f-9691-d53012a06dea)

**Comment by kajoriEU** [comment]
Closing this as fixed/implemented :)

![{0045AC3C-103A-46DD-85CD-8D1A7D3868FD}](https://github.com/user-attachments/assets/f7761bc0-4c3d-48c5-9422-73ff7fcddd7a)
