### ISSUE TITLE
AI - Pets - MP - Instructing ATK pet to "Attack" a mob then "Follow" the healpet, it will enter a permanent Leashing state and suspend behaviors

### ISSUE THREAD

**Issue by Zolarix** [project-rubika/issues#755]
**Describe the bug**
The attack pet suspends all behaviours and a new one must be summoned if it is instructed to attack a valid mob then is instructed to follow the healpet.

Attack pets tested:
- Fury Externalization

Healpets tested:
- Medinos

**To Reproduce**
1. Summon an attack pet and a healpet.
2. Instruct the attack pet to attack a valid mob.
3. Instruct the attack pet to follow the healpet.
Observe -> The attack pet enters a permanent "Leashing" state and suspends all behaviours. Additionally, even the mob it has engaged will become stalled. Terminating the attack pet "resets" the mob.

**Expected behavior**
When commanding the attack pet to follow the healpet after instructing it to attack, the attack pet should either follow the healpet or follow the owner (if asking it to follow the healpet **without** setting it to attack first, it follows the owner).

**Screenshots**
https://github.com/user-attachments/assets/d118e059-3748-4913-bad2-d9705023320d

**Comment by prkdrake** [comment]
Definitely needs reverification since Portaler's changes

**Comment by RaggyLP** [comment]
Confirmed this is fixed, following the above steps, the attack pet now returns to the caster as expected.
