### ISSUE TITLE
Nano and weapon ranges are not checked correctly

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#756]
**Describe the bug**
Hostile nanoprograms obey a range exactly 5m longer than what is listed in the nano description. 

Tested with: 
* Crat Introspective Engagement (Listed: 22m Effective: 27m)
* NT Peaceful Intentions (Listed: 20m, Effective: 25m)
* NT Malaise of Movement (Listed: 25m, Effective: 30m)

**To Reproduce**
1. Using coordinates, position yourself <nano range> + 5 + 0.1 away from a target
2. Attempt to cast hostile nano - out of range
3. Move closer to within <nano range> + 5
4. Attempt to cast hostile nano - it works

**Expected behavior**
Nano programs should utilize the listed range by default, and obey range modifications indicated by the `rangeincreasernf` value. 

**Screenshots**
In this screenshots the targeted Peacekeeper is standing at coordinate 3267.9, 913.4

20m nano hitting at 25m
![image](https://github.com/user-attachments/assets/421c6c4f-7201-41b4-ad48-caf8ee81ab0a)

25m nano hitting at 30m
![image](https://github.com/user-attachments/assets/610dd78b-9a8d-4368-b11d-4bebb8aafcbe)

22m nano hitting at 27m
![image](https://github.com/user-attachments/assets/4841f113-c142-4b7d-a74f-dd68ae6445c9)

**Comment by TheTinkeringIdiot** [comment]
Further testing indicates that weapons are also affected. 

This 15m pistol hits the target at exactly 20m, but no farther. 

![image](https://github.com/user-attachments/assets/80e0a47e-6f7a-4879-8e9e-e1e07d47aed8)

**Comment by RaggyLP** [comment]
Confirmed. There appears to be a discrepancy on ranging based on the size of the targets hitbox vs the size of the player hitbox.

**Comment by prkdrake** [comment]
See also #742

**Comment by RaggyLP** [comment]
MA ranges are currently significantly shorter than on live, resulting in you needing to be almost inside the center part of the hitbox.

**Comment by prkdrake** [comment]
This is mostly fixed I believe- it's a little bit off though, and we haven't implemented the IncRange Weapon stat properly yet.

**Comment by RaggyLP** [comment]
Confirmed. Ranges are now *very* close to expected outcomes, will mark this one as fixed, for RangeInc, refer to #752. Fixed as of 04/09/2024.
