### ISSUE TITLE
tim not spawning

### ISSUE THREAD

**Issue by 7RO11** [project-rubika/issues#761]
**Describe the bug**
the slayerdroid T.I.M. in foremans is not spawning 

**To Reproduce**
1. Go to where T.I.M. spawns, end of foremans
2. it isn't there

**Expected behavior**
T.I.M. spawns

**Screenshots**
where it should spawn, isnt
![Screenshot from 2024-07-18 13-06-13](https://github.com/user-attachments/assets/22de2a23-ff94-4800-93c9-9d736cd88654)

have visited multiple times of day and waited about an hour to confirm

**Comment by Starbouy138** [comment]
I don't recall if you have to speak with Lab Assistant Evelynn Shead first to get him to spawn first. I tried speaking with her and she had no dialogue.
 She is in the windowed room that views T.I.M. through glass.

-Kill T.I.M. Mission
Mission Log:
"Lab Assistant Evelynn Shead has requested your help in shutting off the disposal device known as T.I.M."

T.I.M., a level 100 Slayer

**Comment by 7RO11** [comment]
on live tim spawns on a timer no extras afaik

**Comment by RaggyLP** [comment]
![image](https://github.com/user-attachments/assets/5e2500b5-963a-4f43-aaca-1d146e6fa65e)

Confirmed, TIM is absent from his death pit.

**Comment by RaggyLP** [comment]
![image](https://github.com/user-attachments/assets/f24af822-96dd-4f09-b18a-270ab84af516)


T.I.M is now present and ready for murder.
