### ISSUE TITLE
ICC Shuttleport Bugs [Newb Island]

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#771]
ICC Shuttleport, aka, Newb Island, is currently being heavily worked on. It is currently not accessible outside of teleport commands. If you are intent on supporting testing the zone, please use `.tp newbisle` to access the location. Below is the currently known issues. If you find something new, not on this list, please add a comment to the ticket thread with as much information as possible and reproduction steps so I can confirm it.

- ~~Fixx throws an exception when you talk to him with Stacklund's quest~~
- ~~Dynabosses are aggressive~~ This is the same as on live.
- Dynabosses and other mobs seem to be getting procs/buffs they shouldn't
- ~~Quests may be giving too many credits~~
- ~~The beginner nano-programs shop doesn't work~~
- ~~Some killed mobs have the wrong texture on their corpse~~
- ~~Tradeskill requirements on Antonio's Adaptation Factory are too high~~
- ~~Quest kill counts reset on session end~~
- ~~NPCs always turn to face true north~~
- ~~Brandon Thorn gives QL200 Med-kits when traded 3 Monster Parts~~
- ~~Adri Afeli (1322) returns all the relevant items given to him when choosing 'Give items' on [10161] when you give him a Solar-Powered Assault Rifle (121569). Relogging solves the problem, potentially 1 of the quest items not updating on the client correctly?~~
- ~~Aliens do not path to the guards and the guards are non-aggressive to aliens.~~
- The aliens/ICC guards behave very strangely

**Comment by 7yk0** [comment]
ICC Bio-Inspector bugs out after the quest where you identify the boss mob versions of the different beach animals. The mission completes but no reward is given, and then he can't be talked to afterward. His convo box is just blank when talking to him again.

**Comment by Dezzyx** [comment]
**_NPC Dialogue_**

* **Brandon Thorn**: These options do not respond 

![Screenshot 2024-08-13 234939](https://github.com/user-attachments/assets/bd0464d1-8462-4762-a919-d08fd78e0140)

Also, he won't "Explain the skill system".


* **Travis Molen**: This option does not respond 

![Screenshot 2024-08-16 002133](https://github.com/user-attachments/assets/883d7fda-c7b3-41ec-9699-1170a0b3820d)

**_Items_**

* Startup First-Aid Kit shows no Modifier 

![Screenshot 2024-08-16 010903](https://github.com/user-attachments/assets/a36918a5-3276-4bba-9470-56d12ceb8839)

**Comment by 7RO11** [comment]
Specialist - Cha'Heru does not drain nano, tested for about 5 minutes with 1 evades and nr

**Comment by 7RO11** [comment]
mobs are not being leashed back to their spawn area and will chase you around the entire island, not sure if thats accurate to live but i think its causing crashes. it seems to happen the most around the docks area with dynas. sometimes mobs that are pulled too far won't die when theyre killed, creating a corpse where they died and causing fps drops

**Comment by Starbouy138** [comment]
In reference to this particular entry from 7yk0 earlier- "-ICC Bio-Inspector bugs out after the quest where you identify the boss mob versions of the different beach animals. The mission completes but no reward is given, and then he can't be talked to afterward. His convo box is just blank when talking to him again."
-end reference.

Today I did complete the ICC Bio-Inspector Identify/target the 5 boss mobs mission and received the Range Meter reward in my inventory. However, after I did so, I asked what more I could do and all dialogue stopped, I closed the NPC chat window and opened it again to a blank window that remained that way. It eventually closes on its own after about 10 seconds.
![image](https://github.com/user-attachments/assets/d0c06171-7b30-4b63-bd57-95637a227cdb)

**Comment by prkdrake** [comment]
Latest update should fix the following issues: 

- Adri Afeli (1322) returns all the relevant items given to him...
- Fixx throws an exception when you talk to him with Stacklund's quest...
- ICC Bio-Inspector bugs out after the quest...
- Everything in this comment: https://github.com/project-rubika/issues/issues/771#issuecomment-2292459675
- Everything in this comment: https://github.com/project-rubika/issues/issues/771#issuecomment-2294205183

Potentially also fixed: 
- Quest counts updating multiple times on kill
- Quest counts not persisting after logging out

**Comment by prkdrake** [comment]
> - NPCs always turn to face true north

Should be fixed with latest version

**Comment by prkdrake** [comment]
> The beginner nano-programs shop doesn't work

This should be fixed with the latest version.

**Comment by prkdrake** [comment]
- Some killed mobs have the wrong texture on their corpse

Should be fixed with latest update

**Comment by 3F1-1009** [comment]
Many "regular mobs" in addition to "dyna bosses" have a radiation proc which is pretty devastating in starter area.
I have observed 20 point radiation damage proc from following mobs:

Stowaway Rollerrat 787.6 743.6 y 39.8 4582
Crosswired Junkbot 854.2 736.8 y 39.7 4582 / 933.8 752.5 y 39.7 4582
Giant Snake 767.8 830.2 y 38.1 4582

Stowaway Rollerrats having that proc also makes quest to kill Shuttle Saboteur very difficult because target is surrounded by Stowaway Rollerrats.

Armor does not appear to reduce damage taken from the proc.

**Comment by kajoriEU** [comment]
As of today, Travis Molen stopped giving XP Rewards for helping both sides and bringing back their reports. He is supposed to give you 300 XP for completing both questlines.

**Comment by prkdrake** [comment]
Just closing this issue because it's too big and annoying, sorry. Feel free to open a new issue for any unresolved issues
