### ISSUE TITLE
LINUX ingame browser/gmi window

### ISSUE THREAD

**Issue by 7RO11** [project-rubika/issues#772]
**Describe the bug**
opening one of the browser windows like the daily rewards will throw an error on linux

**To Reproduce**
1. press play on a character
2. see error/white window
or
1. open the browser anywhere else
2. see error/white window

**Expected behavior**
the browser displays its contents

**Screenshots**
![1](https://github.com/user-attachments/assets/963d8da6-2bda-47bc-a5d9-6e4d1dd80988)

I am using
wine-6.0.3 (Ubuntu 6.0.3~repack-1)
winetricks 20210206
nvidia-driver-535-183.01-0ubuntu0.22.04.1
GA106 [GeForce RTX 3060 Lite Hash Rate]

since this is linux specific and non fatal it should prolly be considered low priority, it may not even occur on every linux configuration or an issue with wine

**Comment by Unknownprk** [comment]
Seems like you might want to update your wine, this does not happen for me.

I run GE-Proton-9.5.

I will close this issue as it's not something we can solve. In the future if you get a wine specific issue make sure to atleast run the latest wine.

**Comment by 7RO11** [comment]
for those looking back on this and prolly myself later, i was able to solve this by changing wine to the staging branch, stable and development have this issue on both version 6 and 9
