### ISSUE TITLE
Helmet visible option is not implemented

### ISSUE THREAD

**Issue by Dezzyx** [project-rubika/issues#774]
Describe the bug

In Preferences menu, clicking the "Helmet visible" option has no effect

To Reproduce

1. Go to F10 > Preferences
2. Click on Behavior > Helmet visible
3. No changes occur

Expected behavior

Helmet should show/hide accordingly

EDIT: Realized social tab didn't work either, and nothing in equipment window. Then saw #543
I'll keep this open as a friendly reminder and let you close/merge, whatever protocol is.

**Comment by prkdrake** [comment]
Known issue - feature, not implemented yet

**Comment by prkdrake** [comment]
Closing as duplicate of #524
