### ISSUE TITLE
NLC Clothes shops are empty

### ISSUE THREAD

**Issue by Dezzyx** [project-rubika/issues#775]
Describe the bug

In NLC shops the Clothes booths are empty. To note, the first day I played they had items. Subsequent days
they've been empty.

To Reproduce

1. Go to NLC shops
2. Click on Clothes booth
3. Booth has no items

Expected behavior

For there to be items for sale, specifically clothes. 

Screenshots

I can't seem to decide whether I want the invisible pants, or the invisible shirt.... choices, choices.

![Screenshot 2024-08-16 063845](https://github.com/user-attachments/assets/36312f8e-1de5-46b3-802b-6e64d71ef278)

**Comment by Dezzyx** [comment]
Today "Basic Devices" is empty too, but "Clothes" so far has consistently been this way.

**Comment by RaggyLP** [comment]
Just checked the NLC clothes shop. Tailor now sells the expected items. Close as fixed as of 18/08/2024.
