### ISSUE TITLE
Team loot messages are shown to players not in a team

### ISSUE THREAD

**Issue by Dezzyx** [project-rubika/issues#777]
Describe the bug

When Team Loot Messages are enabled, and you loot something, it shows in chat as a team loot message
even if you're not in a team.

To Reproduce
1. Go to Chat config
2. Click on a chat window and enable Team Loot Messages
3. Kill and loot something
4. Chat shows [Team Loot Messages] (You) have looted (item)

Expected behavior

I would think logically a team loot message should not appear because there is no team

Screenshots

![Screenshot 2024-08-16 081416](https://github.com/user-attachments/assets/534ae8ff-10d5-4268-a02d-472b7d1bbbb4)

**Comment by RaggyLP** [comment]
Confirmed. This also shows the 'You can loot these remains.' message when outside of a team, and gives you access to the loot container. It would appear that loot assignment is currently non-functioning.

**Comment by prkdrake** [comment]
I believe this has now been fixed

**Comment by RaggyLP** [comment]
Confirmed. No longer see loot right messages on kills from other players, and also can no longer access corpses without loot rights. However, loot rights are not updated on teaming. When a player who previously did not have access to the container is added to the team that does, the rights should be transferred to the new teammate.

**Comment by Dezzyx** [comment]
So updating here what this issue originally was supposed to be about. 

If you have Team Loot Messages enabled in chat config, when you loot something it shows as "Team Loot Message: (You) have looted (item)" in chat - even if you are not part of a team. Hopefully that's clear, if it's not please ask me to clarify. :)

**Comment by prkdrake** [comment]
I think this might only be the case if you have a pet - can someone please verify this? Thanks.

**Comment by Dezzyx** [comment]
fixed with recent patch, closing.
