### ISSUE TITLE
Weapon swap mid-combat, attack does not continue

### ISSUE THREAD

**Issue by Dezzyx** [project-rubika/issues#778]
Describe the bug

When attacking with a bow and then swapping to fists when enemy gets close, the fists are in fighting animation
but the attack does not continue. After swapping have to stop attack, then start attack again, to continue attacking. 

I'm not sure if this is intended, seems weird since the animation is still in fighting pose after swap, so would think
attack should continue automatically.

To Reproduce

1. Use a bow and attack a mob
2. When it gets close unequip bow so you only have fists
3. You are still in attack animation but attack does not continue with fists

Expected behavior

For attack to continue seamlessly after swapping weapon

**Comment by TheTinkeringIdiot** [comment]
Confirmed. 

Swapping weapons in mid-combat causes further auto-attacks to stop. Special attacks and perks continue to work but combat must be stopped and restarted to resume auto-attacks.

**Comment by Starbouy138** [comment]
Noticed this today when my MA in ICC ShuttlePort had Worn a Dagger in Right Hand and removed during combat, the NPC continued attacking but my character stayed "in" combat but stopped actually attacking. The attack meters filled up and I could not use Brawl or the MA attack from the hotbar until I stopped combat and restarted combat.

**Comment by Dezzyx** [comment]
this has been fixed for a while I think: checked to be sure and yes fixed, closing.
