### ISSUE TITLE
Annie Kingsglade delivery quest not recognised by target NPC.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#782]
**Describe the bug**
Annie Kingsglade (1052) gives a quest (1196), to hand a 'Basic Bio-Communitor' to Robert Ryan (1053), however, he does not recognise that you have the quest, which locks off conversation options [8146] [8147]. Skipping past this with debug opens trade (1227), but he does not recognise the 'Basic Bio-communitor' given to you by Annie and returns the item.

**To Reproduce**
1. `.set level 10` & `set side 1`
2. `.tp 397 339 545`
3. Talk to Annie and choose: "Hello!" > "Sure, it wasn't far anyway!"
4. Go to Robert Ryan (over by WA Basic) (or tp like a lazy. `.tp 451 388 545`).
5. Notice you are unable to choose the relevant conversation option.

**Expected behavior**
Robert Ryan should have the [8146] [8147] options opened by Annies quest being in your log.

**Comment by prkdrake** [comment]
This should now be fixed as of the latest release.

**Comment by RaggyLP** [comment]
Confirmed, Robert Ryan now recognises and accepts his Bio-Communitor! Clsoing as fixed as of 24/08/2024.
