### ISSUE TITLE
Good Time Party Mixer generates hidden quests.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#783]
# **DISCLAIMER - GTPM's QUESTS REQUIRE ACG IMPLEMENTATION, COMPLETE FIX NOT POSSIBLE UNTIL THEN**

**Describe the bug**
Good Time Party Mixer's (94) Living Armour quests are generated on the server, but are not reflected on the client. Conversation options [2323] [2324] [2325] spawns (FNHN) (KIMB) (FNMR) respectively.

**To Reproduce**
1. `.set level 10`
2. Talk to the Good Time Party Mixer `.tp 460 345 566`
3. Choose options: "What are you doing here" > "Living Armor?" > "I am interested in..."
4. Notice lack of addition to the mission window, confirm with `.quests`

**Expected behavior**
GTPM's quests should be visible in the player missions window.

**Screenshots**
![image](https://github.com/user-attachments/assets/0179e5a4-c5c8-426d-b168-57f12bbc96f5)

**Comment by RaggyLP** [comment]
This situation is also present on the OT Party Mixer (1085).

**Comment by prkdrake** [comment]
I've added a restriction to prevent ACG quests from being created for now, this needs to be re-visited when ACG is working.

**Comment by RaggyLP** [comment]
![image](https://github.com/user-attachments/assets/da5f1809-dfeb-40a6-9151-511c703e7790)
Looking good. Closing this ticket for now until ACG is up and running.
