### ISSUE TITLE
Guide 'Kill One Leet' Mission Does Not Update On Kill.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#784]
**Describe the bug**
The 'Kill One Leet' mission (KION) given by the Guide (54), doesn't update on killing the 'Leet' mob/s in the backyard. Tested with both Leet and Eleet.

**To Reproduce**
1. Go to any Guide in a Backyard.
2. Choose > "I want to know how to play this games" > "I prefer doing tasks"
3. Enter a backyard, find a Leet and kill it.
4. Notice lack of update.

**Expected behavior**
The mission should progress on mob kill.

**Comment by prkdrake** [comment]
This should now be fixed as of the latest release.

**Comment by 3F1-1009** [comment]
Quest works, but it also counts Eleet (and possibly any other leet type) as target while live only counts Leet.

**Comment by RaggyLP** [comment]
Also, the linked quest 'Kill three Leets' (KLTR) counts the kill from 'Kill one Leet' (KION), meaning for (KLTR) you only need to kill 2, instead of 3.

**Comment by prkdrake** [comment]
Both above mentioned issues should be fixed with the next update.

**Comment by RaggyLP** [comment]
Confirmed. KLTR now only updates on 'Leet' kill, not 'Eleet' and counts 3, instead of 2. Closing as fixed as of 24/08/2024.
