### ISSUE TITLE
"Disable all XP gains" option not working

### ISSUE THREAD

**Issue by Dezzyx** [project-rubika/issues#785]
Describe the bug

The "Disable all XP gains" preference is not saved on relogg. 

More importantly, the function itself does not work at all, even if you see it ticked on. Furthermore your XP bar value may show no change, but once you relogg the XP you gained with Disable XP on is now added.

To Reproduce

1. Go to Preferences > Tick Disable all XP gains
2. Kill a mob for XP
3. See your XP bar increase. If not relog and see the updated XP.

Expected behavior

With Disable all XP gains on, no XP should be gained. Your preference for the setting (on/off) should also be saved, and not
revert on relogging.

**Comment by prkdrake** [comment]
This feature will be implemented as of the next update.

**Comment by RaggyLP** [comment]
Confirmed. XP is now disabled via the checkbox in the F10 settings menu and retains the tick across zoning. However, XP gained is not sent to the players xppool value, like it is on live. This includes any XP gained from quest rewards.

**Comment by prkdrake** [comment]
XP gains should be going into the pool

**Comment by RaggyLP** [comment]
Indeed, they are. Using `.get xppool` before and after a kill confirms this. Just missing the messaging to confirm that this process is occurring.

**Comment by RaggyLP** [comment]
![image](https://github.com/user-attachments/assets/ecc95435-8642-4be1-bf34-bfbe5dcdde96)

Confirmed, Disable XP Gains is now working excatly as expected. Great job! Closing as fixed as of 25/08/2024.
