### ISSUE TITLE
Tir County devoid of mobs

### ISSUE THREAD

**Issue by Dezzyx** [project-rubika/issues#790]
### Reproduction steps

```bash
1. Go to Tir County
2. Look around for mobs
```

### Expected results

```bash
To see mobs populate the area
```

### Actual results

```bash
It was empty, no mobs
```

### Bug prevalence

Every time I login

### Description

```bash
I was doing Clan start-up quests, on my way to Sam Chin
```

### Report link

https://pastebin.com/84awyE2J

**Comment by 3F1-1009** [comment]
Confirmed. Tir County doesn't have random spawns. Some guards and such are around.

**Comment by Dezzyx** [comment]
seems to have mobs now, closing
