### ISSUE TITLE
Tirbo Ratcatcher Is Very Generous

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#791]
### Reproduction steps

```bash
1. Talk to Tirbo `.tp 326.7 358.5 y 0.6 545`
2. Choose [2228] 'Sure, I can help you.'
3. With (BGTR) in the quest log, choose [2230] 'I'm already looking' > [2231] 'Yes.'
4. Give  him a rollerat tail `.item 165274 165274 1` 
5. LOOT EXPLOSION
```

### Expected results

```bash
Tirbo should generously give you a single piece of armour instead of his whole repository.
```

### Actual results

```bash
My inventory gets carpet bombed with armour.
```

### Bug prevalence

Every time.

### Description

```bash
Further to this, Tirbo will not accept any more Rollerrat tails once you have caused this issue.
```

### Report link

https://pastebin.com/XWS3yarf

**Comment by prkdrake** [comment]
Should be fixed with the latest update.

**Comment by RaggyLP** [comment]
Tirbo is now only giving one piece of amrour as expected, however, once the quest is completed, he will no longer accept other tails, nor give the quest again ):

**Comment by prkdrake** [comment]
Should be fixed with latest version

**Comment by RaggyLP** [comment]
Confirmed! Tirbo is now working exactly as expected! Closing as fixed as of 25/08/2024.
