### ISSUE TITLE
NPCs spawning in weird positions / places

### ISSUE THREAD

**Issue by Dezzyx** [project-rubika/issues#792]
Describe the bug

NPC moved to a weird position, as seen on the screenshot below. I've just seen this one, but Raggy confirmed it seems
to happen to several NPCs.

To Reproduce

1. Go to Sam Chin in Tir County
2. Notice her weird position

Expected behavior

For the NPC to be in their usual, correct position.

Screenshots

![Screenshot 2024-08-24 233242](https://github.com/user-attachments/assets/f1977657-4285-4c62-83bc-adcb66f7fc65)

**Comment by prkdrake** [comment]
Should be mostly fixed now!

**Comment by RaggyLP** [comment]
Confirmed, the previously floaty NPCs are now back to the ground. Closing as fix as of 25/08/2024.
