### ISSUE TITLE
Drake Rodriguez & Brandon Thorn gives duplicate starter items. 

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#796]
### Reproduction steps

```bash
1. Make a fresh char.
2. Talk to Drake (766) `.tp 415.4 352.6 y 76.7 4313`
3. Get double of everything, including, the XP reward.

[DBG] Executing spawn (H38F, 10, m, q, 6)
[DBG] Executing spawn (EXPP, 1, m)
[DBG] Executing spawn (NQ07, 1, m)
[DBG] Executing spawn (SHST, 1, m)
```

### Expected results

```bash
Drake should only supply you with 1 of each item.
```

### Actual results

```bash
You get duplicates, and some messages stating duplicate uniques.
```

### Bug prevalence

Every time.

### Description

```bash
N/A
```

### Report link

https://pastebin.com/tUUt5RRY

**Comment by Starbouy138** [comment]
I have tested this with each of the following toons at ICC Shuttle Port;
--First attempt-Male Solitus Agent doesn't have any issue of duplication.
-Second attempt-Female Solitus Agent gets Duplicate Solar Powered Rifle
-Third attempt-Male Solitus Agent gets Duplicate Solar Powered Rifle
Random results

--First attempt-Female Opifex Adventurer Started with 4 Pistols and Two Swords, then talking to Brandon Thorn gave two more pistols and another sword.
-Second attempt-Female Opifex Adventurer Started with 4 Pistols and Two Swords, then talking to Brandon Thorn gave two more pistols and another sword.
-Third attempt-Female Opifex Adventurer Started with 4 Pistols and Two Swords, then talking to Brandon Thorn gave two more pistols and another sword. This time I "Used the Adventurer: Startup Crystal - Quick Heal" and it added another one with the 2 pistols and sword upon talking to Thorn.
Semi Random with the nanocrystal.

--First attempt-Male Nanomage Meta-Physicist I deleted the Startup First-Aid Kit and Used the Lesser Anger Manifestation, Talking to Brandon Thorn then Duplicated the Meta Shield, and replaced the Startup First-Aid Kit and the Lesser Anger Manifestation Nano. I deleted the Startup First-Aid Kit and Used the Lesser Anger Manifestation, Talking to Brandon Thorn then Duplicated the Meta Shield, and replaced the Startup First-Aid Kit and the Lesser Anger Manifestation Nano.
-Second attempt-Female Nanomage Meta-Physicist I used and deleted nothing, and nothing was duplicated or replaced when talking to Brandon Thorn, it acted as it should this time.
-Third attempt-Male Nanomage Meta-Physicist I used and deleted nothing, and this time the Meta Shield was duplicated.
Random Results

--First attempt Atrox Engineer I used and deleted nothing and the Pistol was duplicated.
-Second attempt Atrox Engineer I used the Swift Weapon Starter Nanocrystal and client crashed (Probably Unrelated), logged back in and deleted Startup Treatment Laboratory, Nanocrystal was replaced, Startup Treatment Laboratory was not replaced, and Solar Powered Pistol was duplicated.
-Third attempt Atrox Engineer I deleted everything from my startup inventory and spoke to Brandon Thorn, speaking to him replaced the Swift Weapon Nanocrystal, the Startup Treatment Laboratory, and the Engineer Automaton Shell, but no Solar Powered Pistol at all.
Random results

**Comment by prkdrake** [comment]
The reason for this is that we used to spawn players in Newland City without any way of getting starter gear, but now that new players start in ICC Shuttleport, I suppose we no longer need to.

**Comment by prkdrake** [comment]
This should be fixed with the latest update.

**Comment by kajoriEU** [comment]
This is fixed as of 15/09/2024 👍
