### ISSUE TITLE
The Brink mission has no description. [SL Start]

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#803]
### Reproduction steps

```bash
1. Talk to Drake (766) and choose [3876] > [3878] > [3899]
2. The quest The Brink (JKUI) will be added, but the description in the mission window only shows [Intro]
```

### Expected results

```bash
The mission should have a correct title and description displayed.
```

### Actual results

```bash
The title and description only display [Intro].
```

### Bug prevalence

Every time.

### Description

```bash
N/A
```

### Report link

N/A

**Comment by prkdrake** [comment]
I believe this should now be fixed.

**Comment by RaggyLP** [comment]
![image](https://github.com/user-attachments/assets/ffaa6a5d-c1f8-427e-90ef-a47f70ba9b6f)
Looks to be the case! Closing as fixed asof 04/09/2024.
