### ISSUE TITLE
'Find a Vagabond Cloak' does not display in the mission window.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#807]
### Reproduction steps

```bash
1. Talk to Graham Simmonds (1019)
2. Choose [7738] and hand him 1 Cred.
3. Choose [7742] -> [7744]
4. Quest 'Find a Vagabond Cloak' (Z62S) is added to the character, but not displayed on the client, confirm with .quests.
```

### Expected results

```bash
The quest should be visible in the mission window.
```

### Actual results

```bash
It is not visible.
```

### Bug prevalence

Every time.

### Description

```bash
N/A
```

### Report link

N/A

**Comment by Dezzyx** [comment]
can confirm, I did this the other day and was wondering why it didn't display as a quest in the window, (I figured maybe some NPCs told you to go get something without actually giving you a quest for it, as other quests did show in window, so i didnt think more of it)

**Comment by prkdrake** [comment]
This should be fixed by the latest update.

**Comment by kajoriEU** [comment]
Confirmed.

Quest now displays in mission window correctly.

![{CC2A6FDE-F8FE-47B6-A896-E9F00B0D26F6}](https://github.com/user-attachments/assets/6f8cb322-ea08-4959-9a08-2e1c739fe041)
