### ISSUE TITLE
Some Subway vendors have invalid heading angle on their spawn points

### ISSUE THREAD

**Issue by prkdrake** [project-rubika/issues#815]
**Describe the bug**

Two vendors in the Subway are spawning facing towards the wall, rather than out over their counters. This data comes from the spawn point angle in the RDB. [Originally reported as a comment](https://github.com/project-rubika/issues/issues/808#issuecomment-2313536052) on #808, but I have split it out into a new ticket.

**To Reproduce**

1. Teleport into the Subway mall - `.tp 226.7 303.0 y 107.6 127` 
2. Look at the Basic Quality Pharmacist and the Basic Quality Weaponsdealer
3. Notice they are facing the wrong direction.

**Expected behavior**

The vendors should be facing away from the wall, rather than towards the wall.

**Screenshots**

![image](https://github.com/user-attachments/assets/46b8c86c-e21e-404e-af25-cafb88e07481)

![image](https://github.com/user-attachments/assets/392e419d-e2b3-4718-8126-032aea897166)

**Comment by RaggyLP** [comment]
Hermit, used for the MA Books from ToTw/IS also spawn on a True North 0 degree facing.

`.tp 823.0 2302.0 y 12.8 647`

**Comment by 3F1-1009** [comment]
This should be fixed now.

**Comment by kajoriEU** [comment]
Subway vendors are fixed and so is Hermit.

![{6DDE6A37-2510-44A4-840A-0D971C0DEDF2}](https://github.com/user-attachments/assets/a615ee15-ad54-41ec-8631-5b6454b4eba1)

![{6258E2B2-9EEB-4DE6-85D8-73715A1FEC3E}](https://github.com/user-attachments/assets/28af4bb9-076b-4ba2-8877-bb56889df37a)

![{E35292DB-D2E7-4A1A-9077-ED9D0B2D1653}](https://github.com/user-attachments/assets/aba5e711-7236-40a5-8e77-930f606250eb)
