### ISSUE TITLE
Changing game account user's password has no effect. Server expects old password.

### ISSUE THREAD

**Issue by ali-gk-sdi** [project-rubika/issues#816]
**Describe the bug**
Changing password does not work for game account username.
I created fresh GAME ACCOUNT username. I was able to login and perform normally. The next day, I forgot my password so I changed it from the https://site.project-rk.com/gameaccounts page . New password did not work. I created 2 more users and realized that the system only expects the original password even though I had changed the password

**To Reproduce**
1. Go to https://site.project-rk.com/gameaccounts
2. Create a new Game account and set any password e.g. "ALPHA" without quotes
3. Log into the game using the username and ALPHA password. Should work.
4. Go to https://site.project-rk.com/gameaccounts
5. Change password to "ALPHA123"
6. Log into the game using the username and ALPHA123 password. FAILS TO LOGIN
7. Log into the game using the username and ALPHA password. Logs in but this is wrong. Should have logged in using ALPHA123

**Expected behavior**
If the password is changed, new password should be accepted and previous password should not be effective. This is a security issue. The sooner this is fixed, the sooner goblins like me should be able to play.

**Screenshots**
N/A

**Character info:**
N/A

**Comment by prkdrake** [comment]
Should be fixed with latest update.

**Comment by bgf122** [comment]
I have changed my game account password and it is working as intended

**Comment by prkdrake** [comment]
Awesome, thank you for letting us know! :)
