### ISSUE TITLE
Mobs can resist procs from perks and single portions of nano programs.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#826]
**Describe the bug**
Mobs can currently resist perk-based weapon procs such as Accumulator and the damage portion of nano programs *after* the nano has actively landed on the target. Procs are not something that can be actively resisted and nano-programs, once landed and passed the initial NR check, shouldn't have their damage portions rolled again.

**To Reproduce**
1. For perks: Get a Trader and put points into Accumulator
2. Keep firing/hitting a target. 
3. You will eventually see 'Target Resisted', indicating that the proc has been stopped.
-
1. For nanos: Use a Trader again, spam a 'Funnel' type nano drain on a target.
2. It will land and at some point, the nano will land, the damage portion wont fire and you will see a 'Target Resisted' message.

**Expected behavior**
Procs should not be resistable & Nanos should not be subject to a second NR roll after the inital landing of the nano has been determined.

**Comment by prkdrake** [comment]
Should be fixed with the latest update.

**Comment by RaggyLP** [comment]
Confirmed solved. NR appears to now be working correctly on enemy targets. Closing as fixed as of 04/09/2024.
