### ISSUE TITLE
Roaming mobs at Borealis Subway go through closed doors and their pathing is messed up

### ISSUE THREAD

**Issue by StormlashTV** [project-rubika/issues#828]
### Reproduction steps

```bash
1. Go to Borealis Subway
2. Get to the first big room and take a left
3. Stand between the first two rooms, next to the pillars, and see what some of them do
```

### Expected results

```bash
I wasn't expecting they could go through closed doors or stand in place doing a walk animation
```

### Actual results

```bash
Some of them went through closed doors and their pathing is messed up
```

### Bug prevalence

Every time

### Description

```bash
Extended location information:
- 149.0, 274.5, 107.6 (149.0 274.5 y 107.6 127)
- Pf Proxy: Model=51100:127 GS=0 SG=0 R=127, resource: 127
- zone: 4, area: "Abandoned Mall", room: "Double door Mini"
Server id: 2252, character id: 50000:2252, time: 2024-09-01 09:54:35 (UTC)
Version: 00.6.3_EP1, map id: NOT FOUND, build: 52606.


Something is going on in these 2 rooms (1 Disobedient Bot, 1 Violent Vagabond, 2 Muggers and 1 Discarded Pet are acting strange)
```

### Report link

https://pastebin.com/dyzB0dXb

**Comment by prkdrake** [comment]
Appears to be two issues: 

1. Mobs are going through closed doors
2. Mobs are pathing incorrectly

Neither report is particularly useful though, so this is a candidate for refinement.

**Comment by kajoriEU** [comment]
I'm unable to identify any issues at the moment, and there seems to be missing information for both problems. Since this issue has been open for 30 days without any reply, I'm closing it for now. Please feel free to reopen it or create a new issue with more detailed information if the problem persists.
