### ISSUE TITLE
XYZ of Flaming Barrels has no shop inventory.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#834]
**Describe the bug**
In both the Thrak and Aban gardens (Nasc), the Or-Mada (OOOA) and Craig-or of Flaming Barrels (CIOA) currently have no shop inventory at all.

Aban `.tp 413.9 431.5 y 110.1 4676`
Thrak `.tp 485.0 310.0 y 33.1 4677`

**To Reproduce**
1. Go to Gardens of Aban/Thrak
2. Talk to the XYZ of Flaming Barrels and choose to shop.
3. Notice lack of options.

**Expected behavior**
Both NPCs should be selling a variety of ranged weapons.

**Screenshots**
![image](https://github.com/user-attachments/assets/13f6eabe-ce78-4747-8953-5e3f1631fdd6)

**Comment by prkdrake** [comment]
Should be fixed with the latest update.

**Comment by kajoriEU** [comment]
Confirmed 👍 

XYZ of Flaming Barrels finally sells the good stuff.


![{E10A84D7-71A9-4E70-B8AF-84826710E0FA}](https://github.com/user-attachments/assets/df8530c2-954a-4cdd-81cc-569e1c04df59)

### Fixed as of 15/09/2024
