### ISSUE TITLE
Deliver a Bronto Burger to Mr. Blake in Rome Blue Quest Description Incorrect.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#836]
**Describe the bug**
OT Bronto Chef (1050) gives the quest (WCEZ) after being given the 5 Chirop Eggs and you choose the convo option [8273]. The quest it self has no information on the descripton.

**To Reproduce**
1. `.quests add WCEZ`
2. Look at Mission window.

**Expected behavior**
Quest information should be present.

**Screenshots**
![image](https://github.com/user-attachments/assets/186c4b28-69a7-4295-98e6-c3d7ca6939e9)

**Comment by prkdrake** [comment]
Looks like an ACG quest text template, interesting

**Comment by prkdrake** [comment]
Yeah, it’s probably just an automatic text replacement thing that works either for ACG or even static quests.

**Comment by prkdrake** [comment]
Should be fixed with the latest update.

**Comment by RaggyLP** [comment]
![image](https://github.com/user-attachments/assets/3f36ee48-5db5-4614-95fc-2ed56bbef371)

Confirmed, Mr. Blake will no longer want for tasty Bronto Burgers. Closing as fixed as of 04/09/2024.
