### ISSUE TITLE
Coil of Nano / Health energy not working

### ISSUE THREAD

**Issue by loysaranne** [project-rubika/issues#837]
### Reproduction steps

```bash
1. Use Coil of Nano / Health Energy (QL 10)
2. Buff gets applied and is repeated, but won't give nano / health
```

### Expected results

```bash
Expect to get nano / health from the buff
```

### Actual results

```bash
Buff gets applied, but no nano / health
```

### Bug prevalence

Everytime I tried it

### Description

```bash
Coils of nano and health not working as they should
```

### Report link

https://pastebin.com/cc6yLwtg

**Comment by loysaranne** [comment]
After you change zone, you get the used items back as well

**Comment by kajoriEU** [comment]
Coil of Health's are working as expected again.

Closing this as fixed as of 20/09/2024


https://github.com/user-attachments/assets/53e4b2f8-d8ba-48dd-8f60-798fcf71c089
