### ISSUE TITLE
You can resist Energize perk every now and then

### ISSUE THREAD

**Issue by loysaranne** [project-rubika/issues#839]
### Reproduction steps

```bash
1. Get the perk Power Up 1
2. Use Energize skill
3. There is a chance that you resist the buff on yourself
```

### Expected results

```bash
Should get Energize buff applied 100% of the time.
```

### Actual results

```bash
Every now and then you resist the buff.
```

### Bug prevalence

About 10% chance to happen

### Description

```bash
Using the skill during combat. I have spare NCU left (it's 0 NCU buff though).
```

### Report link

https://pastebin.com/E31Y1y2k

**Comment by RaggyLP** [comment]
Confirmed. This appears to be *any* friendly nano program currently. Managed to do it with a med kit!

Also:

![image](https://github.com/user-attachments/assets/dfd057b6-65df-4b18-a2af-5ac87a26105a)

**Comment by prkdrake** [comment]
Should be fixed with the latest update.

**Comment by RaggyLP** [comment]
Been playing a lot and not seen and resists on friendly nanos so far. Closing this one as fixed as of 07/09/2024.
