### ISSUE TITLE
Garden save spot doesnt indicate anything when saving at garden

### ISSUE THREAD

**Issue by bgf122** [project-rubika/issues#840]
### Reproduction steps

```bash
1.Try to save at garden 
2.Get no output/visual
3.Die
4.Respawn at garden
```

### Expected results

```bash
Not respawn at garden
```

### Actual results

```bash
respawned at garden
```

### Bug prevalence

Id assume every time I try to save

### Description

```bash
Died in subway, respawned at garden of thrak
```

### Report link

https://pastebin.com/h2jZfTEH

**Comment by RaggyLP** [comment]
Confirmed. The expected 'Saved XP' message along with SL's unique Stun/animation cast for Garden Save Points are missing, however, the players save location *is* updated one running through the terminal.

**Comment by kajoriEU** [comment]
This issue has been resolved. Garden save spots now provide the expected visual and text feedback when saving. 


https://github.com/user-attachments/assets/83857971-7e09-48bc-a873-419adf0bae74
