### ISSUE TITLE
On self cast nanos require self targeting

### ISSUE THREAD

**Issue by bgf122** [project-rubika/issues#843]
### Reproduction steps

```bash
1.try to cast any nano that is only self castable
```

### Expected results

```bash
nano would cast
```

### Actual results

```bash
Your target can't be attacked.
```

### Bug prevalence

every time

### Description

```bash
´.
```

### Report link

https://pastebin.com/MgNCCpUb

**Comment by prkdrake** [comment]
Duplicate of #459
