### ISSUE TITLE
Attack Rating is currently working on breakpoints and not updating in a linear fashion.

### ISSUE THREAD

**Issue by StormlashTV** [project-rubika/issues#848]
### Reproduction steps

```bash
1. Go to Foremans/Biomare dungeon
2. Fight a Chief Base Protector
3. Once he casts Mighty Challenger to Cyclops, his damage goes off the roof and does not reflect the actual modifiers that the Nano Program gives
```

### Expected results

```bash
I expected a flat +20 damage increase, not a x2.5 multiplier
```

### Actual results

```bash
He got a x2.5 damage multiplier.
Base hits were about 63 points of damage
Buffed went to 146
```

### Bug prevalence

Often

### Description

```bash
Chief Base Protector gets insane amounts of damage upon casting a Challenger Nano program
```

### Report link

N/A

**Comment by RaggyLP** [comment]
Further testing has revealed that this is tied to AR as a whole. 399 AR on the mob does nothing, but the moment the mob hits 400 AR (or 800), the damage effectively doubles, suggesting it swaps to a new template.

**Comment by prkdrake** [comment]
Should be fixed with the latest update.

**Comment by RaggyLP** [comment]
Following a few days of tweaking and alterations, I think we've hit upon a very good state with this now. Closing as fixed for the moment. 07/09/2024.
