### ISSUE TITLE
Mezzes immediately fall off the target.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#852]
**Describe the bug**
Casting a mezz on a target causes the Mezz to last maybe 1-2s before it disappears out of the targets NCU and makes them hostile again.

**To Reproduce**
1. Find a mob to mezz.
2. Ensure you have Nano Target NCU visible.
3. Cast a mezz.  `.ncu run 2520571`
4. Notice how the mezz sits in the NCU for a max of 2s before falling off.

**Expected behavior**
A mezz should place the target into a passive state for the duration of the nano.

**Screenshots**
![image](https://github.com/user-attachments/assets/1c0af0c2-a457-4a60-9008-d93ebdf9532a)
![image](https://github.com/user-attachments/assets/1e77c16a-1156-4a19-9324-3ac1879e3c3d)

**Comment by kajoriEU** [comment]
Very happy to report that this is fixed with the latest updates now :)


https://github.com/user-attachments/assets/6bff15e1-87da-48e6-b181-6dd03084e2c0
