### ISSUE TITLE
Trader's Accumulator Proc doesn't give Nano.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#854]
### Reproduction steps

```bash
1. Make a Trader with Accumulator perked.
2. Attack a target until the perk procs.
3. Notice that the Damage and Health portion fire, but the nano portion, does not.
```

### Expected results

```bash
When Accumulator hits a target, it is supposed to drain a portion of the targets Health and Nano.
```

### Actual results

```bash
Currently, only the Damage and Health portion are working.
```

### Bug prevalence

Every time.

### Description

```bash
N/A
```

### Report link

https://pastebin.com/hrimrJRE

**Comment by prkdrake** [comment]
Should now be fixed, please let me know

**Comment by RaggyLP** [comment]
Confirmed, Accumulator is now draining nano as expected and both components are resorted as such. Great stuff :). Closing as fixed as of 10/09/2024.
