### ISSUE TITLE
/pet guard causes a HP discrepancy between owner and pet.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#855]
**Describe the bug**
This is most easily noticed on an Engineer, can be semi-repro'd on an MP and Crat appears unaffected.

When using /pet guard on an Engineer and then attacking a target, your pet will move to the target and begin attacking. However, despite the pet being highest on the hate list of the target, the NPC will *visually* continue to attack you on the client. However, it seems, that the NPC itself actively swaps to the pet as the primary target serverside. This results in a few htings happening. The pet will take continuous 'unknow damage' equal to the damage that *you* take and any damage *you* take, will be removed from your HP bar as expected, however, you cannot 'die'. This is because on the server, you are actually not being attacked at all, but the client thinks you are. This suggests a disconnect between the update packets being sent to the client in this situation, resulting in damage being misattributed on the client.

**To Reproduce**
1. Create an Engi and spawn a pet. `.ncu run 45722`
2. `/pet guard`
3. Attack a target.
4. Your pet will go to the target and attack it, but the NPC will continue to attack you for the lifetime of this situation.
5. Eventually, you will hit 0 life, but will remain alive, during this time, you will see your pet take 'Unknown' damage, periodically.
6. Using the `.hate` command, you can see that the primary target, should be the pet. However, this is not reflected to the client.

**Expected behavior**
When the pet becomes the primary target, the client should be updated to reflect this change.

**Screenshots**
![image](https://github.com/user-attachments/assets/719eefb4-2c0d-4715-83fe-97b11394250c)

https://cdn.discordapp.com/attachments/596438197647704070/1281750093518737511/ao3.mp4?ex=66dd830c&is=66dc318c&hm=5d2b1824aa203b5b24fbfb463c628719c7e59a681eb21b3709cb9914e53f884c&

https://cdn.discordapp.com/attachments/596438197647704070/1281743702162669628/AO2.mp4?ex=66dd7d18&is=66dc2b98&hm=86cb658ec00bef44a28bc5c942b512650e31f8dddad31bcf060c9324b322fea9&

![image](https://github.com/user-attachments/assets/d44ec134-7ad9-42ed-b28e-55668471da87)
![image](https://github.com/user-attachments/assets/bc843113-2e42-4acf-acd3-184c02a27e4d)
![image](https://github.com/user-attachments/assets/1a20b32a-f798-4930-a47f-12a8e290749d)

**Comment by portalerprk** [comment]
Def related to jumbled targeting with pet combat behaviors.

**Comment by RaggyLP** [comment]
Tested and confirmed solved. Closing as fixed as of 15/09/2024.
