### ISSUE TITLE
Dyna bosses have excessive Health

### ISSUE THREAD

**Issue by loysaranne** [project-rubika/issues#858]
### Reproduction steps

```bash
1. Find dyna boss
2. Look at it's health bar
3. .get health
```

### Expected results

```bash
Should give reasonable HP value for the level of the mob
```

### Actual results

```bash
Gives 500k HP for lvl 60ish dyna bosses.
```

### Bug prevalence

All the time

### Description

```bash
Dyna bosses are undoable for their current level right now.
```

### Report link

https://pastebin.com/sYvTVZDK

**Comment by kajoriEU** [comment]
Confirmed. Health might be a little bit much currently.  

Example for a low-level dyna `.tp 2328.1 1046.3 y 32.0 565`

Miss Coyma the Grassland Runner
Level: 25

.get succeeded - Miss Coyma the Grassland Runner health is 542086 (542086 base + 0 mod + 0 trickle + 0 custom)

**Comment by kajoriEU** [comment]
I tested 18 backyard Dynas and an additional 10 (low and highlevel), and none of them had signs of excessive HP. This issue appears to be resolved as of 11/09/2024 .👍
