### ISSUE TITLE
RK Vendors wont open trade

### ISSUE THREAD

**Issue by kajoriEU** [project-rubika/issues#860]
### Reproduction steps

```bash
1. Walk into the subway of your choice.
2. Go to vendors
3. Right/Left Click or 'Use' (E)
```

### Expected results

```bash
It should open a trade (like it did just a few days ago.)
```

### Actual results

```bash
It does nothing anymore.
```

### Bug prevalence

Everytime

### Description

```bash
borked lol :(

also no error message in chat or anything.
```

### Report link

https://pastebin.com/9puMnws6

**Comment by Dezzyx** [comment]
This applies to more than Subway vendors. Last night I tried OT bartenders and they did nothing, as well as some vendors in Tir and also vendors at Inventor Bobic Outpost in Tir County.

**Comment by kajoriEU** [comment]
SL vendors work as expected. 

All of the RK vendors I checked (Subway vendors, Newland barkeepers, FT barkeepers) did not and trying to trade with them results in the trade-window not opening.

**Comment by kajoriEU** [comment]
This seems to be working correctly again.

Marking as fixed and closing 👍
