### ISSUE TITLE
Battle Prepared Nano Recharge Kit is regaining its charges once you change zones and it doesnt consume charges while in combat

### ISSUE THREAD

**Issue by StormlashTV** [project-rubika/issues#863]
### Reproduction steps

```bash
1. Out of combat, sit down and use it
2. Change zones
3. You should get its charges back
4. In combat, sit down and use it
5. No charges are consumed
```

### Expected results

```bash
Charges should be consumed upon use, both in and out of combat
```

### Actual results

```bash
Charges are regained when you change zones
Charges are not being consumed while in combat
```

### Bug prevalence

Every time

### Description

```bash
Tested inside ToTW and outside of it with a .item 204267 204267 20


### Report link

https://pastebin.com/L7tv14jb

**Comment by portalerprk** [comment]
When you report a bug that involves a specific item(s) try and include an `.item <low id> <high id> <ql>` command in the description.. It helps save time when troubleshooting.

**Comment by kajoriEU** [comment]
I can not reproduce this. If you stand up too quickly after using it (and before the item is actually being used) and the item lock timer starts it will visually not use any charges but the item count is immediately corrected on zoning - in fight and out of fight

**In-fight, standing up before itemlock starts**


https://github.com/user-attachments/assets/7f289b49-a216-413c-9123-47d83da911f7



**Out-of-fight, standing up before itemlock starts**


https://github.com/user-attachments/assets/f65e4284-91bf-407d-ac34-a46781684dfd



If you stay seated for the entire duration until the itemlock timer starts, the charges are being used correctly and nothing changes on zoning, as expected.

**In-fight, standing up after itemlock starts**

https://github.com/user-attachments/assets/611eb587-216f-429f-9d5c-fed60c943c2a

**Out-of-fight, standing up before itemlock starts**

https://github.com/user-attachments/assets/b330ca30-8d2c-42bb-9899-96491bd835af
