### ISSUE TITLE
You are able to buy multiple of Unique items from Vendors

### ISSUE THREAD

**Issue by loysaranne** [project-rubika/issues#864]
### Reproduction steps

```bash
1. Go to Antonio in newb island - 932.9, 873.8, 47.0 (932.9 873.8 y 47.0 4582)
2. Open shop
3. Click Adaptation factory multiple times
4. Click Accept
5. Open inventory to check you have multiple Adaptation Factories
```

### Expected results

```bash
Should be able to buy only one at a time
```

### Actual results

```bash
Able to buy multiple unique items at once
```

### Bug prevalence

Everytime

### Description

```bash
This seems to affect all unique items that are buyable from a vendor. You are able to buy multiple copies of a unique item. Client shows only one in the buy menu, but when accepting the trade you end up with multiple copies of it. Server doesn't realize it is unique?
If you already have that particular unique item in your inventory, you are not able to buy it.
```

### Report link

https://pastebin.com/qzsmmSMe

**Comment by kajoriEU** [comment]
Could reproduce, this works on every vendor and shop.

![{DA230344-5ABB-4A4C-8CD2-807E9CD7EE31}](https://github.com/user-attachments/assets/8fc6f0ec-1ce2-4615-80d0-6d6fbbee0962)

![{2DDEF7D3-BF96-4EDD-9233-7548D9FCCCD3}](https://github.com/user-attachments/assets/74f7c3fd-43a0-4862-aa19-34be1cd9d5ed)

**Comment by kajoriEU** [comment]
Can not reproduce anymore. This is fixed as of 11/09/2024 👍
