### ISSUE TITLE
Character Animations Interrupted by Stat Update Events

### ISSUE THREAD

**Issue by StormlashTV** [project-rubika/issues#869]
**Describe the bug**
 - Animations sometimes get canceled mid-execution (combat animations, out-of-combat animations, nano programming casting, sitting down and getting up, using Treatment Laboratory or Basic Nano Recharger, etc)

**To Reproduce**
 - Steps to reproduce the behavior:
1. Get into combat
2. Cast some Nanos Programs
3. Sit down/Get up
4. Heal yourself

**Expected behavior**

 - Animations should be fluid from start to finish, without any mid-execution cancelation (unless you stop them yourself)

**Screenshots**

https://github.com/user-attachments/assets/263fb58b-ee30-4af5-82c0-75867760ba90

https://github.com/user-attachments/assets/0d1070f5-8485-4e54-9bf5-539a15705e9c

https://github.com/user-attachments/assets/5cb07296-0570-4684-86d0-16a679bef6b7

https://github.com/user-attachments/assets/f645cf08-908c-4613-b944-4132545ba31c

**Copy/paste the output of Shift+F9 here**
 - Extended location information:
- 60.6, 41.6, 19.8 (60.6 41.6 y 19.8 1941)
- Pf Proxy: Model=51100:1941 GS=0 SG=0 R=1941, resource: 1941
- zone: 33, area: "Area"
Server id: 2252, character id: 50000:2252, time: 2024-09-09 12:43:29 (UTC)
Version: 00.6.5_EP1, map id: NOT FOUND, build: 52606.

----

**Comment by kajoriEU** [comment]
This is fixed as of 12/09/2024. 👍

**Comment by kajoriEU** [comment]
This is fixed as of 12/09/2024. 👍
