### ISSUE TITLE
Nano Recharger Fills Nano but Client wont show correct amount

### ISSUE THREAD

**Issue by loysaranne** [project-rubika/issues#870]
**Describe the bug**
At the moment Client doesn't visually show Nano gotten from Nano Recharger right away. This means that if you use Nano Recharger and try to cast a nano that exceeds the nano you visually have, you can not cast it, while in truth you should have enough Nano on the server side.

**To Reproduce**
1. Set your Nano to 0
2. Use Nano Recharger
3. Try to cast a Nano that exceeds your current Nano amount

**Expected behavior**
It should cast the Nano as you actually have enough Nano, but the client doesn't visually show it.

**What actually happens**
Client tells you that you don't have enough Nano and won't cast it.

**Comment by kajoriEU** [comment]
Confirmed. The client currently doesn't update after using any form of nano healing. **However**, currentnano on the clientside refreshes with Nanodelta ticks or after zoning/relogging.

https://github.com/user-attachments/assets/d1eaad1c-2a2e-47d3-840e-d6bac6545b9e

**Comment by RaggyLP** [comment]
Confirmed solved. Closing as fixed as of 12/06/2024.
