### ISSUE TITLE
Cycling Combat (Q > Q) resets AbsorbTypeAC values to their current maximums.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#873]
**Describe the bug**
When entering, exiting and re-entering combat, any absorbs such as AbsorbMeleeAC etc, are reset to their original values, based on any current running programs or modifiers. Through constantly spamming Q, a player could effectively never die.

**To Reproduce**
1. For ease of testing, creat an Adventurer.
2. Cast `.ncu run 161571`
3. Fight a mob, spam Q > Q to see the absorbs constantly refresh.

**Expected behavior**
Temporary Absorbs values should carry across fights and only 'cycle' when expected, either by player actions or nano effects.

**Comment by portalerprk** [comment]
I think this should be fixed .. the only thing that should "refresh" an absorb shield is reapplying the nano.. or zoning.

**Comment by RaggyLP** [comment]
The Q>Q Method is definitely fixed and it seems that the value is only updated as mentioned, cycling on the nano also works as expected. Clsoing as fixed as of 10/09/2024.
