### ISSUE TITLE
Cluster Bullets Fail to Inflict Damage on Targets

### ISSUE THREAD

**Issue by loysaranne** [project-rubika/issues#880]
### Reproduction steps

```bash
1. Get Cluster bullets as a fixer (.item 158951 158952 100)
2. Attack someone and use Cluster bullets
```

### Expected results

```bash
Target enemy should be hit for Chemical AC -50 .. -402
```

### Actual results

```bash
Nothing, enemy is not hit for anything
```

### Bug prevalence

Everytime

### Description

```bash
Nothing special
```

### Report link

https://pastebin.com/66Pk1bRf

**Comment by kajoriEU** [comment]
I can confirm this. Upon right-clicking Cluster Bullets the player gets damaged instead of the enemy.

You were attacked with nanobots for 6 points of melee damage.




https://github.com/user-attachments/assets/cef26207-b2b4-4cb3-bb5f-40a72d91cc05

**Comment by loysaranne** [comment]
Player is meant to be hit with nanobots when using cluster bullets
![image](https://github.com/user-attachments/assets/933ad784-c72f-465b-b317-3f185c43710f)

**Comment by kajoriEU** [comment]
Oof, thank you for correcting! You are absolutely right!

**Comment by kajoriEU** [comment]
#### Closing this as fixed as of 20/09/2024
