### ISSUE TITLE
Credits received from quest rewards do not update your total credits value until after relogg/zoning

### ISSUE THREAD

**Issue by Dezzyx** [project-rubika/issues#883]
Describe the bug

When turning in a quest that gives credits as part of the reward, player's credits do not display the updated and
correct value until after relogg/zoning. Has been tested with multiple quests over time.

To Reproduce

1. Accept a quest that gives credits as part of its reward
2. Complete and turn it in
3. See credits showing the same value as before turning in quest

Expected behavior

That my credits would update to the correct value with the received credits

Screenshots

https://github.com/user-attachments/assets/326d9e6e-770c-4255-98c7-fc6410896d50

https://github.com/user-attachments/assets/a1762332-58f1-4104-b837-6f66a20ab012

After relog: 
![Screenshot 2024-09-10 021059](https://github.com/user-attachments/assets/53d2d52c-39be-4917-8ae9-78d2962332be)

**Comment by kajoriEU** [comment]
I can confirm the issue as described. The credits are only displayed correctly after zoning or relogging.

**Comment by prkdrake** [comment]
This should be fixed with the latest update.

**Comment by kajoriEU** [comment]
The recent update has resolved this issue. 👍
