### ISSUE TITLE
Vanguards will not protect you when aggroed by mobs

### ISSUE THREAD

**Issue by SharpTony** [project-rubika/issues#889]
### Reproduction steps

```bash
1.  Go to OA
2.  Aggro a mob and bring it in front of the vanguards
3.  Watch them stay chillin
```

### Expected results

```bash
They should stop magdumping the attacking mobs
```

### Actual results

```bash
Nothing
```

### Bug prevalence

Every time

### Description

```bash
They seem to function fine with opposing faction players
```

### Report link

https://pastebin.com/0kUuqs9w

**Comment by kajoriEU** [comment]
variation of this issue #415

**Comment by RaggyLP** [comment]
![image](https://github.com/user-attachments/assets/8345601e-a87b-41df-b178-fce0b57ef336)

Confirmed solved. Closign as fixed as of 12/06/2024.
