### ISSUE TITLE
Itemspawner issues in Dyna Template Affecting Buffs and Drops

### ISSUE THREAD

**Issue by SharpTony** [project-rubika/issues#891]
### Reproduction steps

```bash
1.  Go to a clan backyard
2.  Kill the boss
3.  Observe 1 item in loot
```

### Expected results

```bash
Generally they will drop 5-7 items, similar to any other dyna on RK
```

### Actual results

```bash
They drop 1 item
```

### Bug prevalence

Every time

### Description

```bash
I also created a bug report about some bosses being overtuned, which is a problem
```

### Report link

yeet

**Comment by kajoriEU** [comment]
Heya, I can not reproduce this. 

![{B69A110E-0ACF-4DB7-96C3-B8CAE9AEE896}](https://github.com/user-attachments/assets/a9479867-a22f-4d9b-9fc1-07c28f9df480)

![{387F4332-493D-40A5-A109-B3ED419AF808}](https://github.com/user-attachments/assets/5626d855-6601-47f7-b908-40b56660e5f9)

![{D8FF2663-15B8-49B6-8CCB-06FC5CE28538}](https://github.com/user-attachments/assets/9eef4456-6f06-466f-be43-79a6cdf153aa)

**Comment by 3F1-1009** [comment]
Reason appears to be wrong interpolation of boss modifier items. Also causes #890

**Comment by kajoriEU** [comment]
This issue appears to be fixed. If you encounter this issue again, please feel free to reopen it.
