### ISSUE TITLE
Missions with countdown timer remain in mission window after expiration

### ISSUE THREAD

**Issue by Dezzyx** [project-rubika/issues#895]
### Reproduction steps

```bash
1. Accept a mission that has a time countdown on it
2. Let the time run out
3. Notice that the mission is still present in your missions window
```

### Expected results

```bash
I expected it to do as on Live, where a mission with a timer will vanish from your mission window once
the "Realtime left:" counter has reached zero.
```

### Actual results

```bash
The mission stayed in my mission window despite the timer having ran out
```

### Bug prevalence

I've noticed it a few times, with at least 2 quests, retested with the last quest to verify

### Description

```bash
I had just taken on a time sensitive mission from Mr. Blake but had to log off for the night. When I logged on the next day and the time to do the mission had long since past, the mission was still
in my mission window only with no countdown on it.
```

### Report link

https://pastebin.com/fKebT256

**Comment by kajoriEU** [comment]
Can confirm. Missions with a timer remain in mission window after expiration.

![{8CB07F1D-59B6-4844-B842-0D1C4DEE2B15}](https://github.com/user-attachments/assets/877e0b89-578c-432b-9944-748b019b074f)

**Comment by prkdrake** [comment]
This should be fixed with the latest update.

**Comment by kajoriEU** [comment]
With the latest update, the mission does now correctly disappear from your mission window once the timer runs out, as expected. 👍
