### ISSUE TITLE
Cannot use Fugus bag on mushrooms as part of Bluetooth Fungi Harvest. [Elysium Yutto Quest]

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#900]
### Reproduction steps

```bash
1. .quests add 3BZH & .item 259700 259700 1
2. .tp 681.3 2022.7 y 10.7 4543
3. Attempt to use the Fungus Sample Bag on the Mushroom

The Mushroom Fixture is https://site.project-rk.com/server/Ithaca/item/259760
```

### Expected results

```bash
Using the Bag on the Mushroom should generate item id 259760 in your inventory.
```

### Actual results

```bash
It's a mushroom.
You can't use this on the mushroom.
```

### Bug prevalence

Every time.

### Description

```bash
Is part of the Bluetooth fungi harvest quest.
```

### Report link

https://pastebin.com/BbksBmbE

**Comment by prkdrake** [comment]
This should be fixed with the latest update.

**Comment by RaggyLP** [comment]
https://cdn.discordapp.com/attachments/1199520766060920873/1284953601713901639/image.png?ex=66e881cb&is=66e7304b&hm=258b769fdab25f3c40193fc37bab84f2556e471698959de1eb8db705f6216495&

Confirmed. Closing as fixed as of 15/09/2024.
