### ISSUE TITLE
Unhandled command 'movenpc' on Assistant Brad Willis

### ISSUE THREAD

**Issue by kajoriEU** [project-rubika/issues#902]
**Describe the bug**

**To Reproduce**
1. Get quest `DXMP` (Test of Intelligence) from Scientist Drake Rodriguez `.tp 414.9 352.4 y 76.7 4313`
2. Go to Assistant Brad Willis `.tp 335.6 244.1 y 33.7 4313`
3. Dialog `[3881] > [3882]`
4. On his last dialogue line it shows 

> Assistant Brad Willis: Ok! Are you ready?
> Here goes...

before freezing the character (chat is unresponsive and so are almost all inputs)

on debug it does not do that but instantly despawns.

> Unhandled command - {movenpc 358 34 264}
> 
> [DBG] Executing delay (120)
> [DBG] Executing terminateself ()

**Expected behavior**
He should go ahead into the cave and attack/tank the Imp for you.

Extended location information:
- 335.6, 244.1, 33.7 (335.6 244.1 y 33.7 4313)
- Pf Proxy: Model=51100:4313 GS=0 SG=0 R=4313, resource: 4313
- zone: 128, area: "Nascense Training Grounds"
Server id: 1, character id: 50000:2478, time: 2024-09-11 20:10:59 (UTC)
Version: 00.6.5_EP1, map id: NOT FOUND, build: 52606.

**Comment by prkdrake** [comment]
This should be fixed in the latest update

**Comment by kajoriEU** [comment]
Happy to report that this is working as expected now! 👍 

![{FDD76A41-2252-4B74-ADD8-A9D0ADCF1372}](https://github.com/user-attachments/assets/bd0ac0f0-e5aa-4c91-a878-fe826931f9fc)
