### ISSUE TITLE
HP Bar is flickering every few seconds

### ISSUE THREAD

**Issue by StormlashTV** [project-rubika/issues#904]
**Describe the bug**
HP Bar is flickering every few seconds
It started happening after:

"Portaler — Today at 9:52 PM
Incoming Patch
Tweaked down global aggro range
Nps will now pause attacks while casting
Current nano/health should now immediately reflect on change
Vanguards should now defend clan players
Neutral guards should defend anyone under attack
Guards will only defend against NPC attacks (for now)
Fixed an issue where "Critical Hit Boss" modifiers would spam casting notifications
Current nano/health should now immediately reflect on change"

**To Reproduce**
1. Log in
2. Watch your HP Bar flicker every few seconds

**Expected behavior**
The HP bar shouldn't flicker like that for no apparent reason

**Screenshots**

https://github.com/user-attachments/assets/813935f5-96f8-4a96-94ab-b833f1a86cd8

https://github.com/user-attachments/assets/9d19e068-ebc2-47fd-9e01-e5077489e300

https://github.com/user-attachments/assets/adef413b-497c-45b6-b0df-1f53edf6ffe9

https://github.com/user-attachments/assets/9ce5da18-bfcf-41d1-a261-fb9acc27eba5

**Character info:**

```
Copy/paste the output of /getfull here
health 	3432

**Playfield info:**

```
Copy/paste the output of Shift+F9 here
Extended location information:
- 1508.9, 1275.3, 10.6 (1508.9 1275.3 y 10.6 600)
- Pf Proxy: Model=51100:600 GS=0 SG=0 R=600, resource: 600
- zone: 3602, area: "Central Rhinoman Village"
Server id: 2252, character id: 50000:2252, time: 2024-09-11 21:11:17 (UTC)
Version: 00.6.5_EP1, map id: NOT FOUND, build: 52606.

----

**Comment by RaggyLP** [comment]
This now appears to be solved. Closing as fixed as of 12/09/2024.
