### ISSUE TITLE
Sirocco - Unhandled exception when attempting to grant Team Fgrid mission.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#906]
**Describe the bug**
`[ERR] Unhandled exception in mission command handler ({mission GEIL}) - Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')`

Talking to Sirocco (74) and choosing [2096] > [2098] >[2100] > [2103] results in the above error.

**To Reproduce**
1. `.tp 283.0 210.0 y 8.0 540`
2. Give Sirocco your Membership Card `.item 162830 162830 1`
3. Follow the above conversation options.

**Expected behavior**
The mission GEIL should be given and placed in the players mission window.

**Comment by prkdrake** [comment]
This should be fixed with the latest update.

**Comment by kajoriEU** [comment]
This issue has been fixed and Sirocco now correctly gives `(GEIL) Give incomplete crystal to Cyborg Grid jumper.` on handing him the Membership Card and finishing the dialogue with him.

**Comment by kajoriEU** [comment]
This issue has been fixed and Sirocco now correctly gives `(GEIL) Give incomplete crystal to Cyborg Grid jumper.` on handing him the Membership Card and finishing the dialogue with him.
