### ISSUE TITLE
Talk to Scientist Donna Red / Veronica Escobar' Does Not Update

### ISSUE THREAD

**Issue by kajoriEU** [project-rubika/issues#909]
On the Jobe bridge, speak to the Emissary of Jobe (`.tp 854.0 1060.9 y 30.0 4310`) to receive two quests related to the beginning of the Garden Key Quests:

```bash
1. Quest 1 (5NU4): Talk to Scientist Donna Red (Clan and Neutral) (`.tp 986.8 1760.4 y 32.7 4310`)

2. Quest 2 (7K9Z): Talk to Scientist Veronica Escobar (Omni-Tek and Neutral) (`.tp 746.9 1878.1 y 31.2 4310`)
```

### Expected results

```bash
1. Talking to Scientist Donna Red should update to quest `(LK56)`.


2. Talking to Scientist Veronica Escobar should update to quest `(076S)`.
```

### Actual results

Neither quest (5NU4 or 7K9Z) progresses after speaking to the respective scientists. The quests cannot be completed.

### Description

Accepting the Aban/Thrak Key quests does not resolve the issue for these quests.

**Comment by prkdrake** [comment]
Should be fixed with the latest update.
