### ISSUE TITLE
Reconstruction perk not usable on pet when I'm attacking an enemy

### ISSUE THREAD

**Issue by Nephima** [project-rubika/issues#913]
### Reproduction steps

```bash
1. As engineer, spawn a bot pet and learn Gadgeteer 2 - Reconstruction perk.
2. Engage in fights to have pet less than full health.
3. Start a fight (doesn't matter if pet fights too or not)
4. While your characters is attacking, try to use perk Reconstruction on pet.
5. Then stop attacking and try to use that perk on pet again.
```

### Expected results

```bash
Reconstruction perk should work on engineer's pet whether pet owner is fighting or not.
```

### Actual results

```bash
Perk currently does NOT work if I am attacking. I receive below messages in chat:

Your no LDBintern (2002:4) is required to be at least 7!
Your %s is required to be at least %d!
Your Monster Type is required to be at least 95!
Your %s is required to be at least %d!
Could not use perk because you do not meet the requirements.
```

### Bug prevalence

Every time.

### Description

```bash
It was introduced with some recent patch, probably connected with recent change to perk target requirement changes?
```

### Report link

https://pastebin.com/FhgmAPN6

**Comment by kajoriEU** [comment]
Confirmed. 👍 

https://github.com/user-attachments/assets/c20620e4-e55d-4cff-b189-69f6b5f24e4c

**Comment by Nephima** [comment]
Confirmed the same scenario when trying to cast Monitor Combat Array (pet only buff) on my pet. But Partial Harmonic Cocoon does work while fighting. So it could hint at issue being limited to pet-only nanos and perks.

**Comment by RaggyLP** [comment]
![image](https://github.com/user-attachments/assets/00932a16-573c-41b3-9a2f-19dbc969d294)
![image](https://github.com/user-attachments/assets/f071382e-3c44-4c28-988f-63e731ea2c27)

Confirmed. Closing as fixed as of 20/09/2024.
