### ISSUE TITLE
Incorrect Cyberdeck Reward Granted to All Professions by Professor Dedlock [Specialization 1 - 4]

### ISSUE THREAD

**Issue by loysaranne** [project-rubika/issues#914]
### Reproduction steps

```bash
1. Be Fixer
2. Collect Mariners book
3. Talk to Professor Dedlock
4. Right away, give him the book without talking anything else
5. Get rewarded with First Spec and Basic Cyberdeck
```

### Expected results

```bash
For Fixer should only get First Spec
```

### Actual results

```bash
You get Nanotech only Cyberdeck
```

### Bug prevalence

Done only once, need verification

### Description

```bash
I'm not a nanotech
```

### Report link

https://pastebin.com/K0E4pFqB

**Comment by kajoriEU** [comment]
Confirmed 👍 

Professor Dedlock is correctly adding first specialization to the character but also wrongfully adds a Basic Cyberdeck for male Solitus to the reward.

![{51095629-74BE-403A-94A9-CA5463D23F9D}](https://github.com/user-attachments/assets/a99f55b6-6f84-4eea-bb40-0bbae2b7e79a)

**Comment by prkdrake** [comment]
I believe this is now working

**Comment by kajoriEU** [comment]
This is fixed as of 15/09/2024 👍
