### ISSUE TITLE
Channel Rage Perk Fails to Apply Correct Buff to MP Attack Pet

### ISSUE THREAD

**Issue by 7RO11** [project-rubika/issues#916]
### Reproduction steps

```bash
1. put 2 perk points into channel rage
2. spawn an mp attack pet above level 27, i used .item 43777 43777 37
3. select them and use the channel rage perk
```

### Expected results

```bash
the channel rage buff to be applied to the pet
```

### Actual results

```bash
no buff was applied
```

### Bug prevalence

once after spawning pet

### Description

```bash
additional attempts to use channel rage on the same pet will give it the incorrect buff



```

### Report link

https://pastebin.com/DC9SRjQg

using the level 10 perk against the level 197 pet at the time

![Screenshot from 2024-09-12 19-09-51](https://cdn.discordapp.com/attachments/981346376162103320/1283929935882223627/Screenshot_from_2024-09-12_19-09-51.png?ex=66e4c86e&is=66e376ee&hm=cd9324625a06e1720fe9607aa7686f64bd4fd6d5a15c741f1dc58fc579b67624&)

**Comment by kajoriEU** [comment]
Confirmed 👍 

Could reproduce. See image of using Channel Rage 2 on a lv. 48 Pet.

![{DA8E529A-8723-4479-B17A-A66C52E6B995}](https://github.com/user-attachments/assets/7c7f8bc6-61c1-43b4-bae1-5de2da822d6d)

**Comment by portalerprk** [comment]
Two this:
1 - I dont see any mechanism on https://auno.org/ao/db.php?id=227693&patch=16000000 that says it should only apply to pets above 27. so I think this is a FC verbiage issue maybe?
2 - I cannot repro (perhaps inadvertently fixed?). It applies the Channel Rage that matches your Perk investment in channel rage.

**Comment by portalerprk** [comment]
Ok. I confirmed its an issue. 

It lands the buff but doesn't actually increase the stats even though the pet is of the right level.

Sorry I just wasn't understanding the repro steps, I didn't main an MP :-P

**Comment by portalerprk** [comment]
I think I fixed it. We were missing the `OnSelf` operator thats used here in ChannelRage. It's used fairly rarely.

**Comment by 7RO11** [comment]
this is fixed now, using channel rage 2 and 7 on the lv 149 pet, gives the pet +30/175 damage
![Screenshot from 2024-09-15 12-45-16](https://github.com/user-attachments/assets/e71a3663-58cb-4bca-afa1-f6230654844d)

**Comment by kajoriEU** [comment]
This is working as expected now. Fixed as 15/09/2024
