### ISSUE TITLE
Using buff perks while casting a nano does not give perk buff

### ISSUE THREAD

**Issue by loysaranne** [project-rubika/issues#922]
### Reproduction steps

```bash
1. Start casting a nano with long attack time
2. Use a perk that gives a NCU buff
```

### Expected results

```bash
You should get the perk buff running in your NCU
```

### Actual results

```bash
Your perk goes into CD and perk buff is not running in NCU
```

### Bug prevalence

Every time

### Description

```bash
Was casting Shadow Step and used Defensive Stance and noticed this bug
```

### Report link

https://pastebin.com/TgNgzETz

**Comment by kajoriEU** [comment]
Confirmed 👍 'Buff' perks are currently not working correctly when you use them while casting a nano.

## Video example

https://github.com/user-attachments/assets/287189fa-cc3c-401d-8888-ececbd0ec8cd

**Comment by kajoriEU** [comment]
This issue has been fixed as of 15/09/2024. 👍

**Comment by loysaranne** [comment]
This is now happening with Perks that apply debuff on enemies. Same behaviour. If you are casting nano (or recharging from nano cast) the debuff wont get applied to the enemy
