### ISSUE TITLE
Charmed mobs currently 'release' themselves as pets upon attack command

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#927]
**Describe the bug**
When a charmed mob is given the attack order, it disappears off the players Pet bar, but continues along its existing pathway. It doesn't actively attack either. The pet stays on the bar if given the Follow or Wait commands.

**To Reproduce**
1. Charm a mob. `.ncu run 231010`
2. Order it to attack a target.

**Expected behavior**
The charmed mob should attack the target like any other pet would. The charmed mob should also be exempt from any leashing logic, so once the charm expires, it doesn't break or immediately attempt to return to its existing spawn point.

**Screenshots**

https://github.com/user-attachments/assets/131f3e33-4240-4c89-b730-421c89f6f26e

**Comment by kajoriEU** [comment]
Happy to announce that the latest update just fixed that 👍 


https://github.com/user-attachments/assets/ec30bbba-d3f6-47fd-8d39-9077464a0f1f


#### Closing as fixed as of 21/09/2024
