### ISSUE TITLE
Able to loot unique items even though you already have the specific items in bank

### ISSUE THREAD

**Issue by Dezzyx** [project-rubika/issues#934]
### Reproduction steps

```bash
1. Acquire some unique item/s (for me it was the sub nodrops copper wire, circuit board etc)
2. Deposit them to bank
3. Go and loot the same item/s again
4. Notice how you are able to loot unique item/s again
```

### Expected results

```bash
I expected that when I already have a unique item in bank I will not be able to loot more 
of that item
```

### Actual results

```bash
I was able to loot the same unique items again
```

### Bug prevalence

Only tested once

### Description

```bash
I was doing Subway and looted these unique items as I wasn't sure if I had them all in my bank
already but I did
```

### Report link

https://pastebin.com/gc6Euzrk

**Comment by kajoriEU** [comment]
This is confirmed and can be even easier reproduced with Antivehicle Rockets from the general weapons shop.

1. `.tp 179.7 122.3 y 5.0 1186.`
2. Access the 'Basic Weapons' shopping terminal.
3. Purchase UNIQUE Antivehicle Rockets.
4. Store purchased rockets in your bank.
5. Successfully purchase another set of UNIQUE Antivehicle Rockets.

**Comment by Dezzyx** [comment]
Confirmed, fixed

![Screenshot 2024-10-02 034628](https://github.com/user-attachments/assets/b41dd454-1442-48c5-98a8-fc14c56ebdcf)
![Screenshot 2024-10-02 035106](https://github.com/user-attachments/assets/1dc85260-65e1-40b6-91ef-3d4c5c5d19fa)
