### ISSUE TITLE
Surgery Clinics don't surgery

### ISSUE THREAD

**Issue by oatbag03** [project-rubika/issues#936]
### Reproduction steps

```bash
1. Right click on Surgery Clinic
2. Get the "Enabled!" pop up text
3. Nothing Happens
```

### Expected results

```bash
Expected the terminal to enable the hostile buff that allows adding and removing implants/symbs and to be able to add/remove implants/symbs.
```

### Actual results

```bash
No buff applied by surgery clinic; unable to add/remove implants.
```

### Bug prevalence

Today is first time, worked previously, but every time now

### Description

```bash
Tested on multiple chars on multiple accounts by multiple people in multiple locations.
```

### Report link

https://pastebin.com/qQ5ecYxW

**Comment by kajoriEU** [comment]
Confirmed 👍 

Above reproduction steps show the issue exactly as described.


https://github.com/user-attachments/assets/2996859f-860f-42c1-acda-e6e73b22612b

**Comment by kajoriEU** [comment]
The recent update has resolved this bug.

Marking this as fixed 👍
