### ISSUE TITLE
SL Gardens Are Not Accessible With Insignias

### ISSUE THREAD

**Issue by donkeyohtay** [project-rubika/issues#949]
### Reproduction steps

```bash
1. Go to SL Garden entrance 
2. Use insignia on garden statue
3. Be sad
```

### Expected results

```bash
Zone into sided garden and insignia is removed.
```

### Actual results

```bash
Insignia is deleted and character is not zoned.
```

### Bug prevalence

Every time

### Description

```bash
Tested with Frontier Bridge statue using Thrak insignia. Tried three times to verify.
```

### Report link

https://pastebin.com/tAhiuKWL

**Comment by kajoriEU** [comment]
Can confirm 👍 Neither Thrak or Aban will work currently. Might be related to the targeting issue with TOTW portal we had earlier :)

**Comment by kajoriEU** [comment]
This is now working as expected again :) 

Closing as fixed 👍
