### ISSUE TITLE
SL Mobs sometimes hit multiple times at once

### ISSUE THREAD

**Issue by donkeyohtay** [project-rubika/issues#950]
### Reproduction steps

```bash
1. Attack a mob in SL
2. (Maybe) evade a few attacks?
3. They will land three hits all at the same time
```

### Expected results

```bash
Only one hit should land per attack
```

### Actual results

```bash
Three hits are landed for one attack, each seems to roll damage individually.
```

### Bug prevalence

Almost every fight

### Description

```bash
I am evading a few attacks before the triple hit, so could be something to do with that. Tested RK mobs, they don't seem to have this bug. Confirmed on spirits and dynas in Nascence by Old Frontier clan exit.
```

### Report link

https://pastebin.com/gmKZKV8Y

**Comment by kajoriEU** [comment]
Confirmed. 👍 

The Lord/Lady have consistently exhibited this behavior the most for me.

**Comment by 7RO11** [comment]
![cy](https://github.com/user-attachments/assets/a67d1a37-d178-41e9-b72f-9e26799ec29c)
seen this behavior on some rk mobs, pictured here outside cyborg barracks

**Comment by kajoriEU** [comment]
@7RO11 Please include Shift + F9 output if possible so that we can reproduce properly.

**Comment by 7RO11** [comment]
Extended location information:
- 2865.2, 2540.3, 16.1 (2865.2 2540.3 y 16.1 647)
- Pf Proxy: Model=51100:647 GS=0 SG=0 R=647, resource: 647
- zone: 5804, area: "Northern Striking Ant Forest"
Server id: 1, character id: 50000:2585, time: 2024-09-20 16:24:21 (UTC)
Version: 00.6.5_EP1, map id: NOT FOUND, build: 52606.

on the approach to cyborg barracks in greater tir county

**Comment by Nephima** [comment]
Speaking of SL mobs' damage, check out Hecklers, for example those lvl 80 ones when teleported to Nascence Wilds, after a fight with them has progressed a bit they suddenly hit THEMSELVES with nanobots for huge damage (like 25% of  their total health), this happens 2 or 3 times and eventually makes them much easier to kill. I've had a lvl 93 pet, so it should be a difficult fight but it's completely trivial in current state. Happens also to Unreedemed mobs around a temple in Elysium. They also hit themselves with nanobots for big damage spikes.

**Comment by kajoriEU** [comment]
This issue has been resolved, and I’m no longer able to reproduce the behavior described. I’m closing it as fixed. Please reopen the issue if you encounter this problem again.
