### ISSUE TITLE
cannot cast pet specific nanos on pets

### ISSUE THREAD

**Issue by 7RO11** [project-rubika/issues#952]
**Describe the bug**
pet classes cannot cast their buffs/nanos on their pets

**To Reproduce**
1. spawn a pet that has a buff line, .item 46028 46028 185 for engis
2. select the pet
3. click on a pet buff nano, .item 205230 205230 15
4. no nano is cast, server responds with:
Your no LDBintern (2002:4) is required to be at least 7!
Your %s is required to be at least %d!
Could not cast nano because you do not meet the requirements..

**Expected behavior**
these nanos should cast if the reqs are met

tested with mp, crat, and engi pets and their main attack lines. also tried the engi heal pet line came up with this error
this doesn't effect regular nanos, you can cast stuff like comps and player buffs on pets

**Comment by kajoriEU** [comment]
This seems to be fixed again. 

![{C54D2DFD-FE86-44AD-A55A-52D3D4D86812}](https://github.com/user-attachments/assets/f24aae5d-bba8-4d60-9ec8-d0a0cdd47070)

![{7551E8F7-C8B2-4FC2-BD30-A9523B22155F}](https://github.com/user-attachments/assets/51140fd9-1a77-45db-b3f6-bac3ecf58550)

![{601657D6-89E5-4184-A1C0-3CD16816913E}](https://github.com/user-attachments/assets/b43a6af1-95d1-49df-aa7c-dbda259bd914)

### Closing this as fixed 👍
