### ISSUE TITLE
Channel Rage 1 does not work on MP Pet

### ISSUE THREAD

**Issue by donkeyohtay** [project-rubika/issues#954]
### Reproduction steps

```bash
1. Perk Channel Rage 1
2. Summon MP Attack pet 
3. Target attack pet and use Channel Rage
```

### Expected results

```bash
Should apply Channel Rage buff to attack pet.
```

### Actual results

```bash
Perk fails with this message:
Your Monster Type is required to be at least 97!
Your %s is required to be at least %d!
Your no LDBintern (2002:4) is required to be at least 7!
Your %s is required to be at least %d!
Could not use perk because you do not meet the requirements.
```

### Bug prevalence

Every time

### Description

```bash
Tried with ql10 and ql 7 pet, neither worked. Attempted relog and resummon, no dice.
```

### Report link

https://pastebin.com/42WCzN2L

**Comment by kajoriEU** [comment]
This is worked as expected again :)

![{40251CCC-19D6-4B3E-AC42-419157374BBD}](https://github.com/user-attachments/assets/f40de293-34ce-4c58-9ea0-cfe33f751886)

![{53FF5030-8CEA-4939-A091-CA5142BDD314}](https://github.com/user-attachments/assets/78a30ad9-0116-495a-8164-27430d51e88c)

### Closing this as fixed 👍
