### ISSUE TITLE
killing mobs as they are casting doesn't interrupt the cast

### ISSUE THREAD

**Issue by 7RO11** [project-rubika/issues#960]
**Describe the bug**
a mob that casts a nano will go through if they died right before it was finished

**To Reproduce**
1. Go to the subway, where architect strikers are
2. aggro an architect striker until it casts a nano
3. kill it right before it finishes
4. the effect of the nano still applies to the player
OR
1. Go to TOTW, find an acolyte or cultist that heals
2. aggro it until it casts a heal
3. kill it right before it finishes
4. the effect of the heal will still apply to the mob, turning it into a zombie

**Expected behavior**
nanos should be interrupted if the mob/player casting them died in the process

**Screenshots**
i made some videos of it since the timing is tricky

https://github.com/user-attachments/assets/0b1c27aa-7081-486e-85c1-697f1feb5f2d

https://github.com/user-attachments/assets/9ea3b668-84c5-44b6-9c65-9c30936891f8

**Comment by kajoriEU** [comment]
Confirmed 👍  The behavior occurs as described. When a mob is killed right before finishing a cast, the nano effect still applies.
