### ISSUE TITLE
Reconstruction perk does not require a target to use

### ISSUE THREAD

**Issue by StormlashTV** [project-rubika/issues#964]
### Reproduction steps

```bash
1. Make sure you have no target selected
2. Use Reconstruction
3. The perk goes on cooldown but does nothing
```

### Expected results

```bash
I expected not to be able to use it without an active target, in this case, Engineer's Pet
```

### Actual results

```bash
The perk did nothing and went on cooldown
```

### Bug prevalence

Every time

### Description

```bash
Reconstruction perk from the Gadgeteer perkline, if no target is selected, it does nothing and goes on cooldown

Extended location information:
- 246.6, 114.5, 81.1 (246.6 114.5 y 81.1 127)
- Pf Proxy: Model=51100:127 GS=0 SG=0 R=127, resource: 127
- zone: 28, area: "Fractured Sewers", room: "Mini Helix-Cathedral"
Server id: 2582, character id: 50000:2582, time: 2024-09-20 21:04:29 (UTC)
Version: 00.6.5_EP1, map id: NOT FOUND, build: 52606.
```

### Report link

https://pastebin.com/BsnLDMM8

**Comment by kajoriEU** [comment]
Confirmed. 

You probably shouldn't be able to fire the perk into the void.

Workaround: Target your pet first ;)

**Comment by kajoriEU** [comment]
This issue has been resolved 👍

Now, if you attempt to use Reconstruction without a target, it will display the error message: 'Can only be used on friendly targets.'

![{FE08D44A-641A-45BD-BEB8-4F420F0E7179}](https://github.com/user-attachments/assets/1d3cc6d0-5ed6-4b8f-9a71-b3abab11ff54)
