### ISSUE TITLE
'Levelling' items such as Living Cyber Armour or Newcomers dont move to overflow.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#973]
**Describe the bug**
If you have a full inventory and 'use' levelling items, the newly generated item is not moved to overflow and is instead deleted.

**To Reproduce**
1. Fill your inventory until you have 1 slot left.
2. `.item 163428 163428 1`
3.  Right click the levelling item.
4. See the overflow window appear, but no item.

**Expected behavior**
The next version of the levelling item should be placed into the overflow window, not outright deleted.

**Comment by kajoriEU** [comment]
Duplicate of #959.
