### ISSUE TITLE
Loot deleted from corpses is not broadcast to nearby/relevant clients.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#975]
**Describe the bug**
Deleting an item from a body does not generate the expected `Player has deleted [Item] from Remains of [NPC]` message to both the actioning player and nearby players.

**To Reproduce**
1. Kill a mob.
2. Delete an item off the body.

**Expected behavior**
When an item is deleted from a body, it should broadcast the information to nearby players via Team Loot Messages and Vicinity Loot Messages

**Comment by kajoriEU** [comment]
This seems to be working correctly now :)

![{28417F1C-5C1E-4FF9-896A-BE247FBA87DC}](https://github.com/user-attachments/assets/0e34d2bc-090e-4249-8dba-ad4801fdbafe)

![{676C0F1F-4EA4-4EC7-B9AA-798EBDEBC10C}](https://github.com/user-attachments/assets/173f33b6-63fd-4f77-b0ee-2fb9dd8e1343)
