### ISSUE TITLE
Damaged Staff of Naja cannot be obtained

### ISSUE THREAD

**Issue by whichpatrick** [project-rubika/issues#981]
**Describe the bug**
Damaged Staff of Naja (the MP starter weapon) cannot be obtained in game. Most of the starter weapons are alternately available for purchase from Antonio Stacklund, and Damaged Staff of Naja should be upgradeable through Antonio's Adaptation Factory but it does not appear to be possible to retrieve it through gameplay.

**To Reproduce**
1. Be a Metaphysicist

**Expected behavior**
Should start with Damaged Staff of Naja (or be able to purchase it from Antonio Stacklund, though this is probably not the case in live).

**Comment by RaggyLP** [comment]
This is an 18.8 item. PRK is on 18.4

https://auno.org/ao/db.php?id=302163


Please use the Item DB on https://site.project-rk.com/ to confirm if an item is present or not.

**Comment by kajoriEU** [comment]
Staff of Naja was Introduced with the New Player Experience in 18.8.53.
