### ISSUE TITLE
Treatment Laboratory can be repeatedly used on team members and doesn't trigger a cooldown

### ISSUE THREAD

**Issue by StormlashTV** [project-rubika/issues#989]
**Describe the bug**
Treatment Laboratory can be repeatedly used on team members without triggering a cooldown

**To Reproduce**
1. Spawn a .item 25811 25812 20
2. Try to use it more than once on a team member

**Expected behavior**
I expected to use it once, wait for its cooldown to be over, and then use it again

**Screenshots**

**Character info:**

```
Copy/paste the output of /getfull here
```

**Playfield info:**

```
Copy/paste the output of Shift+F9 here
```
----

**Comment by kajoriEU** [comment]
Confirmed. 👍

Using the Treatment Laboratory on another player doesn't lock their treatment skill, allowing repeated use without delay.

#


https://github.com/user-attachments/assets/8e0cf2b2-87ce-42bf-92ee-0ced5a5a554a

**Comment by kajoriEU** [comment]
It looks like this issue has been resolved. The Treatment skill now properly locks after being used on another player.

https://github.com/user-attachments/assets/e94716c9-d744-4f68-87cc-1bf9d4ff62c7
