### ISSUE TITLE
High level players are preventing low level team members from getting XP

### ISSUE THREAD

**Issue by StormlashTV** [project-rubika/issues#990]
### Reproduction steps

```bash
1. Team with someone around your level
2. Find a mob that is green to the low-level toon and gray to the high-level toon
3. Kill it
4. The low-level toon doesn't get the XP from the kill
```

### Expected results

```bash
If a mob is green to you, you should get the XP from the kill even if you are teaming with higher-level toons and the mob is gray to them
```

### Actual results

```bash
Green mobs are not granting XP to low-level toons while teamed with someone higher level than them
```

### Bug prevalence

Every time

### Description

```bash
Killing Cultists in TOTW
MA 36 (low level) and Keeper 41 (high level)
```

### Report link

https://pastebin.com/ns5eAz8N

**Comment by kajoriEU** [comment]
Confirmed 👍 The level of the higher-level player seems to determine whether any group member can receive XP from a mob. This affects lower-level players' ability to gain XP if the mob is too low for the higher-level player.

**Comment by kajoriEU** [comment]
Linked to #369 . Please see third comment from Zolarix 

> Worth also mentioning that if the mob that is killed by the team is too low level for the high level player to get more than 1xp, the low level player gets 1xp too. Tested on a level ~150 when the high level player was 220 and the low level player was level 1.
