### ISSUE TITLE
Dyna Boss 'Anti pet' proc is not checking target breed.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#996]
**Describe the bug**
The 'Shadow Touch' proc on Dyna Bosses which is designed as a measure vs pet professions is not checking the targets breed, resulting in it hitting players, significantly increasing the difficulty of fights.

https://site.project-rk.com/server/Ithaca/item/163449

**To Reproduce**
1. Find a Dyna boss
2. Let it attack you
3. Notice a radiation proc that is 'level relevant'

**Expected behavior**
The proc should only hit pets who have a breed value of 7.

**Comment by kajoriEU** [comment]
This issue appears to be resolved. 👍 The Shadow Touch proc no longer affects player characters and now correctly targets pets as expected.

![{9F2130C1-0C2A-498D-BFE2-46ECE97A781F}](https://github.com/user-attachments/assets/7ec7cb76-59af-4aa5-9f51-926d848ed2b2)
