### ISSUE TITLE
Shadowbreed level bug

### ISSUE THREAD

**Issue by bitnykk** [project-rubika/issues#998]
**Describe the bug**
When right clicking a sided SB booster, it should add the new level in perk WHILE deleting lower one.

**To Reproduce**
1. get your side SB booster (xxx side)
2. right clic it
3. check cltr+2 action window

**Expected behavior**
Add new level while deleting lower one.
I see all present in ctrl+2 action window
Should have one only (highest)

**Comment by kajoriEU** [comment]
Duplicate of #561. :(
